// Vocabulary category, Antonyms game: C1-C2 level topic sets. Same
// topic keys as synonymsTopicsC1C2.js so the two games pair up under
// the same level tabs, but with true opposite-meaning pairs instead of
// synonyms. Position of `correct` varied across entries.
const ANTONYMS_TOPICS_C1C2 = {
  businessAndEconomics: [
    { word: "lucrative", choices: ["unprofitable", "profitable", "rewarding", "gainful"], correct: "unprofitable" },
    { word: "diversify", choices: ["broaden", "expand", "consolidate", "vary"], correct: "consolidate" },
    { word: "solvent", choices: ["stable", "insolvent", "secure", "sound"], correct: "insolvent" },
    { word: "boom", choices: ["growth", "surge", "expansion", "recession"], correct: "recession" },
    { word: "surplus", choices: ["deficit", "excess", "abundance", "reserve"], correct: "deficit" },
    { word: "subsidize", choices: ["fund", "support", "tax", "finance"], correct: "tax" },
    { word: "stable", choices: ["steady", "volatile", "constant", "secure"], correct: "volatile" },
    { word: "austerity", choices: ["thrift", "economy", "frugality", "extravagance"], correct: "extravagance" },
    { word: "inflate", choices: ["deflate", "expand", "increase", "raise"], correct: "deflate" },
    { word: "centralize", choices: ["consolidate", "unify", "decentralize", "concentrate"], correct: "decentralize" },
  ],
  politicsAndGovernance: [
    { word: "legislate", choices: ["enact", "repeal", "establish", "pass"], correct: "repeal" },
    { word: "sovereignty", choices: ["independence", "autonomy", "self-rule", "dependency"], correct: "dependency" },
    { word: "unite", choices: ["divide", "join", "merge", "combine"], correct: "divide" },
    { word: "transparency", choices: ["openness", "honesty", "secrecy", "clarity"], correct: "secrecy" },
    { word: "centralize", choices: ["consolidate", "decentralize", "unify", "concentrate"], correct: "decentralize" },
    { word: "democratic", choices: ["representative", "elected", "free", "authoritarian"], correct: "authoritarian" },
    { word: "cooperate", choices: ["obstruct", "collaborate", "assist", "support"], correct: "obstruct" },
    { word: "autonomous", choices: ["self-ruling", "independent", "dependent", "free"], correct: "dependent" },
    { word: "legitimate", choices: ["lawful", "illegitimate", "valid", "rightful"], correct: "illegitimate" },
    { word: "stability", choices: ["order", "peace", "balance", "instability"], correct: "instability" },
  ],
  scienceAndInnovation: [
    { word: "innovative", choices: ["inventive", "original", "conventional", "novel"], correct: "conventional" },
    { word: "empirical", choices: ["theoretical", "evidence-based", "observed", "factual"], correct: "theoretical" },
    { word: "advance", choices: ["progress", "improve", "develop", "regress"], correct: "regress" },
    { word: "verify", choices: ["confirm", "refute", "validate", "prove"], correct: "refute" },
    { word: "complex", choices: ["intricate", "elaborate", "simple", "complicated"], correct: "simple" },
    { word: "accelerate", choices: ["decelerate", "speed up", "hasten", "quicken"], correct: "decelerate" },
    { word: "discover", choices: ["find", "uncover", "reveal", "conceal"], correct: "conceal" },
    { word: "precise", choices: ["accurate", "imprecise", "exact", "specific"], correct: "imprecise" },
    { word: "viable", choices: ["feasible", "practical", "unworkable", "workable"], correct: "unworkable" },
    { word: "obsolete", choices: ["cutting-edge", "outdated", "dated", "old-fashioned"], correct: "cutting-edge" },
  ],
  artsAndCulture: [
    { word: "authentic", choices: ["genuine", "real", "original", "counterfeit"], correct: "counterfeit" },
    { word: "avant-garde", choices: ["experimental", "traditional", "innovative", "modern"], correct: "traditional" },
    { word: "renowned", choices: ["celebrated", "famous", "obscure", "acclaimed"], correct: "obscure" },
    { word: "provocative", choices: ["dull", "thought-provoking", "stimulating", "controversial"], correct: "dull" },
    { word: "eclectic", choices: ["diverse", "varied", "mixed", "uniform"], correct: "uniform" },
    { word: "timeless", choices: ["enduring", "dated", "classic", "lasting"], correct: "dated" },
    { word: "subtle", choices: ["understated", "nuanced", "blatant", "delicate"], correct: "blatant" },
    { word: "sincere", choices: ["insincere", "genuine", "heartfelt", "honest"], correct: "insincere" },
    { word: "elaborate", choices: ["intricate", "detailed", "ornate", "simple"], correct: "simple" },
    { word: "harmonious", choices: ["balanced", "discordant", "pleasing", "unified"], correct: "discordant" },
  ],
  ethicsAndPhilosophy: [
    { word: "virtue", choices: ["vice", "goodness", "morality", "integrity"], correct: "vice" },
    { word: "altruism", choices: ["generosity", "selflessness", "selfishness", "charity"], correct: "selfishness" },
    { word: "honest", choices: ["truthful", "deceptive", "sincere", "candid"], correct: "deceptive" },
    { word: "autonomy", choices: ["independence", "freedom", "self-rule", "dependency"], correct: "dependency" },
    { word: "objective", choices: ["subjective", "impartial", "neutral", "factual"], correct: "subjective" },
    { word: "compassionate", choices: ["kind", "caring", "callous", "empathetic"], correct: "callous" },
    { word: "rational", choices: ["logical", "irrational", "sensible", "reasonable"], correct: "irrational" },
    { word: "consistent", choices: ["steady", "reliable", "principled", "hypocritical"], correct: "hypocritical" },
    { word: "tolerant", choices: ["prejudiced", "accepting", "open-minded", "fair"], correct: "prejudiced" },
    { word: "humble", choices: ["modest", "meek", "arrogant", "unassuming"], correct: "arrogant" },
  ],
  globalAffairs: [
    { word: "unite", choices: ["merge", "fragment", "join", "combine"], correct: "fragment" },
    { word: "peace", choices: ["harmony", "calm", "stability", "conflict"], correct: "conflict" },
    { word: "cooperation", choices: ["rivalry", "collaboration", "partnership", "alliance"], correct: "rivalry" },
    { word: "expand", choices: ["grow", "enlarge", "contract", "increase"], correct: "contract" },
    { word: "isolate", choices: ["separate", "integrate", "exclude", "segregate"], correct: "integrate" },
    { word: "stability", choices: ["order", "peace", "calm", "turmoil"], correct: "turmoil" },
    { word: "open", choices: ["restrictive", "accessible", "free", "liberal"], correct: "restrictive" },
    { word: "prosperity", choices: ["wealth", "abundance", "poverty", "affluence"], correct: "poverty" },
    { word: "voluntary", choices: ["chosen", "forced", "willing", "optional"], correct: "forced" },
    { word: "domestic", choices: ["national", "local", "internal", "foreign"], correct: "foreign" },
  ],
  psychologyAndBehavior: [
    { word: "rational", choices: ["logical", "deliberate", "impulsive", "calculated"], correct: "impulsive" },
    { word: "confident", choices: ["insecure", "assured", "self-assured", "certain"], correct: "insecure" },
    { word: "resilient", choices: ["tough", "strong", "hardy", "fragile"], correct: "fragile" },
    { word: "empathetic", choices: ["compassionate", "indifferent", "caring", "sympathetic"], correct: "indifferent" },
    { word: "introverted", choices: ["reserved", "withdrawn", "extroverted", "shy"], correct: "extroverted" },
    { word: "calm", choices: ["agitated", "peaceful", "relaxed", "serene"], correct: "agitated" },
    { word: "optimistic", choices: ["hopeful", "positive", "upbeat", "pessimistic"], correct: "pessimistic" },
    { word: "cautious", choices: ["careful", "reckless", "wary", "prudent"], correct: "reckless" },
    { word: "genuine", choices: ["authentic", "sincere", "pretentious", "real"], correct: "pretentious" },
    { word: "patient", choices: ["impatient", "tolerant", "calm", "enduring"], correct: "impatient" },
  ],
  lawAndJustice: [
    { word: "guilty", choices: ["culpable", "innocent", "liable", "blameworthy"], correct: "innocent" },
    { word: "legal", choices: ["lawful", "legitimate", "permitted", "illegal"], correct: "illegal" },
    { word: "convict", choices: ["acquit", "sentence", "condemn", "punish"], correct: "acquit" },
    { word: "just", choices: ["fair", "equitable", "unjust", "impartial"], correct: "unjust" },
    { word: "plaintiff", choices: ["claimant", "defendant", "accuser", "litigant"], correct: "defendant" },
    { word: "strict", choices: ["harsh", "rigid", "severe", "lenient"], correct: "lenient" },
    { word: "biased", choices: ["impartial", "prejudiced", "unfair", "one-sided"], correct: "impartial" },
    { word: "prosecute", choices: ["charge", "indict", "defend", "accuse"], correct: "defend" },
    { word: "mandatory", choices: ["required", "optional", "compulsory", "obligatory"], correct: "optional" },
    { word: "formal", choices: ["official", "legal", "structured", "informal"], correct: "informal" },
  ],
  linguisticsAndCommunication: [
    { word: "articulate", choices: ["inarticulate", "fluent", "eloquent", "clear"], correct: "inarticulate" },
    { word: "formal", choices: ["official", "proper", "colloquial", "academic"], correct: "colloquial" },
    { word: "clarity", choices: ["precision", "ambiguity", "clearness", "exactness"], correct: "ambiguity" },
    { word: "verbose", choices: ["wordy", "lengthy", "rambling", "concise"], correct: "concise" },
    { word: "explicit", choices: ["implicit", "clear", "direct", "obvious"], correct: "implicit" },
    { word: "fluent", choices: ["smooth", "effortless", "halting", "natural"], correct: "halting" },
    { word: "coherent", choices: ["logical", "incoherent", "organized", "clear"], correct: "incoherent" },
    { word: "literal", choices: ["exact", "direct", "precise", "figurative"], correct: "figurative" },
    { word: "talkative", choices: ["reticent", "chatty", "voluble", "expressive"], correct: "reticent" },
    { word: "formal", choices: ["proper", "official", "informal", "polished"], correct: "informal" },
  ],
  academiaAndResearch: [
    { word: "rigorous", choices: ["strict", "thorough", "demanding", "lax"], correct: "lax" },
    { word: "original", choices: ["innovative", "derivative", "creative", "novel"], correct: "derivative" },
    { word: "credible", choices: ["trustworthy", "reliable", "dubious", "believable"], correct: "dubious" },
    { word: "thorough", choices: ["superficial", "detailed", "complete", "exhaustive"], correct: "superficial" },
    { word: "objective", choices: ["neutral", "impartial", "factual", "biased"], correct: "biased" },
    { word: "novel", choices: ["new", "conventional", "original", "unprecedented"], correct: "conventional" },
    { word: "relevant", choices: ["pertinent", "applicable", "irrelevant", "significant"], correct: "irrelevant" },
    { word: "published", choices: ["unpublished", "printed", "released", "distributed"], correct: "unpublished" },
    { word: "accurate", choices: ["precise", "correct", "exact", "flawed"], correct: "flawed" },
    { word: "established", choices: ["proven", "emerging", "recognized", "accepted"], correct: "emerging" },
  ],
};

export default ANTONYMS_TOPICS_C1C2;
