// Vocabulary category, Antonyms game: B1-B2 level topic sets. Same
// topic keys as synonymsTopicsB1B2.js so the two games pair up under
// the same level tabs, but with true opposite-meaning pairs instead of
// synonyms. Position of `correct` varied across entries.
const ANTONYMS_TOPICS_B1B2 = {
  workAndCareer: [
    { word: "promotion", choices: ["advancement", "demotion", "resignation", "vacation"], correct: "demotion" },
    { word: "hire", choices: ["employ", "recruit", "retain", "fire"], correct: "fire" },
    { word: "punctual", choices: ["late", "timely", "prompt", "early"], correct: "late" },
    { word: "qualified", choices: ["capable", "skilled", "unfit", "competent"], correct: "unfit" },
    { word: "resign", choices: ["quit", "stay", "leave", "depart"], correct: "stay" },
    { word: "cooperate", choices: ["collaborate", "assist", "help", "compete"], correct: "compete" },
    { word: "efficient", choices: ["wasteful", "productive", "effective", "capable"], correct: "wasteful" },
    { word: "reward", choices: ["prize", "bonus", "punish", "gift"], correct: "punish" },
    { word: "promote", choices: ["advance", "demote", "elevate", "raise"], correct: "demote" },
    { word: "succeed", choices: ["achieve", "accomplish", "triumph", "fail"], correct: "fail" },
  ],
  mediaAndTechnology: [
    { word: "innovative", choices: ["inventive", "modern", "outdated", "advanced"], correct: "outdated" },
    { word: "reliable", choices: ["unreliable", "dependable", "trustworthy", "stable"], correct: "unreliable" },
    { word: "widespread", choices: ["common", "prevalent", "frequent", "rare"], correct: "rare" },
    { word: "connect", choices: ["link", "disconnect", "join", "attach"], correct: "disconnect" },
    { word: "accurate", choices: ["precise", "correct", "inaccurate", "exact"], correct: "inaccurate" },
    { word: "public", choices: ["private", "open", "shared", "visible"], correct: "private" },
    { word: "digital", choices: ["electronic", "online", "virtual", "analog"], correct: "analog" },
    { word: "increase", choices: ["grow", "decrease", "expand", "rise"], correct: "decrease" },
    { word: "genuine", choices: ["authentic", "real", "fake", "true"], correct: "fake" },
    { word: "subscribe", choices: ["unsubscribe", "join", "sign up", "follow"], correct: "unsubscribe" },
  ],
  healthAndWellbeing: [
    { word: "healthy", choices: ["fit", "well", "strong", "unhealthy"], correct: "unhealthy" },
    { word: "recover", choices: ["heal", "worsen", "improve", "mend"], correct: "worsen" },
    { word: "active", choices: ["energetic", "lively", "inactive", "vigorous"], correct: "inactive" },
    { word: "relaxed", choices: ["stressed", "calm", "peaceful", "content"], correct: "stressed" },
    { word: "beneficial", choices: ["helpful", "useful", "positive", "harmful"], correct: "harmful" },
    { word: "prevent", choices: ["avoid", "cause", "stop", "block"], correct: "cause" },
    { word: "gain", choices: ["acquire", "obtain", "lose", "earn"], correct: "lose" },
    { word: "strengthen", choices: ["weaken", "build", "boost", "develop"], correct: "weaken" },
    { word: "fatigued", choices: ["tired", "exhausted", "weary", "energized"], correct: "energized" },
    { word: "soothe", choices: ["calm", "irritate", "comfort", "ease"], correct: "irritate" },
  ],
  moneyAndShopping: [
    { word: "expensive", choices: ["cheap", "costly", "pricey", "valuable"], correct: "cheap" },
    { word: "save", choices: ["keep", "store", "spend", "invest"], correct: "spend" },
    { word: "profit", choices: ["gain", "loss", "earnings", "income"], correct: "loss" },
    { word: "borrow", choices: ["loan", "take", "owe", "lend"], correct: "lend" },
    { word: "increase", choices: ["decrease", "raise", "boost", "grow"], correct: "decrease" },
    { word: "rich", choices: ["wealthy", "affluent", "poor", "prosperous"], correct: "poor" },
    { word: "buy", choices: ["purchase", "sell", "acquire", "obtain"], correct: "sell" },
    { word: "deposit", choices: ["save", "store", "invest", "withdraw"], correct: "withdraw" },
    { word: "generous", choices: ["stingy", "charitable", "giving", "kind"], correct: "stingy" },
    { word: "surplus", choices: ["excess", "abundance", "deficit", "extra"], correct: "deficit" },
  ],
  natureAndEnvironment: [
    { word: "pollute", choices: ["contaminate", "purify", "dirty", "poison"], correct: "purify" },
    { word: "protect", choices: ["preserve", "conserve", "guard", "destroy"], correct: "destroy" },
    { word: "abundant", choices: ["scarce", "plentiful", "ample", "rich"], correct: "scarce" },
    { word: "natural", choices: ["organic", "wild", "artificial", "genuine"], correct: "artificial" },
    { word: "renewable", choices: ["sustainable", "finite", "replenishable", "endless"], correct: "finite" },
    { word: "increase", choices: ["grow", "expand", "reduce", "rise"], correct: "reduce" },
    { word: "fertile", choices: ["barren", "rich", "productive", "lush"], correct: "barren" },
    { word: "clean", choices: ["pure", "clear", "polluted", "fresh"], correct: "polluted" },
    { word: "wild", choices: ["untamed", "tame", "natural", "feral"], correct: "tame" },
    { word: "thrive", choices: ["flourish", "prosper", "grow", "decline"], correct: "decline" },
  ],
  opinionsAndDebate: [
    { word: "agree", choices: ["accept", "concur", "disagree", "support"], correct: "disagree" },
    { word: "support", choices: ["oppose", "back", "favor", "endorse"], correct: "oppose" },
    { word: "confirm", choices: ["verify", "validate", "affirm", "deny"], correct: "deny" },
    { word: "persuade", choices: ["convince", "discourage", "influence", "encourage"], correct: "discourage" },
    { word: "biased", choices: ["one-sided", "prejudiced", "impartial", "unfair"], correct: "impartial" },
    { word: "accept", choices: ["reject", "approve", "agree", "embrace"], correct: "reject" },
    { word: "praise", choices: ["compliment", "admire", "applaud", "criticize"], correct: "criticize" },
    { word: "certain", choices: ["sure", "doubtful", "confident", "positive"], correct: "doubtful" },
    { word: "clarify", choices: ["explain", "simplify", "confuse", "clear up"], correct: "confuse" },
    { word: "unite", choices: ["divide", "join", "combine", "merge"], correct: "divide" },
  ],
  communityAndSociety: [
    { word: "include", choices: ["welcome", "accept", "embrace", "exclude"], correct: "exclude" },
    { word: "equal", choices: ["fair", "unequal", "balanced", "even"], correct: "unequal" },
    { word: "unite", choices: ["join", "gather", "separate", "combine"], correct: "separate" },
    { word: "generous", choices: ["selfish", "giving", "kind", "charitable"], correct: "selfish" },
    { word: "public", choices: ["open", "communal", "shared", "private"], correct: "private" },
    { word: "cooperate", choices: ["collaborate", "conflict", "assist", "help"], correct: "conflict" },
    { word: "tolerant", choices: ["accepting", "open-minded", "intolerant", "patient"], correct: "intolerant" },
    { word: "familiar", choices: ["unfamiliar", "known", "common", "recognized"], correct: "unfamiliar" },
    { word: "modern", choices: ["new", "current", "contemporary", "traditional"], correct: "traditional" },
    { word: "urban", choices: ["city", "rural", "metropolitan", "developed"], correct: "rural" },
  ],
  educationAndLearning: [
    { word: "enroll", choices: ["withdraw", "register", "join", "sign up"], correct: "withdraw" },
    { word: "graduate", choices: ["complete", "finish", "drop out", "succeed"], correct: "drop out" },
    { word: "literate", choices: ["educated", "illiterate", "informed", "skilled"], correct: "illiterate" },
    { word: "discipline", choices: ["order", "control", "structure", "chaos"], correct: "chaos" },
    { word: "advance", choices: ["regress", "progress", "improve", "develop"], correct: "regress" },
    { word: "comprehend", choices: ["understand", "grasp", "misunderstand", "learn"], correct: "misunderstand" },
    { word: "praise", choices: ["compliment", "criticize", "commend", "approve"], correct: "criticize" },
    { word: "active", choices: ["engaged", "involved", "participating", "passive"], correct: "passive" },
    { word: "simplify", choices: ["complicate", "clarify", "explain", "ease"], correct: "complicate" },
    { word: "reward", choices: ["prize", "recognize", "punish", "honor"], correct: "punish" },
  ],
  travelAndTourism: [
    { word: "depart", choices: ["leave", "arrive", "exit", "go"], correct: "arrive" },
    { word: "crowded", choices: ["packed", "busy", "full", "empty"], correct: "empty" },
    { word: "domestic", choices: ["international", "local", "national", "home"], correct: "international" },
    { word: "luxurious", choices: ["lavish", "opulent", "basic", "comfortable"], correct: "basic" },
    { word: "familiar", choices: ["known", "unfamiliar", "recognized", "common"], correct: "unfamiliar" },
    { word: "arrival", choices: ["entry", "landing", "coming", "departure"], correct: "departure" },
    { word: "modern", choices: ["ancient", "contemporary", "new", "recent"], correct: "ancient" },
    { word: "accessible", choices: ["reachable", "convenient", "remote", "nearby"], correct: "remote" },
    { word: "safe", choices: ["secure", "dangerous", "protected", "calm"], correct: "dangerous" },
    { word: "cheap", choices: ["affordable", "inexpensive", "budget", "costly"], correct: "costly" },
  ],
  relationshipsAndFamily: [
    { word: "affection", choices: ["fondness", "warmth", "hostility", "love"], correct: "hostility" },
    { word: "trust", choices: ["suspicion", "confidence", "faith", "belief"], correct: "suspicion" },
    { word: "united", choices: ["together", "joined", "close", "divided"], correct: "divided" },
    { word: "supportive", choices: ["encouraging", "critical", "helpful", "kind"], correct: "critical" },
    { word: "loyal", choices: ["faithful", "devoted", "disloyal", "committed"], correct: "disloyal" },
    { word: "reconcile", choices: ["argue", "make up", "resolve", "forgive"], correct: "argue" },
    { word: "dependent", choices: ["reliant", "attached", "needy", "independent"], correct: "independent" },
    { word: "nurture", choices: ["raise", "neglect", "care for", "support"], correct: "neglect" },
    { word: "close", choices: ["intimate", "near", "distant", "tight"], correct: "distant" },
    { word: "harmony", choices: ["conflict", "peace", "agreement", "unity"], correct: "conflict" },
  ],
};

export default ANTONYMS_TOPICS_B1B2;
