// Vocabulary category, Antonyms game: A1-A2 level topic sets. Same shape
// as before -- [{ word, choices: [4], correct }] -- now 10 topics (was
// 7), matching the same topic set as Synonyms A1-A2 for a consistent
// pairing of the two games. Position of `correct` within each entry's
// `choices` array is varied rather than clustered at one fixed index.
const ANTONYMS_TOPICS = {
  feelings: [
    { word: "happy", choices: ["glad", "proud", "sad", "calm"], correct: "sad" },
    { word: "calm", choices: ["angry", "peaceful", "soft", "neat"], correct: "angry" },
    { word: "brave", choices: ["strong", "bright", "polite", "afraid"], correct: "afraid" },
    { word: "angry", choices: ["mad", "cheerful", "tired", "rough"], correct: "cheerful" },
    { word: "tired", choices: ["sleepy", "sweet", "energetic", "heavy"], correct: "energetic" },
    { word: "nervous", choices: ["relaxed", "anxious", "friendly", "thin"], correct: "relaxed" },
    { word: "upset", choices: ["unhappy", "noisy", "lazy", "pleased"], correct: "pleased" },
    { word: "proud", choices: ["kind", "ashamed", "smooth", "empty"], correct: "ashamed" },
    { word: "lonely", choices: ["alone", "bitter", "social", "stale"], correct: "social" },
    { word: "surprised", choices: ["expected", "amazed", "rough", "helpful"], correct: "expected" },
  ],
  dailyActions: [
    { word: "begin", choices: ["wait", "end", "start", "carry"], correct: "end" },
    { word: "help", choices: ["assist", "answer", "move", "harm"], correct: "harm" },
    { word: "finish", choices: ["start", "close", "break", "clean"], correct: "start" },
    { word: "ask", choices: ["reply", "borrow", "tell", "stand"], correct: "tell" },
    { word: "answer", choices: ["reply", "ask", "finish", "remember"], correct: "ask" },
    { word: "buy", choices: ["purchase", "smile", "hide", "sell"], correct: "sell" },
    { word: "fix", choices: ["damage", "repair", "learn", "arrive"], correct: "damage" },
    { word: "choose", choices: ["select", "open", "reject", "wash"], correct: "reject" },
    { word: "show", choices: ["display", "hide", "follow", "climb"], correct: "hide" },
    { word: "leave", choices: ["depart", "touch", "spell", "stay"], correct: "stay" },
  ],
  describingPeople: [
    { word: "kind", choices: ["rude", "friendly", "quiet", "clever"], correct: "rude" },
    { word: "smart", choices: ["intelligent", "careful", "foolish", "brave"], correct: "foolish" },
    { word: "lazy", choices: ["tired", "active", "calm", "rich"], correct: "active" },
    { word: "honest", choices: ["truthful", "gentle", "bright", "dishonest"], correct: "dishonest" },
    { word: "brave", choices: ["afraid", "courageous", "polite", "healthy"], correct: "afraid" },
    { word: "rich", choices: ["wealthy", "loud", "poor", "shiny"], correct: "poor" },
    { word: "quiet", choices: ["silent", "noisy", "careful", "lucky"], correct: "noisy" },
    { word: "friendly", choices: ["welcoming", "patient", "easy", "cold"], correct: "cold" },
    { word: "funny", choices: ["serious", "amusing", "short", "fresh"], correct: "serious" },
    { word: "polite", choices: ["respectful", "smooth", "rude", "strong"], correct: "rude" },
  ],
  describingThings: [
    { word: "big", choices: ["large", "thick", "wide", "small"], correct: "small" },
    { word: "easy", choices: ["simple", "hard", "sweet", "full"], correct: "hard" },
    { word: "fast", choices: ["quick", "bright", "slow", "clean"], correct: "slow" },
    { word: "small", choices: ["huge", "tiny", "neat", "early"], correct: "huge" },
    { word: "hard", choices: ["difficult", "brave", "crowded", "easy"], correct: "easy" },
    { word: "clean", choices: ["tidy", "dirty", "quiet", "smooth"], correct: "dirty" },
    { word: "dirty", choices: ["messy", "pale", "clean", "lucky"], correct: "clean" },
    { word: "bright", choices: ["dull", "shiny", "soft", "rich"], correct: "dull" },
    { word: "strong", choices: ["powerful", "tiny", "warm", "weak"], correct: "weak" },
    { word: "quiet", choices: ["silent", "noisy", "empty", "gentle"], correct: "noisy" },
  ],
  schoolAndStudy: [
    { word: "correct", choices: ["right", "early", "wrong", "busy"], correct: "wrong" },
    { word: "pass", choices: ["fail", "win", "try", "review"], correct: "fail" },
    { word: "answer", choices: ["reply", "ask", "finish", "remember"], correct: "ask" },
    { word: "teacher", choices: ["instructor", "office", "cousin", "student"], correct: "student" },
    { word: "student", choices: ["pupil", "artist", "teacher", "driver"], correct: "teacher" },
    { word: "learn", choices: ["forget", "study", "borrow", "travel"], correct: "forget" },
    { word: "question", choices: ["query", "reply", "lesson", "ticket"], correct: "reply" },
    { word: "success", choices: ["error", "class", "station", "failure"], correct: "failure" },
    { word: "remember", choices: ["recall", "clean", "forget", "arrive"], correct: "forget" },
    { word: "simple", choices: ["complex", "easy", "brave", "healthy"], correct: "complex" },
  ],
  travelAndPlaces: [
    { word: "near", choices: ["close", "far", "low", "quiet"], correct: "far" },
    { word: "arrive", choices: ["enter", "travel", "stay", "leave"], correct: "leave" },
    { word: "open", choices: ["closed", "free", "smooth", "narrow"], correct: "closed" },
    { word: "far", choices: ["bright", "safe", "near", "tidy"], correct: "near" },
    { word: "enter", choices: ["arrive", "leave", "follow", "wonder"], correct: "leave" },
    { word: "depart", choices: ["reach", "carry", "borrow", "stay"], correct: "stay" },
    { word: "city", choices: ["village", "town", "map", "meal"], correct: "village" },
    { word: "full", choices: ["crowded", "modern", "empty", "local"], correct: "empty" },
    { word: "lost", choices: ["narrow", "found", "early", "simple"], correct: "found" },
    { word: "public", choices: ["quick", "lucky", "noisy", "private"], correct: "private" },
  ],
  homeAndDailyLife: [
    { word: "clean", choices: ["dirty", "tidy", "simple", "careful"], correct: "dirty" },
    { word: "dirty", choices: ["messy", "old", "clean", "strong"], correct: "clean" },
    { word: "open", choices: ["bright", "free", "smooth", "closed"], correct: "closed" },
    { word: "full", choices: ["rich", "empty", "busy", "soft"], correct: "empty" },
    { word: "rest", choices: ["work", "relax", "smile", "listen"], correct: "work" },
    { word: "quiet", choices: ["peaceful", "sweet", "noisy", "deep"], correct: "noisy" },
    { word: "early", choices: ["fresh", "polite", "careful", "late"], correct: "late" },
    { word: "busy", choices: ["active", "free", "shiny", "proud"], correct: "free" },
    { word: "safe", choices: ["dangerous", "strong", "neat", "cheap"], correct: "dangerous" },
    { word: "inside", choices: ["heavy", "straight", "outside", "friendly"], correct: "outside" },
  ],
  foodAndCooking: [
    { word: "tasty", choices: ["delicious", "bland", "spicy", "fresh"], correct: "bland" },
    { word: "fresh", choices: ["ripe", "stale", "frozen", "dry"], correct: "stale" },
    { word: "sweet", choices: ["sugary", "sour", "salty", "bitter"], correct: "sour" },
    { word: "hot", choices: ["warm", "spicy", "cold", "mild"], correct: "cold" },
    { word: "full", choices: ["satisfied", "empty", "hungry", "thirsty"], correct: "hungry" },
    { word: "raw", choices: ["fresh", "cooked", "frozen", "chopped"], correct: "cooked" },
    { word: "thick", choices: ["creamy", "thin", "smooth", "rich"], correct: "thin" },
    { word: "spicy", choices: ["sweet", "hot", "mild", "sour"], correct: "mild" },
    { word: "heat", choices: ["warm", "cool", "boil", "melt"], correct: "cool" },
    { word: "add", choices: ["pour", "remove", "mix", "stir"], correct: "remove" },
  ],
  weatherAndSeasons: [
    { word: "sunny", choices: ["bright", "cloudy", "warm", "clear"], correct: "cloudy" },
    { word: "cold", choices: ["chilly", "warm", "hot", "mild"], correct: "hot" },
    { word: "wet", choices: ["damp", "humid", "dry", "rainy"], correct: "dry" },
    { word: "calm", choices: ["still", "breezy", "stormy", "mild"], correct: "stormy" },
    { word: "windy", choices: ["breezy", "gusty", "still", "humid"], correct: "still" },
    { word: "bright", choices: ["shiny", "dim", "dark", "clear"], correct: "dark" },
    { word: "warm", choices: ["mild", "hot", "freezing", "cool"], correct: "freezing" },
    { word: "clear", choices: ["sunny", "bright", "overcast", "misty"], correct: "overcast" },
    { word: "dry", choices: ["arid", "parched", "humid", "dusty"], correct: "humid" },
    { word: "mild", choices: ["gentle", "soft", "extreme", "calm"], correct: "extreme" },
  ],
  hobbiesAndFreeTime: [
    { word: "active", choices: ["energetic", "lazy", "busy", "fast"], correct: "lazy" },
    { word: "exciting", choices: ["thrilling", "fun", "boring", "lively"], correct: "boring" },
    { word: "relax", choices: ["unwind", "rest", "work", "sleep"], correct: "work" },
    { word: "begin", choices: ["start", "launch", "finish", "open"], correct: "finish" },
    { word: "buy", choices: ["purchase", "collect", "sell", "own"], correct: "sell" },
    { word: "win", choices: ["succeed", "triumph", "lose", "achieve"], correct: "lose" },
    { word: "easy", choices: ["simple", "basic", "difficult", "light"], correct: "difficult" },
    { word: "join", choices: ["enter", "start", "quit", "begin"], correct: "quit" },
    { word: "build", choices: ["create", "make", "destroy", "form"], correct: "destroy" },
    { word: "remember", choices: ["recall", "recognize", "forget", "memorize"], correct: "forget" },
  ],
};

export default ANTONYMS_TOPICS;
