// Vocabulary category, Antonyms game: topic sets beyond the sample.
// Same shape as antonymsGameData.js -- [{ word, choices: [4], correct }].
const ANTONYMS_TOPICS = {
  feelings: [
    { word: "happy", choices: ["glad", "sad", "proud", "calm"], correct: "sad" },
    { word: "calm", choices: ["peaceful", "angry", "soft", "neat"], correct: "angry" },
    { word: "brave", choices: ["strong", "afraid", "bright", "polite"], correct: "afraid" },
    { word: "angry", choices: ["cheerful", "mad", "tired", "rough"], correct: "cheerful" },
    { word: "tired", choices: ["sleepy", "energetic", "sweet", "heavy"], correct: "energetic" },
    { word: "nervous", choices: ["anxious", "relaxed", "friendly", "thin"], correct: "relaxed" },
    { word: "upset", choices: ["unhappy", "pleased", "noisy", "lazy"], correct: "pleased" },
    { word: "proud", choices: ["ashamed", "kind", "smooth", "empty"], correct: "ashamed" },
    { word: "lonely", choices: ["alone", "social", "bitter", "stale"], correct: "social" },
    { word: "surprised", choices: ["amazed", "expected", "rough", "helpful"], correct: "expected" },
  ],
  dailyActions: [
    { word: "begin", choices: ["wait", "start", "end", "carry"], correct: "end" },
    { word: "help", choices: ["assist", "harm", "answer", "move"], correct: "harm" },
    { word: "finish", choices: ["close", "break", "start", "clean"], correct: "start" },
    { word: "ask", choices: ["reply", "tell", "borrow", "stand"], correct: "tell" },
    { word: "answer", choices: ["ask", "reply", "finish", "remember"], correct: "ask" },
    { word: "buy", choices: ["purchase", "sell", "smile", "hide"], correct: "sell" },
    { word: "fix", choices: ["damage", "repair", "learn", "arrive"], correct: "damage" },
    { word: "choose", choices: ["select", "reject", "open", "wash"], correct: "reject" },
    { word: "show", choices: ["display", "hide", "follow", "climb"], correct: "hide" },
    { word: "leave", choices: ["depart", "stay", "touch", "spell"], correct: "stay" },
  ],
  describingPeople: [
    { word: "kind", choices: ["friendly", "rude", "quiet", "clever"], correct: "rude" },
    { word: "smart", choices: ["intelligent", "foolish", "careful", "brave"], correct: "foolish" },
    { word: "lazy", choices: ["tired", "active", "calm", "rich"], correct: "active" },
    { word: "honest", choices: ["truthful", "dishonest", "gentle", "bright"], correct: "dishonest" },
    { word: "brave", choices: ["courageous", "afraid", "polite", "healthy"], correct: "afraid" },
    { word: "rich", choices: ["wealthy", "poor", "loud", "shiny"], correct: "poor" },
    { word: "quiet", choices: ["silent", "noisy", "careful", "lucky"], correct: "noisy" },
    { word: "friendly", choices: ["cold", "welcoming", "patient", "easy"], correct: "cold" },
    { word: "funny", choices: ["amusing", "serious", "short", "fresh"], correct: "serious" },
    { word: "polite", choices: ["respectful", "rude", "smooth", "strong"], correct: "rude" },
  ],
  describingThings: [
    { word: "big", choices: ["large", "small", "thick", "wide"], correct: "small" },
    { word: "easy", choices: ["simple", "hard", "sweet", "full"], correct: "hard" },
    { word: "fast", choices: ["quick", "slow", "bright", "clean"], correct: "slow" },
    { word: "small", choices: ["tiny", "huge", "neat", "early"], correct: "huge" },
    { word: "hard", choices: ["difficult", "easy", "brave", "crowded"], correct: "easy" },
    { word: "clean", choices: ["tidy", "dirty", "quiet", "smooth"], correct: "dirty" },
    { word: "dirty", choices: ["messy", "clean", "pale", "lucky"], correct: "clean" },
    { word: "bright", choices: ["shiny", "dull", "soft", "rich"], correct: "dull" },
    { word: "strong", choices: ["powerful", "weak", "tiny", "warm"], correct: "weak" },
    { word: "quiet", choices: ["silent", "noisy", "empty", "gentle"], correct: "noisy" },
  ],
  schoolAndStudy: [
    { word: "correct", choices: ["wrong", "right", "early", "busy"], correct: "wrong" },
    { word: "pass", choices: ["win", "fail", "try", "review"], correct: "fail" },
    { word: "answer", choices: ["ask", "reply", "finish", "remember"], correct: "ask" },
    { word: "teacher", choices: ["instructor", "student", "office", "cousin"], correct: "student" },
    { word: "student", choices: ["pupil", "teacher", "artist", "driver"], correct: "teacher" },
    { word: "learn", choices: ["study", "forget", "borrow", "travel"], correct: "forget" },
    { word: "question", choices: ["reply", "query", "lesson", "ticket"], correct: "reply" },
    { word: "success", choices: ["error", "failure", "class", "station"], correct: "failure" },
    { word: "remember", choices: ["recall", "forget", "clean", "arrive"], correct: "forget" },
    { word: "simple", choices: ["easy", "complex", "brave", "healthy"], correct: "complex" },
  ],
  travelAndPlaces: [
    { word: "near", choices: ["far", "close", "low", "quiet"], correct: "far" },
    { word: "arrive", choices: ["leave", "enter", "travel", "stay"], correct: "leave" },
    { word: "open", choices: ["closed", "free", "smooth", "narrow"], correct: "closed" },
    { word: "far", choices: ["near", "bright", "safe", "tidy"], correct: "near" },
    { word: "enter", choices: ["leave", "arrive", "follow", "wonder"], correct: "leave" },
    { word: "depart", choices: ["stay", "reach", "carry", "borrow"], correct: "stay" },
    { word: "city", choices: ["village", "town", "map", "meal"], correct: "village" },
    { word: "full", choices: ["empty", "crowded", "modern", "local"], correct: "empty" },
    { word: "lost", choices: ["found", "narrow", "early", "simple"], correct: "found" },
    { word: "public", choices: ["private", "quick", "lucky", "noisy"], correct: "private" },
  ],
  homeAndDailyLife: [
    { word: "clean", choices: ["dirty", "tidy", "simple", "careful"], correct: "dirty" },
    { word: "dirty", choices: ["clean", "messy", "old", "strong"], correct: "clean" },
    { word: "open", choices: ["closed", "bright", "free", "smooth"], correct: "closed" },
    { word: "full", choices: ["empty", "rich", "busy", "soft"], correct: "empty" },
    { word: "rest", choices: ["work", "relax", "smile", "listen"], correct: "work" },
    { word: "quiet", choices: ["noisy", "peaceful", "sweet", "deep"], correct: "noisy" },
    { word: "early", choices: ["late", "fresh", "polite", "careful"], correct: "late" },
    { word: "busy", choices: ["free", "active", "shiny", "proud"], correct: "free" },
    { word: "safe", choices: ["dangerous", "strong", "neat", "cheap"], correct: "dangerous" },
    { word: "inside", choices: ["outside", "heavy", "straight", "friendly"], correct: "outside" },
  ],
};

export default ANTONYMS_TOPICS;
