// A rotating bank of real English-teaching corrections for the Library's
// "Today" page. One entry is featured as the day's headline; three others
// are drawn from the same pool as shorter "briefs." Selection is derived
// from the calendar date (see pickDaily in Library.jsx), so every visitor
// sees the same thing on a given day, and it changes automatically at
// midnight local time -- no database or admin panel needed.

const DAILY_CORRECTIONS = [
  {
    id: "have-gone",
    category: "Verb Tense",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I have " }, { wrong: "went" }, { right: "gone" }, { text: " to three countries this year." }],
    explain: [
      "After \"have,\" the verb takes its past participle, not its simple past form.",
      "Went is the simple past of go; gone is the participle — the form that pairs with have, has and had.",
    ],
  },
  {
    id: "married-to",
    category: "Prepositions",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "She got " }, { text: "married " }, { wrong: "with" }, { right: "to" }, { text: " him last year." }],
    explain: ["Married pairs with \"to,\" never \"with.\" A small word, a common slip."],
  },
  {
    id: "an-idea",
    category: "Articles",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I have " }, { wrong: "a" }, { right: "an" }, { text: " idea for the project." }],
    explain: ["Use \"an\" before a vowel sound, not a vowel letter — idea starts with the sound /aɪ/, so it needs \"an.\""],
  },
  {
    id: "much-advice",
    category: "Countable Nouns",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "She gave me " }, { wrong: "many advices" }, { right: "a lot of advice" }, { text: " before the interview." }],
    explain: ["Advice is uncountable in English — it has no plural. Use \"a piece of advice\" for one specific tip."],
  },
  {
    id: "easier",
    category: "Comparatives",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "This exercise is " }, { wrong: "more easier" }, { right: "easier" }, { text: " than the last one." }],
    explain: ["Short adjectives take \"-er,\" not \"more.\" Doubling up with both is the most common comparative error."],
  },
  {
    id: "everyone-is",
    category: "Subject-Verb Agreement",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "Everyone " }, { wrong: "are" }, { right: "is" }, { text: " happy with the new schedule." }],
    explain: ["Everyone, everybody, someone and nobody are grammatically singular, even though they describe groups of people."],
  },
  {
    id: "like-pizza",
    category: "Word Order",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "I " }, { wrong: "like very much pizza" }, { right: "like pizza very much" }, { text: "." }],
    explain: ["Intensifiers like \"very much\" usually go after the object, not between the verb and the object."],
  },
  {
    id: "turn-off-light",
    category: "Phrasal Verbs",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "Please " }, { wrong: "close" }, { right: "turn off" }, { text: " the light before you leave." }],
    explain: ["English uses \"turn off\" for electrical things (lights, TVs, phones), not \"close\" — that's a common calque from other languages."],
  },
  {
    id: "affect-effect",
    category: "Confusable Words",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "Missing class will " }, { wrong: "effect" }, { right: "affect" }, { text: " your grade." }],
    explain: ["Affect is (almost always) the verb — it means \"to influence.\" Effect is (almost always) the noun — a result."],
  },
  {
    id: "must-go",
    category: "Modal Verbs",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I " }, { wrong: "must to go" }, { right: "must go" }, { text: " now." }],
    explain: ["Modal verbs (must, can, should, will) are always followed by the bare infinitive — never add \"to.\""],
  },
  {
    id: "if-i-have",
    category: "Conditionals",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "If I " }, { wrong: "will have" }, { right: "have" }, { text: " time, I will call you." }],
    explain: ["In a first conditional, the \"if\" clause stays in present tense — \"will\" belongs only in the result clause."],
  },
  {
    id: "told-me",
    category: "Reported Speech",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "She " }, { wrong: "said me" }, { right: "told me" }, { text: " that she was busy." }],
    explain: ["\"Say\" doesn't take a direct object (say something), but \"tell\" does (tell someone something)."],
  },
  {
    id: "enjoy-swimming",
    category: "Gerunds & Infinitives",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I enjoy " }, { wrong: "to swim" }, { right: "swimming" }, { text: " on weekends." }],
    explain: ["Enjoy is always followed by a gerund (-ing form), never a \"to\" infinitive."],
  },
  {
    id: "where-are-you-going",
    category: "Question Formation",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "Where " }, { wrong: "you are going" }, { right: "are you going" }, { text: "?" }],
    explain: ["English questions invert the subject and auxiliary verb — the auxiliary comes before the subject, not after."],
  },
  {
    id: "born-on-monday",
    category: "Prepositions of Time",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I was born " }, { wrong: "in" }, { right: "on" }, { text: " a Monday." }],
    explain: ["Use \"on\" with days and dates, \"in\" with months, years, and seasons, and \"at\" with clock times."],
  },
  {
    id: "saw-yesterday",
    category: "Verb Tense",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I " }, { wrong: "have seen" }, { right: "saw" }, { text: " him yesterday." }],
    explain: ["A specific past time word like \"yesterday\" needs the simple past — present perfect can't be paired with a finished time."],
  },
  {
    id: "big-red-house",
    category: "Adjective Order",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "They live in " }, { wrong: "a red big house" }, { right: "a big red house" }, { text: "." }],
    explain: ["English adjectives follow a set order: opinion, size, age, shape, color, origin, material, then noun — size comes before color."],
  },
  {
    id: "a-lot-of-furniture",
    category: "Countable Nouns",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "We bought " }, { wrong: "many furnitures" }, { right: "a lot of furniture" }, { text: " for the new flat." }],
    explain: ["Furniture, like advice and information, is uncountable — no plural \"-s,\" and no \"many\" in front of it."],
  },
  {
    id: "lend-me",
    category: "Confusable Words",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "Can you " }, { wrong: "borrow" }, { right: "lend" }, { text: " me your pen?" }],
    explain: ["Borrow means to receive; lend means to give. The person asking for the pen needs \"lend,\" not \"borrow.\""],
  },
  {
    id: "depend-on",
    category: "Prepositions",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "It " }, { wrong: "depends of" }, { right: "depends on" }, { text: " the weather." }],
    explain: ["\"Depend\" is always followed by \"on\" in English, even though many languages use their equivalent of \"of.\""],
  },
  {
    id: "make-me-do",
    category: "Causative Verbs",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "My boss " }, { wrong: "makes me to work" }, { right: "makes me work" }, { text: " late." }],
    explain: ["Causative \"make\" takes the bare infinitive (no \"to\") — the same pattern as let and, informally, have."],
  },
  {
    id: "children",
    category: "Irregular Plurals",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "The " }, { wrong: "childs" }, { right: "children" }, { text: " are playing outside." }],
    explain: ["Child is one of a handful of English nouns with an irregular plural — no \"-s\" is added at all."],
  },
  {
    id: "actually-currently",
    category: "False Friends",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "I am " }, { wrong: "actually" }, { right: "currently" }, { text: " studying to be a nurse." }],
    explain: ["In English, \"actually\" means \"in fact\" (often correcting something), not \"right now.\" For that, use \"currently\" or \"at the moment.\""],
  },
  {
    id: "good-at",
    category: "Prepositions",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "She's really " }, { wrong: "good in" }, { right: "good at" }, { text: " math." }],
    explain: ["Skills and abilities use \"good at,\" not \"good in.\" (\"Good in\" is reserved for places — \"good in the kitchen.\")"],
  },
  {
    id: "arent-you",
    category: "Tag Questions",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "You're tired, " }, { wrong: "isn't it" }, { right: "aren't you" }, { text: "?" }],
    explain: ["A tag question echoes the subject and auxiliary of the main clause — it doesn't default to \"isn't it\" for everything."],
  },
  {
    id: "taller-than",
    category: "Comparatives",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "He is " }, { wrong: "as tall than" }, { right: "taller than" }, { text: " his brother." }],
    explain: ["\"As...as\" is for equal comparisons (as tall as); \"-er than\" is for unequal ones. The two structures can't mix."],
  },
  {
    id: "for-three-years",
    category: "Since / For",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I have lived here " }, { wrong: "since" }, { right: "for" }, { text: " three years." }],
    explain: ["Use \"for\" with a length of time (for three years) and \"since\" with a starting point in time (since 2023)."],
  },
  {
    id: "its-raining",
    category: "Its vs. It's",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "" }, { wrong: "Its" }, { right: "It's" }, { text: " raining outside today." }],
    explain: ["\"It's\" is the contraction of \"it is.\" \"Its\" (no apostrophe) shows possession, as in \"the dog wagged its tail.\""],
  },
  {
    id: "capital-i-monday",
    category: "Capitalization",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "" }, { wrong: "i study english on monday" }, { right: "I study English on Monday" }, { text: "." }],
    explain: ["Always capitalize \"I,\" language names, and days of the week — this is one of the fastest ways to make writing look more polished."],
  },
  {
    id: "look-forward-to",
    category: "Prepositions",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I look forward to " }, { wrong: "hear" }, { right: "hearing" }, { text: " from you." }],
    explain: ["The \"to\" in \"look forward to\" is a preposition here, not part of an infinitive — it needs a gerund after it, not a base verb."],
  },
  {
    id: "used-to-live",
    category: "Verb Tense",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I used to " }, { wrong: "lived" }, { right: "live" }, { text: " in Paris when I was young." }],
    explain: ["\"Used to\" is followed by the base form of the verb, not the past tense — the past is already carried by \"used to.\""],
  },
  {
    id: "arrived-at-airport",
    category: "Prepositions",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "We arrived " }, { wrong: "to" }, { right: "at" }, { text: " the airport an hour early." }],
    explain: ["\"Arrive\" pairs with \"at\" for buildings and small places, and \"in\" for cities and countries — never \"to.\""],
  },
  {
    id: "sun-in-the-east",
    category: "Articles",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "The sun rises in " }, { wrong: "east" }, { right: "the east" }, { text: "." }],
    explain: ["Unique things — the sun, the sky, the internet — and cardinal directions like \"the east\" always take \"the.\""],
  },
  {
    id: "much-information",
    category: "Countable Nouns",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "I need " }, { wrong: "many informations" }, { right: "a lot of information" }, { text: " before I can decide." }],
    explain: ["Information, like advice and furniture, is uncountable in English — no plural, and no \"many\" in front of it."],
  },
  {
    id: "most-beautiful",
    category: "Comparatives",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "That's the " }, { wrong: "beautifulest" }, { right: "most beautiful" }, { text: " beach I've ever seen." }],
    explain: ["Longer adjectives (three syllables or more) form the superlative with \"most,\" not by adding \"-est.\""],
  },
  {
    id: "news-is-good",
    category: "Subject-Verb Agreement",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "The news " }, { wrong: "are" }, { right: "is" }, { text: " good today." }],
    explain: ["News looks plural but is grammatically singular in English, along with words like mathematics and physics."],
  },
  {
    id: "always-late",
    category: "Word Order",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "I " }, { wrong: "always am" }, { right: "am always" }, { text: " late for the bus." }],
    explain: ["Adverbs of frequency like always, usually, and never go after the verb \"to be,\" but before other main verbs."],
  },
  {
    id: "look-after-the-baby",
    category: "Phrasal Verbs",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "Can you " }, { wrong: "look for" }, { right: "look after" }, { text: " the baby while I cook?" }],
    explain: ["\"Look after\" means to take care of someone; \"look for\" means to search for something — different meanings, easy to mix up."],
  },
  {
    id: "loose-lose",
    category: "Confusable Words",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "If we don't score soon, we'll " }, { wrong: "loose" }, { right: "lose" }, { text: " the game." }],
    explain: ["Lose (one \"o\") is the verb for not winning or misplacing something. Loose (two \"o\"s) is an adjective meaning not tight."],
  },
  {
    id: "should-have-gone",
    category: "Modal Verbs",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "You " }, { wrong: "should of gone" }, { right: "should have gone" }, { text: " to the doctor sooner." }],
    explain: ["\"Should've\" sounds like \"should of\" when spoken quickly, but the correct written form is always \"should have.\""],
  },
  {
    id: "if-i-were-you",
    category: "Conditionals",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "If I " }, { wrong: "was" }, { right: "were" }, { text: " you, I would apologize." }],
    explain: ["In hypothetical (second) conditionals, \"were\" is used for all subjects, including \"I\" and \"he/she/it\" — not \"was.\""],
  },
  {
    id: "he-said-he-was",
    category: "Reported Speech",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "He said he " }, { wrong: "is" }, { right: "was" }, { text: " tired." }],
    explain: ["When reporting speech in the past, present-tense verbs usually shift back one tense — \"is\" becomes \"was.\""],
  },
  {
    id: "stopped-to-smoke",
    category: "Gerunds & Infinitives",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "He stopped " }, { wrong: "to smoke" }, { right: "smoking" }, { text: " two years ago." }],
    explain: ["\"Stop + gerund\" means ending a habit; \"stop + to + verb\" means pausing to do something else. Here, it's the habit that ended."],
  },
  {
    id: "where-the-station-is",
    category: "Question Formation",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "Do you know where " }, { wrong: "is the station" }, { right: "the station is" }, { text: "?" }],
    explain: ["Inside an indirect question, word order goes back to normal statement order — subject before verb, no inversion."],
  },
  {
    id: "at-night-not-in",
    category: "Prepositions of Time",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "Owls hunt " }, { wrong: "in the night" }, { right: "at night" }, { text: "." }],
    explain: ["English uses \"at night,\" not \"in the night,\" as the standard time expression — one of a handful of fixed exceptions."],
  },
  {
    id: "old-french-wine",
    category: "Adjective Order",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "They served us " }, { wrong: "French old" }, { right: "old French" }, { text: " wine." }],
    explain: ["Age comes before origin in English adjective order — old French wine, not French old wine."],
  },
  {
    id: "people-not-persons",
    category: "Irregular Plurals",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "There were fifty " }, { wrong: "persons" }, { right: "people" }, { text: " at the meeting." }],
    explain: ["\"People\" is the everyday plural of \"person.\" \"Persons\" survives only in formal legal or official language."],
  },
  {
    id: "sensible-sensitive",
    category: "False Friends",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "She's very " }, { wrong: "sensible" }, { right: "sensitive" }, { text: " about her weight." }],
    explain: ["\"Sensible\" means practical or reasonable; \"sensitive\" means easily affected or hurt emotionally — a frequent false-friend mix-up."],
  },
  {
    id: "dont-you-tag",
    category: "Tag Questions",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "You don't like coffee, " }, { wrong: "don't you" }, { right: "do you" }, { text: "?" }],
    explain: ["A tag question flips the polarity of the main clause — a negative statement takes a positive tag, not a matching negative one."],
  },
  {
    id: "capital-nationalities",
    category: "Capitalization",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "She speaks " }, { wrong: "chinese" }, { right: "Chinese" }, { text: " and French." }],
    explain: ["Nationalities and languages are always capitalized in English, even mid-sentence."],
  },
  {
    id: "interested-in-not-on",
    category: "Prepositions",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "He's really " }, { wrong: "interested on" }, { right: "interested in" }, { text: " history." }],
    explain: ["\"Interested\" pairs with \"in,\" not \"on\" — a common slip carried over from other languages' prepositions."],
  },
  {
    id: "much-equipment",
    category: "Countable Nouns",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "The lab has " }, { wrong: "many equipments" }, { right: "a lot of equipment" }, { text: " for every experiment." }],
    explain: ["Equipment, like information and furniture, is uncountable — no plural \"-s\" and no \"many\" before it."],
  },
  {
    id: "give-it-to-me",
    category: "Word Order",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "Can you " }, { wrong: "give to me it" }, { right: "give it to me" }, { text: "?" }],
    explain: ["When the object is a pronoun (it, them, her), it goes directly after the verb, before the preposition phrase — give it to me, not give to me it."],
  },
  {
    id: "than-then",
    category: "Confusable Words",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "She's taller " }, { wrong: "then" }, { right: "than" }, { text: " her brother." }],
    explain: ["\"Than\" is for comparisons (taller than); \"then\" is for time or sequence (first this, then that) — they sound similar but do different jobs."],
  },
  {
    id: "give-up-smoking",
    category: "Phrasal Verbs",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "He finally " }, { wrong: "gave up to smoke" }, { right: "gave up smoking" }, { text: " last year." }],
    explain: ["\"Give up\" is followed by a gerund, never a \"to\" infinitive, when it means quitting a habit."],
  },
  {
    id: "meeting-tomorrow",
    category: "Verb Tense",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I " }, { wrong: "am meet" }, { right: "am meeting" }, { text: " him at the airport tomorrow." }],
    explain: ["For fixed future plans, use the present continuous — am/is/are + verb-ing — not the bare present tense after \"am.\""],
  },
  {
    id: "afraid-of-spiders",
    category: "Prepositions",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "My sister is " }, { wrong: "afraid from" }, { right: "afraid of" }, { text: " spiders." }],
    explain: ["\"Afraid\" is always followed by \"of,\" not \"from\" — a common substitution from other languages' equivalent prepositions."],
  },
  {
    id: "bananas-no-apostrophe",
    category: "Punctuation",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "We bought some " }, { wrong: "banana's" }, { right: "bananas" }, { text: " at the market." }],
    explain: ["An apostrophe before \"s\" shows possession or a contraction, never a simple plural — bananas needs no apostrophe at all."],
  },
  {
    id: "a-few-a-little",
    category: "Quantifiers",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I have " }, { wrong: "a little" }, { right: "a few" }, { text: " friends in this city." }],
    explain: ["\"A few\" is for countable nouns (a few friends); \"a little\" is for uncountable nouns (a little time) — they aren't interchangeable."],
  },
  {
    id: "mine-not-my",
    category: "Possessives",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "This book is " }, { wrong: "my" }, { right: "mine" }, { text: "." }],
    explain: ["Possessive pronouns like mine, yours, and hers stand alone, without a following noun — \"my\" always needs a noun right after it (my book)."],
  },
];

export default DAILY_CORRECTIONS;
