// A rotating bank of real English-teaching corrections for the Library's
// "Today" page. One entry is featured as the day's headline; three others
// are drawn from the same pool as shorter "briefs." Selection is derived
// from the calendar date (see pickDaily in Library.jsx), so every visitor
// sees the same thing on a given day, and it changes automatically at
// midnight local time -- no database or admin panel needed.

const DAILY_CORRECTIONS = [
  {
    id: "have-gone",
    category: "Verb Tense",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I have " }, { wrong: "went" }, { right: "gone" }, { text: " to three countries this year." }],
    explain: [
      "After \"have,\" the verb takes its past participle, not its simple past form.",
      "Went is the simple past of go; gone is the participle — the form that pairs with have, has and had.",
    ],
  },
  {
    id: "married-to",
    category: "Prepositions",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "She got " }, { text: "married " }, { wrong: "with" }, { right: "to" }, { text: " him last year." }],
    explain: ["Married pairs with \"to,\" never \"with.\" A small word, a common slip."],
  },
  {
    id: "an-idea",
    category: "Articles",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I have " }, { wrong: "a" }, { right: "an" }, { text: " idea for the project." }],
    explain: ["Use \"an\" before a vowel sound, not a vowel letter — idea starts with the sound /aɪ/, so it needs \"an.\""],
  },
  {
    id: "much-advice",
    category: "Countable Nouns",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "She gave me " }, { wrong: "many advices" }, { right: "a lot of advice" }, { text: " before the interview." }],
    explain: ["Advice is uncountable in English — it has no plural. Use \"a piece of advice\" for one specific tip."],
  },
  {
    id: "easier",
    category: "Comparatives",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "This exercise is " }, { wrong: "more easier" }, { right: "easier" }, { text: " than the last one." }],
    explain: ["Short adjectives take \"-er,\" not \"more.\" Doubling up with both is the most common comparative error."],
  },
  {
    id: "everyone-is",
    category: "Subject-Verb Agreement",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "Everyone " }, { wrong: "are" }, { right: "is" }, { text: " happy with the new schedule." }],
    explain: ["Everyone, everybody, someone and nobody are grammatically singular, even though they describe groups of people."],
  },
  {
    id: "like-pizza",
    category: "Word Order",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "I " }, { wrong: "like very much pizza" }, { right: "like pizza very much" }, { text: "." }],
    explain: ["Intensifiers like \"very much\" usually go after the object, not between the verb and the object."],
  },
  {
    id: "turn-off-light",
    category: "Phrasal Verbs",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "Please " }, { wrong: "close" }, { right: "turn off" }, { text: " the light before you leave." }],
    explain: ["English uses \"turn off\" for electrical things (lights, TVs, phones), not \"close\" — that's a common calque from other languages."],
  },
  {
    id: "affect-effect",
    category: "Confusable Words",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "Missing class will " }, { wrong: "effect" }, { right: "affect" }, { text: " your grade." }],
    explain: ["Affect is (almost always) the verb — it means \"to influence.\" Effect is (almost always) the noun — a result."],
  },
  {
    id: "must-go",
    category: "Modal Verbs",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I " }, { wrong: "must to go" }, { right: "must go" }, { text: " now." }],
    explain: ["Modal verbs (must, can, should, will) are always followed by the bare infinitive — never add \"to.\""],
  },
  {
    id: "if-i-have",
    category: "Conditionals",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "If I " }, { wrong: "will have" }, { right: "have" }, { text: " time, I will call you." }],
    explain: ["In a first conditional, the \"if\" clause stays in present tense — \"will\" belongs only in the result clause."],
  },
  {
    id: "told-me",
    category: "Reported Speech",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "She " }, { wrong: "said me" }, { right: "told me" }, { text: " that she was busy." }],
    explain: ["\"Say\" doesn't take a direct object (say something), but \"tell\" does (tell someone something)."],
  },
  {
    id: "enjoy-swimming",
    category: "Gerunds & Infinitives",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I enjoy " }, { wrong: "to swim" }, { right: "swimming" }, { text: " on weekends." }],
    explain: ["Enjoy is always followed by a gerund (-ing form), never a \"to\" infinitive."],
  },
  {
    id: "where-are-you-going",
    category: "Question Formation",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "Where " }, { wrong: "you are going" }, { right: "are you going" }, { text: "?" }],
    explain: ["English questions invert the subject and auxiliary verb — the auxiliary comes before the subject, not after."],
  },
  {
    id: "born-on-monday",
    category: "Prepositions of Time",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I was born " }, { wrong: "in" }, { right: "on" }, { text: " a Monday." }],
    explain: ["Use \"on\" with days and dates, \"in\" with months, years, and seasons, and \"at\" with clock times."],
  },
  {
    id: "saw-yesterday",
    category: "Verb Tense",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I " }, { wrong: "have seen" }, { right: "saw" }, { text: " him yesterday." }],
    explain: ["A specific past time word like \"yesterday\" needs the simple past — present perfect can't be paired with a finished time."],
  },
  {
    id: "big-red-house",
    category: "Adjective Order",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "They live in " }, { wrong: "a red big house" }, { right: "a big red house" }, { text: "." }],
    explain: ["English adjectives follow a set order: opinion, size, age, shape, color, origin, material, then noun — size comes before color."],
  },
  {
    id: "a-lot-of-furniture",
    category: "Countable Nouns",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "We bought " }, { wrong: "many furnitures" }, { right: "a lot of furniture" }, { text: " for the new flat." }],
    explain: ["Furniture, like advice and information, is uncountable — no plural \"-s,\" and no \"many\" in front of it."],
  },
  {
    id: "lend-me",
    category: "Confusable Words",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "Can you " }, { wrong: "borrow" }, { right: "lend" }, { text: " me your pen?" }],
    explain: ["Borrow means to receive; lend means to give. The person asking for the pen needs \"lend,\" not \"borrow.\""],
  },
  {
    id: "depend-on",
    category: "Prepositions",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "It " }, { wrong: "depends of" }, { right: "depends on" }, { text: " the weather." }],
    explain: ["\"Depend\" is always followed by \"on\" in English, even though many languages use their equivalent of \"of.\""],
  },
  {
    id: "make-me-do",
    category: "Causative Verbs",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "My boss " }, { wrong: "makes me to work" }, { right: "makes me work" }, { text: " late." }],
    explain: ["Causative \"make\" takes the bare infinitive (no \"to\") — the same pattern as let and, informally, have."],
  },
  {
    id: "children",
    category: "Irregular Plurals",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "The " }, { wrong: "childs" }, { right: "children" }, { text: " are playing outside." }],
    explain: ["Child is one of a handful of English nouns with an irregular plural — no \"-s\" is added at all."],
  },
  {
    id: "actually-currently",
    category: "False Friends",
    hue: "vocab",
    icon: "📚",
    sentence: [{ text: "I am " }, { wrong: "actually" }, { right: "currently" }, { text: " studying to be a nurse." }],
    explain: ["In English, \"actually\" means \"in fact\" (often correcting something), not \"right now.\" For that, use \"currently\" or \"at the moment.\""],
  },
  {
    id: "good-at",
    category: "Prepositions",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "She's really " }, { wrong: "good in" }, { right: "good at" }, { text: " math." }],
    explain: ["Skills and abilities use \"good at,\" not \"good in.\" (\"Good in\" is reserved for places — \"good in the kitchen.\")"],
  },
  {
    id: "arent-you",
    category: "Tag Questions",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "You're tired, " }, { wrong: "isn't it" }, { right: "aren't you" }, { text: "?" }],
    explain: ["A tag question echoes the subject and auxiliary of the main clause — it doesn't default to \"isn't it\" for everything."],
  },
  {
    id: "taller-than",
    category: "Comparatives",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "He is " }, { wrong: "as tall than" }, { right: "taller than" }, { text: " his brother." }],
    explain: ["\"As...as\" is for equal comparisons (as tall as); \"-er than\" is for unequal ones. The two structures can't mix."],
  },
  {
    id: "for-three-years",
    category: "Since / For",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I have lived here " }, { wrong: "since" }, { right: "for" }, { text: " three years." }],
    explain: ["Use \"for\" with a length of time (for three years) and \"since\" with a starting point in time (since 2023)."],
  },
  {
    id: "its-raining",
    category: "Its vs. It's",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "" }, { wrong: "Its" }, { right: "It's" }, { text: " raining outside today." }],
    explain: ["\"It's\" is the contraction of \"it is.\" \"Its\" (no apostrophe) shows possession, as in \"the dog wagged its tail.\""],
  },
  {
    id: "capital-i-monday",
    category: "Capitalization",
    hue: "writing",
    icon: "✍️",
    sentence: [{ text: "" }, { wrong: "i study english on monday" }, { right: "I study English on Monday" }, { text: "." }],
    explain: ["Always capitalize \"I,\" language names, and days of the week — this is one of the fastest ways to make writing look more polished."],
  },
  {
    id: "look-forward-to",
    category: "Prepositions",
    hue: "grammar",
    icon: "🔤",
    sentence: [{ text: "I look forward to " }, { wrong: "hear" }, { right: "hearing" }, { text: " from you." }],
    explain: ["The \"to\" in \"look forward to\" is a preposition here, not part of an infinitive — it needs a gerund after it, not a base verb."],
  },
];

export default DAILY_CORRECTIONS;
