// Ignite (A1 Teens) lesson content, data-driven -- keyed "unit-lesson".
// Converted from IGNITEA1TEENS.docx. Unit 1 Lesson 1 is the separate,
// bespoke TeensSayHelloLesson.jsx (built earlier); everything here is
// rendered by the generic IgniteLesson.jsx player. Each unit's 5th lesson
// is "Unit Review" -- the docx's own capstone/summative lesson, no new
// language, matches the locked "5 teaching + test" shape under a
// different real name.

export const IGNITE_A1_LESSONS = {
  "1-2": {
    slides: [
      { type: "title", stage: "Unit 1 · Lesson 2", eyebrow: "A1 · Ignite", title: "Questions and Answers", subtitle: "Ask and answer basic introduction questions." },
      { type: "vocab", stage: "Ask & Answer", heading: "Five Questions", subheading: "New questions to ask someone new", items: [{ label: "What's your name?" }, { label: "How old are you?" }, { label: "Where are you from?" }, { label: "Favorite color?" }, { label: "Favorite food?" }] },
      { type: "examples", stage: "Learn It", heading: "Question → Answer", subheading: "Notice the pattern", rows: [["What's your name?", "My name is Anna."], ["Where are you from?", "I'm from Korea."]] },
      { type: "dialogue", stage: "Try It", heading: "Ask, Then Answer", subheading: "Then reverse it", turns: [{ who: "teacher", text: "I'm from Japan." }, { who: "student", text: "Where are you from?" }] },
      { type: "dialogue", stage: "Question Detective", heading: "Question Detective", subheading: "Discover five things about a mystery person", turns: [{ who: "student", text: "What's your name?" }, { who: "teacher", text: "I'm Leo." }, { who: "student", text: "How old are you?" }, { who: "teacher", text: "I'm 15." }] },
      { type: "practice", stage: "Exit Check", heading: "Ask Three Questions", subheading: "Ask your teacher independently, no help", line: "___? ___? ___?" },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now ask and answer basic questions about yourself. Next up: spelling and numbers." },
    ],
  },
  "1-3": {
    slides: [
      { type: "title", stage: "Unit 1 · Lesson 3", eyebrow: "A1 · Ignite", title: "Spelling and Numbers", subtitle: "Spell your name and say numbers 1-20." },
      { type: "vocab", stage: "Getting Ready", heading: "The Alphabet", subheading: "A, B, C... spelled out loud", items: [{ label: "A-B-C" }, { label: "How do you spell that?" }] },
      { type: "examples", stage: "Learn It", heading: "Spell It Out", subheading: "Letter by letter", rows: [["How do you spell your name?", "A-L-E-X."], ["How old are you?", "I'm 14."]] },
      { type: "dialogue", stage: "Try It", heading: "Spell & Count", subheading: "Ask and answer", turns: [{ who: "teacher", text: "How do you spell your name?" }, { who: "student", text: "S-A-M." }, { who: "teacher", text: "How old are you?" }, { who: "student", text: "I'm 13." }] },
      { type: "dialogue", stage: "Spell It Challenge", heading: "Spell It Challenge", subheading: "Spell a mystery name letter by letter, student writes it down", turns: [{ who: "teacher", text: "M-A-R-C-U-S." }, { who: "student", text: "Is your name Marcus?" }, { who: "teacher", text: "Yes! And I'm sixteen." }] },
      { type: "practice", stage: "Exit Check", heading: "Spell & Say", subheading: "Spell your own name and say your age", line: "My name is ___. It's spelled ___. I'm ___ years old." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now spell your name and share your age with numbers. Next up: meeting someone new." },
    ],
  },
  "1-4": {
    slides: [
      { type: "title", stage: "Unit 1 · Lesson 4", eyebrow: "A1 · Ignite", title: "Meeting Someone New", subtitle: "Put greetings, questions, and spelling together in one conversation." },
      { type: "vocab", stage: "Getting Ready", heading: "Everything So Far", subheading: "Greet, name, spell, age, country", items: [{ label: "Hi!" }, { label: "Name?" }, { label: "Spell it" }, { label: "Age?" }, { label: "From?" }] },
      { type: "examples", stage: "Learn It", heading: "One Full Conversation", subheading: "All the pieces together", rows: [["Hi! What's your name?", "Hi! I'm Mia."], ["How do you spell that?", "M-I-A."]] },
      { type: "dialogue", stage: "Try It", heading: "Full Conversation Practice", subheading: "Greet, ask, spell, and answer", turns: [{ who: "teacher", text: "Hi! I'm Daniel." }, { who: "student", text: "Nice to meet you! How old are you?" }, { who: "teacher", text: "I'm 15. And you?" }] },
      { type: "dialogue", stage: "Meet a Stranger", heading: "Meet a Stranger", subheading: "A whole first meeting, start to finish", turns: [{ who: "teacher", text: "Hello, I don't think we've met." }, { who: "student", text: "Hi! I'm ___. Nice to meet you." }, { who: "teacher", text: "Where are you from?" } ] },
      { type: "practice", stage: "Exit Check", heading: "Meet Someone New", subheading: "A complete first-meeting conversation, on your own", line: "Hi! I'm ___. I'm from ___. I'm ___ years old." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now handle a full first-meeting conversation on your own. Next up: Unit Review." },
    ],
  },
  "1-5": {
    slides: [
      { type: "title", stage: "Unit 1 · Unit Review", eyebrow: "A1 · Ignite", title: "Unit Review", subtitle: "Complete a first-meeting conversation independently. No new language today." },
      { type: "vocab", stage: "Warm-Up", heading: "Quick-Fire Review", subheading: "Answer fast", items: [{ label: "What's your name?" }, { label: "How old are you?" }, { label: "Where are you from?" }, { label: "How do you spell it?" }] },
      { type: "examples", stage: "Review", heading: "Greet → Name → Spell → Age → Country", subheading: "The whole unit in one chain", rows: [["What's your name?", "My name is Alex."], ["How do you spell that?", "A-L-E-X."]] },
      { type: "dialogue", stage: "Controlled Review", heading: "Choose the Response", subheading: "Pick the right answer for each situation", turns: [{ who: "teacher", text: "How do you spell that?" }, { who: "student", text: "A-L-E-X." }] },
      { type: "dialogue", stage: "The First Meeting Final Challenge", heading: "Final Challenge: Round 1", subheading: "Guided — follow the roadmap: HELLO → NAME → SPELL → AGE → FROM → NICE TO MEET", turns: [{ who: "teacher", text: "Hi!" }, { who: "student", text: "Hi! I'm ___. N-A-M-E. I'm ___ years old, from ___. Nice to meet you!" }] },
      { type: "dialogue", stage: "Final Challenge: Round 2 & 3", heading: "No Roadmap, Then a Surprise", subheading: "Remember it all yourself, then meet a new student at school", turns: [{ who: "teacher", text: "Hello! Nice to meet you." }, { who: "student", text: "Hi! I'm ___. Nice to meet you too!" } ] },
      { type: "landing", stage: "Unit Complete!", heading: "Unit 1 Complete!", caption: "You can greet someone, ask and answer questions, spell your name, and handle a full first meeting on your own." },
    ],
  },
  "2-1": {
    slides: [
      { type: "title", stage: "Unit 2 · Lesson 1", eyebrow: "A1 · Ignite", title: "My Family", subtitle: "Name basic family members." },
      { type: "vocab", stage: "Getting Ready", heading: "Family Words", subheading: "New words for this unit", items: [{ label: "mom" }, { label: "dad" }, { label: "brother" }, { label: "sister" }, { label: "grandma" }, { label: "grandpa" }] },
      { type: "examples", stage: "Learn It", heading: "This Is My...", subheading: "Point and name", rows: [["Who is this?", "This is the mother."], ["Show me the brother.", "This is my brother."]] },
      { type: "dialogue", stage: "Try It", heading: "Who Is This?", subheading: "Identify each family member", turns: [{ who: "teacher", text: "Who is this?" }, { who: "student", text: "This is the mother." }, { who: "teacher", text: "Show me the brother." }] },
      { type: "dialogue", stage: "Family Tree Mystery", heading: "Family Tree Mystery", subheading: "The Park Family: Dad David, Mom Lisa, Brother Max, Sister Emma", turns: [{ who: "teacher", text: "I'm a girl. I'm Max's sister. Who am I?" }, { who: "student", text: "Emma!" }, { who: "teacher", text: "Do you have a brother or a sister?" }] },
      { type: "practice", stage: "Exit Check", heading: "Name Five", subheading: "Name each family member without help", line: "This is my ___. This is my ___. This is my ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now name the people in a family. Next up: talking about them." },
    ],
  },
  "2-2": {
    slides: [
      { type: "title", stage: "Unit 2 · Lesson 2", eyebrow: "A1 · Ignite", title: "Talking About Family", subtitle: "Say simple facts about family members." },
      { type: "vocab", stage: "Getting Ready", heading: "I Have...", subheading: "New patterns for this unit", items: [{ label: "I have one brother." }, { label: "His name is..." }, { label: "Her name is..." }, { label: "He is ___ years old." }] },
      { type: "examples", stage: "Learn It", heading: "Build a Fact", subheading: "Relationship + name + age", rows: [["Sophie, sister, 13", "She is my sister. Her name is Sophie. She is 13."]] },
      { type: "dialogue", stage: "Try It", heading: "Give the Facts", subheading: "Turn information into sentences", turns: [{ who: "teacher", text: "Sophie. Sister. 13." }, { who: "student", text: "She is my sister. Her name is Sophie. She is 13 years old." }] },
      { type: "dialogue", stage: "Family Profile Cards", heading: "Family Profile Cards", subheading: "Maya, sister, 14, favorite color purple — some clues hidden each round", turns: [{ who: "teacher", text: "👧 Sister, 14. Tell me about her." }, { who: "student", text: "She is my sister. She is 14 years old." }, { who: "teacher", text: "Now: Jack, brother, 16." }] },
      { type: "practice", stage: "Exit Check", heading: "Talk About Family", subheading: "One family member, at least 3 facts, 20-30 seconds", line: "This is my ___. ___'s name is ___. ___ is ___ years old." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now share real facts about your family. Next up: describing people." },
    ],
  },
  "2-3": {
    slides: [
      { type: "title", stage: "Unit 2 · Lesson 3", eyebrow: "A1 · Ignite", title: "People I Know", subtitle: "Describe people with simple words." },
      { type: "vocab", stage: "Getting Ready", heading: "Appearance & Personality", subheading: "New describing words", items: [{ label: "tall / short" }, { label: "long hair / short hair" }, { label: "nice / funny" }, { label: "friendly / quiet" }] },
      { type: "message", stage: "Learn It", heading: "Is + Adjective, Has + Noun", subheading: "Two different patterns", lines: ["She *is* tall.", "She *has* long hair.", "He *is* funny."] },
      { type: "dialogue", stage: "Try It", heading: "Describe What You See", subheading: "Look at a person and describe them", turns: [{ who: "teacher", text: "What can you see?" }, { who: "student", text: "He is tall. He has short hair." }] },
      { type: "dialogue", stage: "Who Am I Describing?", heading: "Who Am I Describing?", subheading: "Alex tall/funny, Mia short/friendly, Ben quiet, Sara nice — guess from clues", turns: [{ who: "teacher", text: "This person is tall. This person has long hair. This person is friendly." }, { who: "student", text: "Mia!" }, { who: "teacher", text: "Now you describe someone for me." }] },
      { type: "practice", stage: "Exit Check", heading: "Describe One Person", subheading: "At least three simple sentences", line: "He/She is my ___. He/She is ___. He/She has ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now describe people you know. Next up: family questions." },
    ],
  },
  "2-4": {
    slides: [
      { type: "title", stage: "Unit 2 · Lesson 4", eyebrow: "A1 · Ignite", title: "Family Questions", subtitle: "Answer simple questions about family." },
      { type: "vocab", stage: "Getting Ready", heading: "Family Questions", subheading: "New questions for this unit", items: [{ label: "Do you have a brother?" }, { label: "How many sisters?" }, { label: "What's his/her name?" }, { label: "What is he/she like?" }] },
      { type: "examples", stage: "Learn It", heading: "Question → Answer", subheading: "The key patterns", rows: [["Do you have a brother?", "Yes, I do."], ["How many brothers do you have?", "I have two brothers."]] },
      { type: "dialogue", stage: "Try It", heading: "Ask, Then Match", subheading: "Answer, then match answers to questions", turns: [{ who: "teacher", text: "Do you have a sister?" }, { who: "student", text: "Yes, I do." }] },
      { type: "dialogue", stage: "Family Interview", heading: "Family Interview", subheading: "You interview the teacher's fictional character, then switch roles", turns: [{ who: "student", text: "Do you have a brother?" }, { who: "teacher", text: "Yes, I do." }, { who: "student", text: "What's his name?" }, { who: "teacher", text: "His name is Leo." }] },
      { type: "practice", stage: "Exit Check", heading: "Answer Independently", subheading: "3-4 random family questions", line: "Yes, I do. / No, I don't. I have ___ ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now ask and answer family questions confidently. Next up: Unit Review." },
    ],
  },
  "2-5": {
    slides: [
      { type: "title", stage: "Unit 2 · Unit Review", eyebrow: "A1 · Ignite", title: "Unit Review", subtitle: "Talk briefly about family using everything you've learned. No new language today." },
      { type: "vocab", stage: "Quick Review", heading: "Family → Facts → Description → Questions", subheading: "Everything from this unit", items: [{ label: "family members" }, { label: "numbers" }, { label: "ages" }, { label: "appearance" }, { label: "personality" }] },
      { type: "message", stage: "Language Review", heading: "Who? → Facts → Description", subheading: "Your speaking structure", lines: ["This is my brother. His name is Alex. He is *15* years old. He is *tall and funny*."] },
      { type: "dialogue", stage: "Controlled Practice", heading: "Talk About the Profile", subheading: "Use a fictional profile to build sentences", turns: [{ who: "teacher", text: "Sophie, sister, 13, funny. Tell me about her." }, { who: "student", text: "This is my sister. Her name is Sophie. She is 13. She is funny." }] },
      { type: "dialogue", stage: "My Family, My Story", heading: "My Family, My Story", subheading: "Choose real or fictional, prepare, then present 30-60 seconds", turns: [{ who: "student", text: "This is my family. This is my mom. Her name is Anna. She is 40 years old. She is friendly." }, { who: "teacher", text: "What's her name? How old is your brother?" } ] },
      { type: "practice", stage: "Exit Check", heading: "Tell Me About Your Family", subheading: "Speak independently for 30-60 seconds", line: "This is my family. This is my ___. ___'s name is ___. ___ is ___." },
      { type: "landing", stage: "Unit Complete!", heading: "Unit 2 Complete!", caption: "You can name family members, give facts, describe people, answer questions, and talk about your family." },
    ],
  },
  "3-1": {
    slides: [
      { type: "title", stage: "Unit 3 · Lesson 1", eyebrow: "A1 · Ignite", title: "School Subjects", subtitle: "Name basic school subjects." },
      { type: "vocab", stage: "Getting Ready", heading: "School Subjects", subheading: "New words for this unit", items: [{ label: "English" }, { label: "Math" }, { label: "Science" }, { label: "History" }, { label: "Art" }, { label: "PE" }] },
      { type: "examples", stage: "Learn It", heading: "This Is My Subject", subheading: "Name and complete", rows: [["I have ___.", "I have Math."], ["My favorite subject is ___.", "My favorite subject is English."]] },
      { type: "dialogue", stage: "Try It", heading: "Complete the Sentence", subheading: "Identify subjects and complete sentences", turns: [{ who: "teacher", text: "I have ___." }, { who: "student", text: "I have Science." }, { who: "teacher", text: "My favorite subject is ___." }] },
      { type: "dialogue", stage: "Subject Schedule Challenge", heading: "Subject Schedule Challenge", subheading: "Read, then recall a fictional school schedule", turns: [{ who: "teacher", text: "What do you have on Monday?" }, { who: "student", text: "I have Math and English." }, { who: "teacher", text: "What is your favorite subject?" }] },
      { type: "practice", stage: "Exit Check", heading: "Name Five Subjects", subheading: "Then say one sentence about a favorite", line: "I have ___, ___, and ___. My favorite subject is ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now name school subjects and say your favorite. Next up: your school day." },
    ],
  },
  "3-2": {
    slides: [
      { type: "title", stage: "Unit 3 · Lesson 2", eyebrow: "A1 · Ignite", title: "My School Day", subtitle: "Say simple sentences about your school day." },
      { type: "vocab", stage: "Getting Ready", heading: "My Day", subheading: "New patterns for this unit", items: [{ label: "I go to school at 7:30." }, { label: "I have lunch at 12." }, { label: "I go home at 4." }] },
      { type: "examples", stage: "Learn It", heading: "The School-Day Sequence", subheading: "Go to school → classes → lunch → classes → go home", rows: [["What time do you go to school?", "I go to school at 7:30."], ["What time is lunch?", "I have lunch at 12."]] },
      { type: "dialogue", stage: "Try It", heading: "Change the Time", subheading: "Give a time or subject, get a sentence back", turns: [{ who: "teacher", text: "8:00" }, { who: "student", text: "I go to school at 8:00." }] },
      { type: "dialogue", stage: "My School Day Timeline", heading: "My School Day Timeline", subheading: "Order the events, then build your own timeline", turns: [{ who: "teacher", text: "Put these in order: lunch, go home, go to school, classes." }, { who: "student", text: "I go to school. I have classes. I have lunch. I go home." }] },
      { type: "practice", stage: "Exit Check", heading: "A Day in My Life", subheading: "3-4 sentences about a school day", line: "I go to school at ___. I have ___ in the morning. I have lunch at ___. I go home at ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now describe your school day in order. Next up: teachers and classmates." },
    ],
  },
  "3-3": {
    slides: [
      { type: "title", stage: "Unit 3 · Lesson 3", eyebrow: "A1 · Ignite", title: "Teachers and Classmates", subtitle: "Describe people at school in simple terms." },
      { type: "vocab", stage: "Getting Ready", heading: "School People", subheading: "New words for this unit", items: [{ label: "teacher / classmate" }, { label: "strict / nice" }, { label: "tall / short" }, { label: "friendly / quiet" }] },
      { type: "message", stage: "Learn It", heading: "Is + Adjective, Has + Noun", subheading: "The same two patterns from Unit 2", lines: ["My teacher *is* nice.", "He *is* tall.", "My classmate *has* short hair."] },
      { type: "dialogue", stage: "Try It", heading: "Person + Adjective", subheading: "Turn a pair into a sentence", turns: [{ who: "teacher", text: "Teacher + funny." }, { who: "student", text: "The teacher is funny." }] },
      { type: "dialogue", stage: "School People Mystery", heading: "School People Mystery", subheading: "Guess from clues, then compare two people", turns: [{ who: "teacher", text: "This person is tall. This person is friendly." }, { who: "student", text: "Is it the teacher?" }, { who: "teacher", text: "Now compare: he is tall, but she is ___." }] },
      { type: "practice", stage: "Exit Check", heading: "Describe One Person", subheading: "3 sentences about a teacher or classmate", line: "My ___ is ___. He/She is ___. He/She has ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now describe teachers and classmates. Next up: school questions." },
    ],
  },
  "3-4": {
    slides: [
      { type: "title", stage: "Unit 3 · Lesson 4", eyebrow: "A1 · Ignite", title: "School Questions", subtitle: "Answer simple questions about school life." },
      { type: "vocab", stage: "Getting Ready", heading: "School Questions", subheading: "New questions for this unit", items: [{ label: "What's your favorite subject?" }, { label: "What time do you go to school?" }, { label: "Do you like school?" }, { label: "What is your school like?" }] },
      { type: "examples", stage: "Learn It", heading: "Question → Answer", subheading: "What information does each question want?", rows: [["What's your favorite subject?", "My favorite subject is Math."], ["Do you like school?", "Yes, I do."]] },
      { type: "dialogue", stage: "Try It", heading: "Answer in Random Order", subheading: "Use sentence starters if you need them", turns: [{ who: "teacher", text: "What time do you go to school?" }, { who: "student", text: "I go to school at 7:30." }] },
      { type: "dialogue", stage: "School Interview Challenge", heading: "School Interview Challenge", subheading: "You interview a fictional student, then ask a follow-up question", turns: [{ who: "teacher", text: "My favorite subject is Art." }, { who: "student", text: "Why do you like Art?" }, { who: "teacher", text: "Because it's fun. Now ask me another question." }] },
      { type: "practice", stage: "Exit Check", heading: "Answer Independently", subheading: "3 random questions", line: "My favorite subject is ___. I go to school at ___. Yes/No, I ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now answer questions about your school life. Next up: Unit Review." },
    ],
  },
  "3-5": {
    slides: [
      { type: "title", stage: "Unit 3 · Unit Review", eyebrow: "A1 · Ignite", title: "Unit Review", subtitle: "Speak briefly about school subjects and school life. No new language today." },
      { type: "vocab", stage: "Quick Start", heading: "Rapid-Fire Review", subheading: "Name a subject, a school person, an activity", items: [{ label: "Name a subject" }, { label: "Name a school person" }, { label: "Say a school-day activity" }, { label: "Describe a person" }] },
      { type: "message", stage: "Review", heading: "Your School-Talk Patterns", subheading: "Quick correction and review", lines: ["I have… My favorite subject is…", "I go to school at…", "He/She is… He/She has…"] },
      { type: "dialogue", stage: "Try It", heading: "Turn Prompts Into Sentences", subheading: "Math / 7:30 / teacher + funny / lunch", turns: [{ who: "teacher", text: "teacher + funny" }, { who: "student", text: "The teacher is funny." }] },
      { type: "dialogue", stage: "My School Life Challenge", heading: "My School Life Challenge", subheading: "Build a 45-60 second School Life Talk, then answer follow-ups", turns: [{ who: "student", text: "My school is big. My favorite subject is Math. I go to school at 7:30." }, { who: "teacher", text: "What do you do at lunch? Describe one person at your school." } ] },
      { type: "practice", stage: "Exit Check", heading: "Tell Me About Your School Life", subheading: "Favorite subject, school time, and describe one person", line: "My favorite subject is ___. I go to school at ___. My ___ is ___." },
      { type: "landing", stage: "Unit Complete!", heading: "Unit 3 Complete!", caption: "You can name subjects, describe your school day, describe school people, and answer school questions." },
    ],
  },
  "4-1": {
    slides: [
      { type: "title", stage: "Unit 4 · Lesson 1", eyebrow: "A1 · Ignite", title: "Friends and Words for People", subtitle: "Name words for friends and describe friendship." },
      { type: "vocab", stage: "Getting Ready", heading: "Words for Friends", subheading: "New words for this unit", items: [{ label: "friend / best friend" }, { label: "classmate / teammate" }, { label: "kind / helpful" }, { label: "funny / friendly" }] },
      { type: "examples", stage: "Learn It", heading: "He/She Is + Adjective", subheading: "Relationship + personality", rows: [["best friend + funny", "My best friend is funny."], ["classmate + kind", "My classmate is kind."]] },
      { type: "dialogue", stage: "Try It", heading: "Mix Relationship & Personality", subheading: "Turn a pair into a sentence", turns: [{ who: "teacher", text: "best friend + funny" }, { who: "student", text: "My best friend is funny." }] },
      { type: "dialogue", stage: "Friendship Match-Up", heading: "Friendship Match-Up", subheading: "Match friend profiles to clues, then create your own", turns: [{ who: "teacher", text: "This person is kind and helpful. Who is it?" }, { who: "student", text: "That's my classmate!" }, { who: "teacher", text: "Now choose the best friend for this character and explain why." }] },
      { type: "practice", stage: "Exit Check", heading: "Describe a Friend", subheading: "Relationship + 2 personality words + 1 extra detail", line: "My ___ is ___ and ___. ___ also ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now describe your friends. Next up: what friends like." },
    ],
  },
  "4-2": {
    slides: [
      { type: "title", stage: "Unit 4 · Lesson 2", eyebrow: "A1 · Ignite", title: "What Friends Like", subtitle: "Talk about a friend's likes using the simple present." },
      { type: "vocab", stage: "Getting Ready", heading: "He Likes / She Likes", subheading: "New patterns for this unit", items: [{ label: "He likes basketball." }, { label: "She doesn't like soccer." }, { label: "Does he like music?" }] },
      { type: "examples", stage: "Learn It", heading: "I Like, He/She Likes", subheading: "Watch the -s", rows: [["Mia + music", "Mia likes music."], ["I + video games", "I like video games."]] },
      { type: "dialogue", stage: "Try It", heading: "Positive and Negative", subheading: "Practice both forms", turns: [{ who: "teacher", text: "Mia + music" }, { who: "student", text: "Mia likes music." }, { who: "teacher", text: "Alex + soccer (no)" }, { who: "student", text: "Alex doesn't like soccer." }] },
      { type: "dialogue", stage: "Friend Likes Investigator", heading: "Friend Likes Investigator", subheading: "Three fictional friends — ask, remember, report", turns: [{ who: "teacher", text: "Who likes basketball?" }, { who: "student", text: "Alex likes basketball." }, { who: "student", text: "Does Alex like music too?" }, { who: "teacher", text: "No, he doesn't." }] },
      { type: "practice", stage: "Exit Check", heading: "What Does Your Friend Like?", subheading: "3 sentences about a fictional friend", line: "He/She likes ___. He/She likes ___. He/She doesn't like ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now talk about what your friends like. Next up: free-time activities." },
    ],
  },
  "4-3": {
    slides: [
      { type: "title", stage: "Unit 4 · Lesson 3", eyebrow: "A1 · Ignite", title: "Free Time Activities", subtitle: "Name common free-time activities." },
      { type: "vocab", stage: "Getting Ready", heading: "Free-Time Activities", subheading: "New words for this unit", items: [{ label: "play video games" }, { label: "watch movies" }, { label: "listen to music" }, { label: "hang out with friends" }, { label: "ride a bike" }] },
      { type: "examples", stage: "Learn It", heading: "I + Activity", subheading: "Name it, then use it in a sentence", rows: [["watch movies", "I watch movies."], ["listen to music", "I listen to music."]] },
      { type: "dialogue", stage: "Try It", heading: "Activity → Sentence", subheading: "Turn each activity into a sentence", turns: [{ who: "teacher", text: "watch movies" }, { who: "student", text: "I watch movies." }] },
      { type: "dialogue", stage: "Free-Time Choice Board", heading: "Free-Time Choice Board", subheading: "Choose activities for a fictional teen, then adapt to a new situation", turns: [{ who: "teacher", text: "Choose 3 activities for this teen and explain why." }, { who: "student", text: "He likes playing video games because it's fun." }, { who: "teacher", text: "It's raining. You have one free hour. What do you do?" }] },
      { type: "practice", stage: "Exit Check", heading: "Name Five Activities", subheading: "Then say which one you like most", line: "I like ___, ___, and ___. My favorite is ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now talk about free-time activities. Next up: friends and free time questions." },
    ],
  },
  "4-4": {
    slides: [
      { type: "title", stage: "Unit 4 · Lesson 4", eyebrow: "A1 · Ignite", title: "Friends and Free Time Questions", subtitle: "Ask and answer questions about friends and free time." },
      { type: "vocab", stage: "Getting Ready", heading: "Friend & Free-Time Questions", subheading: "New questions for this unit", items: [{ label: "Who is your best friend?" }, { label: "What does your friend like?" }, { label: "What do you do in your free time?" }, { label: "Do you like sports?" }] },
      { type: "examples", stage: "Learn It", heading: "Question → Answer", subheading: "What / Does / Do questions", rows: [["What do you do in your free time?", "I watch movies."], ["Does your friend like music?", "Yes, she does."]] },
      { type: "dialogue", stage: "Try It", heading: "Answer or Match", subheading: "Answer directly, or match answer to question", turns: [{ who: "teacher", text: "I like gaming." }, { who: "student", text: "What is your favorite free-time activity?" }] },
      { type: "dialogue", stage: "Free-Time Chat Show", heading: "Free-Time Chat Show", subheading: "You host — interview the guest, then ask a natural follow-up", turns: [{ who: "student", text: "Who is your best friend?" }, { who: "teacher", text: "My best friend is Alex. I like gaming." }, { who: "student", text: "What games do you like?" }] },
      { type: "practice", stage: "Exit Check", heading: "Answer & Ask", subheading: "3 random questions, then ask the teacher 1", line: "My best friend is ___. In my free time, I ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now ask and answer questions about friends and free time. Next up: Unit Review." },
    ],
  },
  "4-5": {
    slides: [
      { type: "title", stage: "Unit 4 · Unit Review", eyebrow: "A1 · Ignite", title: "Unit Review", subtitle: "Talk briefly about friends and free time. No new language today." },
      { type: "vocab", stage: "Quick Start", heading: "Rapid-Fire Review", subheading: "Name a friend, describe them, name activities", items: [{ label: "Name a type of friend" }, { label: "Describe a friend" }, { label: "Name 3 free-time activities" }, { label: "Say something a friend likes" }] },
      { type: "message", stage: "Review", heading: "Your Friends & Free-Time Patterns", subheading: "Quick correction and review", lines: ["He likes… She doesn't like…", "Does he/she like…?", "My friend is…"] },
      { type: "dialogue", stage: "Try It", heading: "Mixed Prompts", subheading: "friend + funny / friend + music / I + video games", turns: [{ who: "teacher", text: "she + basketball" }, { who: "student", text: "She likes basketball." }] },
      { type: "dialogue", stage: "My Friends & Free Time Story", heading: "My Friends & Free Time Story", subheading: "Build a 45-60 second talk, then retell it from memory", turns: [{ who: "student", text: "My friend Alex is funny. He likes basketball. We hang out and play video games together." }, { who: "teacher", text: "What do you like doing in your free time?" } ] },
      { type: "practice", stage: "Exit Check", heading: "Tell Me About a Friend", subheading: "Who they are, what they like, what you do together", line: "My friend is ___. He/She likes ___. We ___ together." },
      { type: "landing", stage: "Unit Complete!", heading: "Unit 4 Complete!", caption: "You can describe friends, talk about their likes, name free-time activities, and answer questions about both." },
    ],
  },
  "5-1": {
    slides: [
      { type: "title", stage: "Unit 5 · Lesson 1", eyebrow: "A1 · Ignite", title: "Hobbies and Interests", subtitle: "Name common hobbies and interests." },
      { type: "vocab", stage: "Getting Ready", heading: "Hobbies", subheading: "New words for this unit", items: [{ label: "reading" }, { label: "drawing" }, { label: "playing video games" }, { label: "photography" }, { label: "swimming" }] },
      { type: "examples", stage: "Learn It", heading: "My Hobby", subheading: "Name it, then say it", rows: [["drawing", "I like drawing."], ["video games", "I play video games."]] },
      { type: "dialogue", stage: "Try It", heading: "Hobby → Sentence", subheading: "Turn each hobby into a sentence", turns: [{ who: "teacher", text: "drawing" }, { who: "student", text: "I like drawing." }] },
      { type: "dialogue", stage: "Hobby Explorer", heading: "Hobby Explorer", subheading: "Explore a fictional teen's Hobby Room, then choose your own three", turns: [{ who: "teacher", text: "You have 30 minutes and want to do something creative. What hobby do you choose?" }, { who: "student", text: "I choose drawing." }, { who: "teacher", text: "Now, what 3 hobbies would go in your own Hobby Room?" }] },
      { type: "practice", stage: "Exit Check", heading: "Name Five Hobbies", subheading: "Then say one you like", line: "My hobbies are ___, ___, ___, ___, and ___. I like ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now name hobbies and interests. Next up: likes and dislikes." },
    ],
  },
  "5-2": {
    slides: [
      { type: "title", stage: "Unit 5 · Lesson 2", eyebrow: "A1 · Ignite", title: "I Like / I Don't Like", subtitle: "Express simple likes and dislikes about hobbies." },
      { type: "vocab", stage: "Getting Ready", heading: "Love → Like → Don't Like → Hate", subheading: "New patterns for this unit", items: [{ label: "I love playing games." }, { label: "I like reading." }, { label: "I don't like dancing." }, { label: "I hate cleaning." }] },
      { type: "examples", stage: "Learn It", heading: "Four Levels", subheading: "From love to hate", rows: [["drawing (love)", "I love drawing."], ["singing (hate)", "I hate singing."]] },
      { type: "dialogue", stage: "Try It", heading: "React to Each Hobby", subheading: "I like / I don't like / I love / I hate", turns: [{ who: "teacher", text: "dancing" }, { who: "student", text: "I don't like dancing." }] },
      { type: "dialogue", stage: "Like-O-Meter", heading: "Like-O-Meter", subheading: "LOVE ❤️ | LIKE 👍 | DON'T LIKE 👎 | HATE ❌ — place hobbies on the scale", turns: [{ who: "teacher", text: "Where does drawing go on your scale?" }, { who: "student", text: "Drawing goes on LOVE, because it's fun." }, { who: "teacher", text: "What about cleaning?" }] },
      { type: "practice", stage: "Exit Check", heading: "Likes and Dislikes", subheading: "2 things you like, 1 you don't, 1 favorite", line: "I like ___ and ___. I don't like ___. My favorite hobby is ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now express likes and dislikes about hobbies. Next up: interest questions." },
    ],
  },
  "5-3": {
    slides: [
      { type: "title", stage: "Unit 5 · Lesson 3", eyebrow: "A1 · Ignite", title: "Interest Questions", subtitle: "Ask and answer questions about interests." },
      { type: "vocab", stage: "Getting Ready", heading: "Hobby Questions", subheading: "New questions for this unit", items: [{ label: "What are your hobbies?" }, { label: "What's your favorite hobby?" }, { label: "What kind of music do you like?" }, { label: "How often do you do it?" }] },
      { type: "examples", stage: "Learn It", heading: "Answer → Question", subheading: "What question fits this answer?", rows: [["I like drawing.", "What do you like doing?"], ["I do it every day.", "How often do you do your hobby?"]] },
      { type: "dialogue", stage: "Try It", heading: "Create the Question", subheading: "Match the right question to the answer", turns: [{ who: "teacher", text: "I like drawing." }, { who: "student", text: "What do you like doing?" }] },
      { type: "dialogue", stage: "Hobby Detective", heading: "Hobby Detective", subheading: "Discover a fictional person's hobbies with fewer and fewer prompts", turns: [{ who: "student", text: "What are your hobbies?" }, { who: "teacher", text: "I like music and reading." }, { who: "student", text: "What kind of music do you like?" }] },
      { type: "practice", stage: "Exit Check", heading: "Ask and Answer", subheading: "Ask the teacher 2 questions, answer 3", line: "What are your hobbies? What's your favorite hobby?" },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now ask and answer interest questions. Next up: hobbies in real life." },
    ],
  },
  "5-4": {
    slides: [
      { type: "title", stage: "Unit 5 · Lesson 4", eyebrow: "A1 · Ignite", title: "Hobbies in Real Life", subtitle: "Describe when and how you do a hobby." },
      { type: "vocab", stage: "Getting Ready", heading: "When & How", subheading: "New phrases for this unit", items: [{ label: "after school" }, { label: "in the evening" }, { label: "on weekends" }, { label: "with my friends" }, { label: "every day" }] },
      { type: "message", stage: "Learn It", heading: "What + When + How", subheading: "Combine the three pieces", lines: ["I play basketball *after school*.", "I read *in the evening*, *at home*."] },
      { type: "dialogue", stage: "Try It", heading: "Three Prompts, One Sentence", subheading: "reading + evening + at home", turns: [{ who: "teacher", text: "reading + evening + at home" }, { who: "student", text: "I read in the evening at home." }] },
      { type: "dialogue", stage: "Hobby Day Planner", heading: "Hobby Day Planner", subheading: "Plan a fictional teen's routine, then adapt when it changes", turns: [{ who: "teacher", text: "Choose a hobby, when, and where." }, { who: "student", text: "She plays basketball after school with her friends." }, { who: "teacher", text: "Now she can't do it at home. What changes?" }] },
      { type: "practice", stage: "Exit Check", heading: "Describe One Hobby", subheading: "What + when + where/how", line: "I ___ ___ (when) ___ (where/how)." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now describe when and how you do a hobby. Next up: Unit Review." },
    ],
  },
  "5-5": {
    slides: [
      { type: "title", stage: "Unit 5 · Unit Review", eyebrow: "A1 · Ignite", title: "Unit Review", subtitle: "Talk briefly about hobbies and interests. No new language today." },
      { type: "vocab", stage: "Quick Start", heading: "Rapid-Fire Review", subheading: "Name hobbies, likes, dislikes, and when", items: [{ label: "Name 3 hobbies" }, { label: "Say something you like" }, { label: "Say something you don't like" }, { label: "Say when you do a hobby" }] },
      { type: "message", stage: "Review", heading: "Your Hobby Patterns", subheading: "Quick correction and review", lines: ["I like + -ing… I don't like + -ing…", "I do it after school. I do it on weekends."] },
      { type: "dialogue", stage: "Try It", heading: "Mixed Prompts", subheading: "reading + evening / basketball + friends", turns: [{ who: "teacher", text: "drawing + home" }, { who: "student", text: "I draw at home." }] },
      { type: "dialogue", stage: "My Hobby Profile", heading: "My Hobby Profile", subheading: "Build a 45-60 second profile, then present it again from memory", turns: [{ who: "student", text: "My favorite hobby is drawing. I like it because it's relaxing. I do it after school, at home." }, { who: "teacher", text: "Who do you do it with? What hobby don't you like?" } ] },
      { type: "practice", stage: "Exit Check", heading: "Tell Me About Your Hobbies", subheading: "Favorite hobby, when, who with, and one dislike", line: "My favorite hobby is ___. I do it ___, ___. I don't like ___." },
      { type: "landing", stage: "Unit Complete!", heading: "Unit 5 Complete!", caption: "You can name hobbies, express likes and dislikes, ask hobby questions, and describe your own routine." },
    ],
  },
  "6-1": {
    slides: [
      { type: "title", stage: "Unit 6 · Lesson 1", eyebrow: "A1 · Ignite", title: "My Daily Routine", subtitle: "Name common daily routine verbs." },
      { type: "vocab", stage: "Getting Ready", heading: "Routine Verbs", subheading: "New words for this unit", items: [{ label: "wake up" }, { label: "brush my teeth" }, { label: "eat breakfast" }, { label: "do homework" }, { label: "go to bed" }] },
      { type: "examples", stage: "Learn It", heading: "Action → Sentence", subheading: "Name it, then use it", rows: [["wake up", "I wake up."], ["eat breakfast", "I eat breakfast."]] },
      { type: "dialogue", stage: "Try It", heading: "Action → Sentence", subheading: "Turn each action into a sentence", turns: [{ who: "teacher", text: "wake up" }, { who: "student", text: "I wake up." }] },
      { type: "dialogue", stage: "Routine Detective", heading: "Routine Detective", subheading: "Discover a fictional teen's day, put mixed-up cards in order", turns: [{ who: "teacher", text: "This person eats breakfast. What probably happens next?" }, { who: "student", text: "They probably go to school." }, { who: "teacher", text: "Now describe the whole routine using 5 actions." }] },
      { type: "practice", stage: "Exit Check", heading: "Name Six Routine Verbs", subheading: "Then use 3 of them in sentences", line: "I ___. I ___. I ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now name daily routine actions. Next up: telling the time." },
    ],
  },
  "6-2": {
    slides: [
      { type: "title", stage: "Unit 6 · Lesson 2", eyebrow: "A1 · Ignite", title: "Time in My Day", subtitle: "Say simple routine times." },
      { type: "vocab", stage: "Getting Ready", heading: "Telling Time", subheading: "New phrases for this unit", items: [{ label: "seven o'clock" }, { label: "seven thirty" }, { label: "half past seven" }, { label: "eight fifteen" }] },
      { type: "examples", stage: "Learn It", heading: "Action + At + Time", subheading: "Connect routines to times", rows: [["wake up / 7:00", "I wake up at 7:00."], ["go to bed / 10:00", "I go to bed at 10:00."]] },
      { type: "dialogue", stage: "Try It", heading: "Routine + Time", subheading: "Combine an action and a time", turns: [{ who: "teacher", text: "eat breakfast / 7:30" }, { who: "student", text: "I eat breakfast at 7:30." }] },
      { type: "dialogue", stage: "Beat the Clock", heading: "Beat the Clock", subheading: "Build a fictional teen's schedule, then report it from memory", turns: [{ who: "teacher", text: "What time do you have lunch?" }, { who: "student", text: "I have lunch at 12:00." }, { who: "teacher", text: "Now, without looking, what time do you go to school?" }] },
      { type: "practice", stage: "Exit Check", heading: "Three Routine + Time Sentences", subheading: "Say 3 different routine actions with times", line: "I ___ at ___. I ___ at ___. I ___ at ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now tell time and connect it to your routine. Next up: your morning." },
    ],
  },
  "6-3": {
    slides: [
      { type: "title", stage: "Unit 6 · Lesson 3", eyebrow: "A1 · Ignite", title: "My Morning", subtitle: "Describe a simple morning routine, in order." },
      { type: "vocab", stage: "Getting Ready", heading: "Sequence Words", subheading: "New words for this unit", items: [{ label: "first" }, { label: "then" }, { label: "next" }, { label: "after that" }, { label: "finally" }] },
      { type: "message", stage: "Learn It", heading: "First → Then → Next → After That → Finally", subheading: "A 5-step morning routine", lines: ["*First*, I wake up. *Then*, I get up.", "I brush my teeth. *After that*, I get dressed.", "*Finally*, I go to school."] },
      { type: "dialogue", stage: "Try It", heading: "Put It in Order", subheading: "Mixed-up morning actions — order and describe them", turns: [{ who: "teacher", text: "Get dressed, wake up, eat breakfast, brush teeth. Put these in order." }, { who: "student", text: "First, I wake up. Then, I brush my teeth. After that, I get dressed. Finally, I eat breakfast." }] },
      { type: "dialogue", stage: "Morning Routine Remix", heading: "Morning Routine Remix", subheading: "Retell the routine, then handle a late-morning problem", turns: [{ who: "teacher", text: "You wake up late! What do you skip or change?" }, { who: "student", text: "I skip breakfast. First, I wake up, then I get dressed, finally I go to school." }] },
      { type: "practice", stage: "Exit Check", heading: "Describe Your Morning", subheading: "At least 4 actions and 2 sequence words", line: "First, I ___. Then, I ___. Finally, I ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now describe your morning routine in order. Next up: daily routine questions." },
    ],
  },
  "6-4": {
    slides: [
      { type: "title", stage: "Unit 6 · Lesson 4", eyebrow: "A1 · Ignite", title: "Daily Routine Questions", subtitle: "Ask and answer basic routine questions." },
      { type: "vocab", stage: "Getting Ready", heading: "Routine Questions", subheading: "New questions for this unit", items: [{ label: "What time do you wake up?" }, { label: "When do you do your homework?" }, { label: "Do you watch TV at night?" }] },
      { type: "examples", stage: "Learn It", heading: "Answer → Question", subheading: "What question fits this answer?", rows: [["I go to bed at 10:00.", "What time do you go to bed?"], ["I do my homework after school.", "When do you do your homework?"]] },
      { type: "dialogue", stage: "Try It", heading: "Create the Question", subheading: "Match the right question to the answer", turns: [{ who: "teacher", text: "I go to bed at 10:00." }, { who: "student", text: "What time do you go to bed?" }] },
      { type: "dialogue", stage: "Routine Interview Mission", heading: "Routine Interview Mission", subheading: "Discover a fictional teen's secret routine, then summarize it", turns: [{ who: "student", text: "What time do you wake up?" }, { who: "teacher", text: "I wake up at 6:30." }, { who: "student", text: "He wakes up at 6:30. What do you do next?" }] },
      { type: "practice", stage: "Exit Check", heading: "Ask and Answer", subheading: "Ask the teacher 2 questions, answer 3", line: "What time do you wake up? What do you do after school?" },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now ask and answer routine questions. Next up: Unit Review." },
    ],
  },
  "6-5": {
    slides: [
      { type: "title", stage: "Unit 6 · Unit Review", eyebrow: "A1 · Ignite", title: "Unit Review", subtitle: "Describe a simple daily routine. No new language today." },
      { type: "vocab", stage: "Quick Start", heading: "Rapid-Fire Review", subheading: "Verbs, times, morning, after-school", items: [{ label: "Name 3 routine verbs" }, { label: "Give a routine time" }, { label: "Say a morning activity" }, { label: "Say an after-school activity" }] },
      { type: "message", stage: "Review", heading: "Your Routine Patterns", subheading: "Quick correction and review", lines: ["I wake up at… I go to school at…", "I do homework after…", "First…, then…, finally…"] },
      { type: "dialogue", stage: "Try It", heading: "Mixed Prompts", subheading: "wake up + 7:00 / breakfast + 7:30", turns: [{ who: "teacher", text: "homework + after school" }, { who: "student", text: "I do homework after school." }] },
      { type: "dialogue", stage: "A Day in My Life", heading: "A Day in My Life", subheading: "Build a 45-60 second talk, then adapt it for a Saturday", turns: [{ who: "student", text: "I wake up at 7:00. I go to school at 8:00. After school, I do homework." }, { who: "teacher", text: "It's Saturday and you don't have school. What changes?" } ] },
      { type: "practice", stage: "Exit Check", heading: "Tell Me About Your Typical Day", subheading: "Wake-up time, after-school activity, bedtime", line: "I wake up at ___. After school, I ___. I go to bed at ___." },
      { type: "landing", stage: "Unit Complete!", heading: "Unit 6 Complete!", caption: "You can name routine actions, tell time, sequence your morning, and answer questions about your day." },
    ],
  },
  "7-1": {
    slides: [
      { type: "title", stage: "Unit 7 · Lesson 1", eyebrow: "A1 · Ignite", title: "My Room", subtitle: "Name common room objects and furniture." },
      { type: "vocab", stage: "Getting Ready", heading: "Room Objects", subheading: "New words for this unit", items: [{ label: "bed" }, { label: "desk" }, { label: "closet" }, { label: "bookshelf" }, { label: "mirror" }] },
      { type: "examples", stage: "Learn It", heading: "This Is / I Have", subheading: "Name each object", rows: [["What's this?", "It's a lamp."], ["What do you have?", "I have a chair."]] },
      { type: "dialogue", stage: "Try It", heading: "Guess the Object", subheading: "From a clue, name the object", turns: [{ who: "teacher", text: "You sleep on it." }, { who: "student", text: "A bed." }, { who: "teacher", text: "You put books on it." }] },
      { type: "dialogue", stage: "Room Builder Challenge", heading: "Room Builder Challenge", subheading: "Build a fictional room, then say what's missing", turns: [{ who: "teacher", text: "Choose 5 objects for the room." }, { who: "student", text: "A bed, a desk, a chair, a lamp, and a bookshelf." }, { who: "teacher", text: "I removed one object. What's missing?" }] },
      { type: "practice", stage: "Exit Check", heading: "Name Six Objects", subheading: "Then make 3 sentences", line: "This is my ___. I have a ___. I have a ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now name room objects. Next up: where things are." },
    ],
  },
  "7-2": {
    slides: [
      { type: "title", stage: "Unit 7 · Lesson 2", eyebrow: "A1 · Ignite", title: "In My Room", subtitle: "Say where things are using basic prepositions." },
      { type: "vocab", stage: "Getting Ready", heading: "Prepositions of Place", subheading: "New words for this unit", items: [{ label: "on / under" }, { label: "next to / near" }, { label: "behind" }, { label: "in front of" }] },
      { type: "examples", stage: "Learn It", heading: "Where Is It?", subheading: "Object + preposition + place", rows: [["The book is on the desk.", "Where is the book?"], ["The bag is under the chair.", "Where is the bag?"]] },
      { type: "dialogue", stage: "Try It", heading: "Identify or Ask", subheading: "Identify the location, or ask where it is", turns: [{ who: "teacher", text: "The lamp is next to the bed." }, { who: "student", text: "Where is the book?" }] },
      { type: "dialogue", stage: "Fix the Room", heading: "Fix the Room", subheading: "Objects are in strange places — identify, then correct", turns: [{ who: "teacher", text: "The pillow is under the desk. The shoes are on the bookshelf." }, { who: "student", text: "That's strange! The pillow should be on the bed." }, { who: "teacher", text: "Now you make 5 location sentences about the room." }] },
      { type: "practice", stage: "Exit Check", heading: "Where Is...?", subheading: "Answer 4 location questions in complete sentences", line: "The ___ is ___ the ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now say where things are in a room. Next up: describing your own space." },
    ],
  },
  "7-3": {
    slides: [
      { type: "title", stage: "Unit 7 · Lesson 3", eyebrow: "A1 · Ignite", title: "My Space", subtitle: "Describe your room in simple personal terms." },
      { type: "vocab", stage: "Getting Ready", heading: "Describing Words", subheading: "New words for this unit", items: [{ label: "big / small" }, { label: "clean / messy" }, { label: "comfortable" }, { label: "favorite" }] },
      { type: "message", stage: "Learn It", heading: "Make It Personal", subheading: "Adjectives + room vocabulary", lines: ["My room is *small*.", "I have a *big* desk.", "My favorite thing is *my bed*."] },
      { type: "dialogue", stage: "Try It", heading: "Complete the Sentence", subheading: "Fill in with your own room details", turns: [{ who: "teacher", text: "My room is ___." }, { who: "student", text: "My room is clean." }, { who: "teacher", text: "My favorite thing is ___." }] },
      { type: "dialogue", stage: "Room Makeover", heading: "Room Makeover", subheading: "Design a fictional teen's room, then adapt for a space problem", turns: [{ who: "teacher", text: "Choose 3 changes for this room." }, { who: "student", text: "I'll add a desk next to the window and change the color to blue." }, { who: "teacher", text: "There isn't much space! What do you change?" }] },
      { type: "practice", stage: "Exit Check", heading: "Describe Your Room", subheading: "3-4 sentences, real or fictional", line: "My room is ___. I have a ___. My favorite thing is ___ because ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now describe your room personally. Next up: room questions." },
    ],
  },
  "7-4": {
    slides: [
      { type: "title", stage: "Unit 7 · Lesson 4", eyebrow: "A1 · Ignite", title: "Room Questions", subtitle: "Answer simple questions about your room." },
      { type: "vocab", stage: "Getting Ready", heading: "Room Questions", subheading: "New questions for this unit", items: [{ label: "What is in your room?" }, { label: "Is your room big or small?" }, { label: "Where is your bed?" }, { label: "What do you do in your room?" }] },
      { type: "examples", stage: "Learn It", heading: "Question → Answer", subheading: "Short and complete answers", rows: [["What is your favorite thing in your room?", "My favorite thing is my computer."], ["Do you have a TV in your room?", "Yes, I do."]] },
      { type: "dialogue", stage: "Try It", heading: "Answer Fast", subheading: "Random questions, complete sentences", turns: [{ who: "teacher", text: "Where is your desk?" }, { who: "student", text: "My desk is next to the window." }] },
      { type: "dialogue", stage: "Room Q&A Ladder", heading: "Room Q&A Ladder", subheading: "Easy yes/no questions building up to open, personal follow-ups", turns: [{ who: "teacher", text: "Do you have a TV in your room?" }, { who: "student", text: "Yes, I do." }, { who: "teacher", text: "What do you like about your room?" }, { who: "student", text: "I like it because it's comfortable." }] },
      { type: "practice", stage: "Exit Check", heading: "Answer Independently", subheading: "3 random room questions", line: "There is a ___ and a ___. My room is ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now answer questions about your room. Next up: Unit Review." },
    ],
  },
  "7-5": {
    slides: [
      { type: "title", stage: "Unit 7 · Unit Review", eyebrow: "A1 · Ignite", title: "Unit Review", subtitle: "Describe your room and answer questions about it. No new language today." },
      { type: "vocab", stage: "Quick Start", heading: "Room Recall", subheading: "5 objects, 3 prepositions, 2 adjectives", items: [{ label: "5 objects" }, { label: "3 prepositions" }, { label: "2 adjectives" }] },
      { type: "message", stage: "Build a Room", heading: "Describe & Locate", subheading: "Combine objects, location, and description", lines: ["There is a *bed*.", "The desk is *next to the window*.", "My room is *small and clean*."] },
      { type: "dialogue", stage: "Try It", heading: "Choose, Place, Describe", subheading: "Build a real or fictional room", turns: [{ who: "teacher", text: "What's in your room?" }, { who: "student", text: "There is a bed and a desk. The desk is next to the window." }] },
      { type: "dialogue", stage: "Design Your Dream Room", heading: "Design Your Dream Room", subheading: "Present a 45-60 second dream-room talk, then answer a surprise question", turns: [{ who: "student", text: "My dream room has a big bed and a bookshelf. It's blue and comfortable. My favorite thing is the window." }, { who: "teacher", text: "What color are the walls? Now describe it again without your notes." } ] },
      { type: "practice", stage: "Exit Check", heading: "Tell Me About Your Room", subheading: "What's in it, where your bed is, and your favorite thing", line: "In my room, there is ___. My bed is ___. My favorite thing is ___." },
      { type: "landing", stage: "Unit Complete!", heading: "Unit 7 Complete!", caption: "You can name room objects, say where things are, describe your space, and answer questions about it." },
    ],
  },
  "8-1": {
    slides: [
      { type: "title", stage: "Unit 8 · Lesson 1", eyebrow: "A1 · Ignite", title: "Food and Drinks", subtitle: "Name basic food and drink items." },
      { type: "vocab", stage: "Getting Ready", heading: "Food & Drinks", subheading: "New words for this unit", items: [{ label: "rice / noodles" }, { label: "chicken / fish" }, { label: "salad / soup" }, { label: "water / juice / tea" }] },
      { type: "examples", stage: "Learn It", heading: "Food or Drink?", subheading: "Sort each item", rows: [["pizza", "Food."], ["juice", "Drink."]] },
      { type: "dialogue", stage: "Try It", heading: "Category → Item", subheading: "Name an item from the category", turns: [{ who: "teacher", text: "Name a drink." }, { who: "student", text: "Water." }, { who: "teacher", text: "Is rice food or a drink?" }] },
      { type: "dialogue", stage: "Food Basket Challenge", heading: "Food Basket Challenge", subheading: "Build a fictional basket, then say what changed", turns: [{ who: "teacher", text: "Choose 5 foods and 3 drinks for your basket." }, { who: "student", text: "Rice, chicken, fish, bread, fruit. Water, juice, tea." }, { who: "teacher", text: "I changed one item. What's different?" }] },
      { type: "practice", stage: "Exit Check", heading: "Name Foods and Drinks", subheading: "6 foods, 4 drinks", line: "I have ___, ___, ___. I drink ___, ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now name common foods and drinks. Next up: likes and dislikes." },
    ],
  },
  "8-2": {
    slides: [
      { type: "title", stage: "Unit 8 · Lesson 2", eyebrow: "A1 · Ignite", title: "Likes and Dislikes", subtitle: "Say what food and drinks you like or don't like." },
      { type: "vocab", stage: "Getting Ready", heading: "Food Opinions", subheading: "New patterns for this unit", items: [{ label: "I like pizza." }, { label: "I don't like fish." }, { label: "I love ice cream." }, { label: "My favorite food is..." }] },
      { type: "examples", stage: "Learn It", heading: "React to Each Food", subheading: "Natural reactions, not one-word answers", rows: [["Pizza?", "I like pizza."], ["Coffee?", "I don't like coffee."]] },
      { type: "dialogue", stage: "Try It", heading: "Complete My Opinion", subheading: "React to each item", turns: [{ who: "teacher", text: "Ice cream?" }, { who: "student", text: "I love ice cream!" }] },
      { type: "dialogue", stage: "Food Opinion Scale", heading: "Food Opinion Scale", subheading: "LOVE → LIKE → DON'T LIKE → NEVER TRY — react to new foods, then adapt for a picnic", turns: [{ who: "teacher", text: "Where does pizza go on your scale? Why?" }, { who: "student", text: "Pizza goes on LOVE, because it's delicious." }, { who: "teacher", text: "You can only choose three foods for a picnic. What do you pick?" }] },
      { type: "practice", stage: "Exit Check", heading: "Food Opinions", subheading: "2 you like, 2 you don't, plus favorites", line: "I like ___ and ___. I don't like ___ or ___. My favorite food is ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now share food likes and dislikes. Next up: mealtimes." },
    ],
  },
  "8-3": {
    slides: [
      { type: "title", stage: "Unit 8 · Lesson 3", eyebrow: "A1 · Ignite", title: "At Mealtimes", subtitle: "Talk about simple meal routines." },
      { type: "vocab", stage: "Getting Ready", heading: "Meals & Times", subheading: "New words for this unit", items: [{ label: "breakfast" }, { label: "lunch" }, { label: "dinner" }, { label: "snack" }] },
      { type: "examples", stage: "Learn It", heading: "When Do I Eat It?", subheading: "Food → likely meal → sentence", rows: [["Cereal?", "Breakfast."], ["Rice and vegetables?", "Lunch or dinner."]] },
      { type: "dialogue", stage: "Try It", heading: "Food → Meal → Sentence", subheading: "Name the meal, then make a sentence", turns: [{ who: "teacher", text: "Cereal?" }, { who: "student", text: "Breakfast. I eat cereal in the morning." }] },
      { type: "dialogue", stage: "Build a Day of Meals", heading: "Build a Day of Meals", subheading: "Plan breakfast through dinner, then adapt to a new situation", turns: [{ who: "teacher", text: "Choose your breakfast, lunch, snack, and dinner." }, { who: "student", text: "For breakfast, I eat bread. For lunch, I have rice and chicken." }, { who: "teacher", text: "You are at home on Saturday. What changes?" }] },
      { type: "practice", stage: "Exit Check", heading: "Describe Your Meals", subheading: "One sentence each for breakfast, lunch, dinner", line: "For breakfast, I eat ___. For lunch, I have ___. For dinner, I eat ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now talk about your meal routine. Next up: ordering food." },
    ],
  },
  "8-4": {
    slides: [
      { type: "title", stage: "Unit 8 · Lesson 4", eyebrow: "A1 · Ignite", title: "Ordering Food", subtitle: "Use a simple order in a food situation." },
      { type: "vocab", stage: "Getting Ready", heading: "Ordering Phrases", subheading: "New phrases for this unit", items: [{ label: "Can I have...?" }, { label: "I'd like..." }, { label: "Anything else?" }, { label: "No, thank you." }] },
      { type: "dialogue", stage: "Learn It", heading: "A Full Order", subheading: "The model conversation", turns: [{ who: "student", text: "Hello. Can I have a burger, please?" }, { who: "teacher", text: "Sure. Anything else?" }, { who: "student", text: "Yes, a juice, please." }, { who: "teacher", text: "Anything else?" }, { who: "student", text: "No, thank you." }] },
      { type: "dialogue", stage: "Try It", heading: "Build an Order", subheading: "Choose one food and one drink", turns: [{ who: "teacher", text: "What would you like?" }, { who: "student", text: "Can I have a sandwich and a juice, please?" }] },
      { type: "dialogue", stage: "Café Counter Challenge", heading: "Café Counter Challenge", subheading: "Order from a menu, then order without a script", turns: [{ who: "student", text: "Can I have a pizza, please?" }, { who: "teacher", text: "Sure. Anything else?" }, { who: "student", text: "Yes, a water, please." }, { who: "teacher", text: "You're hungry after school. Order a snack and a drink." }] },
      { type: "practice", stage: "Exit Check", heading: "Order Independently", subheading: "One complete order, no script", line: "Can I have ___, please? Yes, a ___, please. No, thank you." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now order food and drinks. Next up: Unit Review." },
    ],
  },
  "8-5": {
    slides: [
      { type: "title", stage: "Unit 8 · Unit Review", eyebrow: "A1 · Ignite", title: "Unit Review", subtitle: "Talk about food, drinks, and preferences. No new language today." },
      { type: "vocab", stage: "Quick Start", heading: "Food Speed Round", subheading: "5 foods, 3 drinks, 2 meals", items: [{ label: "5 foods" }, { label: "3 drinks" }, { label: "2 meals" }] },
      { type: "message", stage: "Review", heading: "Build Your Food Choices", subheading: "Breakfast, lunch, dinner, favorite drink", lines: ["For breakfast, I eat *bread*.", "My favorite drink is *juice*."] },
      { type: "dialogue", stage: "Try It", heading: "Food Conversation", subheading: "Favorite food, dislikes, meals", turns: [{ who: "teacher", text: "What is your favorite food? What don't you like?" }, { who: "student", text: "My favorite food is pizza. I don't like fish." }] },
      { type: "dialogue", stage: "My Food Day Challenge", heading: "My Food Day Challenge", subheading: "Build a 45-60 second food day talk, then adapt for a restaurant", turns: [{ who: "student", text: "For breakfast, I eat bread. For lunch, I have rice and chicken. I like pizza but I don't like fish." }, { who: "teacher", text: "You're eating at a restaurant and can choose only three things. What do you pick?" } ] },
      { type: "practice", stage: "Exit Check", heading: "Tell Me About Your Food", subheading: "Favorite food, usual breakfast, a dislike", line: "My favorite food is ___. I usually eat ___ for breakfast. I don't like ___." },
      { type: "landing", stage: "Unit Complete!", heading: "Unit 8 Complete!", caption: "You can name foods and drinks, share preferences, talk about meals, and place an order." },
    ],
  },
  "9-1": {
    slides: [
      { type: "title", stage: "Unit 9 · Lesson 1", eyebrow: "A1 · Ignite", title: "Clothes and Style", subtitle: "Name basic clothes and style words." },
      { type: "vocab", stage: "Getting Ready", heading: "Clothes", subheading: "New words for this unit", items: [{ label: "shirt / T-shirt" }, { label: "jeans / shorts" }, { label: "jacket / sweater" }, { label: "sneakers / boots" }] },
      { type: "examples", stage: "Learn It", heading: "This Is / These Are", subheading: "Singular and plural clothes", rows: [["shirt", "This is a shirt."], ["shoes", "These are shoes."]] },
      { type: "dialogue", stage: "Try It", heading: "Sort Into Categories", subheading: "Clothes, shoes, or accessories?", turns: [{ who: "teacher", text: "Cap — clothes, shoes, or accessories?" }, { who: "student", text: "Accessories! I have a cap." }] },
      { type: "dialogue", stage: "Pack My Bag Challenge", heading: "Pack My Bag Challenge", subheading: "Pack for different situations, then explain your final choices", turns: [{ who: "teacher", text: "You're going to the beach. Choose 5 items." }, { who: "student", text: "Shorts, a T-shirt, sunglasses, sneakers, a hat." }, { who: "teacher", text: "Now you can only take 4 things. Which do you keep?" }] },
      { type: "practice", stage: "Exit Check", heading: "Name Eight Clothes", subheading: "Then make 3 simple sentences", line: "I have a ___. I have ___. I like ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now name clothes and style words. Next up: what people are wearing." },
    ],
  },
  "9-2": {
    slides: [
      { type: "title", stage: "Unit 9 · Lesson 2", eyebrow: "A1 · Ignite", title: "What Are You Wearing?", subtitle: "Describe what someone is wearing." },
      { type: "message", stage: "Getting Ready", heading: "Be + Wearing", subheading: "New grammar for this unit", lines: ["He *is wearing* a T-shirt.", "She *is wearing* jeans and sneakers.", "They *are wearing* hats."] },
      { type: "examples", stage: "Learn It", heading: "Complete the Outfit", subheading: "Fill in the missing pieces", rows: [["Alex is wearing a ___ and ___.", "Alex is wearing a jacket and jeans."]] },
      { type: "dialogue", stage: "Try It", heading: "Complete the Description", subheading: "Add the missing items", turns: [{ who: "teacher", text: "Alex is wearing a ___ and ___." }, { who: "student", text: "Alex is wearing a T-shirt and sneakers." }] },
      { type: "dialogue", stage: "Outfit Reconstruction", heading: "Outfit Reconstruction", subheading: "Remember and rebuild the outfit from memory", turns: [{ who: "teacher", text: "She is wearing a red dress, white sneakers, and a cap." }, { who: "student", text: "She is wearing a red dress, white sneakers, and a cap." }, { who: "teacher", text: "I changed two items. What's different now?" }] },
      { type: "practice", stage: "Exit Check", heading: "Describe an Outfit", subheading: "3-4 sentences about a fictional person", line: "He/She is wearing a ___ and ___. He/She has ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now describe what someone is wearing. Next up: style and color." },
    ],
  },
  "9-3": {
    slides: [
      { type: "title", stage: "Unit 9 · Lesson 3", eyebrow: "A1 · Ignite", title: "Style and Color", subtitle: "Describe clothes with colors." },
      { type: "vocab", stage: "Getting Ready", heading: "Colors", subheading: "New words for this unit", items: [{ label: "red / blue / green" }, { label: "black / white" }, { label: "pink / purple" }, { label: "brown / gray" }] },
      { type: "examples", stage: "Learn It", heading: "Color + Clothing", subheading: "Combine them naturally", rows: [["shirt", "a red shirt"], ["shoes", "white shoes"]] },
      { type: "dialogue", stage: "Try It", heading: "Color Match", subheading: "Item → color + item", turns: [{ who: "teacher", text: "shirt" }, { who: "student", text: "A green shirt." }] },
      { type: "dialogue", stage: "Outfit Designer", heading: "Outfit Designer", subheading: "Design casual, sporty, and party outfits", turns: [{ who: "teacher", text: "Create a casual outfit with 3 colors." }, { who: "student", text: "A blue T-shirt, black jeans, and white sneakers." }, { who: "teacher", text: "Now you're going to a party. What changes?" }] },
      { type: "practice", stage: "Exit Check", heading: "Describe an Outfit", subheading: "At least 3 colors", line: "I have a ___ ___. I have ___ ___. My favorite color is ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now describe clothes with colors. Next up: shopping for clothes." },
    ],
  },
  "9-4": {
    slides: [
      { type: "title", stage: "Unit 9 · Lesson 4", eyebrow: "A1 · Ignite", title: "Shopping for Clothes", subtitle: "Ask for a clothing item simply." },
      { type: "vocab", stage: "Getting Ready", heading: "Shopping Phrases", subheading: "New phrases for this unit", items: [{ label: "Can I have this, please?" }, { label: "Do you have this in blue?" }, { label: "Do you have a bigger size?" }, { label: "How much is it?" }] },
      { type: "examples", stage: "Learn It", heading: "Make a Request", subheading: "Add color or size when ready", rows: [["black T-shirt", "Can I have a black T-shirt, please?"]] },
      { type: "dialogue", stage: "Try It", heading: "Item + Color", subheading: "Practice a full request", turns: [{ who: "student", text: "Can I have a blue jacket, please?" }, { who: "teacher", text: "Sure. Here you are." }] },
      { type: "dialogue", stage: "Clothing Store Mission", heading: "Clothing Store Mission", subheading: "Ask for item + color + size, then adapt when it's unavailable", turns: [{ who: "student", text: "Can I have a blue jacket, please?" }, { who: "teacher", text: "Sorry, we don't have blue. We have black." }, { who: "student", text: "Okay. Can I have the black jacket, please?" }] },
      { type: "practice", stage: "Exit Check", heading: "Two Independent Requests", subheading: "Ask for two different clothing items", line: "Can I have ___, please? Do you have this in ___?" },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now ask for clothing items while shopping. Next up: Unit Review." },
    ],
  },
  "9-5": {
    slides: [
      { type: "title", stage: "Unit 9 · Unit Review", eyebrow: "A1 · Ignite", title: "Unit Review", subtitle: "Describe clothes, colors, and make a shopping request. No new language today." },
      { type: "vocab", stage: "Quick Start", heading: "Clothing Speed Round", subheading: "6 clothes, 3 colors, 2 style words", items: [{ label: "6 clothes" }, { label: "3 colors" }, { label: "2 style words" }] },
      { type: "message", stage: "Build an Outfit", heading: "Describe the Outfit", subheading: "Choose clothes and colors for a fictional person", lines: ["She is wearing… Her shirt is… Her shoes are…"] },
      { type: "dialogue", stage: "Try It", heading: "Describe It", subheading: "4-5 sentences about an outfit", turns: [{ who: "teacher", text: "Describe her outfit." }, { who: "student", text: "She is wearing a red dress. Her shoes are white." }] },
      { type: "dialogue", stage: "From Outfit to Store", heading: "From Outfit to Store", subheading: "Create an outfit, change it for a party, then shop for 2-3 items", turns: [{ who: "student", text: "I have a blue T-shirt and black jeans." }, { who: "teacher", text: "You're going to a party instead. What changes? Now go shop for it." }, { who: "student", text: "Can I have a black dress, please?" }] },
      { type: "practice", stage: "Exit Check", heading: "Outfit + Colors + Request", subheading: "Describe an outfit, name two colors, make one request", line: "I'm wearing a ___ ___. Can I have ___, please?" },
      { type: "landing", stage: "Unit Complete!", heading: "Unit 9 Complete!", caption: "You can name clothes, describe outfits with color, and make a shopping request." },
    ],
  },
  "10-1": {
    slides: [
      { type: "title", stage: "Unit 10 · Lesson 1", eyebrow: "A1 · Ignite", title: "Weather and Seasons", subtitle: "Name basic weather words and seasons." },
      { type: "vocab", stage: "Getting Ready", heading: "Weather & Seasons", subheading: "New words for this unit", items: [{ label: "sunny / rainy" }, { label: "hot / cold" }, { label: "spring / summer" }, { label: "fall / winter" }] },
      { type: "examples", stage: "Learn It", heading: "Weather or Season?", subheading: "Sort and connect them", rows: [["Winter", "Cold."], ["Sunny", "Weather."]] },
      { type: "dialogue", stage: "Try It", heading: "Weather → Sentence", subheading: "Identify each situation", turns: [{ who: "teacher", text: "☔ (rain)" }, { who: "student", text: "It's rainy!" }] },
      { type: "dialogue", stage: "Weather Forecast Challenge", heading: "Weather Forecast Challenge", subheading: "Be the weather presenter for a 3-day forecast", turns: [{ who: "teacher", text: "Give the forecast for today." }, { who: "student", text: "It's sunny and hot." }, { who: "teacher", text: "Now it's winter. What's the forecast?" }] },
      { type: "practice", stage: "Exit Check", heading: "Name Weather & Seasons", subheading: "5 weather words and all 4 seasons", line: "It is ___. It is ___. The seasons are ___, ___, ___, ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now name weather words and seasons. Next up: answering weather questions." },
    ],
  },
  "10-2": {
    slides: [
      { type: "title", stage: "Unit 10 · Lesson 2", eyebrow: "A1 · Ignite", title: "What's the Weather Like?", subtitle: "Answer a simple weather question." },
      { type: "vocab", stage: "Getting Ready", heading: "Weather Question", subheading: "New pattern for this unit", items: [{ label: "What's the weather like?" }, { label: "It's cloudy and cool." }, { label: "It's rainy today." }] },
      { type: "examples", stage: "Learn It", heading: "Question → Answer", subheading: "For different fictional locations", rows: [["What's the weather like in City A?", "It's sunny."], ["What's the weather like in City B?", "It's cloudy and cool."]] },
      { type: "dialogue", stage: "Try It", heading: "Ask About a Location", subheading: "Different places, different weather", turns: [{ who: "teacher", text: "What's the weather like in City A?" }, { who: "student", text: "It's hot and sunny." }] },
      { type: "dialogue", stage: "Weather Reporter Live", heading: "Weather Reporter Live", subheading: "Report live, then update when the weather suddenly changes", turns: [{ who: "teacher", text: "Report the weather for two locations." }, { who: "student", text: "In City A, it's sunny. In City B, it's rainy." }, { who: "teacher", text: "Oh! The weather changed in City A!" }] },
      { type: "practice", stage: "Exit Check", heading: "Answer the Question", subheading: "3 different situations", line: "What's the weather like? It's ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now answer weather questions. Next up: seasons and clothes." },
    ],
  },
  "10-3": {
    slides: [
      { type: "title", stage: "Unit 10 · Lesson 3", eyebrow: "A1 · Ignite", title: "Seasons and Clothes", subtitle: "Match seasons with suitable clothes." },
      { type: "message", stage: "Getting Ready", heading: "Season + Clothes", subheading: "Connect weather to clothing", lines: ["In *summer*, I wear a T-shirt.", "In *winter*, I wear a coat.", "I wear a jacket when it is *cold*."] },
      { type: "examples", stage: "Learn It", heading: "Dress for the Season", subheading: "Weather → suitable clothes", rows: [["hot", "T-shirt and shorts"], ["cold", "coat and sweater"]] },
      { type: "dialogue", stage: "Try It", heading: "Choose the Clothes", subheading: "Season or weather → sentence", turns: [{ who: "teacher", text: "It's a hot summer day." }, { who: "student", text: "I wear a T-shirt and shorts." }] },
      { type: "dialogue", stage: "Weather Emergency", heading: "Weather Emergency: What Should I Wear?", subheading: "Choose clothes for the weather, then adapt to a sudden change", turns: [{ who: "teacher", text: "It's cold and windy." }, { who: "student", text: "I wear a coat and a scarf." }, { who: "teacher", text: "You planned for summer, but now it's cold! What do you change?" }] },
      { type: "practice", stage: "Exit Check", heading: "Clothes for Two Seasons", subheading: "Suitable clothes, and why", line: "In ___, I wear ___ because it's ___. In ___, I wear ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now match seasons with clothes. Next up: weather preferences." },
    ],
  },
  "10-4": {
    slides: [
      { type: "title", stage: "Unit 10 · Lesson 4", eyebrow: "A1 · Ignite", title: "Weather Preferences", subtitle: "Say which weather you like." },
      { type: "vocab", stage: "Getting Ready", heading: "Weather Opinions", subheading: "New patterns for this unit", items: [{ label: "I like sunny weather." }, { label: "I don't like rainy weather." }, { label: "I love hot weather." }, { label: "My favorite season is..." }] },
      { type: "examples", stage: "Learn It", heading: "Complete the Opinion", subheading: "React to each prompt", rows: [["Sunny?", "I like sunny weather."], ["Winter?", "My favorite season is winter."]] },
      { type: "dialogue", stage: "Try It", heading: "Complete the Opinion", subheading: "Weather or season → your reaction", turns: [{ who: "teacher", text: "Rainy?" }, { who: "student", text: "I don't like rainy weather." }] },
      { type: "dialogue", stage: "Weather Debate: Pick Your Day", heading: "Weather Debate: Pick Your Day", subheading: "Choose your ideal weather, then defend it when challenged", turns: [{ who: "teacher", text: "Sunny and hot, or cloudy and cool? Which do you choose?" }, { who: "student", text: "Sunny and hot, because I love the beach." }, { who: "teacher", text: "But it's very hot! Do you still choose it?" }] },
      { type: "practice", stage: "Exit Check", heading: "Weather Preferences", subheading: "Favorite, least favorite, favorite season, one reason", line: "My favorite weather is ___. I don't like ___. My favorite season is ___ because ___." },
      { type: "landing", stage: "Wrap-Up", heading: "Nice Work!", caption: "You can now say which weather you like and why. Next up: Unit Review." },
    ],
  },
  "10-5": {
    slides: [
      { type: "title", stage: "Unit 10 · Unit Review", eyebrow: "A1 · Ignite", title: "Unit Review", subtitle: "Talk about weather, seasons, and preferences. No new language today." },
      { type: "vocab", stage: "Quick Start", heading: "Weather Speed Round", subheading: "6 weather words, 4 seasons", items: [{ label: "6 weather words" }, { label: "4 seasons" }] },
      { type: "message", stage: "Season Connections", heading: "Connect Season, Weather, Clothes", subheading: "Everything from this unit", lines: ["In summer, it's *hot and sunny*. I wear a *T-shirt*."] },
      { type: "dialogue", stage: "Try It", heading: "Weather Questions", subheading: "Favorite season, likes/dislikes, clothes", turns: [{ who: "teacher", text: "What's your favorite season? Do you like rainy weather?" }, { who: "student", text: "My favorite season is summer. No, I don't like rainy weather." }] },
      { type: "dialogue", stage: "Plan the Perfect Day", heading: "Plan the Perfect Day", subheading: "Build a 45-60 second perfect-day talk, then adapt for sudden rain", turns: [{ who: "student", text: "My perfect day is in summer. It is sunny and warm. I wear a T-shirt and shorts." }, { who: "teacher", text: "Suddenly, it starts raining! What do you change?" } ] },
      { type: "practice", stage: "Exit Check", heading: "Weather, Season, Clothes, Preference", subheading: "4 random questions", line: "It's ___. My favorite season is ___. I wear ___. I like ___ weather." },
      { type: "landing", stage: "Unit Complete!", heading: "Unit 10 Complete!", caption: "You can talk about weather, seasons, appropriate clothes, and your own preferences." },
    ],
  },
};
