// Writing category, Message Reply activity: 10 items per CEFR level group
// (A1-A2 / B1-B2 / C1-C2), 30 total. Shape per item:
// { key, title, cefrGroup, focus, from, context, incoming,
// mustInclude: [3], prompt, sample } -- "mustInclude" lists communicative
// functions the reply should hit (not vocabulary), since this activity
// practices functional/register writing, not word usage.

const A1A2 = [
  {
    key: "missedTheBus",
    title: "Missed the Bus",
    focus: "Explaining, apologizing, simple past",
    from: "Mom",
    context: "Text message",
    incoming: "Where are you? School started 10 minutes ago!",
    mustInclude: ["Apologize", "Explain why", "Say when you'll arrive"],
    prompt: "Reply to Mom's text.",
    sample: "Sorry Mom! I missed the bus because I woke up late. I'm walking to school now. I'll be there in 10 minutes.",
  },
  {
    key: "partyInvitation",
    title: "Party Invitation",
    focus: "Accepting/declining, giving a reason",
    from: "Sam",
    context: "Text message",
    incoming: "Hey! My birthday party is Saturday at 3pm. Can you come?",
    mustInclude: ["Say yes or no", "Thank them", "Ask one question"],
    prompt: "Reply to Sam's invitation.",
    sample: "Hi Sam! Yes, I can come, thank you for inviting me! What time should I be there, and can I bring anything?",
  },
  {
    key: "weekendPlans",
    title: "Weekend Plans",
    focus: "Suggesting, agreeing, simple future",
    from: "Jess",
    context: "Text message",
    incoming: "What are you doing this weekend? Want to hang out?",
    mustInclude: ["Say what you're doing", "Suggest an activity", "Ask when"],
    prompt: "Reply to Jess's text.",
    sample: "I don't have plans yet, so yes! Do you want to go to the mall or watch a movie? What time works for you?",
  },
  {
    key: "lostHomework",
    title: "Lost Homework",
    focus: "Explaining a problem, apologizing",
    from: "Mr. Lee (Teacher)",
    context: "Text message",
    incoming: "I don't see your homework in my inbox. Did you forget to send it?",
    mustInclude: ["Apologize", "Explain what happened", "Say when you'll send it"],
    prompt: "Reply to Mr. Lee's text.",
    sample: "I'm so sorry, Mr. Lee! My laptop stopped working last night and I couldn't send it. I'll send it as soon as I get home today.",
  },
  {
    key: "sickDay",
    title: "Sick Day",
    focus: "Explaining, asking for help",
    from: "Mia",
    context: "Class group chat",
    incoming: "Hey, I wasn't at school today. Did we get any homework?",
    mustInclude: ["Say what happened", "Answer her question", "Offer to help"],
    prompt: "Reply to Mia in the group chat.",
    sample: "Hi Mia! Yes, we got math homework, pages 12 and 13. I hope you feel better soon. I can send you my notes if you want!",
  },
  {
    key: "newPet",
    title: "New Pet",
    focus: "Showing excitement, asking questions",
    from: "Leo",
    context: "Text message",
    incoming: "Guess what, we got a new puppy! His name is Max.",
    mustInclude: ["Show excitement", "Ask a question", "Say something nice"],
    prompt: "Reply to Leo's text.",
    sample: "That's so exciting! What kind of dog is Max? He sounds adorable, I can't wait to meet him!",
  },
  {
    key: "moviePlans",
    title: "Movie Plans",
    focus: "Suggesting, confirming plans",
    from: "Ana",
    context: "Text message",
    incoming: "There's a new movie out this Friday. Want to go together?",
    mustInclude: ["Say yes or no", "Suggest a time", "Ask a question"],
    prompt: "Reply to Ana's text.",
    sample: "Yes, I'd love to! Is 6pm okay for you? Which cinema were you thinking of going to?",
  },
  {
    key: "birthdayWishes",
    title: "Birthday Wishes",
    focus: "Thanking, responding warmly",
    from: "Grandma",
    context: "Text message",
    incoming: "Happy birthday, sweetheart! I hope you have a wonderful day.",
    mustInclude: ["Thank her", "Say how your day is", "Say something kind"],
    prompt: "Reply to Grandma's text.",
    sample: "Thank you so much, Grandma! My day is great so far, everyone has been so nice to me. I love you and I can't wait to see you soon!",
  },
  {
    key: "borrowingSomething",
    title: "Borrowing Something",
    focus: "Asking politely, agreeing",
    from: "Tom",
    context: "Text message",
    incoming: "Could I borrow your notes from science class? I missed it yesterday.",
    mustInclude: ["Say yes", "Say when he can get them", "Offer more help"],
    prompt: "Reply to Tom's text.",
    sample: "Of course, no problem! I can bring them to school tomorrow morning. Let me know if you have any questions about them too!",
  },
  {
    key: "meetingUpAfterSchool",
    title: "Meeting Up After School",
    focus: "Suggesting a place and time",
    from: "Zara",
    context: "Text message",
    incoming: "Want to study together after school today?",
    mustInclude: ["Say yes or no", "Suggest a place", "Suggest a time"],
    prompt: "Reply to Zara's text.",
    sample: "Sure, that sounds great! How about the library at 4pm? We can go over the math homework together.",
  },
];

const B1B2 = [
  {
    key: "groupProjectProblem",
    title: "Group Project Problem",
    focus: "Explaining a problem, proposing a solution",
    from: "Priya",
    context: "Class group chat",
    incoming: "Hey, did you finish your part of the project? We need to submit it tomorrow and I haven't seen your slides yet.",
    mustInclude: ["Explain the situation", "Apologize if needed", "Propose a next step"],
    prompt: "Reply to Priya in the group chat.",
    sample: "Hi Priya, sorry for the late reply! I've been stuck on the research part, but I'll finish my slides tonight and send them by 9pm so we still have time to review everything before tomorrow.",
  },
  {
    key: "canceledPlans",
    title: "Canceled Plans",
    focus: "Responding with understanding, suggesting an alternative",
    from: "Marcus",
    context: "Text message",
    incoming: "I'm really sorry, but I can't make it to the movies this weekend. Something came up with my family.",
    mustInclude: ["Show understanding", "Say it's okay", "Suggest another time"],
    prompt: "Reply to Marcus's text.",
    sample: "No worries at all, family comes first! Hope everything is okay. Want to reschedule for next weekend instead? We could go Sunday if that works better.",
  },
  {
    key: "landlordMessage",
    title: "Landlord Message",
    focus: "Confirming a time, polite requests",
    from: "Mr. Alvarez (Landlord)",
    context: "Text message",
    incoming: "Hi, the plumber can come to fix your sink on Thursday at 2pm. Does that work for you?",
    mustInclude: ["Confirm or suggest another time", "Thank them", "Ask one question"],
    prompt: "Reply to your landlord.",
    sample: "Hi Mr. Alvarez, thank you for arranging this. Thursday at 2pm works for me. Will I need to be home the whole time, or can I leave a key?",
  },
  {
    key: "coworkerQuestion",
    title: "Coworker Question",
    focus: "Agreeing/declining a request, giving a reason",
    from: "Lena (Coworker)",
    context: "Text message",
    incoming: "Hey, would you be able to swap shifts with me next Friday? I have a doctor's appointment.",
    mustInclude: ["Say yes or no", "Give a reason if declining", "Be friendly"],
    prompt: "Reply to Lena.",
    sample: "Hi Lena, no problem, I can swap with you! I don't have any plans that day. Just let the manager know so it's official.",
  },
  {
    key: "restaurantReservationChange",
    title: "Restaurant Reservation Change",
    focus: "Confirming changes, polite requests",
    from: "Bella Vista Restaurant",
    context: "Text message",
    incoming: "Hi, we need to move your 7pm reservation to 8pm due to a scheduling issue. Is that okay?",
    mustInclude: ["Confirm or propose another time", "Ask a follow-up question", "Stay polite"],
    prompt: "Reply to the restaurant.",
    sample: "Hi, thanks for letting me know. 8pm works fine for us. Could you also confirm the table is still for four people?",
  },
  {
    key: "neighborNoiseComplaint",
    title: "Neighbor Noise Complaint",
    focus: "Apologizing, reassuring, explaining",
    from: "Mrs. Chen (Neighbor)",
    context: "Text message",
    incoming: "Hi, I could hear loud music from your apartment quite late last night. Could you please keep it down?",
    mustInclude: ["Apologize", "Explain briefly", "Reassure it won't happen again"],
    prompt: "Reply to Mrs. Chen.",
    sample: "Hi Mrs. Chen, I'm really sorry about that, we were hosting a small get-together and lost track of time. It won't happen again, thank you for letting me know.",
  },
  {
    key: "doctorsAppointmentReminder",
    title: "Doctor's Appointment Reminder",
    focus: "Confirming, rescheduling",
    from: "Riverside Clinic",
    context: "Text message",
    incoming: "Reminder: your appointment with Dr. Santos is tomorrow at 10am. Reply to confirm or let us know if you need to reschedule.",
    mustInclude: ["Confirm or ask to reschedule", "Be polite", "Mention a reason if rescheduling"],
    prompt: "Reply to the clinic.",
    sample: "Hi, thank you for the reminder. I actually need to reschedule due to a work conflict tomorrow morning. Could we move it to later in the week instead?",
  },
  {
    key: "gymMembershipQuestion",
    title: "Gym Membership Question",
    focus: "Asking for information, polite tone",
    from: "FitZone Gym",
    context: "Text message",
    incoming: "Hi! Just checking in, would you like to renew your membership this month before it expires?",
    mustInclude: ["Say yes or no", "Ask about pricing or options", "Thank them"],
    prompt: "Reply to the gym.",
    sample: "Hi, thanks for checking in! I'm interested in renewing. Could you tell me if there are any discounts for a longer membership plan?",
  },
  {
    key: "deliveryDelayNotice",
    title: "Delivery Delay Notice",
    focus: "Expressing concern, asking for an update",
    from: "QuickShip Delivery",
    context: "Text message",
    incoming: "Your package has been delayed and is now expected to arrive 3 days later than planned. We apologize for the inconvenience.",
    mustInclude: ["Express concern politely", "Ask for a new estimated date", "Stay polite"],
    prompt: "Reply to QuickShip Delivery.",
    sample: "Hi, thanks for the update, though I was hoping to receive it sooner. Could you tell me the new expected delivery date so I can plan accordingly?",
  },
  {
    key: "volunteerEventInvite",
    title: "Volunteer Event Invite",
    focus: "Accepting/declining, asking for details",
    from: "Community Center",
    context: "Email",
    incoming: "We're organizing a beach clean-up this Saturday morning and would love for you to join us!",
    mustInclude: ["Say yes or no", "Ask a question", "Thank them for inviting you"],
    prompt: "Reply to the Community Center.",
    sample: "Hi, thank you for inviting me, I'd love to join! What time should I arrive, and is there anything specific I should bring?",
  },
];

const C1C2 = [
  {
    key: "clientComplaint",
    title: "Client Complaint",
    focus: "Apologizing, explaining, offering a resolution",
    from: "Mr. Delgado (Client)",
    context: "Email",
    incoming: "I'm writing to express my disappointment. My order was supposed to arrive last Monday, and it's now Friday with no update. This is affecting my business.",
    mustInclude: ["Apologize sincerely", "Briefly explain the delay", "Offer a concrete solution"],
    prompt: "Reply to Mr. Delgado's email.",
    sample: "Dear Mr. Delgado, I sincerely apologize for the delay and the inconvenience this has caused. Your order was held up due to a shipping issue on our end. I've arranged expedited delivery, and it will arrive by Monday. As an apology, we'd also like to offer a 15% discount on your next order.",
  },
  {
    key: "meetingReschedule",
    title: "Meeting Reschedule",
    focus: "Proposing alternatives, professional tone",
    from: "Ms. Okafor (Colleague)",
    context: "Email",
    incoming: "I need to reschedule our 10am meeting tomorrow due to a conflict. Could we find another time this week?",
    mustInclude: ["Acknowledge the request", "Propose 2 alternative times", "Stay flexible"],
    prompt: "Reply to Ms. Okafor's email.",
    sample: "Hi Ms. Okafor, of course, no problem. I'm available Wednesday at 2pm or Thursday at 11am — please let me know whichever works best for you, and I'll update the calendar accordingly.",
  },
  {
    key: "jobOfferNegotiation",
    title: "Job Offer Negotiation",
    focus: "Negotiating tactfully, professional tone",
    from: "Ms. Whitfield (HR Manager)",
    context: "Email",
    incoming: "We're pleased to offer you the Senior Analyst position with a starting salary of $68,000. Please let us know if you have any questions.",
    mustInclude: ["Thank them for the offer", "Tactfully raise the salary point", "Express continued interest"],
    prompt: "Reply to Ms. Whitfield's email.",
    sample: "Dear Ms. Whitfield, thank you very much for this offer, I'm genuinely excited about the opportunity. Given my experience and the scope of the role, I was hoping we could discuss a starting salary closer to $75,000. I remain very enthusiastic about joining the team and look forward to your thoughts.",
  },
  {
    key: "conferenceInvitation",
    title: "Conference Invitation",
    focus: "Accepting formally, requesting logistics",
    from: "Dr. Patel (Conference Chair)",
    context: "Email",
    incoming: "We would be honored to have you speak at this year's Global Innovation Summit. Please let us know your availability.",
    mustInclude: ["Accept formally", "Confirm or request dates", "Ask about logistics"],
    prompt: "Reply to Dr. Patel's email.",
    sample: "Dear Dr. Patel, thank you for this kind invitation, it would be an honor to speak at the summit. I am available on the proposed dates. Could you share further details regarding the expected topic scope and travel arrangements?",
  },
  {
    key: "performanceReviewFollowUp",
    title: "Performance Review Follow-up",
    focus: "Responding professionally, seeking clarification",
    from: "Mr. Osei (Manager)",
    context: "Email",
    incoming: "Following our performance review, I'd like you to focus on improving cross-team communication over the next quarter.",
    mustInclude: ["Acknowledge the feedback", "Ask a clarifying question", "Show commitment to improving"],
    prompt: "Reply to Mr. Osei's email.",
    sample: "Dear Mr. Osei, thank you for the feedback, I appreciate the clarity. Could you point me toward specific areas or projects where this has been most noticeable? I'm fully committed to improving this over the coming quarter.",
  },
  {
    key: "partnershipProposalResponse",
    title: "Partnership Proposal Response",
    focus: "Expressing interest cautiously, requesting details",
    from: "Ms. Ibarra (Business Development)",
    context: "Email",
    incoming: "We'd like to propose a strategic partnership between our companies. Would you be open to a preliminary discussion?",
    mustInclude: ["Express interest", "Request more detail before committing", "Propose next steps"],
    prompt: "Reply to Ms. Ibarra's email.",
    sample: "Dear Ms. Ibarra, thank you for reaching out, this sounds like an interesting opportunity. Before scheduling a call, could you share a brief outline of what the partnership would involve? I'd be glad to arrange a preliminary discussion once I've had a chance to review it.",
  },
  {
    key: "mediaInterviewRequest",
    title: "Media Interview Request",
    focus: "Declining/accepting formally, setting boundaries",
    from: "Jordan Reyes (Journalist)",
    context: "Email",
    incoming: "I'm writing a feature on industry leaders and would love to interview you next week. Would you be available for a 30-minute call?",
    mustInclude: ["Accept or decline formally", "Set a condition or boundary if needed", "Suggest timing"],
    prompt: "Reply to Jordan's email.",
    sample: "Dear Jordan, thank you for thinking of me for this feature. I'd be glad to take part, provided I can review any quotes before publication. I'm available Tuesday or Wednesday afternoon next week, whichever suits your schedule best.",
  },
  {
    key: "contractClarification",
    title: "Contract Clarification",
    focus: "Requesting clarification, precise formal tone",
    from: "Legal Department",
    context: "Email",
    incoming: "Please review the attached contract and confirm you agree to the terms outlined in Section 4.",
    mustInclude: ["Acknowledge receipt", "Ask a specific clarifying question", "Avoid confirming until clarified"],
    prompt: "Reply to the Legal Department.",
    sample: "Dear team, thank you for sending the contract over. Before confirming, I'd like clarification on the termination clause in Section 4.2, specifically the notice period required. I'll confirm my agreement once this point has been addressed.",
  },
  {
    key: "colleagueConflictResolution",
    title: "Colleague Conflict Resolution",
    focus: "Diplomatic tone, de-escalating",
    from: "Chris (Colleague)",
    context: "Email",
    incoming: "I was frustrated that my suggestions were dismissed in yesterday's meeting without much discussion. I'd like to talk about it.",
    mustInclude: ["Acknowledge their feelings", "Avoid being defensive", "Propose a constructive conversation"],
    prompt: "Reply to Chris's email.",
    sample: "Hi Chris, thank you for being open about this, and I'm sorry it came across that way. That certainly wasn't my intention, and I'd genuinely like to hear more about your perspective. Could we set aside some time this week to talk it through properly?",
  },
  {
    key: "formalComplaintToAVendor",
    title: "Formal Complaint to a Vendor",
    focus: "Formal complaint structure, assertive but professional tone",
    from: "Procurement Team",
    context: "Internal email, to be forwarded to a vendor",
    incoming: "The last three shipments from this vendor have arrived with quality issues. We need you to draft a formal complaint to send to them.",
    mustInclude: ["State the issue clearly", "Reference specifics", "Request a corrective action"],
    prompt: "Draft the formal complaint email to the vendor.",
    sample: "Dear Vendor Team, we are writing to formally raise concerns regarding the quality of our last three shipments, each of which contained defective units exceeding our agreed tolerance threshold. We request a full quality review on your end and a corrective action plan within the next ten business days.",
  },
];

const MESSAGE_REPLY_SETS = [
  ...A1A2.map((t) => ({ ...t, cefrGroup: "A1-A2" })),
  ...B1B2.map((t) => ({ ...t, cefrGroup: "B1-B2" })),
  ...C1C2.map((t) => ({ ...t, cefrGroup: "C1-C2" })),
];

export default MESSAGE_REPLY_SETS;
