// Vocabulary category, Odd One Out game: 30 category packs, 10 per
// CEFR level (A1-A2, B1-B2, C1-C2), matching the level-tab structure
// used by Synonyms/Antonyms/Word Sort (replaces the earlier Kids/
// Teens/Adults audience grouping). Each pack: { key, title, cefrGroup,
// items: [{ words: [4], odd, explanation? }] }. 10 rounds per pack
// (was 15) to match the 10-per-category convention used everywhere
// else in Vocabulary. B1-B2 and C1-C2 rounds carry a short
// `explanation` (matching the old Adults-pack convention); A1-A2
// rounds don't need one, the connection is obvious at that level.
const ODD_ONE_OUT_PACKS = [
  // ---------- A1-A2 (10 packs) ----------
  {
    key: "animals",
    title: "Animals",
    cefrGroup: "A1-A2",
    items: [
      { words: ["dog", "cat", "fish", "chair"], odd: "chair" },
      { words: ["lion", "tiger", "elephant", "pencil"], odd: "pencil" },
      { words: ["bird", "rabbit", "monkey", "shoe"], odd: "shoe" },
      { words: ["cow", "horse", "sheep", "banana"], odd: "banana" },
      { words: ["duck", "chicken", "goat", "table"], odd: "table" },
      { words: ["snake", "frog", "zebra", "book"], odd: "book" },
      { words: ["bear", "panda", "giraffe", "window"], odd: "window" },
      { words: ["dolphin", "whale", "shark", "jacket"], odd: "jacket" },
      { words: ["ant", "bee", "butterfly", "spoon"], odd: "spoon" },
      { words: ["spider", "camel", "donkey", "bed"], odd: "bed" },
    ],
  },
  {
    key: "food",
    title: "Food",
    cefrGroup: "A1-A2",
    items: [
      { words: ["apple", "banana", "orange", "bus"], odd: "bus" },
      { words: ["bread", "rice", "pasta", "pencil"], odd: "pencil" },
      { words: ["cake", "cookie", "ice cream", "chair"], odd: "chair" },
      { words: ["carrot", "potato", "tomato", "shoe"], odd: "shoe" },
      { words: ["egg", "cheese", "yogurt", "table"], odd: "table" },
      { words: ["burger", "pizza", "sandwich", "window"], odd: "window" },
      { words: ["grape", "pear", "peach", "book"], odd: "book" },
      { words: ["soup", "salad", "noodles", "bed"], odd: "bed" },
      { words: ["chicken", "fish", "beef", "ruler"], odd: "ruler" },
      { words: ["onion", "garlic", "pepper", "jacket"], odd: "jacket" },
    ],
  },
  {
    key: "school",
    title: "School",
    cefrGroup: "A1-A2",
    items: [
      { words: ["pencil", "eraser", "ruler", "banana"], odd: "banana" },
      { words: ["desk", "chair", "board", "tiger"], odd: "tiger" },
      { words: ["book", "notebook", "backpack", "apple"], odd: "apple" },
      { words: ["teacher", "student", "classroom", "fish"], odd: "fish" },
      { words: ["pen", "marker", "crayon", "shoe"], odd: "shoe" },
      { words: ["scissors", "glue", "paper", "dog"], odd: "dog" },
      { words: ["lunchbox", "bottle", "bag", "monkey"], odd: "monkey" },
      { words: ["computer", "tablet", "keyboard", "cookie"], odd: "cookie" },
      { words: ["quiz", "homework", "lesson", "elephant"], odd: "elephant" },
      { words: ["map", "clock", "poster", "burger"], odd: "burger" },
    ],
  },
  {
    key: "family",
    title: "Family",
    cefrGroup: "A1-A2",
    items: [
      { words: ["mother", "father", "sister", "car"], odd: "car" },
      { words: ["brother", "cousin", "aunt", "spoon"], odd: "spoon" },
      { words: ["grandmother", "grandfather", "uncle", "pencil"], odd: "pencil" },
      { words: ["son", "daughter", "baby", "chair"], odd: "chair" },
      { words: ["family", "parents", "children", "shoe"], odd: "shoe" },
      { words: ["husband", "wife", "niece", "book"], odd: "book" },
      { words: ["nephew", "twin", "sibling", "table"], odd: "table" },
      { words: ["mom", "dad", "grandma", "window"], odd: "window" },
      { words: ["relative", "in-law", "stepmother", "bed"], odd: "bed" },
      { words: ["household", "generation", "ancestor", "jacket"], odd: "jacket" },
    ],
  },
  {
    key: "weather",
    title: "Weather",
    cefrGroup: "A1-A2",
    items: [
      { words: ["sunny", "rainy", "cloudy", "happy"], odd: "happy" },
      { words: ["hot", "cold", "warm", "book"], odd: "book" },
      { words: ["snow", "rain", "wind", "shoe"], odd: "shoe" },
      { words: ["storm", "fog", "thunder", "chair"], odd: "chair" },
      { words: ["summer", "winter", "spring", "table"], odd: "table" },
      { words: ["cloud", "sun", "moon", "pencil"], odd: "pencil" },
      { words: ["umbrella", "raincoat", "boots", "cake"], odd: "cake" },
      { words: ["breeze", "drizzle", "shower", "window"], odd: "window" },
      { words: ["temperature", "forecast", "climate", "bed"], odd: "bed" },
      { words: ["icy", "freezing", "chilly", "guitar"], odd: "guitar" },
    ],
  },
  {
    key: "colors-shapes",
    title: "Colors and Shapes",
    cefrGroup: "A1-A2",
    items: [
      { words: ["red", "blue", "green", "dog"], odd: "dog" },
      { words: ["circle", "square", "triangle", "apple"], odd: "apple" },
      { words: ["yellow", "purple", "orange", "book"], odd: "book" },
      { words: ["star", "heart", "oval", "shoe"], odd: "shoe" },
      { words: ["pink", "black", "white", "chair"], odd: "chair" },
      { words: ["rectangle", "diamond", "circle", "table"], odd: "table" },
      { words: ["brown", "gray", "gold", "pencil"], odd: "pencil" },
      { words: ["square", "triangle", "star", "window"], odd: "window" },
      { words: ["silver", "green", "red", "bed"], odd: "bed" },
      { words: ["heart", "oval", "rectangle", "jacket"], odd: "jacket" },
    ],
  },
  {
    key: "sports",
    title: "Sports",
    cefrGroup: "A1-A2",
    items: [
      { words: ["soccer", "basketball", "tennis", "pizza"], odd: "pizza" },
      { words: ["swimming", "running", "cycling", "book"], odd: "book" },
      { words: ["volleyball", "baseball", "golf", "shoe"], odd: "shoe" },
      { words: ["coach", "player", "referee", "chair"], odd: "chair" },
      { words: ["goal", "score", "team", "table"], odd: "table" },
      { words: ["stadium", "court", "field", "pencil"], odd: "pencil" },
      { words: ["jump", "kick", "throw", "window"], odd: "window" },
      { words: ["medal", "trophy", "champion", "bed"], odd: "bed" },
      { words: ["boxing", "wrestling", "karate", "jacket"], odd: "jacket" },
      { words: ["racket", "ball", "helmet", "cake"], odd: "cake" },
    ],
  },
  {
    key: "body-parts",
    title: "Body Parts",
    cefrGroup: "A1-A2",
    items: [
      { words: ["hand", "foot", "arm", "car"], odd: "car" },
      { words: ["head", "leg", "eye", "book"], odd: "book" },
      { words: ["ear", "nose", "mouth", "shoe"], odd: "shoe" },
      { words: ["finger", "toe", "knee", "chair"], odd: "chair" },
      { words: ["shoulder", "elbow", "wrist", "table"], odd: "table" },
      { words: ["hair", "chin", "neck", "pencil"], odd: "pencil" },
      { words: ["back", "chest", "stomach", "window"], odd: "window" },
      { words: ["teeth", "tongue", "lips", "bed"], odd: "bed" },
      { words: ["heart", "brain", "bone", "jacket"], odd: "jacket" },
      { words: ["skin", "muscle", "nail", "cake"], odd: "cake" },
    ],
  },
  {
    key: "transportation",
    title: "Transportation",
    cefrGroup: "A1-A2",
    items: [
      { words: ["car", "bus", "train", "apple"], odd: "apple" },
      { words: ["bike", "motorcycle", "scooter", "book"], odd: "book" },
      { words: ["plane", "helicopter", "jet", "shoe"], odd: "shoe" },
      { words: ["boat", "ship", "ferry", "chair"], odd: "chair" },
      { words: ["taxi", "truck", "van", "table"], odd: "table" },
      { words: ["subway", "tram", "trolley", "pencil"], odd: "pencil" },
      { words: ["road", "highway", "bridge", "window"], odd: "window" },
      { words: ["driver", "passenger", "pilot", "bed"], odd: "bed" },
      { words: ["ticket", "station", "airport", "jacket"], odd: "jacket" },
      { words: ["wheel", "engine", "fuel", "cake"], odd: "cake" },
    ],
  },
  {
    key: "clothes",
    title: "Clothes",
    cefrGroup: "A1-A2",
    items: [
      { words: ["shirt", "pants", "dress", "car"], odd: "car" },
      { words: ["shoes", "socks", "boots", "book"], odd: "book" },
      { words: ["hat", "scarf", "gloves", "chair"], odd: "chair" },
      { words: ["jacket", "coat", "sweater", "table"], odd: "table" },
      { words: ["skirt", "shorts", "jeans", "pencil"], odd: "pencil" },
      { words: ["belt", "tie", "button", "window"], odd: "window" },
      { words: ["pajamas", "uniform", "costume", "bed"], odd: "bed" },
      { words: ["sleeve", "collar", "pocket", "apple"], odd: "apple" },
      { words: ["underwear", "swimsuit", "raincoat", "cake"], odd: "cake" },
      { words: ["zipper", "button", "lace", "guitar"], odd: "guitar" },
    ],
  },

  // ---------- B1-B2 (10 packs) ----------
  {
    key: "school-life",
    title: "School Life",
    cefrGroup: "B1-B2",
    items: [
      { words: ["classroom", "homework", "exam", "skateboard"], odd: "skateboard" },
      { words: ["teacher", "student", "principal", "pizza"], odd: "pizza" },
      { words: ["notebook", "textbook", "project", "bicycle"], odd: "bicycle" },
      { words: ["locker", "corridor", "library", "burger"], odd: "burger" },
      { words: ["subject", "timetable", "uniform", "dolphin"], odd: "dolphin" },
      { words: ["lesson", "quiz", "worksheet", "sunglasses"], odd: "sunglasses" },
      { words: ["backpack", "marker", "calculator", "guitar"], odd: "guitar" },
      { words: ["science", "history", "math", "sneakers"], odd: "sneakers" },
      { words: ["canteen", "classroom", "laboratory", "football"], odd: "football" },
      { words: ["semester", "grade", "assignment", "necklace"], odd: "necklace" },
    ],
  },
  {
    key: "hobbies-freetime",
    title: "Hobbies and Free Time",
    cefrGroup: "B1-B2",
    items: [
      { words: ["gaming", "drawing", "reading", "classroom"], odd: "classroom" },
      { words: ["football", "tennis", "swimming", "backpack"], odd: "backpack" },
      { words: ["music", "dance", "photography", "notebook"], odd: "notebook" },
      { words: ["hiking", "cycling", "camping", "calculator"], odd: "calculator" },
      { words: ["painting", "sketching", "crafting", "teacher"], odd: "teacher" },
      { words: ["movie", "series", "cartoon", "ruler"], odd: "ruler" },
      { words: ["singing", "acting", "practicing", "sandwich"], odd: "sandwich" },
      { words: ["jogging", "yoga", "skating", "library"], odd: "library" },
      { words: ["blogging", "vlogging", "posting", "pencil"], odd: "pencil" },
      { words: ["baking", "cooking", "decorating", "exam"], odd: "exam" },
    ],
  },
  {
    key: "friends-social",
    title: "Friends and Social Life",
    cefrGroup: "B1-B2",
    items: [
      { words: ["friend", "classmate", "teammate", "banana"], odd: "banana" },
      { words: ["message", "chat", "call", "notebook"], odd: "notebook" },
      { words: ["party", "hangout", "sleepover", "ruler"], odd: "ruler" },
      { words: ["funny", "kind", "friendly", "backpack"], odd: "backpack" },
      { words: ["trust", "support", "advice", "sandwich"], odd: "sandwich" },
      { words: ["invite", "reply", "cancel", "classroom"], odd: "classroom" },
      { words: ["secret", "joke", "story", "calculator"], odd: "calculator" },
      { words: ["group", "club", "team", "dolphin"], odd: "dolphin" },
      { words: ["text", "post", "comment", "whiteboard"], odd: "whiteboard" },
      { words: ["shy", "confident", "outgoing", "pizza"], odd: "pizza" },
    ],
  },
  {
    key: "money-shopping",
    title: "Money and Shopping",
    cefrGroup: "B1-B2",
    items: [
      { words: ["budget", "savings", "debt", "escalator"], odd: "escalator", explanation: "The first three are personal finance terms." },
      { words: ["discount", "refund", "receipt", "cousin"], odd: "cousin", explanation: "The first three are shopping transaction words." },
      { words: ["salary", "wage", "income", "bookmark"], odd: "bookmark", explanation: "The first three are earnings terms." },
      { words: ["expensive", "affordable", "overpriced", "microwave"], odd: "microwave", explanation: "The first three are price-description words." },
      { words: ["checkout", "basket", "cart", "seminar"], odd: "seminar", explanation: "The first three are shopping process items." },
      { words: ["cash", "credit card", "transfer", "pillow"], odd: "pillow", explanation: "The first three are payment methods." },
      { words: ["bargain", "deal", "sale", "passport"], odd: "passport", explanation: "The first three are money-saving words." },
      { words: ["invest", "save", "borrow", "toothbrush"], odd: "toothbrush", explanation: "The first three are money actions." },
      { words: ["wallet", "purse", "bank card", "laundry"], odd: "laundry", explanation: "The first three are money-carry items." },
      { words: ["bill", "fee", "charge", "balcony"], odd: "balcony", explanation: "The first three are cost-related nouns." },
    ],
  },
  {
    key: "health-wellness",
    title: "Health and Wellness",
    cefrGroup: "B1-B2",
    items: [
      { words: ["sleep", "exercise", "hydration", "printer"], odd: "printer", explanation: "The first three are health habits." },
      { words: ["stress", "burnout", "anxiety", "suitcase"], odd: "suitcase", explanation: "The first three are mental-health pressure terms." },
      { words: ["routine", "balance", "discipline", "cucumber"], odd: "cucumber", explanation: "The first three are lifestyle-management ideas." },
      { words: ["stretch", "jog", "cycle", "necklace"], odd: "necklace", explanation: "The first three are physical activities." },
      { words: ["bedtime", "alarm", "nap", "contract"], odd: "contract", explanation: "The first three are sleep-related words." },
      { words: ["meditation", "breathing", "mindfulness", "escalator"], odd: "escalator", explanation: "The first three are calming practices." },
      { words: ["healthy", "processed", "nutritious", "receptionist"], odd: "receptionist", explanation: "The first three describe food or diet quality." },
      { words: ["headache", "fatigue", "tension", "refund"], odd: "refund", explanation: "The first three are physical or stress symptoms." },
      { words: ["routine", "schedule", "habit", "boarding pass"], odd: "boarding pass", explanation: "The first three structure daily life." },
      { words: ["gym", "trainer", "workout", "cousin"], odd: "cousin", explanation: "The first three are exercise-context words." },
    ],
  },
  {
    key: "work-basics",
    title: "Work Basics",
    cefrGroup: "B1-B2",
    items: [
      { words: ["resume", "cover letter", "reference", "deadline"], odd: "deadline", explanation: "The first three are job application items." },
      { words: ["manager", "colleague", "assistant", "invoice"], odd: "invoice", explanation: "The first three are people at work." },
      { words: ["salary", "bonus", "wage", "interview"], odd: "interview", explanation: "The first three are types of pay." },
      { words: ["overtime", "commute", "shift", "contract"], odd: "contract", explanation: "The first three are parts of a work routine." },
      { words: ["presentation", "workshop", "seminar", "refund"], odd: "refund", explanation: "The first three are professional events." },
      { words: ["deadline", "target", "workload", "receptionist"], odd: "receptionist", explanation: "The first three are work pressure concepts." },
      { words: ["hire", "train", "promote", "keyboard"], odd: "keyboard", explanation: "The first three are HR actions." },
      { words: ["office", "branch", "headquarters", "passport"], odd: "passport", explanation: "The first three are workplace locations." },
      { words: ["client", "customer", "supplier", "pajamas"], odd: "pajamas", explanation: "The first three are business contacts." },
      { words: ["negotiate", "persuade", "propose", "kettle"], odd: "kettle", explanation: "The first three are professional communication actions." },
    ],
  },
  {
    key: "travel",
    title: "Travel",
    cefrGroup: "B1-B2",
    items: [
      { words: ["boarding pass", "passport", "visa", "receipt"], odd: "receipt", explanation: "The first three are border or flight documents." },
      { words: ["departure", "arrival", "layover", "dentist"], odd: "dentist", explanation: "The first three are journey stages." },
      { words: ["resort", "hostel", "guesthouse", "escalator"], odd: "escalator", explanation: "The first three are accommodation types." },
      { words: ["sightseeing", "backpacking", "cruising", "detergent"], odd: "detergent", explanation: "The first three are travel styles or activities." },
      { words: ["platform", "terminal", "gate", "balcony"], odd: "balcony", explanation: "The first three are transport-access points." },
      { words: ["route", "destination", "journey", "frying pan"], odd: "frying pan", explanation: "The first three describe a trip." },
      { words: ["guidebook", "map", "itinerary", "cushion"], odd: "cushion", explanation: "The first three are trip-planning tools." },
      { words: ["customs", "security", "immigration", "necklace"], odd: "necklace", explanation: "The first three are airport or border processes." },
      { words: ["taxi", "shuttle", "subway", "blanket"], odd: "blanket", explanation: "The first three are transport options." },
      { words: ["delay", "cancellation", "connection", "landlord"], odd: "landlord", explanation: "The first three are travel disruptions." },
    ],
  },
  {
    key: "technology",
    title: "Technology",
    cefrGroup: "B1-B2",
    items: [
      { words: ["smartphone", "laptop", "tablet", "sandwich"], odd: "sandwich", explanation: "The first three are personal devices." },
      { words: ["password", "username", "login", "umbrella"], odd: "umbrella", explanation: "The first three are account-access terms." },
      { words: ["download", "upload", "stream", "cactus"], odd: "cactus", explanation: "The first three are ways to move digital content." },
      { words: ["Wi-Fi", "signal", "bandwidth", "napkin"], odd: "napkin", explanation: "The first three relate to internet connection." },
      { words: ["app", "software", "update", "sofa"], odd: "sofa", explanation: "The first three are things installed on a device." },
      { words: ["notification", "alert", "reminder", "pillow"], odd: "pillow", explanation: "The first three are things a phone sends you." },
      { words: ["battery", "charger", "cable", "trophy"], odd: "trophy", explanation: "The first three are power-related tech items." },
      { words: ["email", "message", "inbox", "candle"], odd: "candle", explanation: "The first three are digital communication terms." },
      { words: ["screen", "keyboard", "mouse", "blanket"], odd: "blanket", explanation: "The first three are computer hardware parts." },
      { words: ["hacker", "virus", "firewall", "cushion"], odd: "cushion", explanation: "The first three are cybersecurity terms." },
    ],
  },
  {
    key: "environment",
    title: "Environment",
    cefrGroup: "B1-B2",
    items: [
      { words: ["pollution", "recycling", "climate", "birthday"], odd: "birthday", explanation: "The first three are environmental topics." },
      { words: ["forest", "ocean", "wildlife", "calculator"], odd: "calculator", explanation: "The first three are parts of nature." },
      { words: ["drought", "flood", "wildfire", "envelope"], odd: "envelope", explanation: "The first three are natural disasters." },
      { words: ["solar", "wind", "renewable", "sandwich"], odd: "sandwich", explanation: "The first three relate to clean energy." },
      { words: ["plastic", "waste", "landfill", "umbrella"], odd: "umbrella", explanation: "The first three are pollution-related terms." },
      { words: ["conservation", "habitat", "biodiversity", "kettle"], odd: "kettle", explanation: "The first three describe protecting nature." },
      { words: ["emission", "carbon", "greenhouse", "napkin"], odd: "napkin", explanation: "The first three relate to climate change causes." },
      { words: ["endangered", "extinct", "species", "trophy"], odd: "trophy", explanation: "The first three describe threatened animals." },
      { words: ["compost", "reuse", "reduce", "candle"], odd: "candle", explanation: "The first three are sustainable habits." },
      { words: ["ecosystem", "rainforest", "coral reef", "cushion"], odd: "cushion", explanation: "The first three are natural environments." },
    ],
  },
  {
    key: "emotions",
    title: "Emotions",
    cefrGroup: "B1-B2",
    items: [
      { words: ["frustration", "satisfaction", "anxiety", "ladder"], odd: "ladder", explanation: "The first three are emotional states." },
      { words: ["relief", "pride", "disappointment", "envelope"], odd: "envelope", explanation: "The first three are feelings after an event." },
      { words: ["nervous", "confident", "embarrassed", "calculator"], odd: "calculator", explanation: "The first three describe how someone feels." },
      { words: ["grateful", "jealous", "hopeful", "sandwich"], odd: "sandwich", explanation: "The first three are emotional attitudes." },
      { words: ["overwhelmed", "content", "irritated", "umbrella"], odd: "umbrella", explanation: "The first three describe a mood." },
      { words: ["excitement", "boredom", "curiosity", "kettle"], odd: "kettle", explanation: "The first three are feelings toward something new." },
      { words: ["guilt", "regret", "shame", "napkin"], odd: "napkin", explanation: "The first three are feelings about a past action." },
      { words: ["calm", "tense", "restless", "trophy"], odd: "trophy", explanation: "The first three describe emotional energy levels." },
      { words: ["empathy", "sympathy", "compassion", "candle"], odd: "candle", explanation: "The first three are feelings toward others." },
      { words: ["motivated", "discouraged", "determined", "cushion"], odd: "cushion", explanation: "The first three relate to drive or willpower." },
    ],
  },

  // ---------- C1-C2 (10 packs) ----------
  {
    key: "business-economics",
    title: "Business and Economics",
    cefrGroup: "C1-C2",
    items: [
      { words: ["inflation", "recession", "revenue", "umbrella"], odd: "umbrella", explanation: "The first three are economic terms." },
      { words: ["subsidy", "commodity", "monopoly", "napkin"], odd: "napkin", explanation: "The first three relate to markets and trade." },
      { words: ["stakeholder", "shareholder", "investor", "kettle"], odd: "kettle", explanation: "The first three are people with a financial interest in a company." },
      { words: ["merger", "acquisition", "takeover", "candle"], odd: "candle", explanation: "The first three describe companies combining." },
      { words: ["austerity", "surplus", "deficit", "trophy"], odd: "trophy", explanation: "The first three describe a budget's financial state." },
      { words: ["volatile", "stagnant", "booming", "cushion"], odd: "cushion", explanation: "The first three describe how a market is performing." },
      { words: ["leverage", "capital", "asset", "ladder"], odd: "ladder", explanation: "The first three are financial resources." },
      { words: ["tariff", "quota", "embargo", "envelope"], odd: "envelope", explanation: "The first three are trade restrictions." },
      { words: ["dividend", "interest", "yield", "sandwich"], odd: "sandwich", explanation: "The first three describe returns on an investment." },
      { words: ["consolidate", "diversify", "liquidate", "umbrella"], odd: "umbrella", explanation: "The first three are financial strategies." },
    ],
  },
  {
    key: "politics-governance",
    title: "Politics and Governance",
    cefrGroup: "C1-C2",
    items: [
      { words: ["legislation", "referendum", "sovereignty", "napkin"], odd: "napkin", explanation: "The first three are governance concepts." },
      { words: ["diplomacy", "coalition", "alliance", "kettle"], odd: "kettle", explanation: "The first three describe political cooperation." },
      { words: ["corruption", "bribery", "nepotism", "candle"], odd: "candle", explanation: "The first three are forms of political misconduct." },
      { words: ["bureaucracy", "administration", "authority", "trophy"], odd: "trophy", explanation: "The first three relate to governing institutions." },
      { words: ["dissent", "protest", "opposition", "cushion"], odd: "cushion", explanation: "The first three describe pushing back against power." },
      { words: ["autonomous", "sovereign", "independent", "ladder"], odd: "ladder", explanation: "The first three describe self-governance." },
      { words: ["mandate", "decree", "directive", "envelope"], odd: "envelope", explanation: "The first three are official orders." },
      { words: ["constituency", "electorate", "delegate", "sandwich"], odd: "sandwich", explanation: "The first three relate to representation and voting." },
      { words: ["policy", "regulation", "statute", "umbrella"], odd: "umbrella", explanation: "The first three are types of official rules." },
      { words: ["monarchy", "democracy", "republic", "napkin"], odd: "napkin", explanation: "The first three are systems of government." },
    ],
  },
  {
    key: "science-innovation",
    title: "Science and Innovation",
    cefrGroup: "C1-C2",
    items: [
      { words: ["hypothesis", "empirical", "catalyst", "kettle"], odd: "kettle", explanation: "The first three are research/scientific-method terms." },
      { words: ["prototype", "innovation", "breakthrough", "candle"], odd: "candle", explanation: "The first three describe new inventions." },
      { words: ["anomaly", "variable", "correlation", "trophy"], odd: "trophy", explanation: "The first three are data-analysis terms." },
      { words: ["synthesis", "compound", "reaction", "cushion"], odd: "cushion", explanation: "The first three are chemistry terms." },
      { words: ["algorithm", "automation", "artificial intelligence", "ladder"], odd: "ladder", explanation: "The first three are computing concepts." },
      { words: ["genome", "mutation", "organism", "envelope"], odd: "envelope", explanation: "The first three are biology terms." },
      { words: ["obsolete", "cutting-edge", "emerging", "sandwich"], odd: "sandwich", explanation: "The first three describe how new or old technology is." },
      { words: ["replicate", "verify", "validate", "umbrella"], odd: "umbrella", explanation: "The first three describe confirming a scientific result." },
      { words: ["theory", "law", "principle", "napkin"], odd: "napkin", explanation: "The first three are types of established scientific ideas." },
      { words: ["viable", "sustainable", "scalable", "kettle"], odd: "kettle", explanation: "The first three describe whether an innovation can succeed long-term." },
    ],
  },
  {
    key: "arts-culture",
    title: "Arts and Culture",
    cefrGroup: "C1-C2",
    items: [
      { words: ["aesthetic", "avant-garde", "eclectic", "candle"], odd: "candle", explanation: "The first three describe artistic style." },
      { words: ["narrative", "genre", "motif", "trophy"], odd: "trophy", explanation: "The first three are literary/storytelling terms." },
      { words: ["renowned", "acclaimed", "celebrated", "cushion"], odd: "cushion", explanation: "The first three describe a famous artist's reputation." },
      { words: ["satirical", "provocative", "poignant", "ladder"], odd: "ladder", explanation: "The first three describe the tone of a work of art." },
      { words: ["exhibition", "gallery", "installation", "envelope"], odd: "envelope", explanation: "The first three relate to displaying art." },
      { words: ["heritage", "tradition", "custom", "sandwich"], odd: "sandwich", explanation: "The first three describe cultural continuity." },
      { words: ["nuanced", "subtle", "understated", "umbrella"], odd: "umbrella", explanation: "The first three describe a delicate artistic quality." },
      { words: ["critic", "curator", "patron", "napkin"], odd: "napkin", explanation: "The first three are people involved in the art world." },
      { words: ["symbolism", "allegory", "metaphor", "kettle"], odd: "kettle", explanation: "The first three are literary devices." },
      { words: ["timeless", "contemporary", "classical", "candle"], odd: "candle", explanation: "The first three describe when a work of art belongs." },
    ],
  },
  {
    key: "ethics-philosophy",
    title: "Ethics and Philosophy",
    cefrGroup: "C1-C2",
    items: [
      { words: ["virtue", "integrity", "altruism", "trophy"], odd: "trophy", explanation: "The first three are moral qualities." },
      { words: ["dilemma", "predicament", "quandary", "cushion"], odd: "cushion", explanation: "The first three describe a difficult moral choice." },
      { words: ["autonomy", "free will", "agency", "ladder"], odd: "ladder", explanation: "The first three relate to personal choice and control." },
      { words: ["hypocrisy", "pretense", "deceit", "envelope"], odd: "envelope", explanation: "The first three describe dishonest behavior." },
      { words: ["utilitarian", "idealistic", "pragmatic", "sandwich"], odd: "sandwich", explanation: "The first three describe philosophical approaches to decisions." },
      { words: ["subjective", "objective", "impartial", "umbrella"], odd: "umbrella", explanation: "The first three describe how a viewpoint is formed." },
      { words: ["coercion", "consent", "obligation", "napkin"], odd: "napkin", explanation: "The first three relate to how someone agrees to something." },
      { words: ["humility", "arrogance", "vanity", "kettle"], odd: "kettle", explanation: "The first three describe how someone views themselves." },
      { words: ["justice", "fairness", "equity", "candle"], odd: "candle", explanation: "The first three relate to treating people rightly." },
      { words: ["conscience", "morality", "principle", "trophy"], odd: "trophy", explanation: "The first three guide right and wrong behavior." },
    ],
  },
  {
    key: "global-affairs",
    title: "Global Affairs",
    cefrGroup: "C1-C2",
    items: [
      { words: ["globalization", "interdependence", "integration", "cushion"], odd: "cushion", explanation: "The first three describe countries becoming connected." },
      { words: ["refugee", "displaced person", "asylum seeker", "ladder"], odd: "ladder", explanation: "The first three describe people forced to leave home." },
      { words: ["sanction", "embargo", "boycott", "envelope"], odd: "envelope", explanation: "The first three are ways countries pressure each other." },
      { words: ["summit", "conference", "negotiation", "sandwich"], odd: "sandwich", explanation: "The first three are formal international meetings." },
      { words: ["treaty", "accord", "pact", "umbrella"], odd: "umbrella", explanation: "The first three are formal agreements between nations." },
      { words: ["humanitarian", "philanthropic", "charitable", "napkin"], odd: "napkin", explanation: "The first three describe helping people in need." },
      { words: ["instability", "unrest", "turmoil", "kettle"], odd: "kettle", explanation: "The first three describe a troubled situation in a country." },
      { words: ["diaspora", "migration", "emigration", "candle"], odd: "candle", explanation: "The first three describe people moving across borders." },
      { words: ["intervention", "mediation", "arbitration", "trophy"], odd: "trophy", explanation: "The first three describe getting involved to resolve conflict." },
      { words: ["prosperity", "development", "growth", "cushion"], odd: "cushion", explanation: "The first three describe a country's progress." },
    ],
  },
  {
    key: "psychology-behavior",
    title: "Psychology and Behavior",
    cefrGroup: "C1-C2",
    items: [
      { words: ["cognition", "perception", "reasoning", "ladder"], odd: "ladder", explanation: "The first three are mental processes." },
      { words: ["resilience", "grit", "perseverance", "envelope"], odd: "envelope", explanation: "The first three describe the ability to keep going." },
      { words: ["empathy", "compassion", "sympathy", "sandwich"], odd: "sandwich", explanation: "The first three describe caring about others' feelings." },
      { words: ["impulsive", "spontaneous", "reckless", "umbrella"], odd: "umbrella", explanation: "The first three describe acting without much thought." },
      { words: ["introspection", "self-reflection", "rumination", "napkin"], odd: "napkin", explanation: "The first three describe thinking about oneself." },
      { words: ["temperament", "disposition", "personality", "kettle"], odd: "kettle", explanation: "The first three describe someone's natural character." },
      { words: ["motivation", "incentive", "drive", "candle"], odd: "candle", explanation: "The first three push someone toward a goal." },
      { words: ["bias", "prejudice", "stereotype", "trophy"], odd: "trophy", explanation: "The first three describe unfair assumptions." },
      { words: ["subconscious", "instinct", "intuition", "cushion"], odd: "cushion", explanation: "The first three relate to thinking below conscious awareness." },
      { words: ["gratification", "satisfaction", "fulfillment", "ladder"], odd: "ladder", explanation: "The first three describe a sense of contentment." },
    ],
  },
  {
    key: "law-justice",
    title: "Law and Justice",
    cefrGroup: "C1-C2",
    items: [
      { words: ["verdict", "ruling", "judgment", "envelope"], odd: "envelope", explanation: "The first three are official court decisions." },
      { words: ["testimony", "evidence", "affidavit", "sandwich"], odd: "sandwich", explanation: "The first three are used to support a case in court." },
      { words: ["plaintiff", "defendant", "witness", "umbrella"], odd: "umbrella", explanation: "The first three are people involved in a trial." },
      { words: ["litigation", "lawsuit", "arbitration", "napkin"], odd: "napkin", explanation: "The first three are ways legal disputes are resolved." },
      { words: ["acquit", "exonerate", "absolve", "kettle"], odd: "kettle", explanation: "The first three mean clearing someone of guilt." },
      { words: ["jurisdiction", "precedent", "statute", "candle"], odd: "candle", explanation: "The first three are legal-system terms." },
      { words: ["indict", "prosecute", "charge", "trophy"], odd: "trophy", explanation: "The first three mean formally accusing someone." },
      { words: ["impartial", "unbiased", "neutral", "cushion"], odd: "cushion", explanation: "The first three describe fair judgment." },
      { words: ["contract", "agreement", "covenant", "ladder"], odd: "ladder", explanation: "The first three are legally binding arrangements." },
      { words: ["culpable", "liable", "responsible", "envelope"], odd: "envelope", explanation: "The first three describe being at fault." },
    ],
  },
  {
    key: "linguistics-communication",
    title: "Linguistics and Communication",
    cefrGroup: "C1-C2",
    items: [
      { words: ["rhetoric", "eloquence", "articulation", "sandwich"], odd: "sandwich", explanation: "The first three relate to speaking persuasively and clearly." },
      { words: ["dialect", "accent", "vernacular", "umbrella"], odd: "umbrella", explanation: "The first three describe regional variations of speech." },
      { words: ["ambiguity", "vagueness", "obscurity", "napkin"], odd: "napkin", explanation: "The first three describe unclear meaning." },
      { words: ["syntax", "grammar", "structure", "kettle"], odd: "kettle", explanation: "The first three relate to how sentences are built." },
      { words: ["connotation", "implication", "nuance", "candle"], odd: "candle", explanation: "The first three describe hidden or subtle meaning." },
      { words: ["discourse", "dialogue", "conversation", "trophy"], odd: "trophy", explanation: "The first three describe an exchange of ideas." },
      { words: ["colloquial", "informal", "casual", "cushion"], odd: "cushion", explanation: "The first three describe relaxed, everyday language." },
      { words: ["paraphrase", "summarize", "reword", "ladder"], odd: "ladder", explanation: "The first three mean restating something differently." },
      { words: ["fluency", "proficiency", "competence", "envelope"], odd: "envelope", explanation: "The first three describe language skill level." },
      { words: ["literal", "figurative", "metaphorical", "sandwich"], odd: "sandwich", explanation: "The first three describe types of meaning in language." },
    ],
  },
  {
    key: "academia-research",
    title: "Academia and Research",
    cefrGroup: "C1-C2",
    items: [
      { words: ["methodology", "approach", "framework", "umbrella"], odd: "umbrella", explanation: "The first three describe how research is conducted." },
      { words: ["citation", "reference", "bibliography", "napkin"], odd: "napkin", explanation: "The first three credit sources used in research." },
      { words: ["hypothesis", "thesis", "proposition", "kettle"], odd: "kettle", explanation: "The first three are claims to be tested or argued." },
      { words: ["peer review", "evaluation", "assessment", "candle"], odd: "candle", explanation: "The first three describe checking the quality of research." },
      { words: ["plagiarism", "forgery", "fabrication", "trophy"], odd: "trophy", explanation: "The first three are forms of academic dishonesty." },
      { words: ["scholarship", "grant", "fellowship", "cushion"], odd: "cushion", explanation: "The first three fund academic study." },
      { words: ["empirical", "theoretical", "analytical", "ladder"], odd: "ladder", explanation: "The first three describe types of academic reasoning." },
      { words: ["dissertation", "thesis", "manuscript", "envelope"], odd: "envelope", explanation: "The first three are extended pieces of academic writing." },
      { words: ["tenure", "professorship", "faculty", "sandwich"], odd: "sandwich", explanation: "The first three relate to academic careers." },
      { words: ["interdisciplinary", "multidisciplinary", "cross-disciplinary", "umbrella"], odd: "umbrella", explanation: "The first three describe combining multiple fields of study." },
    ],
  },
];

export default ODD_ONE_OUT_PACKS;
