// Vocabulary category, Odd One Out game: 9 category packs grouped by audience.
// Each pack: { key, title, audience: "Kids" | "Teens" | "Adults", items: [{ words: [4], odd }] }
const ODD_ONE_OUT_PACKS = [
  {
    key: "kids-animals",
    title: "Animals",
    audience: "Kids",
    items: [
      { words: ["dog", "cat", "fish", "chair"], odd: "chair" },
      { words: ["lion", "tiger", "elephant", "pencil"], odd: "pencil" },
      { words: ["bird", "rabbit", "monkey", "shoe"], odd: "shoe" },
      { words: ["cow", "horse", "sheep", "banana"], odd: "banana" },
      { words: ["duck", "chicken", "goat", "table"], odd: "table" },
      { words: ["snake", "frog", "zebra", "book"], odd: "book" },
      { words: ["bear", "panda", "giraffe", "window"], odd: "window" },
      { words: ["dolphin", "whale", "shark", "jacket"], odd: "jacket" },
      { words: ["ant", "bee", "butterfly", "spoon"], odd: "spoon" },
      { words: ["spider", "camel", "donkey", "bed"], odd: "bed" },
      { words: ["fox", "wolf", "deer", "eraser"], odd: "eraser" },
      { words: ["penguin", "parrot", "eagle", "sock"], odd: "sock" },
      { words: ["hamster", "mouse", "rabbit", "bus"], odd: "bus" },
      { words: ["crocodile", "turtle", "lizard", "cup"], odd: "cup" },
      { words: ["octopus", "crab", "starfish", "hat"], odd: "hat" },
    ],
  },
  {
    key: "kids-food",
    title: "Food",
    audience: "Kids",
    items: [
      { words: ["apple", "banana", "orange", "bus"], odd: "bus" },
      { words: ["bread", "rice", "pasta", "pencil"], odd: "pencil" },
      { words: ["cake", "cookie", "ice cream", "chair"], odd: "chair" },
      { words: ["carrot", "potato", "tomato", "shoe"], odd: "shoe" },
      { words: ["egg", "cheese", "yogurt", "table"], odd: "table" },
      { words: ["burger", "pizza", "sandwich", "window"], odd: "window" },
      { words: ["grape", "pear", "peach", "book"], odd: "book" },
      { words: ["soup", "salad", "noodles", "bed"], odd: "bed" },
      { words: ["chicken", "fish", "beef", "ruler"], odd: "ruler" },
      { words: ["onion", "garlic", "pepper", "jacket"], odd: "jacket" },
      { words: ["milk", "juice", "water", "banana"], odd: "banana" },
      { words: ["candy", "chocolate", "lollipop", "desk"], odd: "desk" },
      { words: ["corn", "peas", "beans", "sock"], odd: "sock" },
      { words: ["pancake", "waffle", "muffin", "lamp"], odd: "lamp" },
      { words: ["strawberry", "blueberry", "watermelon", "notebook"], odd: "notebook" },
    ],
  },
  {
    key: "kids-school",
    title: "School",
    audience: "Kids",
    items: [
      { words: ["pencil", "eraser", "ruler", "banana"], odd: "banana" },
      { words: ["desk", "chair", "board", "tiger"], odd: "tiger" },
      { words: ["book", "notebook", "backpack", "apple"], odd: "apple" },
      { words: ["teacher", "student", "classroom", "fish"], odd: "fish" },
      { words: ["pen", "marker", "crayon", "shoe"], odd: "shoe" },
      { words: ["scissors", "glue", "paper", "dog"], odd: "dog" },
      { words: ["lunchbox", "bottle", "bag", "monkey"], odd: "monkey" },
      { words: ["computer", "tablet", "keyboard", "cookie"], odd: "cookie" },
      { words: ["quiz", "homework", "lesson", "elephant"], odd: "elephant" },
      { words: ["map", "clock", "poster", "burger"], odd: "burger" },
      { words: ["library", "gym", "hall", "dolphin"], odd: "dolphin" },
      { words: ["number", "letter", "word", "spoon"], odd: "spoon" },
      { words: ["class", "break", "test", "rabbit"], odd: "rabbit" },
      { words: ["sharpener", "folder", "binder", "orange"], odd: "orange" },
      { words: ["principal", "classmate", "teacher", "pizza"], odd: "pizza" },
    ],
  },
  {
    key: "teens-school-life",
    title: "School Life",
    audience: "Teens",
    items: [
      { words: ["classroom", "homework", "exam", "skateboard"], odd: "skateboard" },
      { words: ["teacher", "student", "principal", "pizza"], odd: "pizza" },
      { words: ["notebook", "textbook", "project", "bicycle"], odd: "bicycle" },
      { words: ["locker", "corridor", "library", "burger"], odd: "burger" },
      { words: ["subject", "timetable", "uniform", "dolphin"], odd: "dolphin" },
      { words: ["lesson", "quiz", "worksheet", "sunglasses"], odd: "sunglasses" },
      { words: ["backpack", "marker", "calculator", "guitar"], odd: "guitar" },
      { words: ["science", "history", "math", "sneakers"], odd: "sneakers" },
      { words: ["canteen", "classroom", "laboratory", "football"], odd: "football" },
      { words: ["semester", "grade", "assignment", "necklace"], odd: "necklace" },
      { words: ["pencil case", "folder", "binder", "beach"], odd: "beach" },
      { words: ["attendance", "detention", "break", "hamburger"], odd: "hamburger" },
      { words: ["presentation", "speech", "report", "shampoo"], odd: "shampoo" },
      { words: ["tutor", "classmate", "counselor", "pancake"], odd: "pancake" },
      { words: ["whiteboard", "projector", "worksheet", "roller skates"], odd: "roller skates" },
    ],
  },
  {
    key: "teens-hobbies",
    title: "Hobbies and Free Time",
    audience: "Teens",
    items: [
      { words: ["gaming", "drawing", "reading", "classroom"], odd: "classroom" },
      { words: ["football", "tennis", "swimming", "backpack"], odd: "backpack" },
      { words: ["music", "dance", "photography", "notebook"], odd: "notebook" },
      { words: ["hiking", "cycling", "camping", "calculator"], odd: "calculator" },
      { words: ["painting", "sketching", "crafting", "teacher"], odd: "teacher" },
      { words: ["movie", "series", "cartoon", "ruler"], odd: "ruler" },
      { words: ["singing", "acting", "practicing", "sandwich"], odd: "sandwich" },
      { words: ["jogging", "yoga", "skating", "library"], odd: "library" },
      { words: ["blogging", "vlogging", "posting", "pencil"], odd: "pencil" },
      { words: ["baking", "cooking", "decorating", "exam"], odd: "exam" },
      { words: ["fishing", "surfing", "diving", "eraser"], odd: "eraser" },
      { words: ["collecting", "trading", "building", "corridor"], odd: "corridor" },
      { words: ["chatting", "texting", "calling", "desk"], odd: "desk" },
      { words: ["camping", "trekking", "climbing", "principal"], odd: "principal" },
      { words: ["drums", "guitar", "keyboard", "locker"], odd: "locker" },
    ],
  },
  {
    key: "teens-friends",
    title: "Friends and Social Life",
    audience: "Teens",
    items: [
      { words: ["friend", "classmate", "teammate", "banana"], odd: "banana" },
      { words: ["message", "chat", "call", "notebook"], odd: "notebook" },
      { words: ["party", "hangout", "sleepover", "ruler"], odd: "ruler" },
      { words: ["funny", "kind", "friendly", "backpack"], odd: "backpack" },
      { words: ["trust", "support", "advice", "sandwich"], odd: "sandwich" },
      { words: ["invite", "reply", "cancel", "classroom"], odd: "classroom" },
      { words: ["secret", "joke", "story", "calculator"], odd: "calculator" },
      { words: ["group", "club", "team", "dolphin"], odd: "dolphin" },
      { words: ["text", "post", "comment", "whiteboard"], odd: "whiteboard" },
      { words: ["shy", "confident", "outgoing", "pizza"], odd: "pizza" },
      { words: ["weekend", "mall", "cinema", "eraser"], odd: "eraser" },
      { words: ["argument", "problem", "apology", "keyboard"], odd: "keyboard" },
      { words: ["best friend", "neighbor", "cousin", "basketball"], odd: "basketball" },
      { words: ["celebrate", "laugh", "share", "exam"], odd: "exam" },
      { words: ["playlist", "selfie", "status", "marker"], odd: "marker" },
    ],
  },
  {
    key: "adults-work",
    title: "Work",
    audience: "Adults",
    items: [
      { words: ["meeting", "deadline", "manager", "pillow"], odd: "pillow" },
      { words: ["office", "laptop", "email", "banana"], odd: "banana" },
      { words: ["salary", "promotion", "contract", "bicycle"], odd: "bicycle" },
      { words: ["colleague", "client", "supervisor", "sandwich"], odd: "sandwich" },
      { words: ["interview", "resume", "vacancy", "dolphin"], odd: "dolphin" },
      { words: ["report", "spreadsheet", "presentation", "toothbrush"], odd: "toothbrush" },
      { words: ["commute", "shift", "overtime", "watermelon"], odd: "watermelon" },
      { words: ["conference", "project", "target", "slipper"], odd: "slipper" },
      { words: ["agenda", "schedule", "task", "guitar"], odd: "guitar" },
      { words: ["uniform", "office", "receptionist", "potato"], odd: "potato" },
      { words: ["deadline", "pressure", "feedback", "umbrella"], odd: "umbrella" },
      { words: ["manager", "assistant", "employee", "pancake"], odd: "pancake" },
      { words: ["printer", "document", "signature", "rabbit"], odd: "rabbit" },
      { words: ["training", "workshop", "seminar", "socks"], odd: "socks" },
      { words: ["negotiation", "proposal", "strategy", "notebook"], odd: "notebook" },
    ],
  },
  {
    key: "adults-travel",
    title: "Travel",
    audience: "Adults",
    items: [
      { words: ["passport", "suitcase", "airport", "toothbrush"], odd: "toothbrush" },
      { words: ["hotel", "booking", "check-in", "elephant"], odd: "elephant" },
      { words: ["flight", "boarding pass", "gate", "frying pan"], odd: "frying pan" },
      { words: ["tourist", "guide", "itinerary", "pillow"], odd: "pillow" },
      { words: ["visa", "customs", "luggage", "bicycle"], odd: "bicycle" },
      { words: ["train", "platform", "ticket", "shampoo"], odd: "shampoo" },
      { words: ["map", "route", "destination", "cookie"], odd: "cookie" },
      { words: ["hostel", "reservation", "reception", "monkey"], odd: "monkey" },
      { words: ["delay", "departure", "arrival", "jacket"], odd: "jacket" },
      { words: ["beach", "resort", "sightseeing", "calculator"], odd: "calculator" },
      { words: ["backpack", "journey", "trip", "cucumber"], odd: "cucumber" },
      { words: ["taxi", "station", "terminal", "blanket"], odd: "blanket" },
      { words: ["museum", "landmark", "guidebook", "toothbrush"], odd: "toothbrush" },
      { words: ["currency", "exchange", "traveler", "sofa"], odd: "sofa" },
      { words: ["ferry", "harbor", "cruise", "desk"], odd: "desk" },
    ],
  },
  {
    key: "adults-daily-life",
    title: "Daily Life and Relationships",
    audience: "Adults",
    items: [
      { words: ["partner", "friend", "neighbor", "suitcase"], odd: "suitcase" },
      { words: ["dinner", "routine", "chores", "tiger"], odd: "tiger" },
      { words: ["text", "reply", "conversation", "passport"], odd: "passport" },
      { words: ["marriage", "dating", "breakup", "sandwich"], odd: "sandwich" },
      { words: ["trust", "support", "respect", "laptop"], odd: "laptop" },
      { words: ["shopping", "cleaning", "cooking", "dolphin"], odd: "dolphin" },
      { words: ["family", "cousin", "sibling", "airport"], odd: "airport" },
      { words: ["argument", "apology", "compromise", "notebook"], odd: "notebook" },
      { words: ["rent", "bills", "groceries", "elephant"], odd: "elephant" },
      { words: ["busy", "relaxed", "lonely", "umbrella"], odd: "umbrella" },
      { words: ["neighbor", "landlord", "roommate", "pancake"], odd: "pancake" },
      { words: ["weekend", "errands", "laundry", "guitar"], odd: "guitar" },
      { words: ["message", "call", "voicemail", "bicycle"], odd: "bicycle" },
      { words: ["anniversary", "gift", "dinner", "classroom"], odd: "classroom" },
      { words: ["habit", "routine", "balance", "shark"], odd: "shark" },
    ],
  },
];

export default ODD_ONE_OUT_PACKS;
