// Vocabulary category, Odd One Out game: 9 category packs grouped by audience.
// Each pack: { key, title, audience: "Kids" | "Teens" | "Adults", items: [{ words: [4], odd }] }
const ODD_ONE_OUT_PACKS = [
  {
    key: "kids-animals",
    title: "Animals",
    audience: "Kids",
    items: [
      { words: ["dog", "cat", "fish", "chair"], odd: "chair" },
      { words: ["lion", "tiger", "elephant", "pencil"], odd: "pencil" },
      { words: ["bird", "rabbit", "monkey", "shoe"], odd: "shoe" },
      { words: ["cow", "horse", "sheep", "banana"], odd: "banana" },
      { words: ["duck", "chicken", "goat", "table"], odd: "table" },
      { words: ["snake", "frog", "zebra", "book"], odd: "book" },
      { words: ["bear", "panda", "giraffe", "window"], odd: "window" },
      { words: ["dolphin", "whale", "shark", "jacket"], odd: "jacket" },
      { words: ["ant", "bee", "butterfly", "spoon"], odd: "spoon" },
      { words: ["spider", "camel", "donkey", "bed"], odd: "bed" },
      { words: ["fox", "wolf", "deer", "eraser"], odd: "eraser" },
      { words: ["penguin", "parrot", "eagle", "sock"], odd: "sock" },
      { words: ["hamster", "mouse", "rabbit", "bus"], odd: "bus" },
      { words: ["crocodile", "turtle", "lizard", "cup"], odd: "cup" },
      { words: ["octopus", "crab", "starfish", "hat"], odd: "hat" },
    ],
  },
  {
    key: "kids-food",
    title: "Food",
    audience: "Kids",
    items: [
      { words: ["apple", "banana", "orange", "bus"], odd: "bus" },
      { words: ["bread", "rice", "pasta", "pencil"], odd: "pencil" },
      { words: ["cake", "cookie", "ice cream", "chair"], odd: "chair" },
      { words: ["carrot", "potato", "tomato", "shoe"], odd: "shoe" },
      { words: ["egg", "cheese", "yogurt", "table"], odd: "table" },
      { words: ["burger", "pizza", "sandwich", "window"], odd: "window" },
      { words: ["grape", "pear", "peach", "book"], odd: "book" },
      { words: ["soup", "salad", "noodles", "bed"], odd: "bed" },
      { words: ["chicken", "fish", "beef", "ruler"], odd: "ruler" },
      { words: ["onion", "garlic", "pepper", "jacket"], odd: "jacket" },
      { words: ["milk", "juice", "water", "banana"], odd: "banana" },
      { words: ["candy", "chocolate", "lollipop", "desk"], odd: "desk" },
      { words: ["corn", "peas", "beans", "sock"], odd: "sock" },
      { words: ["pancake", "waffle", "muffin", "lamp"], odd: "lamp" },
      { words: ["strawberry", "blueberry", "watermelon", "notebook"], odd: "notebook" },
    ],
  },
  {
    key: "kids-school",
    title: "School",
    audience: "Kids",
    items: [
      { words: ["pencil", "eraser", "ruler", "banana"], odd: "banana" },
      { words: ["desk", "chair", "board", "tiger"], odd: "tiger" },
      { words: ["book", "notebook", "backpack", "apple"], odd: "apple" },
      { words: ["teacher", "student", "classroom", "fish"], odd: "fish" },
      { words: ["pen", "marker", "crayon", "shoe"], odd: "shoe" },
      { words: ["scissors", "glue", "paper", "dog"], odd: "dog" },
      { words: ["lunchbox", "bottle", "bag", "monkey"], odd: "monkey" },
      { words: ["computer", "tablet", "keyboard", "cookie"], odd: "cookie" },
      { words: ["quiz", "homework", "lesson", "elephant"], odd: "elephant" },
      { words: ["map", "clock", "poster", "burger"], odd: "burger" },
      { words: ["library", "gym", "hall", "dolphin"], odd: "dolphin" },
      { words: ["number", "letter", "word", "spoon"], odd: "spoon" },
      { words: ["class", "break", "test", "rabbit"], odd: "rabbit" },
      { words: ["sharpener", "folder", "binder", "orange"], odd: "orange" },
      { words: ["principal", "classmate", "teacher", "pizza"], odd: "pizza" },
    ],
  },
  {
    key: "teens-school-life",
    title: "School Life",
    audience: "Teens",
    items: [
      { words: ["classroom", "homework", "exam", "skateboard"], odd: "skateboard" },
      { words: ["teacher", "student", "principal", "pizza"], odd: "pizza" },
      { words: ["notebook", "textbook", "project", "bicycle"], odd: "bicycle" },
      { words: ["locker", "corridor", "library", "burger"], odd: "burger" },
      { words: ["subject", "timetable", "uniform", "dolphin"], odd: "dolphin" },
      { words: ["lesson", "quiz", "worksheet", "sunglasses"], odd: "sunglasses" },
      { words: ["backpack", "marker", "calculator", "guitar"], odd: "guitar" },
      { words: ["science", "history", "math", "sneakers"], odd: "sneakers" },
      { words: ["canteen", "classroom", "laboratory", "football"], odd: "football" },
      { words: ["semester", "grade", "assignment", "necklace"], odd: "necklace" },
      { words: ["pencil case", "folder", "binder", "beach"], odd: "beach" },
      { words: ["attendance", "detention", "break", "hamburger"], odd: "hamburger" },
      { words: ["presentation", "speech", "report", "shampoo"], odd: "shampoo" },
      { words: ["tutor", "classmate", "counselor", "pancake"], odd: "pancake" },
      { words: ["whiteboard", "projector", "worksheet", "roller skates"], odd: "roller skates" },
    ],
  },
  {
    key: "teens-hobbies",
    title: "Hobbies and Free Time",
    audience: "Teens",
    items: [
      { words: ["gaming", "drawing", "reading", "classroom"], odd: "classroom" },
      { words: ["football", "tennis", "swimming", "backpack"], odd: "backpack" },
      { words: ["music", "dance", "photography", "notebook"], odd: "notebook" },
      { words: ["hiking", "cycling", "camping", "calculator"], odd: "calculator" },
      { words: ["painting", "sketching", "crafting", "teacher"], odd: "teacher" },
      { words: ["movie", "series", "cartoon", "ruler"], odd: "ruler" },
      { words: ["singing", "acting", "practicing", "sandwich"], odd: "sandwich" },
      { words: ["jogging", "yoga", "skating", "library"], odd: "library" },
      { words: ["blogging", "vlogging", "posting", "pencil"], odd: "pencil" },
      { words: ["baking", "cooking", "decorating", "exam"], odd: "exam" },
      { words: ["fishing", "surfing", "diving", "eraser"], odd: "eraser" },
      { words: ["collecting", "trading", "building", "corridor"], odd: "corridor" },
      { words: ["chatting", "texting", "calling", "desk"], odd: "desk" },
      { words: ["camping", "trekking", "climbing", "principal"], odd: "principal" },
      { words: ["drums", "guitar", "keyboard", "locker"], odd: "locker" },
    ],
  },
  {
    key: "teens-friends",
    title: "Friends and Social Life",
    audience: "Teens",
    items: [
      { words: ["friend", "classmate", "teammate", "banana"], odd: "banana" },
      { words: ["message", "chat", "call", "notebook"], odd: "notebook" },
      { words: ["party", "hangout", "sleepover", "ruler"], odd: "ruler" },
      { words: ["funny", "kind", "friendly", "backpack"], odd: "backpack" },
      { words: ["trust", "support", "advice", "sandwich"], odd: "sandwich" },
      { words: ["invite", "reply", "cancel", "classroom"], odd: "classroom" },
      { words: ["secret", "joke", "story", "calculator"], odd: "calculator" },
      { words: ["group", "club", "team", "dolphin"], odd: "dolphin" },
      { words: ["text", "post", "comment", "whiteboard"], odd: "whiteboard" },
      { words: ["shy", "confident", "outgoing", "pizza"], odd: "pizza" },
      { words: ["weekend", "mall", "cinema", "eraser"], odd: "eraser" },
      { words: ["argument", "problem", "apology", "keyboard"], odd: "keyboard" },
      { words: ["best friend", "neighbor", "cousin", "basketball"], odd: "basketball" },
      { words: ["celebrate", "laugh", "share", "exam"], odd: "exam" },
      { words: ["playlist", "selfie", "status", "marker"], odd: "marker" },
    ],
  },
  {
    key: "adults-work",
    title: "Work and Careers",
    audience: "Adults",
    items: [
      { words: ["resume", "cover letter", "reference", "deadline"], odd: "deadline", explanation: "The first three are job application items." },
      { words: ["manager", "colleague", "assistant", "invoice"], odd: "invoice", explanation: "The first three are people at work." },
      { words: ["salary", "bonus", "wage", "interview"], odd: "interview", explanation: "The first three are types of pay." },
      { words: ["overtime", "commute", "shift", "contract"], odd: "contract", explanation: "The first three are parts of a work routine." },
      { words: ["presentation", "workshop", "seminar", "refund"], odd: "refund", explanation: "The first three are professional events." },
      { words: ["deadline", "target", "workload", "receptionist"], odd: "receptionist", explanation: "The first three are work pressure concepts." },
      { words: ["hire", "train", "promote", "keyboard"], odd: "keyboard", explanation: "The first three are HR actions." },
      { words: ["office", "branch", "headquarters", "passport"], odd: "passport", explanation: "The first three are workplace locations." },
      { words: ["client", "customer", "supplier", "pajamas"], odd: "pajamas", explanation: "The first three are business contacts." },
      { words: ["negotiate", "persuade", "propose", "kettle"], odd: "kettle", explanation: "The first three are professional communication actions." },
      { words: ["freelance", "remote", "full-time", "bookshelf"], odd: "bookshelf", explanation: "The first three are work arrangements." },
      { words: ["schedule", "agenda", "timetable", "necklace"], odd: "necklace", explanation: "The first three organize time." },
      { words: ["feedback", "appraisal", "evaluation", "suitcase"], odd: "suitcase", explanation: "The first three are performance-review terms." },
      { words: ["colleague", "teammate", "supervisor", "pancake"], odd: "pancake", explanation: "The first three are work relationships." },
      { words: ["promotion", "transfer", "resignation", "toothpaste"], odd: "toothpaste", explanation: "The first three are career changes." },
    ],
  },
  {
    key: "adults-travel",
    title: "Travel and Movement",
    audience: "Adults",
    items: [
      { words: ["boarding pass", "passport", "visa", "receipt"], odd: "receipt", explanation: "The first three are border or flight documents." },
      { words: ["departure", "arrival", "layover", "dentist"], odd: "dentist", explanation: "The first three are journey stages." },
      { words: ["resort", "hostel", "guesthouse", "escalator"], odd: "escalator", explanation: "The first three are accommodation types." },
      { words: ["sightseeing", "backpacking", "cruising", "detergent"], odd: "detergent", explanation: "The first three are travel styles or activities." },
      { words: ["platform", "terminal", "gate", "balcony"], odd: "balcony", explanation: "The first three are transport-access points." },
      { words: ["route", "destination", "journey", "frying pan"], odd: "frying pan", explanation: "The first three describe a trip." },
      { words: ["guidebook", "map", "itinerary", "cushion"], odd: "cushion", explanation: "The first three are trip-planning tools." },
      { words: ["customs", "security", "immigration", "necklace"], odd: "necklace", explanation: "The first three are airport or border processes." },
      { words: ["taxi", "shuttle", "subway", "blanket"], odd: "blanket", explanation: "The first three are transport options." },
      { words: ["delay", "cancellation", "connection", "landlord"], odd: "landlord", explanation: "The first three are travel disruptions." },
      { words: ["luggage", "baggage", "suitcase", "keyboard"], odd: "keyboard", explanation: "The first three are travel-carry items." },
      { words: ["tourist", "backpacker", "traveler", "accountant"], odd: "accountant", explanation: "The first three are traveler roles." },
      { words: ["reserve", "check in", "board", "microwave"], odd: "microwave", explanation: "The first three are travel actions." },
      { words: ["landmark", "monument", "museum", "salary"], odd: "salary", explanation: "The first three are sightseeing places." },
      { words: ["exchange rate", "local currency", "cash withdrawal", "conference room"], odd: "conference room", explanation: "The first three are travel-money concepts." },
    ],
  },
  {
    key: "adults-daily-life",
    title: "Daily Life and Relationships",
    audience: "Adults",
    items: [
      { words: ["trust", "honesty", "respect", "receipt"], odd: "receipt", explanation: "The first three are relationship values." },
      { words: ["roommate", "landlord", "neighbor", "password"], odd: "password", explanation: "The first three are people in living situations." },
      { words: ["anniversary", "engagement", "wedding", "keyboard"], odd: "keyboard", explanation: "The first three are relationship milestones." },
      { words: ["argument", "misunderstanding", "compromise", "backpack"], odd: "backpack", explanation: "The first three are relationship-conflict terms." },
      { words: ["partner", "spouse", "ex", "kettle"], odd: "kettle", explanation: "The first three are relationship-role words." },
      { words: ["chores", "groceries", "laundry", "interview"], odd: "interview", explanation: "The first three are domestic routine tasks." },
      { words: ["text", "voicemail", "reply", "cucumber"], odd: "cucumber", explanation: "The first three are communication items." },
      { words: ["lonely", "jealous", "grateful", "shampoo"], odd: "shampoo", explanation: "The first three are emotions in personal life." },
      { words: ["apology", "promise", "compliment", "platform"], odd: "platform", explanation: "The first three are interpersonal acts." },
      { words: ["cousin", "sibling", "aunt", "deadline"], odd: "deadline", explanation: "The first three are family members." },
      { words: ["rent", "utility bill", "groceries", "workshop"], odd: "workshop", explanation: "The first three are household expenses." },
      { words: ["date", "breakup", "chemistry", "suitcase"], odd: "suitcase", explanation: "The first three are dating-related terms." },
      { words: ["habit", "routine", "balance", "receptionist"], odd: "receptionist", explanation: "The first three relate to personal lifestyle patterns." },
      { words: ["support", "advice", "encouragement", "runway"], odd: "runway", explanation: "The first three are forms of help." },
      { words: ["celebrate", "forgive", "reconnect", "blender"], odd: "blender", explanation: "The first three are relationship-repair or bonding actions." },
    ],
  },
  {
    key: "adults-money-shopping",
    title: "Money and Shopping",
    audience: "Adults",
    items: [
      { words: ["budget", "savings", "debt", "escalator"], odd: "escalator", explanation: "The first three are personal finance terms." },
      { words: ["discount", "refund", "receipt", "cousin"], odd: "cousin", explanation: "The first three are shopping transaction words." },
      { words: ["salary", "wage", "income", "bookmark"], odd: "bookmark", explanation: "The first three are earnings terms." },
      { words: ["expensive", "affordable", "overpriced", "microwave"], odd: "microwave", explanation: "The first three are price-description words." },
      { words: ["checkout", "basket", "cart", "seminar"], odd: "seminar", explanation: "The first three are shopping process items." },
      { words: ["cash", "credit card", "transfer", "pillow"], odd: "pillow", explanation: "The first three are payment methods." },
      { words: ["bargain", "deal", "sale", "passport"], odd: "passport", explanation: "The first three are money-saving words." },
      { words: ["invest", "save", "borrow", "toothbrush"], odd: "toothbrush", explanation: "The first three are money actions." },
      { words: ["wallet", "purse", "bank card", "laundry"], odd: "laundry", explanation: "The first three are money-carry items." },
      { words: ["bill", "fee", "charge", "balcony"], odd: "balcony", explanation: "The first three are cost-related nouns." },
      { words: ["customer", "cashier", "shop assistant", "suitcase"], odd: "suitcase", explanation: "The first three are people in a shopping context." },
      { words: ["brand", "quality", "size", "dentist"], odd: "dentist", explanation: "The first three are product-choice factors." },
      { words: ["monthly payment", "loan", "interest", "frying pan"], odd: "frying pan", explanation: "The first three are borrowing terms." },
      { words: ["return", "exchange", "replace", "wedding"], odd: "wedding", explanation: "The first three are post-purchase actions." },
      { words: ["afford", "cost", "spend", "referee"], odd: "referee", explanation: "The first three relate to using money." },
    ],
  },
  {
    key: "adults-lifestyle-wellness",
    title: "Lifestyle and Wellness",
    audience: "Adults",
    items: [
      { words: ["sleep", "exercise", "hydration", "printer"], odd: "printer", explanation: "The first three are health habits." },
      { words: ["stress", "burnout", "anxiety", "suitcase"], odd: "suitcase", explanation: "The first three are mental-health pressure terms." },
      { words: ["routine", "balance", "discipline", "cucumber"], odd: "cucumber", explanation: "The first three are lifestyle-management ideas." },
      { words: ["stretch", "jog", "cycle", "necklace"], odd: "necklace", explanation: "The first three are physical activities." },
      { words: ["bedtime", "alarm", "nap", "contract"], odd: "contract", explanation: "The first three are sleep-related words." },
      { words: ["meditation", "breathing", "mindfulness", "escalator"], odd: "escalator", explanation: "The first three are calming practices." },
      { words: ["healthy", "processed", "nutritious", "receptionist"], odd: "receptionist", explanation: "The first three describe food or diet quality." },
      { words: ["headache", "fatigue", "tension", "refund"], odd: "refund", explanation: "The first three are physical or stress symptoms." },
      { words: ["routine", "schedule", "habit", "boarding pass"], odd: "boarding pass", explanation: "The first three structure daily life." },
      { words: ["gym", "trainer", "workout", "cousin"], odd: "cousin", explanation: "The first three are exercise-context words." },
      { words: ["screen time", "posture", "focus", "shampoo"], odd: "shampoo", explanation: "The first three are modern lifestyle concerns." },
      { words: ["meal prep", "portion", "calorie", "suitcase"], odd: "suitcase", explanation: "The first three are diet-management terms." },
      { words: ["motivation", "progress", "consistency", "landmark"], odd: "landmark", explanation: "The first three are self-improvement concepts." },
      { words: ["rest", "recovery", "energy", "passport"], odd: "passport", explanation: "The first three are wellness-state words." },
      { words: ["therapy", "support group", "counseling", "frying pan"], odd: "frying pan", explanation: "The first three are help or treatment options." },
    ],
  },
];

export default ODD_ONE_OUT_PACKS;
