// Writing category, Proofreading activity: 10 items per CEFR level group
// (A1-A2 / B1-B2 / C1-C2), 30 total. Shape per item:
// { key, title, cefrGroup, focus, warmup, mistakes, corrected, followup }
// Text genre gets more complex/abstract as level rises, not just harder
// vocabulary under the same genre: A1-A2 stays personal/everyday, B1-B2
// shifts to social/workplace writing, C1-C2 shifts to professional/
// academic writing.

const A1A2 = [
  {
    key: "myWeekend",
    title: "My Weekend",
    focus: "Simple past tense",
    warmup: "What did you do last weekend? Tell your teacher one thing you did.",
    mistakes: "Last weekend I go to the beach with my family. We swim in the sea and eating lunch on the sand. It were very fun. In the evening we watch a movie and I sleeped early.",
    corrected: "Last weekend I went to the beach with my family. We swam in the sea and ate lunch on the sand. It was very fun. In the evening we watched a movie and I slept early.",
    followup: "Now tell your teacher about your own last weekend using the past tense correctly.",
  },
  {
    key: "myFamily",
    title: "My Family",
    focus: "Possessives, present simple",
    warmup: "How many people are in your family? Name them.",
    mistakes: "This is my family. My father name is Carlos and he work in a office. My mother are a teacher and she like reading books. I have two brother, they names are Leo and Max.",
    corrected: "This is my family. My father's name is Carlos and he works in an office. My mother is a teacher and she likes reading books. I have two brothers, their names are Leo and Max.",
    followup: "Describe your own family to your teacher: their names and jobs.",
  },
  {
    key: "myRoom",
    title: "My Room",
    focus: "There is / there are, prepositions",
    warmup: "What is in your bedroom? Name three things.",
    mistakes: "In my room there is a bed and a desk. There are a lamp on the desk. My books is on the shelf next the window. The chair are behind of the desk.",
    corrected: "In my room there is a bed and a desk. There is a lamp on the desk. My books are on the shelf next to the window. The chair is behind the desk.",
    followup: "Describe your own room to your teacher using 'there is / there are'.",
  },
  {
    key: "tripToThePark",
    title: "A Trip to the Park",
    focus: "Simple past, sequencing words",
    warmup: "Do you like going to the park? What do you do there?",
    mistakes: "Yesterday me and my friends goes to the park. First we playing football, then we eat ice cream. After that we sit on the grass and talked. It was a great day and we has fun.",
    corrected: "Yesterday my friends and I went to the park. First we played football, then we ate ice cream. After that we sat on the grass and talked. It was a great day and we had fun.",
    followup: "Tell your teacher about a park you visited and what you did there.",
  },
  {
    key: "myBestFriend",
    title: "My Best Friend",
    focus: "Adjectives, present simple",
    warmup: "Who is your best friend? What are they like?",
    mistakes: "My best friend name is Ana. She is very kindly and funny. She like to draw and she draws very good. We are friend since five years and we always laugh together.",
    corrected: "My best friend's name is Ana. She is very kind and funny. She likes to draw and she draws very well. We have been friends for five years and we always laugh together.",
    followup: "Describe your own best friend to your teacher.",
  },
  {
    key: "shoppingList",
    title: "Shopping List",
    focus: "Countable/uncountable nouns, quantifiers",
    warmup: "What do you usually buy at the supermarket?",
    mistakes: "I need buy some breads, two milk and a apple. I also need a little eggs and some rices. Don't forget buy sugar too, we don't have any sugars at home.",
    corrected: "I need to buy some bread, two milks and an apple. I also need a few eggs and some rice. Don't forget to buy sugar too, we don't have any sugar at home.",
    followup: "Tell your teacher what is on your own shopping list this week.",
  },
  {
    key: "myMorningRoutine",
    title: "My Morning Routine",
    focus: "Present simple, time expressions",
    warmup: "What time do you wake up? What do you do first?",
    mistakes: "Every morning I waking up at 6am. I brushing my teeth and taking a shower. After that, I eats breakfast quick and I go to school by 7:30. Sometimes I forgets my bag.",
    corrected: "Every morning I wake up at 6am. I brush my teeth and take a shower. After that, I eat breakfast quickly and I go to school at 7:30. Sometimes I forget my bag.",
    followup: "Describe your own morning routine to your teacher, step by step.",
  },
  {
    key: "myPet",
    title: "My Pet",
    focus: "Present simple, adjectives",
    warmup: "Do you have a pet? What does it look like?",
    mistakes: "I have a dog, his name Rocky. He are very playful and he love to run in the garden. Rocky have brown fur and big ears. Every day I feeds him two time.",
    corrected: "I have a dog, his name is Rocky. He is very playful and he loves to run in the garden. Rocky has brown fur and big ears. Every day I feed him two times.",
    followup: "Tell your teacher about a pet you have, or a pet you would like to have.",
  },
  {
    key: "textToAFriend",
    title: "A Text to a Friend",
    focus: "Present continuous, question forms",
    warmup: "What are you doing right now? Tell your teacher.",
    mistakes: "Hi! What you doing today? I am watch a movie at home. You want come over later? We can play games and I am cooking some snacks too. Let me knowing!",
    corrected: "Hi! What are you doing today? I am watching a movie at home. Do you want to come over later? We can play games and I am cooking some snacks too. Let me know!",
    followup: "Write and say a text to your teacher inviting them to do something.",
  },
  {
    key: "myFavoriteFood",
    title: "My Favorite Food",
    focus: "Present simple, adjectives of taste",
    warmup: "What is your favorite food? Why do you like it?",
    mistakes: "My favorite food are pizza. I loves it because is very delicious and cheesy. My mom cook pizza every Friday. It have tomato, cheese and sometimes mushroom on top.",
    corrected: "My favorite food is pizza. I love it because it is very delicious and cheesy. My mom cooks pizza every Friday. It has tomato, cheese and sometimes mushrooms on top.",
    followup: "Describe your own favorite food to your teacher.",
  },
];

const B1B2 = [
  {
    key: "jobApplicationEmail",
    title: "Job Application Email",
    focus: "Formal register, verb tense consistency",
    warmup: "Have you ever written an email to apply for a job or an internship?",
    mistakes: "Dear Sir/Madam, I am writing for apply the marketing assistant position. I have three years experience in a similar role and I am very organize person. I hope you consider my application and I look forward to hear from you.",
    corrected: "Dear Sir/Madam, I am writing to apply for the marketing assistant position. I have three years of experience in a similar role and I am a very organized person. I hope you will consider my application and I look forward to hearing from you.",
    followup: "What would you include in your own job application email?",
  },
  {
    key: "restaurantReview",
    title: "A Restaurant Review",
    focus: "Past tense, descriptive adjectives",
    warmup: "Have you written a review online before? What did you write about?",
    mistakes: "I visit this restaurant last week and the food were amazing. The service was a bit slowly but the staff was friendly. I especially enjoy the pasta, it tasted so good. I will definitely coming back again.",
    corrected: "I visited this restaurant last week and the food was amazing. The service was a bit slow but the staff was friendly. I especially enjoyed the pasta, it tasted so good. I will definitely come back again.",
    followup: "Tell your teacher about a restaurant you would review, good or bad.",
  },
  {
    key: "planningATrip",
    title: "Planning a Trip",
    focus: "Future forms, conditional sentences",
    warmup: "How do you usually plan a trip? What do you check first?",
    mistakes: "If we will go to Japan, we need book the flights early. I am thinking we visit Tokyo first and then we will traveling to Kyoto. If the weather is good, we will can visit the mountains too.",
    corrected: "If we go to Japan, we need to book the flights early. I am thinking we will visit Tokyo first and then we will travel to Kyoto. If the weather is good, we will be able to visit the mountains too.",
    followup: "Describe a trip you are planning, or would like to plan, to your teacher.",
  },
  {
    key: "complaintLetter",
    title: "A Complaint Letter",
    focus: "Formal tone, passive voice",
    warmup: "Have you ever complained about a product or service? What happened?",
    mistakes: "I am writing to complain about the product I buyed last week. The item were damaged when it arrive and nobody has contacted me since. I am expecting a full refund or the item was replace as soon as possible.",
    corrected: "I am writing to complain about the product I bought last week. The item was damaged when it arrived and nobody has contacted me since. I am expecting a full refund or for the item to be replaced as soon as possible.",
    followup: "Tell your teacher about a time you had to complain about something.",
  },
  {
    key: "socialMediaPost",
    title: "Social Media Post",
    focus: "Informal register, present perfect",
    warmup: "What do you usually post about on social media?",
    mistakes: "Just finish my first marathon!! I have train for six months and it was totally worth it. I never felt so proud of myself before. Thank you to everyone who support me, you guys is the best!",
    corrected: "Just finished my first marathon!! I have trained for six months and it was totally worth it. I have never felt so proud of myself before. Thank you to everyone who supported me, you guys are the best!",
    followup: "What would you post about a personal achievement of your own?",
  },
  {
    key: "givingDirections",
    title: "Giving Directions",
    focus: "Imperatives, prepositions of place",
    warmup: "How do you usually give directions to someone? What phrases do you use?",
    mistakes: "To get to the museum, you go straight until the traffic light, then you are turning left. The museum is between of the bank and a coffee shop, you can't miss. It take about ten minute by walk.",
    corrected: "To get to the museum, go straight until the traffic light, then turn left. The museum is between the bank and a coffee shop, you can't miss it. It takes about ten minutes on foot.",
    followup: "Give your teacher directions from your home to somewhere you go often.",
  },
  {
    key: "productReview",
    title: "A Product Review",
    focus: "Comparatives, present perfect",
    warmup: "Have you left a review for something you bought online?",
    mistakes: "I have use this blender for two months now and it work great. It is more quiet than my old one and it more powerful too. The only problem is the lid don't fit very well, but overall I am satisfying.",
    corrected: "I have used this blender for two months now and it works great. It is quieter than my old one and it is more powerful too. The only problem is the lid doesn't fit very well, but overall I am satisfied.",
    followup: "Describe a product you have used recently to your teacher.",
  },
  {
    key: "requestingTimeOff",
    title: "Requesting Time Off",
    focus: "Formal requests, modal verbs",
    warmup: "How would you politely ask your manager for time off work?",
    mistakes: "Dear Manager, I am writing to requesting three days off next month for a family event. I hope this will not causing any problems for the team. Please let me knowing if this dates works for you.",
    corrected: "Dear Manager, I am writing to request three days off next month for a family event. I hope this will not cause any problems for the team. Please let me know if these dates work for you.",
    followup: "Practice politely asking your teacher for a favor, as if they were your manager.",
  },
  {
    key: "problemAtWork",
    title: "Describing a Problem at Work",
    focus: "Past tense, linking words",
    warmup: "Have you ever had a problem at work or school that you had to explain to someone?",
    mistakes: "Last week the printer stop working suddenly and we couldn't finish the report on time. I tried fixing it myself but it didn't worked, so I called for the IT support. Because of this, we submit the report one day late.",
    corrected: "Last week the printer suddenly stopped working and we couldn't finish the report on time. I tried to fix it myself but it didn't work, so I called IT support. Because of this, we submitted the report one day late.",
    followup: "Tell your teacher about a problem you had to solve recently.",
  },
  {
    key: "opinionBlogPost",
    title: "An Opinion Blog Post",
    focus: "Opinion language, present simple",
    warmup: "What is a topic you have a strong opinion about?",
    mistakes: "In my opinion, remote work are better than office work for most people. It give employees more flexibility and it save time because you don't need commuting. However, some peoples think it make teamwork more harder.",
    corrected: "In my opinion, remote work is better than office work for most people. It gives employees more flexibility and it saves time because you don't need to commute. However, some people think it makes teamwork harder.",
    followup: "Share your own opinion on remote work, or another topic, with your teacher.",
  },
];

const C1C2 = [
  {
    key: "businessProposal",
    title: "A Formal Business Proposal",
    focus: "Formal register, nominalization",
    warmup: "Have you ever had to pitch an idea formally, in writing or in a meeting?",
    mistakes: "This proposal outline a new strategy for expand our market share in Southeast Asia. We believe that by investing on local partnerships, the company can significantly increasing its revenue while it reduce operational risk over the coming three years.",
    corrected: "This proposal outlines a new strategy for expanding our market share in Southeast Asia. We believe that by investing in local partnerships, the company can significantly increase its revenue while reducing operational risk over the coming three years.",
    followup: "How would you pitch a new idea to your team or manager?",
  },
  {
    key: "academicEssayExcerpt",
    title: "An Academic Essay Excerpt",
    focus: "Hedging language, complex sentence structure",
    warmup: "What makes academic writing sound different from everyday writing?",
    mistakes: "It can be argue that social media have fundamentally change the way people is consuming news. While this shift bring undeniable benefits in term of accessibility, it also raise serious concern about the reliability of information which is shared.",
    corrected: "It can be argued that social media has fundamentally changed the way people consume news. While this shift brings undeniable benefits in terms of accessibility, it also raises serious concerns about the reliability of the information being shared.",
    followup: "What is your own view on how social media has changed news consumption?",
  },
  {
    key: "newsEditorial",
    title: "A News Editorial",
    focus: "Persuasive tone, subject-verb agreement",
    warmup: "What makes a newspaper editorial persuasive rather than just informative?",
    mistakes: "The city's decision to cutting public transport funding are deeply concerning. Not only does it disproportionately affect low-income residents, it also undermine years of progress toward reduce traffic congestion and carbon emission across the region.",
    corrected: "The city's decision to cut public transport funding is deeply concerning. Not only does it disproportionately affect low-income residents, it also undermines years of progress toward reducing traffic congestion and carbon emissions across the region.",
    followup: "What is a local policy decision you feel strongly about?",
  },
  {
    key: "coverLetter",
    title: "A Cover Letter",
    focus: "Formal register, parallel structure",
    warmup: "What makes a cover letter stand out to a hiring manager?",
    mistakes: "Throughout my career, I have consistently demonstrate strong leadership, I am managing cross-functional teams and delivered projects under tight deadline. I am confident that my experience align closely with the requirement of this senior role.",
    corrected: "Throughout my career, I have consistently demonstrated strong leadership, managing cross-functional teams and delivering projects under tight deadlines. I am confident that my experience aligns closely with the requirements of this senior role.",
    followup: "What strengths would you highlight in your own cover letter?",
  },
  {
    key: "researchSummary",
    title: "A Research Summary",
    focus: "Passive voice, precise academic vocabulary",
    warmup: "What is the purpose of an abstract or summary in a research paper?",
    mistakes: "This study examine the effect of sleep deprivation on decision-making. Data was collect from 200 participant over a six-week period, and the result suggests that even moderate sleep loss can significantly impairing judgment and reaction time.",
    corrected: "This study examines the effect of sleep deprivation on decision-making. Data was collected from 200 participants over a six-week period, and the results suggest that even moderate sleep loss can significantly impair judgment and reaction time.",
    followup: "What research topic would you be interested in summarizing yourself?",
  },
  {
    key: "policyRecommendation",
    title: "A Policy Recommendation",
    focus: "Formal register, modal verbs of recommendation",
    warmup: "How would you formally recommend a change to a policy at your workplace or school?",
    mistakes: "It is recommend that the company adopting a four-day work week on a trial basis. This measure could improving employee wellbeing without necessarily reducing overall productivity, provide that clear performance metric are established beforehand.",
    corrected: "It is recommended that the company adopt a four-day work week on a trial basis. This measure could improve employee wellbeing without necessarily reducing overall productivity, provided that clear performance metrics are established beforehand.",
    followup: "What policy change would you recommend at your own workplace or school?",
  },
  {
    key: "persuasiveArgument",
    title: "A Persuasive Argument",
    focus: "Concession and counter-argument structures",
    warmup: "How do you usually structure an argument to make it more convincing?",
    mistakes: "Although some critics argues that artificial intelligence threaten jobs, this view overlook the numerous new roles the technology is creating. In fact, history has shown repeatedly that technological disruption tend to generate more opportunity than it eliminate.",
    corrected: "Although some critics argue that artificial intelligence threatens jobs, this view overlooks the numerous new roles the technology is creating. In fact, history has shown repeatedly that technological disruption tends to generate more opportunities than it eliminates.",
    followup: "What is a counter-argument you would raise against a common opinion?",
  },
  {
    key: "professionalReport",
    title: "A Professional Report",
    focus: "Formal register, complex noun phrases",
    warmup: "What sections would you expect to find in a professional report?",
    mistakes: "The quarterly report indicate that customer satisfaction have improved significantly, largely due to the implementation of a new support system which was design to reduce response time and it also increased first-contact resolution rate.",
    corrected: "The quarterly report indicates that customer satisfaction has improved significantly, largely due to the implementation of a new support system which was designed to reduce response times and increase first-contact resolution rates.",
    followup: "What would you highlight in a report about your own recent work?",
  },
  {
    key: "conferenceAbstract",
    title: "A Conference Abstract",
    focus: "Academic register, dense noun phrases",
    warmup: "What makes a conference abstract effective at capturing attention quickly?",
    mistakes: "This paper investigate the long-term impact of remote learning on student engagement across secondary school. Drawing on survey data collected between 2022 and 2024, we identifies several factor that correlates with sustain engagement over time.",
    corrected: "This paper investigates the long-term impact of remote learning on student engagement across secondary schools. Drawing on survey data collected between 2022 and 2024, we identify several factors that correlate with sustained engagement over time.",
    followup: "What topic would you propose for your own conference presentation?",
  },
  {
    key: "literaryAnalysis",
    title: "A Literary Analysis",
    focus: "Analytical register, present tense for literary discussion",
    warmup: "How is writing about literature different from writing about facts or events?",
    mistakes: "Throughout the novel, the author use isolation as a recurring motif that reflect the protagonist's inner turmoil. This technique were particularly effective in the final chapters, where the narrative pace slow down considerably to mirror her growing sense of despair.",
    corrected: "Throughout the novel, the author uses isolation as a recurring motif that reflects the protagonist's inner turmoil. This technique is particularly effective in the final chapters, where the narrative pace slows down considerably to mirror her growing sense of despair.",
    followup: "What is a book or story whose themes you would like to analyze?",
  },
];

const PROOFREADING_SETS = [
  ...A1A2.map((t) => ({ ...t, cefrGroup: "A1-A2" })),
  ...B1B2.map((t) => ({ ...t, cefrGroup: "B1-B2" })),
  ...C1C2.map((t) => ({ ...t, cefrGroup: "C1-C2" })),
];

export default PROOFREADING_SETS;
