// Writing category, Register Rewrite activity: 10 items per CEFR level
// group (A1-A2 / B1-B2 / C1-C2), 30 total. Shape per item:
// { key, title, cefrGroup, focus, direction, context, original,
// helpfulPhrases: [3-4], prompt, sample }
// "direction" is "toFormal" or "toCasual" -- alternated across items so
// students practice register-shifting both ways, not just formalizing.

const A1A2 = [
  {
    key: "textToATeacher",
    title: "Text to a Teacher",
    focus: "Formal greetings, polite requests",
    direction: "toFormal",
    context: "You're texting your teacher, not a friend.",
    original: "hey i forgot my homework at home lol can i bring it tmrw",
    helpfulPhrases: ["Dear Mr./Ms. ___", "I apologize for", "Would it be possible to"],
    prompt: "Rewrite this message formally for your teacher.",
    sample: "Dear Ms. Reyes, I apologize, but I forgot my homework at home today. Would it be possible to bring it tomorrow instead? Thank you for understanding.",
  },
  {
    key: "partyInvite",
    title: "Party Invite",
    focus: "Casual greetings, contractions",
    direction: "toCasual",
    context: "You're inviting your best friend, not a stranger.",
    original: "You are cordially invited to attend a gathering at my residence this Saturday at 3:00 PM. Your presence would be appreciated.",
    helpfulPhrases: ["Hey!", "come over", "It'll be fun"],
    prompt: "Rewrite this invitation casually for your friend.",
    sample: "Hey! Come over to my place this Saturday at 3! It'll be so fun, hope you can make it!",
  },
  {
    key: "messageToMom",
    title: "Message to Mom",
    focus: "Casual family tone, contractions",
    direction: "toCasual",
    context: "You're texting your mom, not writing a formal note.",
    original: "I would like to inform you that I will be returning home later than usual this evening due to a school activity.",
    helpfulPhrases: ["Hey Mom", "gonna be late", "no worries"],
    prompt: "Rewrite this message casually for your mom.",
    sample: "Hey Mom, I'm gonna be late tonight, we have a school activity. No worries though, I'll text you when I'm on my way!",
  },
  {
    key: "noteToAClassmate",
    title: "Note to a Classmate",
    focus: "Casual, friendly tone",
    direction: "toCasual",
    context: "You're passing a note to a classmate, not writing to a teacher.",
    original: "Excuse me, would you be so kind as to lend me a pencil? I appear to have forgotten mine today.",
    helpfulPhrases: ["hey", "can i borrow", "forgot mine"],
    prompt: "Rewrite this note casually for your classmate.",
    sample: "hey, can i borrow a pencil? i forgot mine at home lol",
  },
  {
    key: "thankYouNote",
    title: "Thank You Note",
    focus: "Formal gratitude, polite phrasing",
    direction: "toFormal",
    context: "This note is going to your grandparents, not a friend.",
    original: "thx so much for the gift!! it was awesome, love u",
    helpfulPhrases: ["Thank you very much for", "I really appreciate", "With love"],
    prompt: "Rewrite this note formally for your grandparents.",
    sample: "Thank you very much for the wonderful gift! I really appreciate your kindness and thoughtfulness. With love, always thinking of you.",
  },
  {
    key: "askingToBorrowAPencil",
    title: "Asking to Borrow a Pencil",
    focus: "Formal classroom requests",
    direction: "toFormal",
    context: "You're asking your teacher, not a classmate.",
    original: "hey can i get a pencil, i dont have one",
    helpfulPhrases: ["Excuse me", "Would it be possible to", "Thank you"],
    prompt: "Rewrite this request formally for your teacher.",
    sample: "Excuse me, would it be possible to borrow a pencil? I don't have one with me today. Thank you.",
  },
  {
    key: "invitingAFriendOver",
    title: "Inviting a Friend Over",
    focus: "Casual invitations, contractions",
    direction: "toCasual",
    context: "You're inviting a close friend, not writing a formal card.",
    original: "I would like to formally invite you to visit my home this afternoon, should your schedule permit.",
    helpfulPhrases: ["wanna come over", "this afternoon", "let me know"],
    prompt: "Rewrite this invitation casually for your friend.",
    sample: "wanna come over this afternoon? let me know if you're free!",
  },
  {
    key: "tellingATeacherYoureSick",
    title: "Telling a Teacher You're Sick",
    focus: "Formal absence explanation",
    direction: "toFormal",
    context: "This message is going to your teacher, not a friend.",
    original: "im sick today so i cant come to class sry",
    helpfulPhrases: ["Dear Mr./Ms. ___", "I am unable to attend", "I apologize for"],
    prompt: "Rewrite this message formally for your teacher.",
    sample: "Dear Ms. Reyes, I am unable to attend class today as I am feeling unwell. I apologize for any inconvenience this may cause.",
  },
  {
    key: "askingAboutHomework",
    title: "Asking About Homework",
    focus: "Casual questions, contractions",
    direction: "toCasual",
    context: "You're asking a classmate, not your teacher.",
    original: "Could you please inform me of the homework assignment, as I was absent from class today?",
    helpfulPhrases: ["hey", "what's the hw", "wasn't in class"],
    prompt: "Rewrite this message casually for your classmate.",
    sample: "hey, what's the hw today? i wasn't in class, sorry to bug you",
  },
  {
    key: "sayingSorryToAFriend",
    title: "Saying Sorry to a Friend",
    focus: "Casual, sincere apology",
    direction: "toCasual",
    context: "You're texting a close friend, not writing a formal apology letter.",
    original: "I sincerely apologize for my behavior yesterday and hope that you can find it in your heart to forgive me.",
    helpfulPhrases: ["hey, sorry about", "my bad", "hope we're good"],
    prompt: "Rewrite this message casually for your friend.",
    sample: "hey, sorry about yesterday, that was my bad. hope we're good?",
  },
];

const B1B2 = [
  {
    key: "schoolAbsenceNote",
    title: "School Absence Note",
    focus: "Formal tone, no slang or abbreviations",
    direction: "toFormal",
    context: "This note goes to the school office.",
    original: "hey so i wasnt at school yesterday bc i was sick, sorry about that, can u mark me present today tho",
    helpfulPhrases: ["I was absent on", "due to illness", "I would appreciate it if"],
    prompt: "Rewrite this note formally for the school office.",
    sample: "Dear School Office, I was absent yesterday due to illness. I apologize for the inconvenience and would appreciate it if my attendance today could be marked as present.",
  },
  {
    key: "chattingWithAFriend",
    title: "Chatting with a Friend",
    focus: "Casual contractions, relaxed tone",
    direction: "toCasual",
    context: "You're texting your close friend, not writing an essay.",
    original: "I am writing to inform you that I will be unable to attend our planned meeting this afternoon due to a prior commitment.",
    helpfulPhrases: ["hey", "can't make it", "sorry!"],
    prompt: "Rewrite this message casually for your friend.",
    sample: "hey sorry, i can't make it this afternoon, something came up! can we hang out another day?",
  },
  {
    key: "messageToYourBoss",
    title: "Message to Your Boss",
    focus: "Formal workplace tone, polite phrasing",
    direction: "toFormal",
    context: "You're messaging your manager, not a coworker friend.",
    original: "hey boss the printer is broken again lol someone needs to fix it asap",
    helpfulPhrases: ["I wanted to let you know", "at your earliest convenience", "Thank you for your attention"],
    prompt: "Rewrite this message formally for your boss.",
    sample: "Good morning, I wanted to let you know that the printer is broken again. Could someone please look into it at your earliest convenience? Thank you for your attention to this.",
  },
  {
    key: "textToAFriend",
    title: "Text to a Friend",
    focus: "Casual, relaxed everyday tone",
    direction: "toCasual",
    context: "You're texting a close friend, not a stranger.",
    original: "Good afternoon. I am writing to ask whether you would be available to meet for coffee sometime this week.",
    helpfulPhrases: ["hey", "wanna", "free this week?"],
    prompt: "Rewrite this message casually for your friend.",
    sample: "hey! wanna grab coffee sometime this week? let me know when you're free!",
  },
  {
    key: "askingACoworkerForHelp",
    title: "Asking a Coworker for Help",
    focus: "Polite workplace requests, semi-formal tone",
    direction: "toFormal",
    context: "You're messaging a coworker you don't know very well.",
    original: "yo can u help me with this report, im kinda stuck lol",
    helpfulPhrases: ["Would you be able to", "I'd really appreciate", "when you have a moment"],
    prompt: "Rewrite this message more formally for a coworker.",
    sample: "Hi, would you be able to help me with this report when you have a moment? I'd really appreciate your input, I'm a bit stuck on one section.",
  },
  {
    key: "decliningAnInvitation",
    title: "Declining an Invitation",
    focus: "Polite refusal, softening language",
    direction: "toFormal",
    context: "You're replying to an acquaintance's invitation, not a close friend.",
    original: "nah i cant come, im busy that day",
    helpfulPhrases: ["Thank you for the invitation", "Unfortunately, I won't be able to", "I hope"],
    prompt: "Rewrite this message more politely for an acquaintance.",
    sample: "Thank you so much for the invitation! Unfortunately, I won't be able to make it that day as I already have plans. I hope you all have a wonderful time.",
  },
  {
    key: "requestingARefund",
    title: "Requesting a Refund",
    focus: "Polite but assertive tone",
    direction: "toFormal",
    context: "You're emailing customer service, not complaining to a friend.",
    original: "this product is broken and i want my money back now",
    helpfulPhrases: ["I am writing to request", "Unfortunately, the item", "I would appreciate"],
    prompt: "Rewrite this message formally for customer service.",
    sample: "I am writing to request a refund for a recent purchase. Unfortunately, the item arrived broken and is unusable. I would appreciate a full refund at your earliest convenience.",
  },
  {
    key: "introducingYourselfOnline",
    title: "Introducing Yourself Online",
    focus: "Friendly but clear self-introduction",
    direction: "toCasual",
    context: "This is a casual community forum, not a job application.",
    original: "Greetings. My name is Daniel and I am pleased to be joining this online community. I look forward to engaging with fellow members.",
    helpfulPhrases: ["hey everyone", "excited to be here", "looking forward to"],
    prompt: "Rewrite this introduction casually for a community forum.",
    sample: "hey everyone! I'm Daniel, excited to be here. Looking forward to chatting with you all!",
  },
  {
    key: "askingALandlordForARepair",
    title: "Asking a Landlord for a Repair",
    focus: "Polite but clear requests",
    direction: "toFormal",
    context: "You're messaging your landlord, not a friend who's helping you move.",
    original: "hey the sink is leaking again can u send someone to fix it",
    helpfulPhrases: ["I wanted to let you know", "Could you please arrange", "at your earliest convenience"],
    prompt: "Rewrite this message formally for your landlord.",
    sample: "Hi, I wanted to let you know that the sink is leaking again. Could you please arrange for someone to fix it at your earliest convenience? Thank you.",
  },
  {
    key: "congratulatingAFriend",
    title: "Congratulating a Friend",
    focus: "Warm, casual congratulations",
    direction: "toCasual",
    context: "You're texting a close friend, not writing a formal card.",
    original: "Congratulations on your recent achievement. I wish to extend my sincere congratulations on this well-deserved success.",
    helpfulPhrases: ["omg congrats!!", "so proud of you", "you deserve it"],
    prompt: "Rewrite this message casually for your friend.",
    sample: "omg congrats!! I'm so proud of you, you totally deserve it!!",
  },
];

const C1C2 = [
  {
    key: "complaintEmail",
    title: "Complaint Email",
    focus: "Formal complaint structure, no informal venting",
    direction: "toFormal",
    context: "This becomes a formal complaint email to a company.",
    original: "this is honestly ridiculous, my order is a week late and nobody has told me anything, i want this fixed now",
    helpfulPhrases: ["I am writing to express", "I would appreciate an update", "I trust this will be resolved"],
    prompt: "Rewrite this as a formal complaint email.",
    sample: "I am writing to express my concern regarding my order, which is now a week overdue with no update provided. I would appreciate an explanation and a revised delivery date. I trust this matter will be resolved promptly.",
  },
  {
    key: "catchingUpWithAnOldFriend",
    title: "Catching Up with an Old Friend",
    focus: "Warm, casual, conversational tone",
    direction: "toCasual",
    context: "You're emailing an old friend, not a business contact.",
    original: "Dear Michael, I hope this message finds you well. I am writing to inquire about your current circumstances and to propose that we arrange a meeting at your earliest convenience.",
    helpfulPhrases: ["hey stranger", "how've you been", "let's catch up"],
    prompt: "Rewrite this message casually for an old friend.",
    sample: "Hey stranger! It's been way too long, how've you been? We should really catch up sometime soon, are you free this week?",
  },
  {
    key: "negotiatingADeadline",
    title: "Negotiating a Deadline",
    focus: "Assertive but diplomatic professional tone",
    direction: "toFormal",
    context: "You're emailing a client, not messaging a friend.",
    original: "there's no way we can hit that deadline, we need more time, sorry",
    helpfulPhrases: ["Upon review, we believe", "we would like to propose", "to ensure the highest quality"],
    prompt: "Rewrite this message formally for a client.",
    sample: "Upon review of the current timeline, we believe additional time will be required to ensure the highest quality outcome. We would like to propose an adjusted deadline and are happy to discuss options at your convenience.",
  },
  {
    key: "decliningAJobOffer",
    title: "Declining a Job Offer",
    focus: "Formal, gracious refusal",
    direction: "toFormal",
    context: "You're emailing a hiring manager, not chatting with a friend.",
    original: "thanks but no thanks, i got a better offer somewhere else",
    helpfulPhrases: ["Thank you very much for", "After careful consideration", "I have decided to"],
    prompt: "Rewrite this message formally for the hiring manager.",
    sample: "Thank you very much for offering me this position. After careful consideration, I have decided to accept another opportunity that better aligns with my current goals. I truly appreciate your time and consideration.",
  },
  {
    key: "addressingATeamConflict",
    title: "Addressing a Team Conflict",
    focus: "Diplomatic, de-escalating tone",
    direction: "toFormal",
    context: "You're emailing your team, not venting to a friend.",
    original: "everyone needs to stop arguing and just do their job, this is getting ridiculous",
    helpfulPhrases: ["I've noticed some tension", "I'd like us to", "moving forward"],
    prompt: "Rewrite this message formally for your team.",
    sample: "I've noticed some tension within the team recently, and I'd like us to address it directly rather than let it affect our work. Moving forward, let's set aside time to discuss any concerns openly.",
  },
  {
    key: "requestingAReference",
    title: "Requesting a Reference",
    focus: "Polite formal request",
    direction: "toFormal",
    context: "You're emailing a former manager, not a close friend.",
    original: "hey can you be my reference for this new job im applying to",
    helpfulPhrases: ["I hope this message finds you well", "I would be grateful if", "at your convenience"],
    prompt: "Rewrite this message formally for your former manager.",
    sample: "Dear Mr. Chen, I hope this message finds you well. I am applying for a new position and would be grateful if you would be willing to serve as a reference. Please let me know at your convenience if this would be possible.",
  },
  {
    key: "announcingAResignation",
    title: "Announcing a Resignation",
    focus: "Formal, professional, gracious tone",
    direction: "toFormal",
    context: "This is a formal resignation email to your manager.",
    original: "im quitting, my last day is in two weeks, thanks for everything i guess",
    helpfulPhrases: ["I am writing to formally notify you", "my last working day will be", "I am grateful for"],
    prompt: "Rewrite this message formally for your manager.",
    sample: "Dear [Manager], I am writing to formally notify you of my resignation. My last working day will be two weeks from today. I am grateful for the opportunities I've had here and will do everything I can to ensure a smooth transition.",
  },
  {
    key: "respondingToNegativeFeedback",
    title: "Responding to Negative Feedback",
    focus: "Professional, non-defensive tone",
    direction: "toFormal",
    context: "You're replying to a client's critical review, not arguing with a friend.",
    original: "that's not even true, we did everything right, you're being unfair",
    helpfulPhrases: ["Thank you for sharing your feedback", "we understand your concern", "we would welcome the chance to"],
    prompt: "Rewrite this message formally for the client.",
    sample: "Thank you for sharing your feedback. We understand your concern and take it seriously. We would welcome the chance to discuss this further and make things right wherever possible.",
  },
  {
    key: "proposingAPartnership",
    title: "Proposing a Partnership",
    focus: "Formal, persuasive business tone",
    direction: "toFormal",
    context: "This is a formal proposal email to another company.",
    original: "hey we think our companies should team up, could be good for both of us",
    helpfulPhrases: ["we believe there is a strong opportunity", "we would welcome the chance to discuss", "mutually beneficial"],
    prompt: "Rewrite this message formally for a potential business partner.",
    sample: "Dear team, we believe there is a strong opportunity for a mutually beneficial partnership between our companies. We would welcome the chance to discuss this further at a time convenient for you.",
  },
  {
    key: "reconnectingWithAMentor",
    title: "Reconnecting with a Mentor",
    focus: "Warm but respectful semi-formal tone",
    direction: "toCasual",
    context: "You're emailing a mentor you know well, not a stranger.",
    original: "Dear Professor Alvarado, I am writing to inquire whether you might have availability to reconnect, as it has been an extended period since our last correspondence.",
    helpfulPhrases: ["Hi Professor Alvarado", "it's been way too long", "would love to catch up"],
    prompt: "Rewrite this message a bit more warmly for a mentor you know well.",
    sample: "Hi Professor Alvarado, it's been way too long since we last talked! I'd love to catch up whenever you have some free time. Hope you've been doing well.",
  },
];

const REGISTER_REWRITE_SETS = [
  ...A1A2.map((t) => ({ ...t, cefrGroup: "A1-A2" })),
  ...B1B2.map((t) => ({ ...t, cefrGroup: "B1-B2" })),
  ...C1C2.map((t) => ({ ...t, cefrGroup: "C1-C2" })),
];

export default REGISTER_REWRITE_SETS;
