// SPARK Teens 2 — School
// 20-minute one-to-one online ESL trial lesson for teens (A1+ to B1).

export default {
  id: "spark-teens-2",
  code: "SPARK Teens 2",
  title: "School",
  length: "20 min",
  coreAim: "Help the learner speak about daily school life through simple mini-games while teaching useful school words they can reuse immediately.",
  targetVocab: [
    { word: "subject", meaning: "A class you study at school", model: "My favorite subject is English." },
    { word: "break", meaning: "Free time between classes", model: "At break, I talk to my friends." },
    { word: "classmate", meaning: "A student in your class", model: "My classmate sits next to me." },
  ],

  slides: [
    {
      title: "School Start",
      timing: "2 min",
      purpose: "Warm-up and easy personal entry",
      miniGameType: "Quick pick",
      sceneIcons: ["schoolbag", "book"],
      prompt: "What do you like more: English class, PE, or lunch break?",
      sentenceStems: ["I like ___ best because ___."],
      teacherScript: ["Today we'll talk about school.", "Choose one thing you like best.", "Now give me one reason."],
      likelyAnswers: ["I like PE best because it is active.", "I like lunch break because I can talk with friends."],
      followUps: ["Who do you usually sit with?", "Which class is difficult for you?", "What do you do there?"],
      correctionNotes: ["Accept simple answers first.", "Prompt for “because” if possible."],
      pacingNote: "Make it feel easy and familiar from the start.",
    },
    {
      title: "New Word: Subject",
      timing: "2 min",
      purpose: "Introduce first school word",
      miniGameType: "Say and personalize",
      sceneIcons: ["book"],
      wordCard: { word: "subject", meaning: "a class you study in school" },
      prompt: "What is your favorite subject?",
      sentenceStems: ["My favorite subject is ___."],
      teacherScript: ["New word: subject.", "A subject is a class, like math or English.", "Say: My favorite subject is ___."],
      likelyAnswers: ["My favorite subject is English.", "My favorite subject is science."],
      followUps: ["Why do you like it?", "Is it easy or difficult?", "Who is your teacher?"],
      correctionNotes: ["Model the full sentence if the learner says only one word."],
      pacingNote: "Keep the explanation very short and get the student talking.",
    },
    {
      title: "Mini-Game 1: Pick One",
      timing: "4 min",
      purpose: "Opinion speaking with familiar school choices",
      miniGameType: "Choice + reason",
      sceneIcons: ["pencil", "book"],
      choices: ["Homework or test?", "Sit in the front or the back?"],
      sentenceStems: ["I choose ___ because ___.", "___ is better for me because ___."],
      teacherScript: ["Choose one quickly.", "Now explain your answer.", "Good — add one more detail."],
      likelyAnswers: ["I choose homework because I can do it at home.", "I sit in the back because I feel comfortable."],
      followUps: ["What about your friends?", "What happens in your class?", "Is that common in your school?"],
      correctionNotes: ["Lower level: accept one reason.", "Higher level: push for comparison or example."],
      pacingNote: "Keep it playful; this is a quick-reaction round.",
    },
    {
      title: "New Word: Break",
      timing: "2 min",
      purpose: "Introduce second school word",
      miniGameType: "Word to routine",
      sceneIcons: ["clock", "apple"],
      wordCard: { word: "break", meaning: "free time between classes" },
      prompt: "What do you do at break?",
      sentenceStems: ["At break, I ___."],
      teacherScript: ["New word: break.", "Break is free time between lessons.", "Tell me: At break, I ___."],
      likelyAnswers: ["At break, I talk to my friends.", "At break, I eat a snack.", "At break, I use my phone."],
      followUps: ["Where do you go at break?", "Who do you talk to?", "How long is your break?"],
      correctionNotes: ["Focus on making one complete sentence."],
      pacingNote: "This should feel very practical and personal.",
    },
    {
      title: "Mini-Game 2: Fast Card Talk",
      timing: "4 min",
      purpose: "Build a short school conversation",
      miniGameType: "One card, three linked questions",
      sceneIcons: ["clock", "book"],
      cardTitle: "My School Day",
      questions: ["What time does school start?", "Which subject do you like?", "What do you do at break?"],
      sentenceStems: ["School starts at ___.", "I like ___ because ___.", "At break, I usually ___."],
      teacherScript: ["Let's talk about your school day.", "Answer in full sentences.", "After each answer, I'll ask one more question."],
      likelyAnswers: ["School starts at eight.", "I like history because it is interesting.", "At break, I usually talk with my friends."],
      followUps: ["What subject is hardest for you?", "Do you eat at school?", "What happens after school?"],
      correctionNotes: ["Keep the flow conversational.", "Recast, then move on."],
      pacingNote: "This is the heart of the lesson; leave time for answers.",
    },
    {
      title: "New Word: Classmate",
      timing: "2 min",
      purpose: "Introduce third school word",
      miniGameType: "Model and personalize",
      sceneIcons: ["boy", "girl"],
      wordCard: { word: "classmate", meaning: "a student in your class" },
      prompt: "Who do you sit next to?",
      sentenceStems: ["My classmate is ___.", "I sit next to my classmate."],
      teacherScript: ["New word: classmate.", "A classmate is a student in your class.", "Try this: I sit next to my classmate ___."],
      likelyAnswers: ["I sit next to my classmate Ali.", "My classmate is funny.", "My classmate helps me."],
      followUps: ["Is your classmate quiet or loud?", "Do you study together?", "Who is your best classmate?"],
      correctionNotes: ["If needed, replace names with “my friend” first, then upgrade to “classmate.”"],
      pacingNote: "Keep it simple and spoken.",
    },
    {
      title: "Mini-Game 3: True or False",
      timing: "3 min",
      purpose: "More open school opinions",
      miniGameType: "Personal statements",
      sceneIcons: ["book", "pencil"],
      instructions: "Say if it is true or false for you. Then explain.",
      statements: ["Homework is useful.", "Break time is the best part of school.", "A good classmate is very important."],
      sentenceStems: ["That's true for me because ___.", "That's false for me because ___."],
      teacherScript: ["True or false?", "Now tell me why.", "Can you add one more sentence?"],
      likelyAnswers: ["That's true for me because homework helps me study.", "That's false for me because lunch is better."],
      followUps: ["What do your friends think?", "Does your teacher agree?", "What is the best part of your school?"],
      correctionNotes: ["Let opinions lead; do not over-focus on errors."],
      pacingNote: "Use this to hear personality and confidence.",
    },
    {
      kind: "feedback",
      title: "Feedback",
      timing: "2 min",
      purpose: "Give live feedback — strength, target, and recommended next step.",
      teacherScript: ["Great job today!", "Here's what you did well, and here's your next step."],
    },
    {
      kind: "final",
      title: "Great job!",
      subtitle: "Thank you!",
      timing: "1 min",
      purpose: "Clean closing slide only.",
    },
  ],
};
