// SPARK Teens 1 — Football
// 20-minute one-to-one online ESL trial lesson for teens (A1+ to B1).

export default {
  id: "spark-teens-1",
  code: "SPARK Teens 1",
  title: "Football",
  length: "20 min",
  coreAim: "Get the learner speaking confidently about football through simple, fun mini-games while teaching useful football words in context.",
  targetVocab: [
    { word: "team", meaning: "A group that plays together", model: "My favorite team is ___." },
    { word: "teammate", meaning: "A person on your team", model: "My teammate is very fast." },
    { word: "cheer for", meaning: "Support a team by shouting or encouraging", model: "I cheer for ___." },
  ],

  slides: [
    {
      title: "Welcome Kickoff",
      timing: "2 min",
      purpose: "Warm-up and confidence start",
      miniGameType: "Quick pick",
      prompt: "Do you like playing football or watching football?",
      sentenceStems: ["I like ___ because ___."],
      teacherScript: ["Today we'll talk about football.", "Choose one: playing football or watching football?", "Say one reason."],
      likelyAnswers: ["I like playing football because it is fun.", "I like watching football because I like my team.", "I like both."],
      followUps: ["Where do you play?", "Who do you watch with?", "Is football popular in your country?"],
      correctionNotes: ["Accept very short answers first.", "Recast only once if sentence structure is broken."],
      pacingNote: "Keep this fast. The goal is confidence, not accuracy drilling.",
    },
    {
      title: "New Word: Team",
      timing: "2 min",
      purpose: "Introduce first useful word",
      miniGameType: "Say and personalize",
      wordCard: { word: "team", meaning: "the group you support or play in" },
      prompt: "What team do you like?",
      sentenceStems: ["My favorite team is ___."],
      teacherScript: ["New word: team.", "A team is a group of players.", "Say: My favorite team is ___.", "Now your answer."],
      likelyAnswers: ["My favorite team is Barcelona.", "My favorite team is Real Madrid.", "I don't have a favorite team."],
      followUps: ["Why do you like that team?", "Do your friends like the same team?", "Do you watch their matches?"],
      correctionNotes: ["Model “My favorite team is…” if needed.", "If the learner does not know a team, allow “I don't have a favorite team.”"],
      pacingNote: "Move quickly from word meaning to student use.",
    },
    {
      title: "Mini-Game 1: Pick One",
      timing: "4 min",
      purpose: "Easy opinion speaking",
      miniGameType: "Choice + reason",
      choices: ["Play football or watch football?", "Big stadium or street football?", "Win 1-0 or win 4-3?"],
      sentenceStems: ["I choose ___ because ___.", "I think ___ is better because ___."],
      teacherScript: ["Choose one quickly.", "Now give one reason.", "Good — one more detail."],
      likelyAnswers: ["I choose street football because it is more fun.", "I think win 4-3 is better because it is exciting."],
      followUps: ["Who do you play with?", "Why is it exciting?", "Which is more difficult?"],
      correctionNotes: ["Lower level: accept one reason.", "Higher level: ask for comparison language."],
      pacingNote: "Keep the rhythm fast. Treat it like a reaction game.",
    },
    {
      title: "New Word: Teammate",
      timing: "2 min",
      purpose: "Introduce second useful word",
      miniGameType: "Word to sentence",
      wordCard: { word: "teammate", meaning: "a person on your team" },
      prompt: "What makes a good teammate?",
      sentenceStems: ["My teammate is ___.", "A good teammate is ___."],
      teacherScript: ["New word: teammate.", "A teammate is a person on your team.", "Tell me: what makes a good teammate?"],
      likelyAnswers: ["A good teammate is friendly.", "A good teammate passes the ball.", "My teammate is fast."],
      followUps: ["Is a good teammate loud or calm?", "Is a famous player always a good teammate?", "Who is your best teammate?"],
      correctionNotes: ["Help with adjective patterns: friendly, fast, helpful, strong."],
      pacingNote: "Push from repetition into meaning quickly.",
    },
    {
      title: "Mini-Game 2: Fast Card Talk",
      timing: "4 min",
      purpose: "Structured conversation on a familiar theme",
      miniGameType: "One card, three linked questions",
      cardTitle: "My Football Life",
      questions: ["Do you play football?", "Where do you play?", "Who do you play with?"],
      sentenceStems: ["I play ___ times a week.", "I play with my friends / classmates / teammates."],
      teacherScript: ["Let's answer three football questions.", "Try to answer in full sentences.", "After each answer, I'll ask one more question."],
      likelyAnswers: ["I play football twice a week.", "I play in the park.", "I play with my friends and teammates."],
      followUps: ["What position do you play?", "Are you good at scoring?", "Do you play at school or outside school?"],
      correctionNotes: ["If the learner does not play football, switch naturally to watching football.", "Alternative stem: I don't play, but I like watching ___."],
      pacingNote: "Let this feel like a real conversation, not a checklist.",
    },
    {
      title: "New Phrase: Cheer for",
      timing: "2 min",
      purpose: "Introduce third useful phrase",
      miniGameType: "Model and personalize",
      wordCard: { word: "cheer for", meaning: "support a team by shouting or encouraging" },
      prompt: "Who do you cheer for?",
      sentenceStems: ["I cheer for ___."],
      teacherScript: ["New phrase: cheer for.", "If you like a team and support them, you cheer for them.", "Say: I cheer for ___."],
      likelyAnswers: ["I cheer for Liverpool.", "I cheer for my school team.", "I don't cheer for one team."],
      followUps: ["Do your friends cheer for the same team?", "Where do you watch matches?", "Do you cheer loudly or quietly?"],
      correctionNotes: ["Correct the phrase through modeling, not explanation."],
      pacingNote: "Keep it light and spoken.",
    },
    {
      title: "Mini-Game 3: True, False, Maybe",
      timing: "3 min",
      purpose: "Fun speaking + flexible follow-up",
      miniGameType: "Personal statements",
      instructions: "Say if it is true, false, or maybe for you. Then explain.",
      statements: ["Football is the best sport.", "I always cheer for one team.", "A good teammate is more important than a famous player."],
      sentenceStems: ["That's true for me because ___.", "Maybe, because ___.", "That's false for me because ___."],
      teacherScript: ["True, false, or maybe?", "Now tell me why.", "Good — can you say one more sentence?"],
      likelyAnswers: ["That's true for me because football is exciting.", "Maybe, because I like two teams.", "That's false for me because basketball is the best sport."],
      followUps: ["Why do you think that?", "What does your best friend think?", "Is this popular in your school?"],
      correctionNotes: ["This is the freest speaking part; do not over-correct."],
      pacingNote: "Keep energy high and let the student show personality.",
    },
    {
      title: "Review, Win, Feedback",
      timing: "1 min speaking + 2 min feedback",
      purpose: "Check retention and close strongly",
      miniGameType: "Quick recap challenge",
      isFinal: true,
      reviewWords: ["team", "teammate", "cheer for"],
      finalPrompt: "Tell me about football in 3 sentences.",
      teacherScript: ["Can you use all 3 words?", "Now give me 3 sentences about football.", "Excellent — here's what you did well, and here's the next step."],
      likelyAnswers: ["My favorite team is ___.", "A good teammate is friendly.", "I cheer for ___."],
      pacingNote: "End positively and clearly.",
    },
  ],
};
