// SPARK Adults 1 — Personality Types
// 20-minute one-to-one adult trial lesson. Signature gimmick: Spin the Wheel.

export default {
  id: "spark-adults-1",
  code: "SPARK Adults 1",
  title: "Personality Types",
  length: "20 minutes",
  gimmick: "Spin the Wheel",
  coreAim: "The wheel lands on short person descriptions; the student classifies each as introvert, extrovert, or ambivert, then speaks. The real value comes from the follow-up questions and personal examples the teacher runs from the guide.",
  followUpBank: ["Which type is it?", "Why?", "Do you know anybody like that?", "Are you similar or different?"],
  lessonLogic: [],

  slides: [
    { kind: "cover", title: "Personality Types", timing: "1 min", purpose: "Clean opening slide only." },
    {
      kind: "list",
      title: "Warm-up",
      instruction: "Describe yourself in three words.",
      items: ["calm", "social", "quiet", "friendly", "serious", "funny"],
      timing: "2 min",
      purpose: "Easy entry into self-description.",
      teacherNote: "Use the words only as support; teacher extends orally.",
    },
    {
      kind: "list",
      title: "Core idea",
      instruction: "Read and choose.",
      items: ["Introvert — recharges alone", "Extrovert — energized by people", "Ambivert — a mix of both"],
      timing: "2 min",
      purpose: "Give the minimum concept frame before speaking.",
      teacherNote: "Teacher handles fuller explanation and checking.",
    },
    {
      kind: "list",
      title: "Wheel setup",
      instruction: "Spin and answer.",
      items: ["Loves big parties", "Needs quiet time alone", "Enjoys people, then needs space", "Talks easily with strangers", "Changes with the situation"],
      timing: "1 min",
      purpose: "Introduce the wheel wedges cleanly.",
      teacherNote: "Teacher uses the repeated follow-up sequence orally after each spin.",
    },
    {
      kind: "wheel",
      title: "Wheel round",
      instruction: "Spin and speak.",
      wheelOptions: ["Loves big parties", "Needs quiet time alone", "Enjoys people, then needs space", "Talks easily with strangers", "Changes with the situation"],
      items: ["Which type is it?", "Why?", "Similar or different?"],
      timing: "4 min",
      purpose: "Main wheel activity.",
      teacherNote: "Teacher also adds “Do you know anybody like that?” from the guide, without adding text to the slide.",
    },
    {
      kind: "list",
      title: "This or That",
      instruction: "Choose one and explain.",
      items: ["Big party / Quiet night", "One close friend / Many friends", "Work alone / Work with a team", "Call / Text"],
      timing: "3 min",
      purpose: "Natural personality-linked preference speaking.",
      teacherNote: "Teacher pushes for reasons and self-description.",
    },
    {
      kind: "list",
      title: "Personality Line",
      instruction: "Choose your number and explain.",
      items: ["1 = very introverted", "5 = ambivert", "10 = very extroverted"],
      timing: "2 min",
      purpose: "Add nuance beyond labels.",
      teacherNote: "Teacher asks follow-ups such as “Why not lower?” or “Why not higher?” off-slide.",
    },
    {
      kind: "list",
      title: "Speed Debate",
      instruction: "Agree, disagree, or partly agree.",
      items: ["Introverts are better listeners.", "Extroverts have more fun.", "Ambiverts are more adaptable."],
      timing: "3 min",
      purpose: "Opinion speaking with longer answers.",
      teacherNote: "One statement at a time; teacher manages timing and follow-up.",
    },
    {
      kind: "list",
      title: "Final task",
      instruction: "Talk about your personality.",
      items: ["with friends", "with strangers", "at work or school"],
      timing: "1 min",
      purpose: "Freer fluency stage using lesson language and ideas.",
      teacherNote: "Teacher supports only if needed and prioritizes flow.",
    },
    { kind: "feedback", title: "Feedback", timing: "1 min", purpose: "Final slide only." },
  ],
};
