// SPARK Kids 1 — Picture Quest
// 20-minute one-to-one online ESL trial lesson for kids (beginner to low elementary).
// Familiar nouns, simple describing language, fast picture-based speaking.

export default {
  id: "spark-1",
  code: "SPARK 1",
  title: "Picture Quest",
  subtitle: "Familiar nouns, describing language, and fast picture-based speaking",
  length: "20 min",
  coreAim: "Get the child speaking in short but repeated sentences using playful picture-based game tasks with visible speaking support.",
  hiddenAssessment: "Listening, confidence, vocabulary access, sentence formation, follow-up response, and willingness to speak.",
  materials: [
    "6 familiar vocabulary pictures for Pick a Box, e.g. dog, cat, banana, ball, car, fish",
    "2-3 hidden or zoomed images for the mystery game",
    "3 icons or prompt cards for Find and Say, e.g. pencil, book, toy, something blue",
    "1 final challenge image from earlier in the lesson",
  ],
  pacing: [
    { part: "Hello + first answers", time: "2 min" },
    { part: "Game 1: Pick a Box", time: "5 min" },
    { part: "Game 2: Mystery Zoom", time: "5 min" },
    { part: "Game 3: Find and Say", time: "4 min" },
    { part: "Final challenge + feedback", time: "4 min" },
  ],

  slides: [
    {
      title: "Hello!",
      purpose: "Start speaking immediately and lower anxiety.",
      timing: "2 min",
      kidGuide: ["My name is ___.", "I like ___."],
      sayMore: ["My name is ___ and I like ___."],
      teacherScript: ["Hello! What's your name?", "How are you today?", "What do you like — dogs or cats?"],
      expectedOutput: ["My name is Ken.", "I like dogs.", "I am happy."],
      supportMoves: ["If the child says only one word, upgrade gently.", "Student: \"Dogs.\" Teacher: \"I like dogs.\" Student repeats."],
      requiredImage: "Large teacher avatar or wave icon; 2 large easy-choice icons (e.g. dog and cat, or apple and banana); optional star counter",
    },
    {
      title: "Pick a Box!",
      purpose: "Introduce the main game mechanic with almost no explanation.",
      timing: "30 sec",
      kidGuide: ["I pick number ___."],
      sayMore: ["I pick number ___, please."],
      teacherScript: ["Pick a box!", "Which number?"],
      expectedOutput: ["I pick number 3."],
      requiredImage: "6 large colorful boxes numbered 1-6, each clickable/tappable, with small star or treasure icons",
    },
    {
      title: "What is it?",
      purpose: "Get the learner to produce a simple naming sentence from a familiar picture.",
      timing: "2 min",
      kidGuide: ["It's a ___.", "I can see a ___."],
      sayMore: ["It's a ___ and it is ___."],
      teacherScript: ["What is it?", "Can you say: It's a ___?", "What color is it? / Big or small?", "Do you like dogs?"],
      expectedOutput: ["It's a dog.", "I can see a dog.", "It's a brown dog.", "I like dogs."],
      requiredImage: "One revealed picture from the chosen box — familiar noun, e.g. dog. Large, centered. One star appears after the answer.",
    },
    {
      title: "Say More!",
      purpose: "Repeat the same mechanic with a second picture so the child gets another fast success cycle.",
      timing: "1.5 min",
      kidGuide: ["It's a ___.", "It is ___."],
      sayMore: ["It's a ___ and it is ___.", "I like / don't like ___."],
      teacherScript: ["What is it?", "What color is it?", "Do you like it?"],
      expectedOutput: ["It's a banana.", "It is yellow.", "I like bananas."],
      requiredImage: "Second revealed picture from a different box — familiar noun, e.g. banana, ball, cat, car. Small bonus-star icon if the student uses the longer sentence.",
    },
    {
      title: "One More Box!",
      purpose: "Give one final quick round before switching mechanics.",
      timing: "1.5 min",
      kidGuide: ["It's a ___."],
      sayMore: ["It's a ___ and it is ___.", "I like ___."],
      teacherScript: ["One more box!", "Tell me about it!"],
      expectedOutput: ["One short sentence minimum.", "One longer sentence if possible."],
      requiredImage: "Either a third reveal, or a review board showing 2 previous images plus 1 new one — teacher's choice based on time/energy.",
    },
    {
      title: "Mystery Picture",
      purpose: "Shift from naming to guessing language.",
      timing: "30 sec",
      kidGuide: ["I think it is a ___.", "Is it a ___?"],
      sayMore: ["I think it is a ___ because it is ___."],
      teacherScript: ["Look! What do you think it is?"],
      requiredImage: "A zoomed-in partial or blurred image preview, fun question-mark graphics, a staged \"reveal more\" area.",
    },
    {
      title: "Guess!",
      purpose: "Get repeated guessing sentences from one hidden picture.",
      timing: "2 min",
      kidGuide: ["I think it is a ___.", "Maybe it is a ___."],
      sayMore: ["I think it is a ___ because it is ___."],
      teacherScript: ["What do you think it is?", "Is it a cat? A dog? A fish? (if extra support is needed)", "Reveal more.", "Now what do you think?", "After reveal: Do you like it?"],
      expectedOutput: ["I think it is a cat.", "Maybe it is a fish.", "It is a fish!", "I like fish."],
      requiredImage: "Hidden familiar object or animal image, shown in stage 1 with an optional button/cue for a further reveal. Keep Kid Guide visible throughout.",
    },
    {
      title: "Guess Again!",
      purpose: "Repeat the guessing mechanic with a new image.",
      timing: "2.5 min",
      kidGuide: ["I think it is a ___.", "Is it a ___?"],
      sayMore: ["I think it is a ___ because it is ___.", "It is a ___ and I like it."],
      teacherScript: ["What do you think?", "Why? / What color can you see?", "Reveal more.", "Now say the whole sentence."],
      expectedOutput: ["I think it is a banana because it is yellow.", "It is a banana and I like it."],
      requiredImage: "Second hidden familiar image, same structure as the previous slide for predictability.",
    },
    {
      title: "Find and Show!",
      purpose: "Move from screen pictures to the child's real environment for a more personal speaking task.",
      timing: "30 sec",
      kidGuide: ["Here is my ___.", "I found a ___."],
      sayMore: ["Here is my ___ and it is ___."],
      teacherScript: ["Find something!", "Show me a pencil / a book / something blue!"],
      requiredImage: "3 large prompt icons, e.g. pencil, book, something blue. Bright, active design suggesting movement.",
    },
    {
      title: "Show Me!",
      purpose: "Check listening response and extend speaking with personal objects.",
      timing: "3.5 min",
      kidGuide: ["This is my ___.", "It is ___.", "I have a ___."],
      sayMore: ["This is my ___ and it is ___."],
      teacherScript: ["Show me a book.", "What is it?", "What color is it?", "Is it big or small?"],
      expectedOutput: ["This is my book.", "It is blue.", "This is my book and it is blue."],
      promptOptions: ["Show me a pencil.", "Show me a book.", "Show me something blue.", "Show me a toy."],
      requiredImage: "Prompt cards/icons the teacher can pick from quickly; optional 3-step path graphic: Find → Show → Say.",
    },
    {
      title: "Star Challenge",
      purpose: "End with a final easy success and one fuller sentence.",
      timing: "1 min",
      kidGuide: ["It's a ___.", "I like ___."],
      sayMore: ["It's a ___ and it is ___."],
      teacherScript: ["Choose a star!", "Tell me about it!"],
      expectedOutput: ["It's a dog.", "It's a brown dog.", "I like dogs."],
      requiredImage: "3 large stars, each revealing one familiar image from earlier in the lesson. Bright \"Great job!\" visual.",
    },
    {
      title: "Great Job Today!",
      purpose: "Give positive child-facing feedback and a parent-ready summary.",
      timing: "3 min",
      isFeedback: true,
      childText: ["Great job!", "You listened well!", "You spoke English today!"],
      feedback: {
        strength: "Good listening, good participation, strong vocabulary recognition, willing to repeat and try.",
        target: "Needs support making full sentences, needs more confidence answering follow-up questions, needs more describing words such as colors and sizes.",
        recommendedPath: "Fun speaking and vocabulary classes with sentence frames and picture games.",
      },
      requiredImage: "3 badges or stars labeled Great Job / Next Step / Best Class; optional smiley face or trophy icon.",
    },
  ],
};
