// SPARK Kids 3 — Action Quest
// 20-minute one-to-one online ESL trial lesson for kids (beginner to low elementary).
// Movement, location language, and real objects.

export default {
  id: "spark-3",
  code: "SPARK 3",
  title: "Action Quest",
  subtitle: "Action, location, and real-object tasks",
  length: "20 min",
  coreAim: "Get the child speaking through action, location, and real-object tasks such as “It is on the chair” and “I have a pencil.”",
  hiddenAssessment: "Listening response, classroom English, prepositions, simple action verbs, and willingness to respond physically and verbally.",
  materials: [
    "1 teddy, toy, or cartoon object image for location modeling",
    "3-4 preposition images, e.g. on, in, under, next to",
    "3 prompt icons for action tasks, e.g. jump, clap, sit, stand",
    "2 real-object prompt icons, e.g. pencil, book, toy",
  ],
  pacing: [
    { part: "Hello + action warm-up", time: "2 min" },
    { part: "Game 1: Copy the Action", time: "4 min" },
    { part: "Game 2: Where Is It?", time: "6 min" },
    { part: "Game 3: Show and Put", time: "4 min" },
    { part: "Final challenge + feedback", time: "4 min" },
  ],

  slides: [
    {
      title: "Hello! Let's Move!",
      purpose: "Wake up the learner and get instant response.",
      timing: "2 min",
      kidGuide: ["I can ___.", "I am ___ing."],
      sayMore: ["I can ___ and ___!"],
      teacherScript: ["Wave!", "Clap!", "Can you jump?", "Say: I can jump."],
      expectedOutput: ["I can jump.", "I am jumping."],
      requiredImage: "Cheerful title; big icons for clap, wave, jump, sit.",
    },
    {
      title: "Copy Me!",
      purpose: "Start with movement plus short speaking frames.",
      timing: "30 sec",
      kidGuide: ["I can ___.", "I am ___ing."],
      sayMore: ["I can ___ fast!"],
      teacherScript: ["Copy me!", "Jump!", "Now say it!"],
      requiredImage: "3-4 action icons; maybe a big \"Go!\" button or arrow.",
    },
    {
      title: "Action Time",
      purpose: "Check response to simple action commands and turn action into speech.",
      timing: "3.5 min",
      kidGuide: ["I can ___.", "I am ___ing."],
      sayMore: ["I can ___ fast / slowly."],
      teacherScript: ["Jump!", "What are you doing?", "Say: I am jumping.", "Can you clap?", "Say: I can clap."],
      expectedOutput: ["I am jumping.", "I can clap."],
      promptOptions: ["jump", "clap", "sit", "stand", "dance"],
      requiredImage: "Large action image or icon shown one at a time, with space for quick action switching.",
    },
    {
      title: "Where Is the Teddy?",
      purpose: "Introduce preposition language with a toy or object.",
      timing: "30 sec",
      kidGuide: ["It is on the ___.", "It is in the ___.", "It is under the ___."],
      sayMore: ["The teddy is on the ___."],
      teacherScript: ["Where is the teddy?"],
      requiredImage: "One toy or teddy graphic, one reference object (box, chair, table), 3 location labels visually represented (on, in, under).",
    },
    {
      title: "Look and Say",
      purpose: "Get the learner to say the location from a picture.",
      timing: "2 min",
      kidGuide: ["It is on the ___."],
      sayMore: ["The teddy is on the chair."],
      teacherScript: ["Where is it?", "Say the whole sentence.", "Good! On the chair."],
      expectedOutput: ["It is on the chair."],
      requiredImage: "One clear preposition picture — example: teddy on the chair.",
    },
    {
      title: "Look and Say Again",
      purpose: "Repeat with a second location.",
      timing: "2 min",
      kidGuide: ["It is under the ___."],
      sayMore: ["The teddy is under the table."],
      teacherScript: ["Where is it now?", "Under or on?", "Say the whole sentence."],
      expectedOutput: ["It is under the table."],
      requiredImage: "Example: teddy under the table.",
    },
    {
      title: "One More Place",
      purpose: "Add one more location for repetition and confidence.",
      timing: "2 min",
      kidGuide: ["It is in the ___.", "It is next to the ___."],
      sayMore: ["The teddy is in the box."],
      teacherScript: ["Where is it?", "Can you say the whole sentence?"],
      expectedOutput: ["It is in the box."],
      requiredImage: "Example: teddy in the box or next to the chair.",
    },
    {
      title: "Show and Put",
      purpose: "Move from picture response to real-object action.",
      timing: "30 sec",
      kidGuide: ["This is my ___.", "It is on the ___.", "It is under the ___."],
      sayMore: ["This is my ___ and it is on the ___."],
      teacherScript: ["Show me a pencil.", "Put it on your book.", "Now say it!"],
      requiredImage: "Prompt icons for pencil, book, toy; arrow showing object movement.",
    },
    {
      title: "Your Turn!",
      purpose: "Check listening and speaking using the child's own objects.",
      timing: "3.5 min",
      kidGuide: ["This is my ___.", "It is on the ___.", "It is under the ___."],
      sayMore: ["This is my pencil and it is on the book."],
      teacherScript: ["Show me a pencil.", "Put it on the book.", "Where is it?", "Say: It is on the book."],
      expectedOutput: ["This is my pencil.", "It is on the book.", "It is under the book."],
      promptOptions: ["Show me a pencil.", "Put it on the book.", "Put it under the book.", "Put it next to the book."],
    },
    {
      title: "Super Challenge!",
      purpose: "Combine action and location in one final short task.",
      timing: "1.5 min",
      kidGuide: ["I can ___.", "It is in the ___."],
      sayMore: ["I can jump and the toy is in the box."],
      teacherScript: ["Jump two times.", "Put the toy in the box.", "Now tell me!"],
      expectedOutput: ["I can jump.", "The toy is in the box."],
      requiredImage: "One simple two-step mission card, e.g. toy + box + jump.",
    },
    {
      title: "Great Job Today!",
      purpose: "Give positive child-facing feedback and a parent-ready summary.",
      timing: "4 min",
      isFeedback: true,
      childText: ["Great job!", "You listened fast!", "You did the actions and spoke English!"],
      feedback: {
        strength: "Strong listening response, good participation, good understanding of action commands, willing to repeat full sentences.",
        target: "Needs more support with location words like on/in/under, needs more confidence making full answers, needs more repetition for sentence building.",
        recommendedPath: "Fun action-based speaking lessons with classroom English, prepositions, and simple sentence frames.",
      },
    },
  ],
};
