// SPARK Adults 2 — Travel & Adventure
// 20-minute one-to-one adult trial lesson. Signature gimmick: Boarding Pass reveal.

export default {
  id: "spark-adults-2",
  code: "SPARK Adults 2",
  title: "Travel & Adventure",
  length: "20 minutes",
  gimmick: "Boarding Pass reveal",
  coreAim: "The student \"checks in\" and a destination boarding pass flips up on screen. That destination drives the whole lesson — planning the trip, imagining the experience, and reacting to a surprise problem.",
  followUpBank: ["Why there?", "Who would you take?", "What is the first thing you would do?", "Have you done something like this before?"],
  lessonLogic: [
    "Boarding pass reveal = the hook that starts a real \"trip.\"",
    "Plan the trip = the main extended speaking task.",
    "Pack your bag = choices with reasons.",
    "Something happens = spontaneous problem-solving.",
    "Tell the story / Recommend = freer fluency and a confident finish.",
  ],

  slides: [
    { kind: "cover", title: "Travel & Adventure", timing: "1 min", purpose: "Clean opening slide only." },
    {
      kind: "list",
      title: "Warm-up",
      instruction: "Name a place you want to visit.",
      items: ["a city", "a beach", "the mountains", "another country"],
      timing: "2 min",
      purpose: "Quick, personal entry into the travel theme.",
      teacherNote: "Accept any place; teacher asks one quick “why there?” orally.",
    },
    {
      kind: "list",
      title: "Useful words",
      instruction: "Read the travel words.",
      items: ["pack", "flight", "hotel", "explore", "souvenir"],
      timing: "2 min",
      purpose: "Give a small set of useful travel words before speaking.",
      teacherNote: "Teacher checks meaning quickly and models one word in a sentence.",
    },
    {
      kind: "boardingpass",
      title: "Boarding pass reveal",
      instruction: "Check in and see your destination.",
      destinations: [
        { place: "Tokyo", tag: "City" },
        { place: "A tropical beach", tag: "Relax" },
        { place: "The mountains", tag: "Adventure" },
        { place: "Paris", tag: "Culture" },
        { place: "A road trip", tag: "Freedom" },
      ],
      timing: "1 min",
      purpose: "The signature reveal that launches the trip.",
      teacherNote: "Teacher reveals one destination for the student and reacts with them; keep the slide to the single instruction.",
    },
    {
      kind: "list",
      title: "Plan the trip",
      instruction: "Plan your trip. What will you do?",
      items: ["Where will you stay?", "What will you do there?", "Who will you go with?"],
      timing: "4 min",
      purpose: "Main speaking activity — the student plans the revealed trip in detail.",
      teacherNote: "Teacher pushes for details and future forms (“I will…”, “I'm going to…”); prompts live in the guide, not on the slide.",
    },
    {
      kind: "list",
      title: "Pack your bag",
      instruction: "Choose three things to pack. Say why.",
      items: ["camera", "passport", "good shoes", "sun cream", "warm jacket", "map"],
      timing: "3 min",
      purpose: "Focused speaking with reasons, tied to the destination.",
      teacherNote: "Teacher links the choices to the revealed place (“Why that for the mountains?”).",
    },
    {
      kind: "list",
      title: "Something happens",
      instruction: "React to the problem. What do you do?",
      items: ["Your flight is late.", "You lose your bag.", "It rains all day."],
      timing: "3 min",
      purpose: "Problem-solving speaking — longer, more spontaneous answers.",
      teacherNote: "One problem at a time; teacher can add “Who do you ask for help?” orally.",
    },
    {
      kind: "list",
      title: "Tell the story",
      instruction: "Tell me about a trip you remember.",
      items: ["where", "who with", "one good moment"],
      timing: "2 min",
      purpose: "Freer fluency using past experience and lesson language.",
      teacherNote: "Teacher supports past-tense storytelling and keeps the flow going.",
    },
    {
      kind: "list",
      title: "Recommend",
      instruction: "Tell me one place I should visit.",
      items: ["the place", "one reason"],
      timing: "1 min",
      purpose: "Short recommendation task to close the speaking on a personal, confident note.",
      teacherNote: "Teacher asks one follow-up, then moves to feedback.",
    },
    { kind: "feedback", title: "Feedback", timing: "1 min", purpose: "Final slide only." },
  ],
};
