// SPARK Kids 1 — Picture Quest
// 20-minute one-to-one online ESL trial lesson for kids (beginner to low elementary).
// Familiar nouns, simple describing language, fast picture-based speaking.

export default {
  id: "spark-1",
  code: "SPARK 1",
  title: "Picture Quest",
  subtitle: "Familiar nouns, describing language, and fast picture-based speaking",
  length: "20 min",
  coreAim: "Get the child speaking in short but repeated sentences using playful picture-based game tasks with visible speaking support.",
  hiddenAssessment: "Listening, confidence, vocabulary access, sentence formation, follow-up response, and willingness to speak.",
  materials: [
    "5 flippable number cards revealing 2 animals, 1 food, and 2 sports",
    "3 hidden mystery pictures for the guessing round",
    "3 prompt cards for Find and Show, e.g. pencil, book, something blue",
  ],
  pacing: [
    { part: "Cover + get-to-know-you", time: "3 min" },
    { part: "Game 1: Pick a Box", time: "5 min" },
    { part: "Game 2: I Like / I Don't Like", time: "4 min" },
    { part: "Game 3: Mystery Box", time: "3 min" },
    { part: "Game 4: Find and Show", time: "3 min" },
    { part: "Final challenge + feedback", time: "2 min" },
  ],

  slides: [
    {
      kind: "flipcards",
      title: "Pick a Box!",
      purpose: "Introduce the main game mechanic with almost no explanation.",
      timing: "5 min",
      teacherScript: ["Pick a box!", "Which number?", "What is it?", "Can you say: It's a ___?"],
      supportMoves: ["If the child says only one word, upgrade gently.", "Student: \"Dog.\" Teacher: \"It's a dog.\" Student repeats."],
      cards: [
        { number: 1, label: "dog", icon: "dog", category: "animal" },
        { number: 2, label: "cat", icon: "cat", category: "animal" },
        { number: 3, label: "banana", icon: "banana", category: "food" },
        { number: 4, label: "ball", icon: "basketball", category: "sport" },
        { number: 5, label: "football", icon: "soccerball", category: "sport" },
      ],
      starters: ["I pick number ___.", "It's a ___."],
    },
    {
      kind: "sort",
      title: "I Like / I Don't Like",
      purpose: "Turn naming into a real opinion sentence.",
      timing: "4 min",
      teacherScript: ["What is it?", "Do you like it?", "Put it in I like or I don't like."],
      supportMoves: ["Ask what it is first (It's a ___), then ask if they like it.", "Drag the picture into whichever box the child chooses."],
      items: [
        { label: "dog", icon: "dog" },
        { label: "cat", icon: "cat" },
        { label: "banana", icon: "banana" },
        { label: "ball", icon: "basketball" },
        { label: "football", icon: "soccerball" },
      ],
      idStarter: "It's a ___.",
      likeStarter: "I like ___.",
      dislikeStarter: "I don't like ___.",
    },
    {
      kind: "mystery",
      title: "Mystery Box 1",
      purpose: "Shift from naming to guessing language.",
      timing: "1 min",
      teacherScript: ["Look! What do you think it is?", "Reveal it!", "Were you right?"],
      label: "elephant",
      icon: "elephant",
      starter: "I think it's a ___.",
    },
    {
      kind: "mystery",
      title: "Mystery Box 2",
      purpose: "Repeat the guessing mechanic with a new animal for a second fast round.",
      timing: "1 min",
      teacherScript: ["Another mystery box!", "What do you think it is this time?", "Reveal it!", "Were you right?"],
      label: "lion",
      icon: "lion",
      starter: "I think it's a ___.",
    },
    {
      kind: "mystery",
      title: "Mystery Box 3",
      purpose: "One more quick guessing round before moving on.",
      timing: "1 min",
      teacherScript: ["Last mystery box!", "What do you think it is?", "Reveal it!", "Were you right?"],
      label: "fish",
      icon: "fish",
      starter: "I think it's a ___.",
    },
    {
      kind: "findshow",
      title: "Find and Show",
      purpose: "Move from screen pictures to the child's real environment, and end on an easy win.",
      timing: "3 min",
      teacherScript: ["Find something!", "Show me a pencil / a book / something blue!", "You found it — great job!"],
      prompts: ["something blue", "a pencil", "a toy"],
      starter: "I have a ___.",
    },
    {
      kind: "feedback",
      title: "Great Job Today!",
      purpose: "End on a clean, positive note with a parent-ready summary.",
      timing: "2 min",
      childText: ["Great job!", "Thank you!"],
      feedback: {
        strength: "Good listening, good participation, strong vocabulary recognition, willing to repeat and try.",
        target: "Needs support making full sentences, needs more confidence answering follow-up questions, needs more describing words such as colors and sizes.",
        recommendedPath: "Fun speaking and vocabulary classes with sentence frames and picture games.",
      },
    },
  ],
};
