// SPARK Kids 2 — Story Quest
// 20-minute one-to-one online ESL trial lesson for kids (beginner to low elementary).
// Picture-sequence storytelling and prediction.

export default {
  id: "spark-2",
  code: "SPARK 2",
  title: "Story Quest",
  subtitle: "Story-based sentences through prediction and sequencing",
  length: "20 min",
  coreAim: "Get the child speaking through short story-based sentences such as “He is…”, “She has…”, “First…”, and “Then…”.",
  hiddenAssessment: "Listening, sequencing, prediction, basic sentence formation, and willingness to retell.",
  materials: [
    "1 story character image, e.g. boy, girl, monkey, dog",
    "4 simple story-sequence pictures with a clear event chain",
    "2 prediction pictures where the next event is guessable",
    "1 final review collage of 3 story moments",
  ],
  pacing: [
    { part: "Hello + character warm-up", time: "2 min" },
    { part: "Game 1: Meet the Character", time: "4 min" },
    { part: "Game 2: What Happens Next?", time: "6 min" },
    { part: "Game 3: Put the Story in Order", time: "4 min" },
    { part: "Final retell + feedback", time: "4 min" },
  ],

  slides: [
    {
      title: "Hello Story Time!",
      purpose: "Warm up with a friendly character choice and start simple speaking.",
      timing: "2 min",
      kidGuide: ["It is a ___.", "I choose ___."],
      teacherScript: ["Who do you choose?", "Is it a boy or a girl?", "Do you like the dog or the monkey?"],
      expectedOutput: ["I choose the dog.", "It is a boy.", "I choose the monkey because I like monkeys."],
      sceneIcons: ["boy", "girl"],
    },
    {
      title: "Meet the Character",
      purpose: "Use one simple picture to build repeated describing language.",
      timing: "30 sec",
      kidGuide: ["He is ___.", "She is ___.", "He has ___.", "She has ___."],
      teacherScript: ["Look at the picture.", "Who is it?", "What does he have?"],
      sceneIcons: ["boy", "hat", "apple"],
    },
    {
      title: "Tell Me About the Picture",
      purpose: "Elicit descriptive sentences from a single story scene.",
      timing: "3.5 min",
      kidGuide: ["He is a boy.", "He has a ball.", "It is red."],
      teacherScript: ["Who is it?", "What does he have?", "What color is it?", "Is he happy or sad?"],
      expectedOutput: ["He is a boy.", "He has a ball.", "It is red.", "He is happy."],
      sceneIcons: ["boy", "ball"],
    },
    {
      title: "What Happens Next?",
      purpose: "Shift from describing to prediction.",
      timing: "30 sec",
      kidGuide: ["I think ___.", "He goes to ___.", "She goes to ___."],
      teacherScript: ["What happens next?", "Where does he go?"],
      sceneIcons: ["boy", "arrow", "apple"],
    },
    {
      title: "Guess the Story",
      purpose: "Get the child to predict the next event with support.",
      timing: "2 min",
      kidGuide: ["I think he goes to ___.", "I think she gets a ___."],
      teacherScript: ["What happens next?", "Choose one.", "Say the whole sentence.", "Reveal correct next image."],
      expectedOutput: ["I think he goes to the park.", "I think she gets an apple."],
      sceneIcons: ["girl", "arrow", "apple"],
    },
    {
      title: "Guess Again!",
      purpose: "Repeat the same mechanic with a new story moment.",
      timing: "2 min",
      kidGuide: ["He is ___.", "Then he ___."],
      teacherScript: ["What is he doing?", "What happens next?", "Can you say: First… then…?"],
      expectedOutput: ["Then he runs.", "First he plays, then he goes home."],
      sceneIcons: ["monkey", "arrow", "banana"],
    },
    {
      title: "Put It in Order",
      purpose: "Move into sequencing language.",
      timing: "30 sec",
      kidGuide: ["First ___.", "Then ___.", "Last ___."],
      teacherScript: ["Which one is first?", "What is next?"],
      sceneIcons: ["boy", "girl", "monkey", "dog"],
    },
    {
      title: "Story Order Challenge",
      purpose: "Get the child to say the order of events.",
      timing: "3.5 min",
      kidGuide: ["First ___.", "Then ___.", "Last ___."],
      teacherScript: ["Show me number 1.", "What happens first?", "What happens next?", "What happens last?"],
      expectedOutput: ["First he has a ball.", "Then he goes to the park.", "Last he goes home."],
      sceneIcons: ["boy", "ball", "apple"],
    },
    {
      title: "Tell the Story!",
      purpose: "End with one short retell using the learner's best supported language.",
      timing: "2 min",
      kidGuide: ["First ___.", "Then ___.", "Last ___."],
      teacherScript: ["Can you tell me the story?", "Use: first, then, last."],
      expectedOutput: ["Short 3-part retell."],
      sceneIcons: ["boy", "arrow", "apple"],
    },
    {
      kind: "feedback",
      title: "Great Story!",
      purpose: "Give positive child-facing feedback and a parent-ready summary.",
      timing: "4 min",
      childText: ["Great job!", "You told a story!", "You listened very well!"],
      feedback: {
        strength: "Good listening, good visual understanding, strong participation in picture tasks, good sequencing support.",
        target: "Needs more confidence making full sentences, needs support using story words like first/then/last, needs more describing vocabulary.",
        recommendedPath: "Fun speaking lessons with stories, picture talk, and sentence frames.",
      },
    },
  ],
};
