// SPARK Teens 3 — Friends
// 20-minute one-to-one online ESL trial lesson for teens (A1+ to B1).

export default {
  id: "spark-teens-3",
  code: "SPARK Teens 3",
  title: "Friends",
  length: "20 min",
  coreAim: "Help the learner speak more openly about friendship, personality, and social activities through simple mini-games and a small set of useful friendship words.",
  targetVocab: [
    { word: "friend", meaning: "A person you like and spend time with", model: "My best friend is funny." },
    { word: "invite", meaning: "Ask someone to come with you", model: "I invite my friend to play football." },
    { word: "honest", meaning: "Tells the truth", model: "A good friend is honest." },
  ],

  slides: [
    {
      title: "Friend Start",
      timing: "2 min",
      purpose: "Easy entry into a personal topic",
      miniGameType: "Quick pick",
      prompt: "Do you like big friend groups or one close friend?",
      sentenceStems: ["I prefer ___ because ___."],
      teacherScript: ["Today we'll talk about friends.", "Choose one: big group or one close friend?", "Tell me why."],
      likelyAnswers: ["I prefer one close friend because it is easier.", "I prefer a big group because it is fun."],
      followUps: ["How many close friends do you have?", "Do you usually go out with friends?", "Are your friends from school?"],
      correctionNotes: ["Keep it low-pressure and welcoming."],
      pacingNote: "This lesson should feel friendly, not intense.",
    },
    {
      title: "New Word: Friend",
      timing: "2 min",
      purpose: "Start with a very accessible word and move into description",
      miniGameType: "Say and personalize",
      wordCard: { word: "friend", meaning: "a person you like and spend time with" },
      prompt: "Describe your best friend in 2 words.",
      sentenceStems: ["My best friend is ___."],
      teacherScript: ["New word: friend.", "Tell me about your best friend.", "Use two words."],
      likelyAnswers: ["My best friend is funny and kind.", "My best friend is quiet and smart."],
      followUps: ["Where did you meet?", "What do you do together?", "How often do you talk?"],
      correctionNotes: ["Help with adjective choice if needed."],
      pacingNote: "Push description, not just naming.",
    },
    {
      title: "Mini-Game 1: Pick One",
      timing: "4 min",
      purpose: "Opinion speaking about friendship",
      miniGameType: "Choice + reason",
      choices: ["Funny friend or serious friend?", "Online friend or school friend?"],
      sentenceStems: ["I choose ___ because ___.", "For me, ___ is better because ___."],
      teacherScript: ["Choose one quickly.", "Now give a reason.", "Good — one more detail."],
      likelyAnswers: ["I choose school friend because I see them every day.", "For me, funny friend is better because life is more fun."],
      followUps: ["What about your best friend?", "Do your parents agree?", "Is that easy or difficult?"],
      correctionNotes: ["Lower levels can answer with one reason; higher levels can compare."],
      pacingNote: "Keep it playful and responsive.",
    },
    {
      title: "New Word: Invite",
      timing: "2 min",
      purpose: "Add a practical social verb",
      miniGameType: "Word to action",
      wordCard: { word: "invite", meaning: "ask someone to come with you" },
      prompt: "What do you invite your friends to do?",
      sentenceStems: ["I invite my friend to ___."],
      teacherScript: ["New word: invite.", "If I ask my friend to come, I invite my friend.", "Say: I invite my friend to ___."],
      likelyAnswers: ["I invite my friend to play football.", "I invite my friend to my house.", "I invite my friend to go out."],
      followUps: ["Who do you invite most?", "Do your friends invite you too?", "What is a fun place to go?"],
      correctionNotes: ["Model the verb pattern rather than explain grammar."],
      pacingNote: "Keep it practical and social.",
    },
    {
      title: "Mini-Game 2: Fast Card Talk",
      timing: "4 min",
      purpose: "Build a short conversation about a real friend",
      miniGameType: "One card, three linked questions",
      cardTitle: "My Friend",
      questions: ["Who is your best friend?", "Where did you meet?", "What do you do together?"],
      sentenceStems: ["My best friend is ___.", "We met at ___.", "We usually ___."],
      teacherScript: ["Now tell me about one real friend.", "Answer in full sentences.", "After each answer, I'll ask one more question."],
      likelyAnswers: ["My best friend is Ahmed.", "We met at school.", "We usually play games together."],
      followUps: ["How long have you been friends?", "What do you like about this person?", "Do you fight sometimes?"],
      correctionNotes: ["Keep it natural and supportive."],
      pacingNote: "Let the student talk more here than in earlier slides.",
    },
    {
      title: "New Word: Honest",
      timing: "2 min",
      purpose: "Add a personality word for friendship values",
      miniGameType: "Model and personalize",
      wordCard: { word: "honest", meaning: "tells the truth" },
      prompt: "What makes a good friend?",
      sentenceStems: ["A good friend is honest because ___."],
      teacherScript: ["New word: honest.", "An honest person tells the truth.", "Tell me: A good friend is honest because ___."],
      likelyAnswers: ["A good friend is honest because I can trust them.", "Honest is important.", "A good friend is honest and kind."],
      followUps: ["Is honesty very important for you?", "What other qualities are important?", "Can a funny friend be a bad friend?"],
      correctionNotes: ["If needed, allow short answer first, then expand."],
      pacingNote: "This adds emotional depth; keep language simple.",
    },
    {
      title: "Mini-Game 3: True or False",
      timing: "3 min",
      purpose: "Open personal opinions about friendship",
      miniGameType: "Personal statements",
      instructions: "Say if it is true or false for you. Then explain.",
      statements: ["One best friend is enough.", "A good friend always tells the truth.", "Friends should invite each other often."],
      sentenceStems: ["That's true for me because ___.", "That's false for me because ___."],
      teacherScript: ["True or false?", "Now explain your answer.", "Can you say one more sentence?"],
      likelyAnswers: ["That's true for me because one close friend is enough.", "That's false for me because people need more friends."],
      followUps: ["What do your friends think?", "Is this different for teens and adults?", "What is most important in friendship?"],
      correctionNotes: ["Prioritize meaning and confidence over form here."],
      pacingNote: "This is the most open-speaking stage; let the learner express opinions.",
    },
    {
      kind: "feedback",
      title: "Feedback",
      timing: "2 min",
      purpose: "Give live feedback — strength, target, and recommended next step.",
      teacherScript: ["Great job today!", "Here's what you did well, and here's your next step."],
    },
    {
      kind: "final",
      title: "Great job!",
      subtitle: "Thank you!",
      timing: "1 min",
      purpose: "Clean closing slide only.",
    },
  ],
};
