// SPARK Adults 3 — Food & Restaurants
// 20-minute one-to-one adult trial lesson. Signature gimmick: Mystery Menu + role-play.

export default {
  id: "spark-adults-3",
  code: "SPARK Adults 3",
  title: "Food & Restaurants",
  length: "20 minutes",
  gimmick: "Mystery Menu + role-play",
  coreAim: "A restaurant menu with a hidden \"mystery dish\" reveals on tap, followed by a short waiter-and-customer role-play. Speaking is driven by ordering, reacting to taste, and acting out a real restaurant scene.",
  followUpBank: ["Do you eat this often?", "Who cooks it best?", "Would you order it again?", "Sweet or spicy — which do you prefer?"],
  lessonLogic: [
    "The menu = normal ordering to warm up the scene.",
    "Mystery dish reveal = the surprise hook and reaction moment.",
    "Describe the taste = focused describing language.",
    "Role-play (order, then problem) = the main extended speaking, with a role-swap.",
    "Recommend = a confident, personal finish.",
  ],

  slides: [
    { kind: "cover", title: "Food & Restaurants", timing: "1 min", purpose: "Clean opening slide only." },
    {
      kind: "list",
      title: "Warm-up",
      instruction: "Name your favorite food.",
      items: ["something sweet", "something spicy", "something you eat often"],
      timing: "2 min",
      purpose: "Fast, personal entry into the food theme.",
      teacherNote: "Teacher asks “when do you eat it?” orally to open it up.",
    },
    {
      kind: "list",
      title: "Useful words",
      instruction: "Read the taste words.",
      items: ["sweet", "spicy", "salty", "fresh", "delicious"],
      timing: "2 min",
      purpose: "Give a small set of describing words before speaking.",
      teacherNote: "Teacher checks meaning and models one word with a real food.",
    },
    {
      kind: "menu",
      title: "The menu",
      instruction: "Read the menu. What do you choose?",
      dishes: ["Grilled chicken", "Vegetable soup", "Fresh salad"],
      mysteryOptions: ["Fish soup", "Very spicy noodles", "A sweet dessert", "A local specialty", "Something you've never eaten"],
      revealHere: false,
      timing: "2 min",
      purpose: "Introduce the menu and let the student order normally first.",
      teacherNote: "Teacher asks the student to order and give one reason; save the mystery slot for the next slide.",
    },
    {
      kind: "menu",
      title: "Mystery dish reveal",
      instruction: "Reveal the dish. Would you try it?",
      dishes: ["Grilled chicken", "Vegetable soup", "Fresh salad"],
      mysteryOptions: ["Fish soup", "Very spicy noodles", "A sweet dessert", "A local specialty", "Something you've never eaten"],
      revealHere: true,
      timing: "2 min",
      purpose: "The signature reveal — a surprise dish to react to.",
      teacherNote: "Teacher reveals one dish, then asks “yes or no, and why?”; keep the slide to a single instruction.",
    },
    {
      kind: "list",
      title: "Describe the taste",
      instruction: "Describe a food using two words.",
      items: ["sweet + soft", "spicy + hot", "fresh + light", "salty + crunchy"],
      timing: "2 min",
      purpose: "Focused describing practice with combinations.",
      teacherNote: "Teacher pushes for a real example (“What food is spicy and hot for you?”).",
    },
    {
      kind: "list",
      title: "Role-play: order",
      instruction: "Order your meal. I am the waiter.",
      items: ["“What would you like?”", "“Anything to drink?”"],
      timing: "3 min",
      purpose: "Live role-play — the student orders in a real scene.",
      teacherNote: "Teacher plays the waiter, then swaps so the student is the waiter for one round.",
    },
    {
      kind: "list",
      title: "Role-play: a small problem",
      instruction: "Solve the problem with the waiter.",
      items: ["The food is cold.", "The order is wrong.", "You want to pay."],
      timing: "3 min",
      purpose: "Higher-output role-play with a realistic complication.",
      teacherNote: "One situation at a time; teacher keeps the scene polite and natural.",
    },
    {
      kind: "list",
      title: "Recommend",
      instruction: "Recommend a restaurant or dish to me.",
      items: ["the place or dish", "one reason"],
      timing: "1 min",
      purpose: "Freer, confident closing task using lesson language.",
      teacherNote: "Teacher asks one follow-up, then moves to feedback.",
    },
    { kind: "feedback", title: "Feedback", timing: "1 min", purpose: "Final slide only." },
  ],
};
