// Vocabulary category, Synonyms game: C1-C2 level topic sets. Same shape
// as synonymsTopics.js -- [{ word, choices: [4], correct }] -- 10 topics
// (was 7), with the position of `correct` within each entry's `choices`
// array varied rather than clustered at a fixed index.
const SYNONYMS_TOPICS_C1C2 = {
  businessAndEconomics: [
    { word: "lucrative", choices: ["unprofitable", "stagnant", "profitable", "insolvent"], correct: "profitable" },
    { word: "diversify", choices: ["broaden", "narrow", "consolidate", "restrict"], correct: "broaden" },
    { word: "insolvent", choices: ["prosperous", "solvent", "thriving", "bankrupt"], correct: "bankrupt" },
    { word: "stagnant", choices: ["booming", "sluggish", "dynamic", "flourishing"], correct: "sluggish" },
    { word: "monopoly", choices: ["fair competition", "shared market", "exclusive control", "open trade"], correct: "exclusive control" },
    { word: "subsidize", choices: ["fund", "tax", "withhold", "penalize"], correct: "fund" },
    { word: "volatile", choices: ["steady", "predictable", "constant", "unstable"], correct: "unstable" },
    { word: "austerity", choices: ["extravagance", "cost-cutting", "expansion", "surplus"], correct: "cost-cutting" },
    { word: "commodity", choices: ["service", "currency", "tradeable good", "asset class"], correct: "tradeable good" },
    { word: "leverage", choices: ["borrowed capital", "personal savings", "pure profit", "tax refund"], correct: "borrowed capital" },
  ],
  politicsAndGovernance: [
    { word: "legislation", choices: ["opinion", "law", "custom", "rumor"], correct: "law" },
    { word: "sovereignty", choices: ["dependency", "occupation", "colonization", "self-governance"], correct: "self-governance" },
    { word: "diplomacy", choices: ["negotiation", "conflict", "invasion", "isolation"], correct: "negotiation" },
    { word: "coalition", choices: ["rivalry", "opposition", "alliance", "division"], correct: "alliance" },
    { word: "corruption", choices: ["integrity", "dishonesty", "transparency", "fairness"], correct: "dishonesty" },
    { word: "referendum", choices: ["private meeting", "court ruling", "royal decree", "public vote"], correct: "public vote" },
    { word: "bureaucracy", choices: ["administration", "anarchy", "monarchy", "democracy"], correct: "administration" },
    { word: "dissent", choices: ["consensus", "approval", "disagreement", "conformity"], correct: "disagreement" },
    { word: "autonomous", choices: ["dependent", "self-ruling", "controlled", "subordinate"], correct: "self-ruling" },
    { word: "mandate", choices: ["rejection", "suggestion", "request", "authorization"], correct: "authorization" },
  ],
  scienceAndInnovation: [
    { word: "hypothesis", choices: ["theory", "fact", "law", "conclusion"], correct: "theory" },
    { word: "empirical", choices: ["theoretical", "speculative", "evidence-based", "hypothetical"], correct: "evidence-based" },
    { word: "innovation", choices: ["stagnation", "breakthrough", "repetition", "tradition"], correct: "breakthrough" },
    { word: "catalyst", choices: ["obstacle", "byproduct", "residue", "trigger"], correct: "trigger" },
    { word: "anomaly", choices: ["irregularity", "pattern", "norm", "standard"], correct: "irregularity" },
    { word: "synthesis", choices: ["separation", "division", "combination", "isolation"], correct: "combination" },
    { word: "obsolete", choices: ["cutting-edge", "outdated", "modern", "current"], correct: "outdated" },
    { word: "prototype", choices: ["finished product", "byproduct", "flaw", "model"], correct: "model" },
    { word: "viable", choices: ["workable", "impossible", "disposable", "short-lived"], correct: "workable" },
    { word: "replicate", choices: ["invent", "discard", "reproduce", "alter"], correct: "reproduce" },
  ],
  artsAndCulture: [
    { word: "aesthetic", choices: ["functional", "practical", "mundane", "artistic"], correct: "artistic" },
    { word: "avant-garde", choices: ["conventional", "experimental", "traditional", "classical"], correct: "experimental" },
    { word: "eclectic", choices: ["uniform", "narrow", "diverse", "monotonous"], correct: "diverse" },
    { word: "provocative", choices: ["thought-provoking", "dull", "predictable", "bland"], correct: "thought-provoking" },
    { word: "renowned", choices: ["obscure", "unknown", "forgotten", "celebrated"], correct: "celebrated" },
    { word: "authentic", choices: ["counterfeit", "genuine", "imitation", "artificial"], correct: "genuine" },
    { word: "narrative", choices: ["setting", "genre", "storyline", "critique"], correct: "storyline" },
    { word: "satirical", choices: ["mocking", "sincere", "reverent", "solemn"], correct: "mocking" },
    { word: "nuanced", choices: ["obvious", "blunt", "crude", "subtle"], correct: "subtle" },
    { word: "timeless", choices: ["fleeting", "enduring", "dated", "trendy"], correct: "enduring" },
  ],
  ethicsAndPhilosophy: [
    { word: "integrity", choices: ["deceit", "corruption", "honesty", "hypocrisy"], correct: "honesty" },
    { word: "dilemma", choices: ["predicament", "solution", "certainty", "resolution"], correct: "predicament" },
    { word: "virtue", choices: ["vice", "moral goodness", "flaw", "weakness"], correct: "moral goodness" },
    { word: "hypocrisy", choices: ["sincerity", "honesty", "consistency", "pretense"], correct: "pretense" },
    { word: "autonomy", choices: ["dependency", "obedience", "self-determination", "conformity"], correct: "self-determination" },
    { word: "utilitarian", choices: ["practical-minded", "idealistic", "sentimental", "romantic"], correct: "practical-minded" },
    { word: "subjective", choices: ["objective", "personal", "universal", "factual"], correct: "personal" },
    { word: "coerce", choices: ["persuade gently", "invite", "welcome", "force"], correct: "force" },
    { word: "altruism", choices: ["selfishness", "greed", "selflessness", "vanity"], correct: "selflessness" },
    { word: "ambivalent", choices: ["conflicted", "certain", "decisive", "resolute"], correct: "conflicted" },
  ],
  globalAffairs: [
    { word: "globalization", choices: ["isolationism", "worldwide integration", "nationalism", "protectionism"], correct: "worldwide integration" },
    { word: "humanitarian", choices: ["military", "commercial", "political", "relief-focused"], correct: "relief-focused" },
    { word: "displacement", choices: ["forced relocation", "settlement", "migration by choice", "expansion"], correct: "forced relocation" },
    { word: "sanctions", choices: ["rewards", "alliances", "penalties", "treaties"], correct: "penalties" },
    { word: "refugee", choices: ["tourist", "displaced person", "immigrant by choice", "diplomat"], correct: "displaced person" },
    { word: "summit", choices: ["protest", "election", "ceremony", "high-level meeting"], correct: "high-level meeting" },
    { word: "treaty", choices: ["formal agreement", "informal chat", "rumor", "threat"], correct: "formal agreement" },
    { word: "instability", choices: ["peace", "order", "unrest", "stability"], correct: "unrest" },
    { word: "intervention", choices: ["withdrawal", "involvement", "neutrality", "avoidance"], correct: "involvement" },
    { word: "diaspora", choices: ["native population", "single tribe", "isolated village", "scattered population"], correct: "scattered population" },
  ],
  psychologyAndBehavior: [
    { word: "cognition", choices: ["thinking", "feeling", "acting", "resting"], correct: "thinking" },
    { word: "resilience", choices: ["fragility", "weakness", "toughness", "vulnerability"], correct: "toughness" },
    { word: "introspection", choices: ["distraction", "denial", "avoidance", "self-reflection"], correct: "self-reflection" },
    { word: "impulsive", choices: ["cautious", "spontaneous", "deliberate", "methodical"], correct: "spontaneous" },
    { word: "empathy", choices: ["compassion", "indifference", "hostility", "apathy"], correct: "compassion" },
    { word: "cognitive bias", choices: ["logical proof", "factual error", "mental shortcut", "random guess"], correct: "mental shortcut" },
    { word: "subconscious", choices: ["conscious thought", "spoken word", "physical action", "unconscious mind"], correct: "unconscious mind" },
    { word: "gratification", choices: ["frustration", "satisfaction", "disappointment", "deprivation"], correct: "satisfaction" },
    { word: "temperament", choices: ["disposition", "appearance", "intelligence", "skill"], correct: "disposition" },
    { word: "rationalize", choices: ["confess", "deny", "justify", "regret"], correct: "justify" },
  ],
  lawAndJustice: [
    { word: "verdict", choices: ["ruling", "accusation", "appeal", "testimony"], correct: "ruling" },
    { word: "testimony", choices: ["evidence bag", "statement", "verdict", "warrant"], correct: "statement" },
    { word: "plaintiff", choices: ["claimant", "defendant", "witness", "juror"], correct: "claimant" },
    { word: "acquit", choices: ["convict", "exonerate", "indict", "charge"], correct: "exonerate" },
    { word: "litigation", choices: ["settlement", "lawsuit", "mediation", "arbitration"], correct: "lawsuit" },
    { word: "culpable", choices: ["innocent", "blameless", "at fault", "exempt"], correct: "at fault" },
    { word: "jurisdiction", choices: ["legal authority", "courtroom", "evidence", "verdict"], correct: "legal authority" },
    { word: "indict", choices: ["formally accuse", "acquit", "pardon", "release"], correct: "formally accuse" },
    { word: "precedent", choices: ["prior ruling", "new law", "exception", "loophole"], correct: "prior ruling" },
    { word: "impartial", choices: ["biased", "prejudiced", "unbiased", "partial"], correct: "unbiased" },
  ],
  linguisticsAndCommunication: [
    { word: "rhetoric", choices: ["persuasive language", "silence", "grammar rule", "dialect"], correct: "persuasive language" },
    { word: "articulate", choices: ["well-spoken", "tongue-tied", "silent", "hesitant"], correct: "well-spoken" },
    { word: "ambiguity", choices: ["clarity", "vagueness", "precision", "certainty"], correct: "vagueness" },
    { word: "connotation", choices: ["implied meaning", "literal meaning", "spelling", "pronunciation"], correct: "implied meaning" },
    { word: "discourse", choices: ["extended discussion", "single word", "short reply", "silence"], correct: "extended discussion" },
    { word: "colloquial", choices: ["formal", "technical", "informal", "academic"], correct: "informal" },
    { word: "paraphrase", choices: ["quote directly", "reword", "translate", "memorize"], correct: "reword" },
    { word: "syntax", choices: ["vocabulary list", "sentence structure", "pronunciation guide", "spelling rule"], correct: "sentence structure" },
    { word: "eloquence", choices: ["fluent expression", "stammering", "silence", "confusion"], correct: "fluent expression" },
    { word: "dialect", choices: ["regional variety", "foreign language", "slang only", "written form"], correct: "regional variety" },
  ],
  academiaAndResearch: [
    { word: "methodology", choices: ["research approach", "final result", "raw data", "hypothesis"], correct: "research approach" },
    { word: "peer review", choices: ["expert evaluation", "public vote", "self-assessment", "random check"], correct: "expert evaluation" },
    { word: "citation", choices: ["reference", "footnote symbol", "summary", "title"], correct: "reference" },
    { word: "plagiarism", choices: ["original writing", "copying without credit", "paraphrasing with credit", "quoting properly"], correct: "copying without credit" },
    { word: "dissertation", choices: ["thesis", "lecture", "textbook", "syllabus"], correct: "thesis" },
    { word: "paradigm", choices: ["model of thought", "raw data", "footnote", "citation"], correct: "model of thought" },
    { word: "scrutinize", choices: ["ignore", "examine closely", "skim", "summarize"], correct: "examine closely" },
    { word: "empirical evidence", choices: ["observed data", "personal opinion", "assumption", "guesswork"], correct: "observed data" },
    { word: "tenure", choices: ["temporary role", "permanent position", "internship", "scholarship"], correct: "permanent position" },
    { word: "interdisciplinary", choices: ["combining fields", "single subject", "narrow focus", "isolated study"], correct: "combining fields" },
  ],
};

export default SYNONYMS_TOPICS_C1C2;
