// Vocabulary category, Synonyms game: B1-B2 level topic sets. Same shape
// and same topic keys as synonymsTopics.js (the A1-A2 set), but harder
// vocabulary and subtler, same-semantic-field distractors appropriate to
// intermediate learners.
const SYNONYMS_TOPICS_B1B2 = {
  feelings: [
    { word: "delighted", choices: ["annoyed", "thrilled", "confused", "exhausted"], correct: "thrilled" },
    { word: "anxious", choices: ["apprehensive", "content", "indifferent", "delighted"], correct: "apprehensive" },
    { word: "furious", choices: ["enraged", "amused", "puzzled", "relieved"], correct: "enraged" },
    { word: "gloomy", choices: ["downcast", "cheerful", "curious", "confident"], correct: "downcast" },
    { word: "astonished", choices: ["astounded", "bored", "annoyed", "calm"], correct: "astounded" },
    { word: "embarrassed", choices: ["humiliated", "delighted", "confident", "relaxed"], correct: "humiliated" },
    { word: "content", choices: ["satisfied", "frustrated", "nervous", "jealous"], correct: "satisfied" },
    { word: "exhausted", choices: ["drained", "energized", "curious", "amused"], correct: "drained" },
    { word: "irritated", choices: ["annoyed", "delighted", "relieved", "grateful"], correct: "annoyed" },
    { word: "hopeful", choices: ["optimistic", "pessimistic", "indifferent", "anxious"], correct: "optimistic" },
  ],
  dailyActions: [
    { word: "accomplish", choices: ["achieve", "abandon", "delay", "ignore"], correct: "achieve" },
    { word: "postpone", choices: ["delay", "complete", "announce", "resolve"], correct: "delay" },
    { word: "examine", choices: ["inspect", "ignore", "discard", "announce"], correct: "inspect" },
    { word: "obtain", choices: ["acquire", "release", "reject", "waste"], correct: "acquire" },
    { word: "recall", choices: ["remember", "forget", "ignore", "predict"], correct: "remember" },
    { word: "resolve", choices: ["settle", "worsen", "delay", "confuse"], correct: "settle" },
    { word: "assemble", choices: ["gather", "scatter", "destroy", "hide"], correct: "gather" },
    { word: "maintain", choices: ["sustain", "neglect", "abandon", "disrupt"], correct: "sustain" },
    { word: "eliminate", choices: ["remove", "add", "restore", "increase"], correct: "remove" },
    { word: "confirm", choices: ["verify", "deny", "postpone", "ignore"], correct: "verify" },
  ],
  describingPeople: [
    { word: "generous", choices: ["charitable", "stingy", "cautious", "indifferent"], correct: "charitable" },
    { word: "stubborn", choices: ["obstinate", "flexible", "agreeable", "shy"], correct: "obstinate" },
    { word: "confident", choices: ["self-assured", "timid", "hesitant", "modest"], correct: "self-assured" },
    { word: "arrogant", choices: ["conceited", "humble", "polite", "shy"], correct: "conceited" },
    { word: "reliable", choices: ["dependable", "careless", "forgetful", "distracted"], correct: "dependable" },
    { word: "curious", choices: ["inquisitive", "indifferent", "bored", "reluctant"], correct: "inquisitive" },
    { word: "cautious", choices: ["wary", "reckless", "bold", "careless"], correct: "wary" },
    { word: "ambitious", choices: ["driven", "lazy", "content", "modest"], correct: "driven" },
    { word: "modest", choices: ["humble", "arrogant", "boastful", "vain"], correct: "humble" },
    { word: "talkative", choices: ["chatty", "reserved", "silent", "shy"], correct: "chatty" },
  ],
  describingThings: [
    { word: "essential", choices: ["crucial", "optional", "minor", "irrelevant"], correct: "crucial" },
    { word: "ancient", choices: ["archaic", "modern", "recent", "current"], correct: "archaic" },
    { word: "fragile", choices: ["delicate", "sturdy", "flexible", "solid"], correct: "delicate" },
    { word: "vast", choices: ["immense", "tiny", "narrow", "shallow"], correct: "immense" },
    { word: "obvious", choices: ["evident", "hidden", "unclear", "vague"], correct: "evident" },
    { word: "flexible", choices: ["adaptable", "rigid", "fixed", "stubborn"], correct: "adaptable" },
    { word: "reasonable", choices: ["sensible", "absurd", "extreme", "irrational"], correct: "sensible" },
    { word: "genuine", choices: ["authentic", "fake", "artificial", "false"], correct: "authentic" },
    { word: "efficient", choices: ["productive", "wasteful", "sluggish", "clumsy"], correct: "productive" },
    { word: "complex", choices: ["intricate", "simple", "basic", "plain"], correct: "intricate" },
  ],
  schoolAndStudy: [
    { word: "analyze", choices: ["examine", "ignore", "summarize", "guess"], correct: "examine" },
    { word: "summarize", choices: ["condense", "expand", "repeat", "translate"], correct: "condense" },
    { word: "comprehend", choices: ["understand", "misread", "forget", "skip"], correct: "understand" },
    { word: "emphasize", choices: ["stress", "ignore", "hide", "omit"], correct: "stress" },
    { word: "evaluate", choices: ["assess", "ignore", "postpone", "invent"], correct: "assess" },
    { word: "clarify", choices: ["explain", "confuse", "hide", "avoid"], correct: "explain" },
    { word: "outline", choices: ["sketch", "erase", "finalize", "memorize"], correct: "sketch" },
    { word: "revise", choices: ["review", "ignore", "delete", "postpone"], correct: "review" },
    { word: "demonstrate", choices: ["illustrate", "conceal", "deny", "confuse"], correct: "illustrate" },
    { word: "conclude", choices: ["determine", "begin", "interrupt", "avoid"], correct: "determine" },
  ],
  travelAndPlaces: [
    { word: "journey", choices: ["voyage", "pause", "delay", "residence"], correct: "voyage" },
    { word: "destination", choices: ["endpoint", "origin", "route", "departure"], correct: "endpoint" },
    { word: "accommodation", choices: ["lodging", "transport", "luggage", "itinerary"], correct: "lodging" },
    { word: "scenic", choices: ["picturesque", "dull", "crowded", "polluted"], correct: "picturesque" },
    { word: "remote", choices: ["isolated", "central", "accessible", "crowded"], correct: "isolated" },
    { word: "departure", choices: ["leaving", "arrival", "delay", "return"], correct: "leaving" },
    { word: "excursion", choices: ["outing", "residence", "delay", "border"], correct: "outing" },
    { word: "vehicle", choices: ["transport", "shelter", "cargo", "terrain"], correct: "transport" },
    { word: "boundary", choices: ["border", "center", "path", "harbor"], correct: "border" },
    { word: "itinerary", choices: ["schedule", "receipt", "ticket", "passport"], correct: "schedule" },
  ],
  homeAndDailyLife: [
    { word: "household", choices: ["domestic", "public", "foreign", "commercial"], correct: "domestic" },
    { word: "renovate", choices: ["remodel", "demolish", "neglect", "vacate"], correct: "remodel" },
    { word: "tidy", choices: ["organized", "cluttered", "messy", "chaotic"], correct: "organized" },
    { word: "routine", choices: ["habit", "surprise", "exception", "accident"], correct: "habit" },
    { word: "upkeep", choices: ["maintenance", "neglect", "abandonment", "damage"], correct: "maintenance" },
    { word: "spacious", choices: ["roomy", "cramped", "narrow", "confined"], correct: "roomy" },
    { word: "cozy", choices: ["comfortable", "harsh", "sterile", "cold"], correct: "comfortable" },
    { word: "chore", choices: ["task", "hobby", "vacation", "reward"], correct: "task" },
    { word: "neighborhood", choices: ["community", "wilderness", "office", "warehouse"], correct: "community" },
    { word: "utility", choices: ["amenity", "obstacle", "burden", "liability"], correct: "amenity" },
  ],
};

export default SYNONYMS_TOPICS_B1B2;
