// Vocabulary category, Synonyms game: B1-B2 level topic sets. Same shape
// as synonymsTopics.js -- [{ word, choices: [4], correct }] -- 10 topics
// (was 7), with the position of `correct` within each entry's `choices`
// array varied rather than clustered at a fixed index.
const SYNONYMS_TOPICS_B1B2 = {
  workAndCareer: [
    { word: "promotion", choices: ["demotion", "resignation", "advancement", "vacation"], correct: "advancement" },
    { word: "colleague", choices: ["coworker", "rival", "client", "supervisor"], correct: "coworker" },
    { word: "deadline", choices: ["holiday", "bonus", "meeting", "due date"], correct: "due date" },
    { word: "qualified", choices: ["unfit", "capable", "inexperienced", "reluctant"], correct: "capable" },
    { word: "resign", choices: ["hire", "promote", "quit", "retain"], correct: "quit" },
    { word: "negotiate", choices: ["bargain", "refuse", "ignore", "surrender"], correct: "bargain" },
    { word: "efficient", choices: ["wasteful", "careless", "slow", "productive"], correct: "productive" },
    { word: "responsibility", choices: ["privilege", "duty", "excuse", "reward"], correct: "duty" },
    { word: "collaborate", choices: ["compete", "isolate", "cooperate", "withdraw"], correct: "cooperate" },
    { word: "achievement", choices: ["accomplishment", "failure", "attempt", "delay"], correct: "accomplishment" },
  ],
  mediaAndTechnology: [
    { word: "innovative", choices: ["outdated", "inventive", "traditional", "ordinary"], correct: "inventive" },
    { word: "reliable", choices: ["faulty", "unpredictable", "temporary", "dependable"], correct: "dependable" },
    { word: "widespread", choices: ["prevalent", "rare", "limited", "occasional"], correct: "prevalent" },
    { word: "influence", choices: ["silence", "absence", "impact", "delay"], correct: "impact" },
    { word: "broadcast", choices: ["conceal", "transmit", "cancel", "delete"], correct: "transmit" },
    { word: "accurate", choices: ["vague", "misleading", "biased", "precise"], correct: "precise" },
    { word: "outdated", choices: ["obsolete", "modern", "current", "advanced"], correct: "obsolete" },
    { word: "convenient", choices: ["awkward", "complicated", "practical", "costly"], correct: "practical" },
    { word: "advertisement", choices: ["review", "promotion", "warning", "report"], correct: "promotion" },
    { word: "subscribe", choices: ["cancel", "unfollow", "block", "sign up"], correct: "sign up" },
  ],
  healthAndWellbeing: [
    { word: "exhausted", choices: ["fatigued", "energetic", "refreshed", "alert"], correct: "fatigued" },
    { word: "recover", choices: ["worsen", "collapse", "heal", "relapse"], correct: "heal" },
    { word: "nutritious", choices: ["processed", "wholesome", "artificial", "empty"], correct: "wholesome" },
    { word: "stressed", choices: ["relaxed", "content", "carefree", "overwhelmed"], correct: "overwhelmed" },
    { word: "symptom", choices: ["sign", "cure", "remedy", "treatment"], correct: "sign" },
    { word: "prevent", choices: ["cause", "encourage", "avoid", "worsen"], correct: "avoid" },
    { word: "vigorous", choices: ["feeble", "energetic", "sluggish", "weary"], correct: "energetic" },
    { word: "chronic", choices: ["temporary", "occasional", "brief", "persistent"], correct: "persistent" },
    { word: "soothe", choices: ["calm", "irritate", "provoke", "alarm"], correct: "calm" },
    { word: "beneficial", choices: ["harmful", "pointless", "helpful", "risky"], correct: "helpful" },
  ],
  moneyAndShopping: [
    { word: "afford", choices: ["waste", "borrow", "lose", "manage"], correct: "manage" },
    { word: "discount", choices: ["increase", "reduction", "fee", "charge"], correct: "reduction" },
    { word: "budget", choices: ["profit", "debt", "spending plan", "salary"], correct: "spending plan" },
    { word: "expensive", choices: ["costly", "cheap", "affordable", "free"], correct: "costly" },
    { word: "purchase", choices: ["return", "sell", "donate", "acquire"], correct: "acquire" },
    { word: "refund", choices: ["charge", "reimbursement", "penalty", "deposit"], correct: "reimbursement" },
    { word: "bargain", choices: ["rip-off", "loan", "good deal", "loss"], correct: "good deal" },
    { word: "invest", choices: ["commit funds", "spend carelessly", "borrow", "donate"], correct: "commit funds" },
    { word: "economical", choices: ["wasteful", "extravagant", "pricey", "cost-effective"], correct: "cost-effective" },
    { word: "debt", choices: ["savings", "money owed", "income", "profit"], correct: "money owed" },
  ],
  natureAndEnvironment: [
    { word: "pollution", choices: ["purity", "cleanliness", "contamination", "clarity"], correct: "contamination" },
    { word: "sustainable", choices: ["renewable", "limited", "disposable", "temporary"], correct: "renewable" },
    { word: "habitat", choices: ["shelter", "environment", "climate", "territory"], correct: "environment" },
    { word: "endangered", choices: ["abundant", "protected", "thriving", "threatened"], correct: "threatened" },
    { word: "conserve", choices: ["waste", "destroy", "preserve", "consume"], correct: "preserve" },
    { word: "drought", choices: ["dry spell", "flood", "storm", "frost"], correct: "dry spell" },
    { word: "emission", choices: ["absorption", "discharge", "reduction", "storage"], correct: "discharge" },
    { word: "renewable", choices: ["finite", "scarce", "exhaustible", "replenishable"], correct: "replenishable" },
    { word: "biodiversity", choices: ["single species", "extinction", "variety of life", "uniformity"], correct: "variety of life" },
    { word: "erosion", choices: ["wearing away", "buildup", "growth", "formation"], correct: "wearing away" },
  ],
  opinionsAndDebate: [
    { word: "argue", choices: ["agree", "contend", "concede", "accept"], correct: "contend" },
    { word: "persuade", choices: ["discourage", "confuse", "ignore", "convince"], correct: "convince" },
    { word: "controversial", choices: ["disputed", "agreed", "settled", "obvious"], correct: "disputed" },
    { word: "viewpoint", choices: ["fact", "rule", "perspective", "result"], correct: "perspective" },
    { word: "justify", choices: ["criticize", "defend", "deny", "ignore"], correct: "defend" },
    { word: "assume", choices: ["prove", "confirm", "verify", "presume"], correct: "presume" },
    { word: "biased", choices: ["one-sided", "fair", "balanced", "neutral"], correct: "one-sided" },
    { word: "acknowledge", choices: ["deny", "ignore", "admit", "reject"], correct: "admit" },
    { word: "objection", choices: ["agreement", "protest", "approval", "support"], correct: "protest" },
    { word: "compromise", choices: ["victory", "defeat", "conflict", "middle ground"], correct: "middle ground" },
  ],
  communityAndSociety: [
    { word: "diverse", choices: ["varied", "uniform", "identical", "similar"], correct: "varied" },
    { word: "tradition", choices: ["invention", "trend", "custom", "novelty"], correct: "custom" },
    { word: "generation", choices: ["family", "nation", "culture", "age group"], correct: "age group" },
    { word: "volunteer", choices: ["employee", "unpaid helper", "manager", "customer"], correct: "unpaid helper" },
    { word: "community", choices: ["neighborhood", "isolation", "workplace", "market"], correct: "neighborhood" },
    { word: "inequality", choices: ["fairness", "balance", "imbalance", "equality"], correct: "imbalance" },
    { word: "cooperation", choices: ["conflict", "rivalry", "isolation", "teamwork"], correct: "teamwork" },
    { word: "heritage", choices: ["future", "legacy", "invention", "prediction"], correct: "legacy" },
    { word: "charity", choices: ["donation", "profit", "loan", "tax"], correct: "donation" },
    { word: "civic", choices: ["private", "personal", "public", "secret"], correct: "public" },
  ],
  educationAndLearning: [
    { word: "curriculum", choices: ["framework", "syllabus", "exam", "classroom"], correct: "syllabus" },
    { word: "enroll", choices: ["withdraw", "graduate", "register", "skip"], correct: "register" },
    { word: "scholarship", choices: ["debt", "grant", "fee", "fine"], correct: "grant" },
    { word: "lecture", choices: ["talk", "test", "break", "game"], correct: "talk" },
    { word: "tuition", choices: ["allowance", "school fees", "salary", "refund"], correct: "school fees" },
    { word: "graduate", choices: ["enroll", "drop out", "complete studies", "fail"], correct: "complete studies" },
    { word: "literacy", choices: ["ability to read", "inability to write", "numeracy", "fluency"], correct: "ability to read" },
    { word: "discipline", choices: ["chaos", "self-control", "distraction", "rebellion"], correct: "self-control" },
    { word: "mentor", choices: ["rival", "advisor", "student", "stranger"], correct: "advisor" },
    { word: "comprehension", choices: ["confusion", "memorization", "understanding", "repetition"], correct: "understanding" },
  ],
  travelAndTourism: [
    { word: "itinerary", choices: ["ticket", "travel plan", "passport", "visa"], correct: "travel plan" },
    { word: "souvenir", choices: ["keepsake", "luggage", "ticket", "map"], correct: "keepsake" },
    { word: "currency", choices: ["money", "language", "custom", "border"], correct: "money" },
    { word: "excursion", choices: ["delay", "outing", "residence", "border"], correct: "outing" },
    { word: "landmark", choices: ["monument", "suburb", "alley", "warehouse"], correct: "monument" },
    { word: "hospitality", choices: ["rudeness", "welcoming service", "silence", "delay"], correct: "welcoming service" },
    { word: "voyage", choices: ["journey", "pause", "arrival", "departure gate"], correct: "journey" },
    { word: "customs", choices: ["border control", "hotel lobby", "train station", "airport lounge"], correct: "border control" },
    { word: "resort", choices: ["office", "vacation spot", "hospital", "school"], correct: "vacation spot" },
    { word: "jet lag", choices: ["excitement", "travel fatigue", "hunger", "boredom"], correct: "travel fatigue" },
  ],
  relationshipsAndFamily: [
    { word: "affection", choices: ["fondness", "dislike", "indifference", "anger"], correct: "fondness" },
    { word: "reunion", choices: ["separation", "gathering", "argument", "departure"], correct: "gathering" },
    { word: "sibling", choices: ["brother or sister", "cousin", "parent", "neighbor"], correct: "brother or sister" },
    { word: "bond", choices: ["connection", "distance", "conflict", "rivalry"], correct: "connection" },
    { word: "trust", choices: ["suspicion", "confidence", "doubt", "fear"], correct: "confidence" },
    { word: "supportive", choices: ["encouraging", "discouraging", "critical", "distant"], correct: "encouraging" },
    { word: "reconcile", choices: ["argue", "make up", "separate", "ignore"], correct: "make up" },
    { word: "dependent", choices: ["independent", "reliant", "distant", "hostile"], correct: "reliant" },
    { word: "nurture", choices: ["neglect", "raise with care", "ignore", "abandon"], correct: "raise with care" },
    { word: "companionship", choices: ["loneliness", "friendship", "rivalry", "distance"], correct: "friendship" },
  ],
};

export default SYNONYMS_TOPICS_B1B2;
