// Vocabulary category, Synonyms game: B1-B2 level topic sets. Same shape
// as synonymsTopics.js -- [{ word, choices: [4], correct }] -- but the
// topics themselves are DIFFERENT from the A1-A2 set (not just harder
// words under the same topic names), shifting from concrete everyday
// life toward work, media, and social/civic themes appropriate to
// intermediate learners.
const SYNONYMS_TOPICS_B1B2 = {
  workAndCareer: [
    { word: "promotion", choices: ["advancement", "demotion", "resignation", "vacation"], correct: "advancement" },
    { word: "colleague", choices: ["coworker", "rival", "client", "supervisor"], correct: "coworker" },
    { word: "deadline", choices: ["due date", "holiday", "bonus", "meeting"], correct: "due date" },
    { word: "qualified", choices: ["capable", "unfit", "inexperienced", "reluctant"], correct: "capable" },
    { word: "resign", choices: ["quit", "hire", "promote", "retain"], correct: "quit" },
    { word: "negotiate", choices: ["bargain", "refuse", "ignore", "surrender"], correct: "bargain" },
    { word: "efficient", choices: ["productive", "wasteful", "careless", "slow"], correct: "productive" },
    { word: "responsibility", choices: ["duty", "privilege", "excuse", "reward"], correct: "duty" },
    { word: "collaborate", choices: ["cooperate", "compete", "isolate", "withdraw"], correct: "cooperate" },
    { word: "achievement", choices: ["accomplishment", "failure", "attempt", "delay"], correct: "accomplishment" },
  ],
  mediaAndTechnology: [
    { word: "innovative", choices: ["inventive", "outdated", "traditional", "ordinary"], correct: "inventive" },
    { word: "reliable", choices: ["dependable", "faulty", "unpredictable", "temporary"], correct: "dependable" },
    { word: "widespread", choices: ["prevalent", "rare", "limited", "occasional"], correct: "prevalent" },
    { word: "influence", choices: ["impact", "silence", "absence", "delay"], correct: "impact" },
    { word: "broadcast", choices: ["transmit", "conceal", "cancel", "delete"], correct: "transmit" },
    { word: "accurate", choices: ["precise", "vague", "misleading", "biased"], correct: "precise" },
    { word: "outdated", choices: ["obsolete", "modern", "current", "advanced"], correct: "obsolete" },
    { word: "convenient", choices: ["practical", "awkward", "complicated", "costly"], correct: "practical" },
    { word: "advertisement", choices: ["promotion", "review", "warning", "report"], correct: "promotion" },
    { word: "subscribe", choices: ["sign up", "cancel", "unfollow", "block"], correct: "sign up" },
  ],
  healthAndWellbeing: [
    { word: "exhausted", choices: ["fatigued", "energetic", "refreshed", "alert"], correct: "fatigued" },
    { word: "recover", choices: ["heal", "worsen", "collapse", "relapse"], correct: "heal" },
    { word: "nutritious", choices: ["wholesome", "processed", "artificial", "empty"], correct: "wholesome" },
    { word: "stressed", choices: ["overwhelmed", "relaxed", "content", "carefree"], correct: "overwhelmed" },
    { word: "symptom", choices: ["sign", "cure", "remedy", "treatment"], correct: "sign" },
    { word: "prevent", choices: ["avoid", "cause", "encourage", "worsen"], correct: "avoid" },
    { word: "vigorous", choices: ["energetic", "feeble", "sluggish", "weary"], correct: "energetic" },
    { word: "chronic", choices: ["persistent", "temporary", "occasional", "brief"], correct: "persistent" },
    { word: "soothe", choices: ["calm", "irritate", "provoke", "alarm"], correct: "calm" },
    { word: "beneficial", choices: ["helpful", "harmful", "pointless", "risky"], correct: "helpful" },
  ],
  moneyAndShopping: [
    { word: "afford", choices: ["manage", "waste", "borrow", "lose"], correct: "manage" },
    { word: "discount", choices: ["reduction", "increase", "fee", "charge"], correct: "reduction" },
    { word: "budget", choices: ["spending plan", "profit", "debt", "salary"], correct: "spending plan" },
    { word: "expensive", choices: ["costly", "cheap", "affordable", "free"], correct: "costly" },
    { word: "purchase", choices: ["acquire", "return", "sell", "donate"], correct: "acquire" },
    { word: "refund", choices: ["reimbursement", "charge", "penalty", "deposit"], correct: "reimbursement" },
    { word: "bargain", choices: ["good deal", "rip-off", "loan", "loss"], correct: "good deal" },
    { word: "invest", choices: ["commit funds", "spend carelessly", "borrow", "donate"], correct: "commit funds" },
    { word: "economical", choices: ["cost-effective", "wasteful", "extravagant", "pricey"], correct: "cost-effective" },
    { word: "debt", choices: ["money owed", "savings", "income", "profit"], correct: "money owed" },
  ],
  natureAndEnvironment: [
    { word: "pollution", choices: ["contamination", "purity", "cleanliness", "clarity"], correct: "contamination" },
    { word: "sustainable", choices: ["renewable", "limited", "disposable", "temporary"], correct: "renewable" },
    { word: "habitat", choices: ["environment", "shelter", "climate", "territory"], correct: "environment" },
    { word: "endangered", choices: ["threatened", "abundant", "protected", "thriving"], correct: "threatened" },
    { word: "conserve", choices: ["preserve", "waste", "destroy", "consume"], correct: "preserve" },
    { word: "drought", choices: ["dry spell", "flood", "storm", "frost"], correct: "dry spell" },
    { word: "emission", choices: ["discharge", "absorption", "reduction", "storage"], correct: "discharge" },
    { word: "renewable", choices: ["replenishable", "finite", "scarce", "exhaustible"], correct: "replenishable" },
    { word: "biodiversity", choices: ["variety of life", "single species", "extinction", "uniformity"], correct: "variety of life" },
    { word: "erosion", choices: ["wearing away", "buildup", "growth", "formation"], correct: "wearing away" },
  ],
  opinionsAndDebate: [
    { word: "argue", choices: ["contend", "agree", "concede", "accept"], correct: "contend" },
    { word: "persuade", choices: ["convince", "discourage", "confuse", "ignore"], correct: "convince" },
    { word: "controversial", choices: ["disputed", "agreed", "settled", "obvious"], correct: "disputed" },
    { word: "viewpoint", choices: ["perspective", "fact", "rule", "result"], correct: "perspective" },
    { word: "justify", choices: ["defend", "criticize", "deny", "ignore"], correct: "defend" },
    { word: "assume", choices: ["presume", "prove", "confirm", "verify"], correct: "presume" },
    { word: "biased", choices: ["one-sided", "fair", "balanced", "neutral"], correct: "one-sided" },
    { word: "acknowledge", choices: ["admit", "deny", "ignore", "reject"], correct: "admit" },
    { word: "objection", choices: ["protest", "agreement", "approval", "support"], correct: "protest" },
    { word: "compromise", choices: ["middle ground", "victory", "defeat", "conflict"], correct: "middle ground" },
  ],
  communityAndSociety: [
    { word: "diverse", choices: ["varied", "uniform", "identical", "similar"], correct: "varied" },
    { word: "tradition", choices: ["custom", "invention", "trend", "novelty"], correct: "custom" },
    { word: "generation", choices: ["age group", "family", "nation", "culture"], correct: "age group" },
    { word: "volunteer", choices: ["unpaid helper", "employee", "manager", "customer"], correct: "unpaid helper" },
    { word: "community", choices: ["neighborhood", "isolation", "workplace", "market"], correct: "neighborhood" },
    { word: "inequality", choices: ["imbalance", "fairness", "balance", "equality"], correct: "imbalance" },
    { word: "cooperation", choices: ["teamwork", "conflict", "rivalry", "isolation"], correct: "teamwork" },
    { word: "heritage", choices: ["legacy", "future", "invention", "prediction"], correct: "legacy" },
    { word: "charity", choices: ["donation", "profit", "loan", "tax"], correct: "donation" },
    { word: "civic", choices: ["public", "private", "personal", "secret"], correct: "public" },
  ],
};

export default SYNONYMS_TOPICS_B1B2;
