// Vocabulary category, Synonyms game: C1-C2 level topic sets. Same shape
// and same topic keys as synonymsTopics.js (the A1-A2 set), but advanced,
// low-frequency vocabulary and near-synonym distractors that require
// genuine discrimination, appropriate to advanced learners.
const SYNONYMS_TOPICS_C1C2 = {
  feelings: [
    { word: "elated", choices: ["euphoric", "despondent", "apathetic", "wary"], correct: "euphoric" },
    { word: "melancholy", choices: ["wistful", "jubilant", "indifferent", "irate"], correct: "wistful" },
    { word: "indignant", choices: ["outraged", "content", "serene", "nonchalant"], correct: "outraged" },
    { word: "apprehensive", choices: ["trepidatious", "nonchalant", "elated", "complacent"], correct: "trepidatious" },
    { word: "disdainful", choices: ["contemptuous", "admiring", "sympathetic", "affectionate"], correct: "contemptuous" },
    { word: "complacent", choices: ["self-satisfied", "anxious", "restless", "vigilant"], correct: "self-satisfied" },
    { word: "poignant", choices: ["moving", "trivial", "dull", "banal"], correct: "moving" },
    { word: "exasperated", choices: ["vexed", "placated", "amused", "gratified"], correct: "vexed" },
    { word: "wistful", choices: ["nostalgic", "indifferent", "hostile", "elated"], correct: "nostalgic" },
    { word: "resigned", choices: ["reconciled", "defiant", "hopeful", "outraged"], correct: "reconciled" },
  ],
  dailyActions: [
    { word: "reconcile", choices: ["resolve", "provoke", "sabotage", "postpone"], correct: "resolve" },
    { word: "circumvent", choices: ["bypass", "confront", "enforce", "endorse"], correct: "bypass" },
    { word: "substantiate", choices: ["corroborate", "refute", "conceal", "dismiss"], correct: "corroborate" },
    { word: "relinquish", choices: ["surrender", "retain", "seize", "acquire"], correct: "surrender" },
    { word: "expedite", choices: ["accelerate", "hinder", "postpone", "suspend"], correct: "accelerate" },
    { word: "curtail", choices: ["reduce", "expand", "prolong", "amplify"], correct: "reduce" },
    { word: "deliberate", choices: ["ponder", "dismiss", "ignore", "assume"], correct: "ponder" },
    { word: "instigate", choices: ["initiate", "terminate", "suppress", "conclude"], correct: "initiate" },
    { word: "mitigate", choices: ["alleviate", "aggravate", "provoke", "intensify"], correct: "alleviate" },
    { word: "conjecture", choices: ["speculate", "verify", "confirm", "document"], correct: "speculate" },
  ],
  describingPeople: [
    { word: "meticulous", choices: ["punctilious", "careless", "haphazard", "negligent"], correct: "punctilious" },
    { word: "audacious", choices: ["bold", "timid", "docile", "cautious"], correct: "bold" },
    { word: "obstinate", choices: ["intransigent", "compliant", "amenable", "yielding"], correct: "intransigent" },
    { word: "eloquent", choices: ["articulate", "inarticulate", "reticent", "taciturn"], correct: "articulate" },
    { word: "shrewd", choices: ["astute", "naive", "gullible", "oblivious"], correct: "astute" },
    { word: "pretentious", choices: ["affected", "unassuming", "modest", "genuine"], correct: "affected" },
    { word: "benevolent", choices: ["magnanimous", "callous", "vindictive", "spiteful"], correct: "magnanimous" },
    { word: "candid", choices: ["forthright", "evasive", "secretive", "deceptive"], correct: "forthright" },
    { word: "aloof", choices: ["detached", "gregarious", "affectionate", "warm"], correct: "detached" },
    { word: "tenacious", choices: ["persistent", "fickle", "irresolute", "wavering"], correct: "persistent" },
  ],
  describingThings: [
    { word: "ephemeral", choices: ["fleeting", "permanent", "enduring", "perpetual"], correct: "fleeting" },
    { word: "ubiquitous", choices: ["omnipresent", "scarce", "rare", "isolated"], correct: "omnipresent" },
    { word: "ambiguous", choices: ["equivocal", "definitive", "explicit", "unambiguous"], correct: "equivocal" },
    { word: "exacting", choices: ["meticulous", "sloppy", "careless", "slapdash"], correct: "meticulous" },
    { word: "arbitrary", choices: ["capricious", "systematic", "deliberate", "principled"], correct: "capricious" },
    { word: "innate", choices: ["inherent", "acquired", "external", "learned"], correct: "inherent" },
    { word: "superfluous", choices: ["redundant", "essential", "indispensable", "vital"], correct: "redundant" },
    { word: "profound", choices: ["deep", "shallow", "trivial", "superficial"], correct: "deep" },
    { word: "convoluted", choices: ["intricate", "straightforward", "simple", "plain"], correct: "intricate" },
    { word: "resilient", choices: ["robust", "fragile", "brittle", "vulnerable"], correct: "robust" },
  ],
  schoolAndStudy: [
    { word: "synthesize", choices: ["amalgamate", "dissect", "fragment", "isolate"], correct: "amalgamate" },
    { word: "corroborate", choices: ["substantiate", "refute", "contradict", "dispute"], correct: "substantiate" },
    { word: "elucidate", choices: ["clarify", "obscure", "confound", "muddle"], correct: "clarify" },
    { word: "discern", choices: ["perceive", "overlook", "disregard", "ignore"], correct: "perceive" },
    { word: "rigorous", choices: ["stringent", "lax", "lenient", "casual"], correct: "stringent" },
    { word: "postulate", choices: ["hypothesize", "disprove", "confirm", "verify"], correct: "hypothesize" },
    { word: "extrapolate", choices: ["infer", "restate", "quote", "record"], correct: "infer" },
    { word: "refute", choices: ["disprove", "validate", "affirm", "endorse"], correct: "disprove" },
    { word: "concise", choices: ["succinct", "verbose", "rambling", "wordy"], correct: "succinct" },
    { word: "cogent", choices: ["compelling", "unconvincing", "flimsy", "weak"], correct: "compelling" },
  ],
  travelAndPlaces: [
    { word: "sojourn", choices: ["stay", "departure", "exile", "flight"], correct: "stay" },
    { word: "picturesque", choices: ["scenic", "drab", "dreary", "bleak"], correct: "scenic" },
    { word: "secluded", choices: ["isolated", "bustling", "crowded", "populous"], correct: "isolated" },
    { word: "itinerant", choices: ["wandering", "settled", "stationary", "rooted"], correct: "wandering" },
    { word: "expanse", choices: ["stretch", "boundary", "corner", "fragment"], correct: "stretch" },
    { word: "traverse", choices: ["cross", "avoid", "circle", "retreat"], correct: "cross" },
    { word: "cosmopolitan", choices: ["worldly", "provincial", "insular", "parochial"], correct: "worldly" },
    { word: "pristine", choices: ["unspoiled", "polluted", "degraded", "tarnished"], correct: "unspoiled" },
    { word: "vantage point", choices: ["viewpoint", "obstacle", "boundary", "detour"], correct: "viewpoint" },
    { word: "peripheral", choices: ["outlying", "central", "core", "focal"], correct: "outlying" },
  ],
  homeAndDailyLife: [
    { word: "domesticity", choices: ["home life", "wanderlust", "isolation", "exile"], correct: "home life" },
    { word: "mundane", choices: ["ordinary", "extraordinary", "exotic", "remarkable"], correct: "ordinary" },
    { word: "fastidious", choices: ["meticulous", "careless", "slovenly", "sloppy"], correct: "meticulous" },
    { word: "declutter", choices: ["streamline", "accumulate", "hoard", "clutter"], correct: "streamline" },
    { word: "sustenance", choices: ["nourishment", "deprivation", "scarcity", "famine"], correct: "nourishment" },
    { word: "dwelling", choices: ["residence", "workplace", "vehicle", "venue"], correct: "residence" },
    { word: "amenity", choices: ["convenience", "hindrance", "obstacle", "nuisance"], correct: "convenience" },
    { word: "pragmatic", choices: ["practical", "idealistic", "impractical", "whimsical"], correct: "practical" },
    { word: "frugal", choices: ["thrifty", "extravagant", "wasteful", "lavish"], correct: "thrifty" },
    { word: "solitude", choices: ["seclusion", "company", "crowd", "gathering"], correct: "seclusion" },
  ],
};

export default SYNONYMS_TOPICS_C1C2;
