// Vocabulary category, Synonyms game: A1-A2 level topic sets. Same shape
// as before -- [{ word, choices: [4], correct }] -- now 10 topics (was
// 7), and the position of `correct` within each entry's `choices` array
// is varied rather than clustered at one fixed index (the game engine
// already shuffles display order at runtime, but the source data itself
// should not read as a fixed pattern either).
const SYNONYMS_TOPICS = {
  feelings: [
    { word: "happy", choices: ["sad", "tired", "glad", "angry"], correct: "glad" },
    { word: "scared", choices: ["afraid", "excited", "proud", "lazy"], correct: "afraid" },
    { word: "calm", choices: ["noisy", "hungry", "weak", "peaceful"], correct: "peaceful" },
    { word: "angry", choices: ["cheerful", "mad", "shy", "fresh"], correct: "mad" },
    { word: "tired", choices: ["sleepy", "loud", "busy", "brave"], correct: "sleepy" },
    { word: "nervous", choices: ["relaxed", "funny", "anxious", "sweet"], correct: "anxious" },
    { word: "surprised", choices: ["bored", "amazed", "empty", "rude"], correct: "amazed" },
    { word: "upset", choices: ["pleased", "smooth", "active", "unhappy"], correct: "unhappy" },
    { word: "lonely", choices: ["crowded", "bright", "alone", "simple"], correct: "alone" },
    { word: "proud", choices: ["pleased", "ashamed", "broken", "tiny"], correct: "pleased" },
  ],
  dailyActions: [
    { word: "begin", choices: ["stop", "wait", "break", "start"], correct: "start" },
    { word: "help", choices: ["assist", "drop", "hide", "push"], correct: "assist" },
    { word: "finish", choices: ["open", "borrow", "end", "jump"], correct: "end" },
    { word: "ask", choices: ["answer", "question", "forget", "arrive"], correct: "question" },
    { word: "answer", choices: ["shout", "carry", "watch", "reply"], correct: "reply" },
    { word: "buy", choices: ["purchase", "sell", "throw", "miss"], correct: "purchase" },
    { word: "fix", choices: ["damage", "close", "repair", "spell"], correct: "repair" },
    { word: "choose", choices: ["follow", "select", "lose", "lend"], correct: "select" },
    { word: "show", choices: ["hide", "visit", "cook", "display"], correct: "display" },
    { word: "leave", choices: ["depart", "stay", "climb", "wash"], correct: "depart" },
  ],
  describingPeople: [
    { word: "smart", choices: ["quiet", "intelligent", "messy", "sleepy"], correct: "intelligent" },
    { word: "kind", choices: ["rude", "empty", "slow", "nice"], correct: "nice" },
    { word: "brave", choices: ["courageous", "afraid", "noisy", "lazy"], correct: "courageous" },
    { word: "funny", choices: ["serious", "weak", "amusing", "polite"], correct: "amusing" },
    { word: "rich", choices: ["careful", "wealthy", "hungry", "gentle"], correct: "wealthy" },
    { word: "quiet", choices: ["rough", "honest", "lucky", "silent"], correct: "silent" },
    { word: "honest", choices: ["truthful", "clever", "noisy", "sleepy"], correct: "truthful" },
    { word: "friendly", choices: ["cold", "ancient", "welcoming", "tight"], correct: "welcoming" },
    { word: "lazy", choices: ["active", "idle", "shiny", "thirsty"], correct: "idle" },
    { word: "rude", choices: ["cheerful", "tidy", "simple", "impolite"], correct: "impolite" },
  ],
  describingThings: [
    { word: "big", choices: ["short", "cold", "large", "weak"], correct: "large" },
    { word: "easy", choices: ["simple", "deep", "dry", "bright"], correct: "simple" },
    { word: "fast", choices: ["heavy", "old", "rough", "quick"], correct: "quick" },
    { word: "small", choices: ["sweet", "tiny", "early", "smooth"], correct: "tiny" },
    { word: "hard", choices: ["fresh", "narrow", "difficult", "noisy"], correct: "difficult" },
    { word: "clean", choices: ["tidy", "thick", "wild", "nervous"], correct: "tidy" },
    { word: "dirty", choices: ["proud", "soft", "hungry", "messy"], correct: "messy" },
    { word: "bright", choices: ["weak", "shiny", "bitter", "empty"], correct: "shiny" },
    { word: "quiet", choices: ["large", "broken", "silent", "sour"], correct: "silent" },
    { word: "strong", choices: ["powerful", "lucky", "pale", "gentle"], correct: "powerful" },
  ],
  schoolAndStudy: [
    { word: "test", choices: ["meal", "street", "chair", "exam"], correct: "exam" },
    { word: "idea", choices: ["driver", "thought", "lesson", "window"], correct: "thought" },
    { word: "correct", choices: ["right", "late", "bitter", "dirty"], correct: "right" },
    { word: "student", choices: ["office", "writer", "pupil", "cousin"], correct: "pupil" },
    { word: "teacher", choices: ["baker", "neighbor", "pilot", "instructor"], correct: "instructor" },
    { word: "answer", choices: ["corner", "reply", "bottle", "ticket"], correct: "reply" },
    { word: "lesson", choices: ["class", "mirror", "pocket", "traffic"], correct: "class" },
    { word: "mistake", choices: ["prize", "bridge", "error", "vacation"], correct: "error" },
    { word: "question", choices: ["blanket", "wallet", "station", "query"], correct: "query" },
    { word: "learn", choices: ["borrow", "study", "whisper", "travel"], correct: "study" },
  ],
  travelAndPlaces: [
    { word: "trip", choices: ["journey", "classroom", "wallet", "dinner"], correct: "journey" },
    { word: "near", choices: ["tall", "sweet", "close", "empty"], correct: "close" },
    { word: "place", choices: ["weather", "location", "pocket", "mirror"], correct: "location" },
    { word: "far", choices: ["tiny", "salty", "noisy", "distant"], correct: "distant" },
    { word: "road", choices: ["street", "lesson", "spoon", "pillow"], correct: "street" },
    { word: "map", choices: ["plant", "jacket", "guide", "ladder"], correct: "guide" },
    { word: "hotel", choices: ["cave", "inn", "desk", "meal"], correct: "inn" },
    { word: "city", choices: ["pencil", "cookie", "shower", "town"], correct: "town" },
    { word: "arrive", choices: ["reach", "borrow", "fix", "imagine"], correct: "reach" },
    { word: "depart", choices: ["taste", "wave", "leave", "measure"], correct: "leave" },
  ],
  homeAndDailyLife: [
    { word: "home", choices: ["market", "house", "beach", "office"], correct: "house" },
    { word: "room", choices: ["train", "cloud", "salad", "space"], correct: "space" },
    { word: "clean", choices: ["bitter", "broken", "tidy", "narrow"], correct: "tidy" },
    { word: "dirty", choices: ["messy", "patient", "early", "smooth"], correct: "messy" },
    { word: "kitchen", choices: ["classroom", "cooking area", "garden", "station"], correct: "cooking area" },
    { word: "sofa", choices: ["shelf", "mirror", "blanket", "couch"], correct: "couch" },
    { word: "job", choices: ["holiday", "answer", "work", "storm"], correct: "work" },
    { word: "rest", choices: ["relax", "shout", "hurry", "repair"], correct: "relax" },
    { word: "chore", choices: ["movie", "task", "river", "pillow"], correct: "task" },
    { word: "quiet", choices: ["spicy", "clever", "expensive", "peaceful"], correct: "peaceful" },
  ],
  foodAndCooking: [
    { word: "tasty", choices: ["delicious", "bitter", "raw", "stale"], correct: "delicious" },
    { word: "cook", choices: ["boil", "prepare", "freeze", "waste"], correct: "prepare" },
    { word: "slice", choices: ["mix", "peel", "cut", "pour"], correct: "cut" },
    { word: "meal", choices: ["snack", "recipe", "kitchen", "dish"], correct: "dish" },
    { word: "fresh", choices: ["ripe", "rotten", "frozen", "dry"], correct: "ripe" },
    { word: "hungry", choices: ["full", "starving", "thirsty", "tired"], correct: "starving" },
    { word: "mix", choices: ["separate", "pour", "combine", "heat"], correct: "combine" },
    { word: "sweet", choices: ["sour", "salty", "bitter", "sugary"], correct: "sugary" },
    { word: "boil", choices: ["heat", "cool", "freeze", "chop"], correct: "heat" },
    { word: "serve", choices: ["hide", "present", "waste", "store"], correct: "present" },
  ],
  weatherAndSeasons: [
    { word: "sunny", choices: ["bright", "cloudy", "rainy", "cold"], correct: "bright" },
    { word: "cold", choices: ["warm", "chilly", "hot", "mild"], correct: "chilly" },
    { word: "rain", choices: ["snow", "shower", "wind", "fog"], correct: "shower" },
    { word: "storm", choices: ["breeze", "calm", "tempest", "mist"], correct: "tempest" },
    { word: "windy", choices: ["still", "breezy", "damp", "humid"], correct: "breezy" },
    { word: "hot", choices: ["cool", "cold", "warm", "icy"], correct: "warm" },
    { word: "season", choices: ["holiday", "month", "period", "week"], correct: "period" },
    { word: "cloudy", choices: ["clear", "sunny", "bright", "overcast"], correct: "overcast" },
    { word: "dry", choices: ["wet", "damp", "arid", "humid"], correct: "arid" },
    { word: "foggy", choices: ["misty", "clear", "bright", "sunny"], correct: "misty" },
  ],
  hobbiesAndFreeTime: [
    { word: "hobby", choices: ["pastime", "chore", "job", "duty"], correct: "pastime" },
    { word: "relax", choices: ["work", "unwind", "hurry", "rush"], correct: "unwind" },
    { word: "enjoy", choices: ["dislike", "hate", "like", "avoid"], correct: "like" },
    { word: "paint", choices: ["cook", "draw", "clean", "write"], correct: "draw" },
    { word: "collect", choices: ["waste", "gather", "lose", "sell"], correct: "gather" },
    { word: "play", choices: ["watch", "study", "perform", "rest"], correct: "perform" },
    { word: "watch", choices: ["view", "ignore", "break", "sell"], correct: "view" },
    { word: "draw", choices: ["sketch", "erase", "paint", "fold"], correct: "sketch" },
    { word: "dance", choices: ["move", "sit", "sleep", "stand"], correct: "move" },
    { word: "travel", choices: ["stay", "explore", "sleep", "work"], correct: "explore" },
  ],
};

export default SYNONYMS_TOPICS;
