// Vocabulary category, Synonyms game: topic sets beyond the sample.
// Same shape as synonymsGameData.js -- [{ word, choices: [4], correct }].
const SYNONYMS_TOPICS = {
  feelings: [
    { word: "happy", choices: ["sad", "glad", "tired", "angry"], correct: "glad" },
    { word: "scared", choices: ["excited", "afraid", "proud", "lazy"], correct: "afraid" },
    { word: "calm", choices: ["noisy", "peaceful", "hungry", "weak"], correct: "peaceful" },
    { word: "angry", choices: ["cheerful", "mad", "shy", "fresh"], correct: "mad" },
    { word: "tired", choices: ["sleepy", "loud", "busy", "brave"], correct: "sleepy" },
    { word: "nervous", choices: ["relaxed", "anxious", "funny", "sweet"], correct: "anxious" },
    { word: "surprised", choices: ["bored", "amazed", "empty", "rude"], correct: "amazed" },
    { word: "upset", choices: ["pleased", "unhappy", "smooth", "active"], correct: "unhappy" },
    { word: "lonely", choices: ["crowded", "alone", "bright", "simple"], correct: "alone" },
    { word: "proud", choices: ["ashamed", "pleased", "broken", "tiny"], correct: "pleased" },
  ],
  dailyActions: [
    { word: "begin", choices: ["stop", "start", "wait", "break"], correct: "start" },
    { word: "help", choices: ["drop", "assist", "hide", "push"], correct: "assist" },
    { word: "finish", choices: ["open", "end", "borrow", "jump"], correct: "end" },
    { word: "ask", choices: ["answer", "question", "forget", "arrive"], correct: "question" },
    { word: "answer", choices: ["shout", "reply", "carry", "watch"], correct: "reply" },
    { word: "buy", choices: ["sell", "purchase", "throw", "miss"], correct: "purchase" },
    { word: "fix", choices: ["damage", "repair", "close", "spell"], correct: "repair" },
    { word: "choose", choices: ["select", "follow", "lose", "lend"], correct: "select" },
    { word: "show", choices: ["hide", "display", "visit", "cook"], correct: "display" },
    { word: "leave", choices: ["stay", "depart", "climb", "wash"], correct: "depart" },
  ],
  describingPeople: [
    { word: "smart", choices: ["quiet", "messy", "intelligent", "sleepy"], correct: "intelligent" },
    { word: "kind", choices: ["rude", "nice", "empty", "slow"], correct: "nice" },
    { word: "brave", choices: ["afraid", "courageous", "noisy", "lazy"], correct: "courageous" },
    { word: "funny", choices: ["serious", "amusing", "weak", "polite"], correct: "amusing" },
    { word: "rich", choices: ["wealthy", "careful", "hungry", "gentle"], correct: "wealthy" },
    { word: "quiet", choices: ["silent", "rough", "honest", "lucky"], correct: "silent" },
    { word: "honest", choices: ["truthful", "clever", "noisy", "sleepy"], correct: "truthful" },
    { word: "friendly", choices: ["cold", "welcoming", "ancient", "tight"], correct: "welcoming" },
    { word: "lazy", choices: ["active", "idle", "shiny", "thirsty"], correct: "idle" },
    { word: "rude", choices: ["impolite", "cheerful", "tidy", "simple"], correct: "impolite" },
  ],
  describingThings: [
    { word: "big", choices: ["large", "short", "cold", "weak"], correct: "large" },
    { word: "easy", choices: ["simple", "deep", "dry", "bright"], correct: "simple" },
    { word: "fast", choices: ["quick", "heavy", "old", "rough"], correct: "quick" },
    { word: "small", choices: ["tiny", "sweet", "early", "smooth"], correct: "tiny" },
    { word: "hard", choices: ["difficult", "fresh", "narrow", "noisy"], correct: "difficult" },
    { word: "clean", choices: ["tidy", "thick", "wild", "nervous"], correct: "tidy" },
    { word: "dirty", choices: ["messy", "proud", "soft", "hungry"], correct: "messy" },
    { word: "bright", choices: ["shiny", "weak", "bitter", "empty"], correct: "shiny" },
    { word: "quiet", choices: ["silent", "large", "broken", "sour"], correct: "silent" },
    { word: "strong", choices: ["powerful", "lucky", "pale", "gentle"], correct: "powerful" },
  ],
  schoolAndStudy: [
    { word: "test", choices: ["meal", "exam", "street", "chair"], correct: "exam" },
    { word: "idea", choices: ["thought", "driver", "lesson", "window"], correct: "thought" },
    { word: "correct", choices: ["right", "late", "bitter", "dirty"], correct: "right" },
    { word: "student", choices: ["pupil", "office", "writer", "cousin"], correct: "pupil" },
    { word: "teacher", choices: ["instructor", "baker", "neighbor", "pilot"], correct: "instructor" },
    { word: "answer", choices: ["reply", "corner", "bottle", "ticket"], correct: "reply" },
    { word: "lesson", choices: ["class", "mirror", "pocket", "traffic"], correct: "class" },
    { word: "mistake", choices: ["error", "prize", "bridge", "vacation"], correct: "error" },
    { word: "question", choices: ["query", "blanket", "wallet", "station"], correct: "query" },
    { word: "learn", choices: ["study", "borrow", "whisper", "travel"], correct: "study" },
  ],
  travelAndPlaces: [
    { word: "trip", choices: ["journey", "classroom", "wallet", "dinner"], correct: "journey" },
    { word: "near", choices: ["close", "tall", "sweet", "empty"], correct: "close" },
    { word: "place", choices: ["location", "weather", "pocket", "mirror"], correct: "location" },
    { word: "far", choices: ["distant", "tiny", "salty", "noisy"], correct: "distant" },
    { word: "road", choices: ["street", "lesson", "spoon", "pillow"], correct: "street" },
    { word: "map", choices: ["guide", "plant", "jacket", "ladder"], correct: "guide" },
    { word: "hotel", choices: ["inn", "cave", "desk", "meal"], correct: "inn" },
    { word: "city", choices: ["town", "pencil", "cookie", "shower"], correct: "town" },
    { word: "arrive", choices: ["reach", "borrow", "fix", "imagine"], correct: "reach" },
    { word: "depart", choices: ["leave", "taste", "wave", "measure"], correct: "leave" },
  ],
  homeAndDailyLife: [
    { word: "home", choices: ["house", "market", "beach", "office"], correct: "house" },
    { word: "room", choices: ["space", "train", "cloud", "salad"], correct: "space" },
    { word: "clean", choices: ["tidy", "bitter", "broken", "narrow"], correct: "tidy" },
    { word: "dirty", choices: ["messy", "patient", "early", "smooth"], correct: "messy" },
    { word: "kitchen", choices: ["cooking area", "classroom", "garden", "station"], correct: "cooking area" },
    { word: "sofa", choices: ["couch", "shelf", "mirror", "blanket"], correct: "couch" },
    { word: "job", choices: ["work", "holiday", "answer", "storm"], correct: "work" },
    { word: "rest", choices: ["relax", "shout", "hurry", "repair"], correct: "relax" },
    { word: "chore", choices: ["task", "movie", "river", "pillow"], correct: "task" },
    { word: "quiet", choices: ["peaceful", "spicy", "clever", "expensive"], correct: "peaceful" },
  ],
};

export default SYNONYMS_TOPICS;
