// Vocabulary category, Synonyms game: C1-C2 level topic sets. Same shape
// as synonymsTopics.js -- [{ word, choices: [4], correct }] -- but the
// topics themselves are DIFFERENT from both the A1-A2 and B1-B2 sets,
// shifting toward abstract, academic, and global-discourse themes with
// advanced, low-frequency vocabulary and near-synonym distractors that
// require genuine discrimination, appropriate to advanced learners.
const SYNONYMS_TOPICS_C1C2 = {
  businessAndEconomics: [
    { word: "lucrative", choices: ["profitable", "unprofitable", "stagnant", "insolvent"], correct: "profitable" },
    { word: "diversify", choices: ["broaden", "narrow", "consolidate", "restrict"], correct: "broaden" },
    { word: "insolvent", choices: ["bankrupt", "prosperous", "solvent", "thriving"], correct: "bankrupt" },
    { word: "stagnant", choices: ["sluggish", "booming", "dynamic", "flourishing"], correct: "sluggish" },
    { word: "monopoly", choices: ["exclusive control", "fair competition", "shared market", "open trade"], correct: "exclusive control" },
    { word: "subsidize", choices: ["fund", "tax", "withhold", "penalize"], correct: "fund" },
    { word: "volatile", choices: ["unstable", "steady", "predictable", "constant"], correct: "unstable" },
    { word: "austerity", choices: ["cost-cutting", "extravagance", "expansion", "surplus"], correct: "cost-cutting" },
    { word: "commodity", choices: ["tradeable good", "service", "currency", "asset class"], correct: "tradeable good" },
    { word: "leverage", choices: ["borrowed capital", "personal savings", "pure profit", "tax refund"], correct: "borrowed capital" },
  ],
  politicsAndGovernance: [
    { word: "legislation", choices: ["law", "opinion", "custom", "rumor"], correct: "law" },
    { word: "sovereignty", choices: ["self-governance", "dependency", "occupation", "colonization"], correct: "self-governance" },
    { word: "diplomacy", choices: ["negotiation", "conflict", "invasion", "isolation"], correct: "negotiation" },
    { word: "coalition", choices: ["alliance", "rivalry", "opposition", "division"], correct: "alliance" },
    { word: "corruption", choices: ["dishonesty", "integrity", "transparency", "fairness"], correct: "dishonesty" },
    { word: "referendum", choices: ["public vote", "private meeting", "court ruling", "royal decree"], correct: "public vote" },
    { word: "bureaucracy", choices: ["administration", "anarchy", "monarchy", "democracy"], correct: "administration" },
    { word: "dissent", choices: ["disagreement", "consensus", "approval", "conformity"], correct: "disagreement" },
    { word: "autonomous", choices: ["self-ruling", "dependent", "controlled", "subordinate"], correct: "self-ruling" },
    { word: "mandate", choices: ["authorization", "rejection", "suggestion", "request"], correct: "authorization" },
  ],
  scienceAndInnovation: [
    { word: "hypothesis", choices: ["theory", "fact", "law", "conclusion"], correct: "theory" },
    { word: "empirical", choices: ["evidence-based", "theoretical", "speculative", "hypothetical"], correct: "evidence-based" },
    { word: "innovation", choices: ["breakthrough", "stagnation", "repetition", "tradition"], correct: "breakthrough" },
    { word: "catalyst", choices: ["trigger", "obstacle", "byproduct", "residue"], correct: "trigger" },
    { word: "anomaly", choices: ["irregularity", "pattern", "norm", "standard"], correct: "irregularity" },
    { word: "synthesis", choices: ["combination", "separation", "division", "isolation"], correct: "combination" },
    { word: "obsolete", choices: ["outdated", "cutting-edge", "modern", "current"], correct: "outdated" },
    { word: "prototype", choices: ["model", "finished product", "byproduct", "flaw"], correct: "model" },
    { word: "viable", choices: ["workable", "impossible", "disposable", "short-lived"], correct: "workable" },
    { word: "replicate", choices: ["reproduce", "invent", "discard", "alter"], correct: "reproduce" },
  ],
  artsAndCulture: [
    { word: "aesthetic", choices: ["artistic", "functional", "practical", "mundane"], correct: "artistic" },
    { word: "avant-garde", choices: ["experimental", "conventional", "traditional", "classical"], correct: "experimental" },
    { word: "eclectic", choices: ["diverse", "uniform", "narrow", "monotonous"], correct: "diverse" },
    { word: "provocative", choices: ["thought-provoking", "dull", "predictable", "bland"], correct: "thought-provoking" },
    { word: "renowned", choices: ["celebrated", "obscure", "unknown", "forgotten"], correct: "celebrated" },
    { word: "authentic", choices: ["genuine", "counterfeit", "imitation", "artificial"], correct: "genuine" },
    { word: "narrative", choices: ["storyline", "setting", "genre", "critique"], correct: "storyline" },
    { word: "satirical", choices: ["mocking", "sincere", "reverent", "solemn"], correct: "mocking" },
    { word: "nuanced", choices: ["subtle", "obvious", "blunt", "crude"], correct: "subtle" },
    { word: "timeless", choices: ["enduring", "fleeting", "dated", "trendy"], correct: "enduring" },
  ],
  ethicsAndPhilosophy: [
    { word: "integrity", choices: ["honesty", "deceit", "corruption", "hypocrisy"], correct: "honesty" },
    { word: "dilemma", choices: ["predicament", "solution", "certainty", "resolution"], correct: "predicament" },
    { word: "virtue", choices: ["moral goodness", "vice", "flaw", "weakness"], correct: "moral goodness" },
    { word: "hypocrisy", choices: ["pretense", "sincerity", "honesty", "consistency"], correct: "pretense" },
    { word: "autonomy", choices: ["self-determination", "dependency", "obedience", "conformity"], correct: "self-determination" },
    { word: "utilitarian", choices: ["practical-minded", "idealistic", "sentimental", "romantic"], correct: "practical-minded" },
    { word: "subjective", choices: ["personal", "objective", "universal", "factual"], correct: "personal" },
    { word: "coerce", choices: ["force", "persuade gently", "invite", "welcome"], correct: "force" },
    { word: "altruism", choices: ["selflessness", "selfishness", "greed", "vanity"], correct: "selflessness" },
    { word: "ambivalent", choices: ["conflicted", "certain", "decisive", "resolute"], correct: "conflicted" },
  ],
  globalAffairs: [
    { word: "globalization", choices: ["worldwide integration", "isolationism", "nationalism", "protectionism"], correct: "worldwide integration" },
    { word: "humanitarian", choices: ["relief-focused", "military", "commercial", "political"], correct: "relief-focused" },
    { word: "displacement", choices: ["forced relocation", "settlement", "migration by choice", "expansion"], correct: "forced relocation" },
    { word: "sanctions", choices: ["penalties", "rewards", "alliances", "treaties"], correct: "penalties" },
    { word: "refugee", choices: ["displaced person", "tourist", "immigrant by choice", "diplomat"], correct: "displaced person" },
    { word: "summit", choices: ["high-level meeting", "protest", "election", "ceremony"], correct: "high-level meeting" },
    { word: "treaty", choices: ["formal agreement", "informal chat", "rumor", "threat"], correct: "formal agreement" },
    { word: "instability", choices: ["unrest", "peace", "order", "stability"], correct: "unrest" },
    { word: "intervention", choices: ["involvement", "withdrawal", "neutrality", "avoidance"], correct: "involvement" },
    { word: "diaspora", choices: ["scattered population", "native population", "single tribe", "isolated village"], correct: "scattered population" },
  ],
  psychologyAndBehavior: [
    { word: "cognition", choices: ["thinking", "feeling", "acting", "resting"], correct: "thinking" },
    { word: "resilience", choices: ["toughness", "fragility", "weakness", "vulnerability"], correct: "toughness" },
    { word: "introspection", choices: ["self-reflection", "distraction", "denial", "avoidance"], correct: "self-reflection" },
    { word: "impulsive", choices: ["spontaneous", "cautious", "deliberate", "methodical"], correct: "spontaneous" },
    { word: "empathy", choices: ["compassion", "indifference", "hostility", "apathy"], correct: "compassion" },
    { word: "cognitive bias", choices: ["mental shortcut", "logical proof", "factual error", "random guess"], correct: "mental shortcut" },
    { word: "subconscious", choices: ["unconscious mind", "conscious thought", "spoken word", "physical action"], correct: "unconscious mind" },
    { word: "gratification", choices: ["satisfaction", "frustration", "disappointment", "deprivation"], correct: "satisfaction" },
    { word: "temperament", choices: ["disposition", "appearance", "intelligence", "skill"], correct: "disposition" },
    { word: "rationalize", choices: ["justify", "confess", "deny", "regret"], correct: "justify" },
  ],
};

export default SYNONYMS_TOPICS_C1C2;
