// Vocabulary category, Word Sort game: 5 category packs.
// Each pack: { key, title, categoryA, categoryB, items: [{ word, category }] }
// category values match categoryA or categoryB exactly.
const WORD_SORT_PACKS = [
  {
    key: "food-drink",
    title: "Food vs Drink",
    categoryA: "Food",
    categoryB: "Drink",
    items: [
      { word: "apple", category: "Food" },
      { word: "bread", category: "Food" },
      { word: "rice", category: "Food" },
      { word: "soup", category: "Food" },
      { word: "egg", category: "Food" },
      { word: "milk", category: "Drink" },
      { word: "water", category: "Drink" },
      { word: "juice", category: "Drink" },
      { word: "tea", category: "Drink" },
      { word: "coffee", category: "Drink" },
    ],
  },
  {
    key: "school-travel",
    title: "School vs Travel",
    categoryA: "School",
    categoryB: "Travel",
    items: [
      { word: "teacher", category: "School" },
      { word: "student", category: "School" },
      { word: "homework", category: "School" },
      { word: "classroom", category: "School" },
      { word: "exam", category: "School" },
      { word: "passport", category: "Travel" },
      { word: "hotel", category: "Travel" },
      { word: "ticket", category: "Travel" },
      { word: "airport", category: "Travel" },
      { word: "suitcase", category: "Travel" },
    ],
  },
  {
    key: "home-outside",
    title: "Home vs Outside",
    categoryA: "Home",
    categoryB: "Outside",
    items: [
      { word: "sofa", category: "Home" },
      { word: "kitchen", category: "Home" },
      { word: "bedroom", category: "Home" },
      { word: "table", category: "Home" },
      { word: "pillow", category: "Home" },
      { word: "park", category: "Outside" },
      { word: "street", category: "Outside" },
      { word: "garden", category: "Outside" },
      { word: "bus stop", category: "Outside" },
      { word: "beach", category: "Outside" },
    ],
  },
  {
    key: "feelings-actions",
    title: "Feelings vs Actions",
    categoryA: "Feelings",
    categoryB: "Actions",
    items: [
      { word: "happy", category: "Feelings" },
      { word: "sad", category: "Feelings" },
      { word: "angry", category: "Feelings" },
      { word: "scared", category: "Feelings" },
      { word: "tired", category: "Feelings" },
      { word: "run", category: "Actions" },
      { word: "jump", category: "Actions" },
      { word: "write", category: "Actions" },
      { word: "eat", category: "Actions" },
      { word: "open", category: "Actions" },
    ],
  },
  {
    key: "people-places",
    title: "People vs Places",
    categoryA: "People",
    categoryB: "Places",
    items: [
      { word: "doctor", category: "People" },
      { word: "teacher", category: "People" },
      { word: "friend", category: "People" },
      { word: "driver", category: "People" },
      { word: "student", category: "People" },
      { word: "hospital", category: "Places" },
      { word: "school", category: "Places" },
      { word: "market", category: "Places" },
      { word: "library", category: "Places" },
      { word: "restaurant", category: "Places" },
    ],
  },
  {
    key: "work-freetime",
    title: "Work vs Free Time",
    level: "Adult Intermediate",
    categoryA: "Work",
    categoryB: "Free Time",
    items: [
      { word: "meeting", category: "Work" },
      { word: "deadline", category: "Work" },
      { word: "colleague", category: "Work" },
      { word: "commute", category: "Work" },
      { word: "promotion", category: "Work" },
      { word: "hobby", category: "Free Time" },
      { word: "weekend", category: "Free Time" },
      { word: "exercise", category: "Free Time" },
      { word: "concert", category: "Free Time" },
      { word: "videogame", category: "Free Time" },
    ],
  },
  {
    key: "travel-technology",
    title: "Travel vs Technology",
    level: "Adult Intermediate",
    categoryA: "Travel",
    categoryB: "Technology",
    items: [
      { word: "luggage", category: "Travel" },
      { word: "sightseeing", category: "Travel" },
      { word: "hostel", category: "Travel" },
      { word: "visa", category: "Travel" },
      { word: "itinerary", category: "Travel" },
      { word: "app", category: "Technology" },
      { word: "password", category: "Technology" },
      { word: "update", category: "Technology" },
      { word: "Wi-Fi", category: "Technology" },
      { word: "notification", category: "Technology" },
    ],
  },
  {
    key: "money-shopping",
    title: "Money vs Shopping",
    level: "Adult Intermediate",
    categoryA: "Money",
    categoryB: "Shopping",
    items: [
      { word: "budget", category: "Money" },
      { word: "salary", category: "Money" },
      { word: "debt", category: "Money" },
      { word: "savings", category: "Money" },
      { word: "bill", category: "Money" },
      { word: "discount", category: "Shopping" },
      { word: "receipt", category: "Shopping" },
      { word: "refund", category: "Shopping" },
      { word: "customer", category: "Shopping" },
      { word: "checkout", category: "Shopping" },
    ],
  },
  {
    key: "health-lifestyle",
    title: "Health vs Lifestyle",
    level: "Adult Intermediate",
    categoryA: "Health",
    categoryB: "Lifestyle",
    items: [
      { word: "headache", category: "Health" },
      { word: "check-up", category: "Health" },
      { word: "prescription", category: "Health" },
      { word: "symptom", category: "Health" },
      { word: "stress", category: "Health" },
      { word: "routine", category: "Lifestyle" },
      { word: "habit", category: "Lifestyle" },
      { word: "balance", category: "Lifestyle" },
      { word: "diet", category: "Lifestyle" },
      { word: "bedtime", category: "Lifestyle" },
    ],
  },
  {
    key: "relationships-personality",
    title: "Relationships vs Personality",
    level: "Adult Intermediate",
    categoryA: "Relationships",
    categoryB: "Personality",
    items: [
      { word: "partner", category: "Relationships" },
      { word: "colleague", category: "Relationships" },
      { word: "neighbor", category: "Relationships" },
      { word: "classmate", category: "Relationships" },
      { word: "friend", category: "Relationships" },
      { word: "introvert", category: "Personality" },
      { word: "extrovert", category: "Personality" },
      { word: "ambivert", category: "Personality" },
      { word: "optimistic", category: "Personality" },
      { word: "shy", category: "Personality" },
    ],
  },
];

export default WORD_SORT_PACKS;
