// Vocabulary category, Word Sort game: 5 category packs.
// Each pack: { key, title, categoryA, categoryB, items: [{ word, category }] }
// category values match categoryA or categoryB exactly.
const WORD_SORT_PACKS = [
  {
    key: "food-drink",
    title: "Food vs Drink",
    categoryA: "Food",
    categoryB: "Drink",
    items: [
      { word: "apple", category: "Food" },
      { word: "bread", category: "Food" },
      { word: "rice", category: "Food" },
      { word: "soup", category: "Food" },
      { word: "egg", category: "Food" },
      { word: "milk", category: "Drink" },
      { word: "water", category: "Drink" },
      { word: "juice", category: "Drink" },
      { word: "tea", category: "Drink" },
      { word: "coffee", category: "Drink" },
    ],
  },
  {
    key: "school-travel",
    title: "School vs Travel",
    categoryA: "School",
    categoryB: "Travel",
    items: [
      { word: "teacher", category: "School" },
      { word: "student", category: "School" },
      { word: "homework", category: "School" },
      { word: "classroom", category: "School" },
      { word: "exam", category: "School" },
      { word: "passport", category: "Travel" },
      { word: "hotel", category: "Travel" },
      { word: "ticket", category: "Travel" },
      { word: "airport", category: "Travel" },
      { word: "suitcase", category: "Travel" },
    ],
  },
  {
    key: "home-outside",
    title: "Home vs Outside",
    categoryA: "Home",
    categoryB: "Outside",
    items: [
      { word: "sofa", category: "Home" },
      { word: "kitchen", category: "Home" },
      { word: "bedroom", category: "Home" },
      { word: "table", category: "Home" },
      { word: "pillow", category: "Home" },
      { word: "park", category: "Outside" },
      { word: "street", category: "Outside" },
      { word: "garden", category: "Outside" },
      { word: "bus stop", category: "Outside" },
      { word: "beach", category: "Outside" },
    ],
  },
  {
    key: "feelings-actions",
    title: "Feelings vs Actions",
    categoryA: "Feelings",
    categoryB: "Actions",
    items: [
      { word: "happy", category: "Feelings" },
      { word: "sad", category: "Feelings" },
      { word: "angry", category: "Feelings" },
      { word: "scared", category: "Feelings" },
      { word: "tired", category: "Feelings" },
      { word: "run", category: "Actions" },
      { word: "jump", category: "Actions" },
      { word: "write", category: "Actions" },
      { word: "eat", category: "Actions" },
      { word: "open", category: "Actions" },
    ],
  },
  {
    key: "people-places",
    title: "People vs Places",
    categoryA: "People",
    categoryB: "Places",
    items: [
      { word: "doctor", category: "People" },
      { word: "teacher", category: "People" },
      { word: "friend", category: "People" },
      { word: "driver", category: "People" },
      { word: "student", category: "People" },
      { word: "hospital", category: "Places" },
      { word: "school", category: "Places" },
      { word: "market", category: "Places" },
      { word: "library", category: "Places" },
      { word: "restaurant", category: "Places" },
    ],
  },
];

export default WORD_SORT_PACKS;
