// Vocabulary category, Word Sort game: 30 category-pair packs, 10 per
// CEFR level (A1-A2, B1-B2, C1-C2), matching the level-tab structure
// used by Synonyms/Antonyms. Each pack: { key, title, cefrGroup,
// categoryA, categoryB, items: [{ word, category }] } -- category
// values match categoryA or categoryB exactly, 5 words per side.
const WORD_SORT_PACKS = [
  // ---------- A1-A2 (10 packs) ----------
  {
    key: "food-drink",
    title: "Food vs Drink",
    cefrGroup: "A1-A2",
    categoryA: "Food",
    categoryB: "Drink",
    items: [
      { word: "apple", category: "Food" },
      { word: "bread", category: "Food" },
      { word: "rice", category: "Food" },
      { word: "soup", category: "Food" },
      { word: "egg", category: "Food" },
      { word: "milk", category: "Drink" },
      { word: "water", category: "Drink" },
      { word: "juice", category: "Drink" },
      { word: "tea", category: "Drink" },
      { word: "coffee", category: "Drink" },
    ],
  },
  {
    key: "school-travel",
    title: "School vs Travel",
    cefrGroup: "A1-A2",
    categoryA: "School",
    categoryB: "Travel",
    items: [
      { word: "teacher", category: "School" },
      { word: "student", category: "School" },
      { word: "homework", category: "School" },
      { word: "classroom", category: "School" },
      { word: "exam", category: "School" },
      { word: "passport", category: "Travel" },
      { word: "hotel", category: "Travel" },
      { word: "ticket", category: "Travel" },
      { word: "airport", category: "Travel" },
      { word: "suitcase", category: "Travel" },
    ],
  },
  {
    key: "home-outside",
    title: "Home vs Outside",
    cefrGroup: "A1-A2",
    categoryA: "Home",
    categoryB: "Outside",
    items: [
      { word: "sofa", category: "Home" },
      { word: "kitchen", category: "Home" },
      { word: "bedroom", category: "Home" },
      { word: "table", category: "Home" },
      { word: "pillow", category: "Home" },
      { word: "park", category: "Outside" },
      { word: "street", category: "Outside" },
      { word: "garden", category: "Outside" },
      { word: "bus stop", category: "Outside" },
      { word: "beach", category: "Outside" },
    ],
  },
  {
    key: "feelings-actions",
    title: "Feelings vs Actions",
    cefrGroup: "A1-A2",
    categoryA: "Feelings",
    categoryB: "Actions",
    items: [
      { word: "happy", category: "Feelings" },
      { word: "sad", category: "Feelings" },
      { word: "angry", category: "Feelings" },
      { word: "scared", category: "Feelings" },
      { word: "tired", category: "Feelings" },
      { word: "run", category: "Actions" },
      { word: "jump", category: "Actions" },
      { word: "write", category: "Actions" },
      { word: "eat", category: "Actions" },
      { word: "open", category: "Actions" },
    ],
  },
  {
    key: "people-places",
    title: "People vs Places",
    cefrGroup: "A1-A2",
    categoryA: "People",
    categoryB: "Places",
    items: [
      { word: "doctor", category: "People" },
      { word: "teacher", category: "People" },
      { word: "friend", category: "People" },
      { word: "driver", category: "People" },
      { word: "student", category: "People" },
      { word: "hospital", category: "Places" },
      { word: "school", category: "Places" },
      { word: "market", category: "Places" },
      { word: "library", category: "Places" },
      { word: "restaurant", category: "Places" },
    ],
  },
  {
    key: "fruits-vegetables",
    title: "Fruits vs Vegetables",
    cefrGroup: "A1-A2",
    categoryA: "Fruits",
    categoryB: "Vegetables",
    items: [
      { word: "apple", category: "Fruits" },
      { word: "banana", category: "Fruits" },
      { word: "orange", category: "Fruits" },
      { word: "grape", category: "Fruits" },
      { word: "pear", category: "Fruits" },
      { word: "carrot", category: "Vegetables" },
      { word: "potato", category: "Vegetables" },
      { word: "onion", category: "Vegetables" },
      { word: "pepper", category: "Vegetables" },
      { word: "corn", category: "Vegetables" },
    ],
  },
  {
    key: "family-jobs",
    title: "Family vs Jobs",
    cefrGroup: "A1-A2",
    categoryA: "Family",
    categoryB: "Jobs",
    items: [
      { word: "mother", category: "Family" },
      { word: "father", category: "Family" },
      { word: "sister", category: "Family" },
      { word: "brother", category: "Family" },
      { word: "grandmother", category: "Family" },
      { word: "doctor", category: "Jobs" },
      { word: "teacher", category: "Jobs" },
      { word: "driver", category: "Jobs" },
      { word: "nurse", category: "Jobs" },
      { word: "chef", category: "Jobs" },
    ],
  },
  {
    key: "sports-music",
    title: "Sports vs Music",
    cefrGroup: "A1-A2",
    categoryA: "Sports",
    categoryB: "Music",
    items: [
      { word: "soccer", category: "Sports" },
      { word: "basketball", category: "Sports" },
      { word: "tennis", category: "Sports" },
      { word: "swimming", category: "Sports" },
      { word: "running", category: "Sports" },
      { word: "guitar", category: "Music" },
      { word: "piano", category: "Music" },
      { word: "drum", category: "Music" },
      { word: "song", category: "Music" },
      { word: "singer", category: "Music" },
    ],
  },
  {
    key: "animals-plants",
    title: "Animals vs Plants",
    cefrGroup: "A1-A2",
    categoryA: "Animals",
    categoryB: "Plants",
    items: [
      { word: "dog", category: "Animals" },
      { word: "cat", category: "Animals" },
      { word: "bird", category: "Animals" },
      { word: "fish", category: "Animals" },
      { word: "horse", category: "Animals" },
      { word: "tree", category: "Plants" },
      { word: "flower", category: "Plants" },
      { word: "grass", category: "Plants" },
      { word: "bush", category: "Plants" },
      { word: "leaf", category: "Plants" },
    ],
  },
  {
    key: "colors-shapes",
    title: "Colors vs Shapes",
    cefrGroup: "A1-A2",
    categoryA: "Colors",
    categoryB: "Shapes",
    items: [
      { word: "red", category: "Colors" },
      { word: "blue", category: "Colors" },
      { word: "green", category: "Colors" },
      { word: "yellow", category: "Colors" },
      { word: "purple", category: "Colors" },
      { word: "circle", category: "Shapes" },
      { word: "square", category: "Shapes" },
      { word: "triangle", category: "Shapes" },
      { word: "star", category: "Shapes" },
      { word: "oval", category: "Shapes" },
    ],
  },

  // ---------- B1-B2 (10 packs) ----------
  {
    key: "work-freetime",
    title: "Work vs Free Time",
    cefrGroup: "B1-B2",
    categoryA: "Work",
    categoryB: "Free Time",
    items: [
      { word: "meeting", category: "Work" },
      { word: "deadline", category: "Work" },
      { word: "colleague", category: "Work" },
      { word: "commute", category: "Work" },
      { word: "promotion", category: "Work" },
      { word: "hobby", category: "Free Time" },
      { word: "weekend", category: "Free Time" },
      { word: "exercise", category: "Free Time" },
      { word: "concert", category: "Free Time" },
      { word: "videogame", category: "Free Time" },
    ],
  },
  {
    key: "travel-technology",
    title: "Travel vs Technology",
    cefrGroup: "B1-B2",
    categoryA: "Travel",
    categoryB: "Technology",
    items: [
      { word: "luggage", category: "Travel" },
      { word: "sightseeing", category: "Travel" },
      { word: "hostel", category: "Travel" },
      { word: "visa", category: "Travel" },
      { word: "itinerary", category: "Travel" },
      { word: "app", category: "Technology" },
      { word: "password", category: "Technology" },
      { word: "update", category: "Technology" },
      { word: "Wi-Fi", category: "Technology" },
      { word: "notification", category: "Technology" },
    ],
  },
  {
    key: "money-shopping",
    title: "Money vs Shopping",
    cefrGroup: "B1-B2",
    categoryA: "Money",
    categoryB: "Shopping",
    items: [
      { word: "budget", category: "Money" },
      { word: "salary", category: "Money" },
      { word: "debt", category: "Money" },
      { word: "savings", category: "Money" },
      { word: "bill", category: "Money" },
      { word: "discount", category: "Shopping" },
      { word: "receipt", category: "Shopping" },
      { word: "refund", category: "Shopping" },
      { word: "customer", category: "Shopping" },
      { word: "checkout", category: "Shopping" },
    ],
  },
  {
    key: "health-lifestyle",
    title: "Health vs Lifestyle",
    cefrGroup: "B1-B2",
    categoryA: "Health",
    categoryB: "Lifestyle",
    items: [
      { word: "headache", category: "Health" },
      { word: "check-up", category: "Health" },
      { word: "prescription", category: "Health" },
      { word: "symptom", category: "Health" },
      { word: "stress", category: "Health" },
      { word: "routine", category: "Lifestyle" },
      { word: "habit", category: "Lifestyle" },
      { word: "balance", category: "Lifestyle" },
      { word: "diet", category: "Lifestyle" },
      { word: "bedtime", category: "Lifestyle" },
    ],
  },
  {
    key: "relationships-personality",
    title: "Relationships vs Personality",
    cefrGroup: "B1-B2",
    categoryA: "Relationships",
    categoryB: "Personality",
    items: [
      { word: "partner", category: "Relationships" },
      { word: "colleague", category: "Relationships" },
      { word: "neighbor", category: "Relationships" },
      { word: "classmate", category: "Relationships" },
      { word: "friend", category: "Relationships" },
      { word: "introvert", category: "Personality" },
      { word: "extrovert", category: "Personality" },
      { word: "ambivert", category: "Personality" },
      { word: "optimistic", category: "Personality" },
      { word: "shy", category: "Personality" },
    ],
  },
  {
    key: "environment-community",
    title: "Environment vs Community",
    cefrGroup: "B1-B2",
    categoryA: "Environment",
    categoryB: "Community",
    items: [
      { word: "pollution", category: "Environment" },
      { word: "recycling", category: "Environment" },
      { word: "climate", category: "Environment" },
      { word: "habitat", category: "Environment" },
      { word: "sustainability", category: "Environment" },
      { word: "neighborhood", category: "Community" },
      { word: "volunteer", category: "Community" },
      { word: "charity", category: "Community" },
      { word: "tradition", category: "Community" },
      { word: "cooperation", category: "Community" },
    ],
  },
  {
    key: "emotions-achievements",
    title: "Emotions vs Achievements",
    cefrGroup: "B1-B2",
    categoryA: "Emotions",
    categoryB: "Achievements",
    items: [
      { word: "frustration", category: "Emotions" },
      { word: "satisfaction", category: "Emotions" },
      { word: "anxiety", category: "Emotions" },
      { word: "relief", category: "Emotions" },
      { word: "pride", category: "Emotions" },
      { word: "accomplishment", category: "Achievements" },
      { word: "milestone", category: "Achievements" },
      { word: "award", category: "Achievements" },
      { word: "promotion", category: "Achievements" },
      { word: "success", category: "Achievements" },
    ],
  },
  {
    key: "media-education",
    title: "Media vs Education",
    cefrGroup: "B1-B2",
    categoryA: "Media",
    categoryB: "Education",
    items: [
      { word: "broadcast", category: "Media" },
      { word: "advertisement", category: "Media" },
      { word: "subscription", category: "Media" },
      { word: "headline", category: "Media" },
      { word: "influencer", category: "Media" },
      { word: "curriculum", category: "Education" },
      { word: "scholarship", category: "Education" },
      { word: "tuition", category: "Education" },
      { word: "literacy", category: "Education" },
      { word: "mentor", category: "Education" },
    ],
  },
  {
    key: "opinions-facts",
    title: "Opinions vs Facts",
    cefrGroup: "B1-B2",
    categoryA: "Opinions",
    categoryB: "Facts",
    items: [
      { word: "viewpoint", category: "Opinions" },
      { word: "belief", category: "Opinions" },
      { word: "judgment", category: "Opinions" },
      { word: "preference", category: "Opinions" },
      { word: "assumption", category: "Opinions" },
      { word: "evidence", category: "Facts" },
      { word: "statistic", category: "Facts" },
      { word: "data", category: "Facts" },
      { word: "proof", category: "Facts" },
      { word: "record", category: "Facts" },
    ],
  },
  {
    key: "transportation-communication",
    title: "Transportation vs Communication",
    cefrGroup: "B1-B2",
    categoryA: "Transportation",
    categoryB: "Communication",
    items: [
      { word: "commute", category: "Transportation" },
      { word: "vehicle", category: "Transportation" },
      { word: "route", category: "Transportation" },
      { word: "terminal", category: "Transportation" },
      { word: "transit", category: "Transportation" },
      { word: "conversation", category: "Communication" },
      { word: "message", category: "Communication" },
      { word: "dialogue", category: "Communication" },
      { word: "correspondence", category: "Communication" },
      { word: "negotiation", category: "Communication" },
    ],
  },

  // ---------- C1-C2 (10 packs) ----------
  {
    key: "economics-politics",
    title: "Economics vs Politics",
    cefrGroup: "C1-C2",
    categoryA: "Economics",
    categoryB: "Politics",
    items: [
      { word: "inflation", category: "Economics" },
      { word: "recession", category: "Economics" },
      { word: "revenue", category: "Economics" },
      { word: "subsidy", category: "Economics" },
      { word: "commodity", category: "Economics" },
      { word: "legislation", category: "Politics" },
      { word: "referendum", category: "Politics" },
      { word: "sovereignty", category: "Politics" },
      { word: "diplomacy", category: "Politics" },
      { word: "coalition", category: "Politics" },
    ],
  },
  {
    key: "science-arts",
    title: "Science vs Arts",
    cefrGroup: "C1-C2",
    categoryA: "Science",
    categoryB: "Arts",
    items: [
      { word: "hypothesis", category: "Science" },
      { word: "empirical", category: "Science" },
      { word: "catalyst", category: "Science" },
      { word: "innovation", category: "Science" },
      { word: "prototype", category: "Science" },
      { word: "aesthetic", category: "Arts" },
      { word: "avant-garde", category: "Arts" },
      { word: "eclectic", category: "Arts" },
      { word: "narrative", category: "Arts" },
      { word: "renowned", category: "Arts" },
    ],
  },
  {
    key: "ethics-law",
    title: "Ethics vs Law",
    cefrGroup: "C1-C2",
    categoryA: "Ethics",
    categoryB: "Law",
    items: [
      { word: "virtue", category: "Ethics" },
      { word: "integrity", category: "Ethics" },
      { word: "altruism", category: "Ethics" },
      { word: "dilemma", category: "Ethics" },
      { word: "autonomy", category: "Ethics" },
      { word: "verdict", category: "Law" },
      { word: "testimony", category: "Law" },
      { word: "litigation", category: "Law" },
      { word: "jurisdiction", category: "Law" },
      { word: "precedent", category: "Law" },
    ],
  },
  {
    key: "psychology-society",
    title: "Psychology vs Society",
    cefrGroup: "C1-C2",
    categoryA: "Psychology",
    categoryB: "Society",
    items: [
      { word: "cognition", category: "Psychology" },
      { word: "resilience", category: "Psychology" },
      { word: "empathy", category: "Psychology" },
      { word: "temperament", category: "Psychology" },
      { word: "introspection", category: "Psychology" },
      { word: "globalization", category: "Society" },
      { word: "humanitarian", category: "Society" },
      { word: "displacement", category: "Society" },
      { word: "diaspora", category: "Society" },
      { word: "sanctions", category: "Society" },
    ],
  },
  {
    key: "linguistics-academia",
    title: "Linguistics vs Academia",
    cefrGroup: "C1-C2",
    categoryA: "Linguistics",
    categoryB: "Academia",
    items: [
      { word: "rhetoric", category: "Linguistics" },
      { word: "colloquial", category: "Linguistics" },
      { word: "syntax", category: "Linguistics" },
      { word: "eloquence", category: "Linguistics" },
      { word: "dialect", category: "Linguistics" },
      { word: "methodology", category: "Academia" },
      { word: "citation", category: "Academia" },
      { word: "dissertation", category: "Academia" },
      { word: "tenure", category: "Academia" },
      { word: "peer review", category: "Academia" },
    ],
  },
  {
    key: "diplomacy-conflict",
    title: "Diplomacy vs Conflict",
    cefrGroup: "C1-C2",
    categoryA: "Diplomacy",
    categoryB: "Conflict",
    items: [
      { word: "negotiation", category: "Diplomacy" },
      { word: "treaty", category: "Diplomacy" },
      { word: "alliance", category: "Diplomacy" },
      { word: "mediation", category: "Diplomacy" },
      { word: "consensus", category: "Diplomacy" },
      { word: "dispute", category: "Conflict" },
      { word: "hostility", category: "Conflict" },
      { word: "confrontation", category: "Conflict" },
      { word: "rivalry", category: "Conflict" },
      { word: "uprising", category: "Conflict" },
    ],
  },
  {
    key: "innovation-tradition",
    title: "Innovation vs Tradition",
    cefrGroup: "C1-C2",
    categoryA: "Innovation",
    categoryB: "Tradition",
    items: [
      { word: "breakthrough", category: "Innovation" },
      { word: "disruption", category: "Innovation" },
      { word: "pioneering", category: "Innovation" },
      { word: "cutting-edge", category: "Innovation" },
      { word: "novel", category: "Innovation" },
      { word: "heritage", category: "Tradition" },
      { word: "custom", category: "Tradition" },
      { word: "ritual", category: "Tradition" },
      { word: "legacy", category: "Tradition" },
      { word: "convention", category: "Tradition" },
    ],
  },
  {
    key: "wealth-poverty",
    title: "Wealth vs Poverty",
    cefrGroup: "C1-C2",
    categoryA: "Wealth",
    categoryB: "Poverty",
    items: [
      { word: "affluence", category: "Wealth" },
      { word: "prosperity", category: "Wealth" },
      { word: "opulence", category: "Wealth" },
      { word: "abundance", category: "Wealth" },
      { word: "fortune", category: "Wealth" },
      { word: "deprivation", category: "Poverty" },
      { word: "scarcity", category: "Poverty" },
      { word: "destitution", category: "Poverty" },
      { word: "hardship", category: "Poverty" },
      { word: "austerity", category: "Poverty" },
    ],
  },
  {
    key: "persuasion-logic",
    title: "Persuasion vs Logic",
    cefrGroup: "C1-C2",
    categoryA: "Persuasion",
    categoryB: "Logic",
    items: [
      { word: "charisma", category: "Persuasion" },
      { word: "appeal", category: "Persuasion" },
      { word: "propaganda", category: "Persuasion" },
      { word: "endorsement", category: "Persuasion" },
      { word: "manipulation", category: "Persuasion" },
      { word: "deduction", category: "Logic" },
      { word: "inference", category: "Logic" },
      { word: "premise", category: "Logic" },
      { word: "syllogism", category: "Logic" },
      { word: "rationale", category: "Logic" },
    ],
  },
  {
    key: "research-speculation",
    title: "Research vs Speculation",
    cefrGroup: "C1-C2",
    categoryA: "Research",
    categoryB: "Speculation",
    items: [
      { word: "investigation", category: "Research" },
      { word: "analysis", category: "Research" },
      { word: "verification", category: "Research" },
      { word: "documentation", category: "Research" },
      { word: "methodology", category: "Research" },
      { word: "conjecture", category: "Speculation" },
      { word: "assumption", category: "Speculation" },
      { word: "guesswork", category: "Speculation" },
      { word: "prediction", category: "Speculation" },
      { word: "hypothesis", category: "Speculation" },
    ],
  },
];

export default WORD_SORT_PACKS;
